# Air-training analysis: full air-cycle organization

The goal of this analysis is to determine how air delivery structures locomotor behavior across the full air-on and air-off cycle.

Rather than using post-pre delta values as the dependent variable, we model actual locomotor values from sequential windows. This allows us to compare biologically meaningful epochs directly while preserving absolute locomotor levels.

The main air-cycle sequence is:

pre_air_on → post_air_on → pre_air_on_mid → post_air_on_mid → pre_air_off → post_air_off → pre_air_off_mid → post_air_off_mid → pre_air_on_next

Planned comparisons:

1. Air-onset transition:
   pre_air_on vs post_air_on

2. Early air-on progression:
   post_air_on vs pre_air_on_mid

3. Late air-on progression:
   post_air_on_mid vs pre_air_off

4. Air-offset transition:
   pre_air_off vs post_air_off

5. Early air-off recovery:
   post_air_off vs pre_air_off_mid

6. Late air-off recovery / return toward next baseline:
   post_air_off_mid vs pre_air_on_next

Outcomes are analyzed in the following order:
1. fraction moving
2. fraction forward
3. path speed and net speed
4. path distance and net distance

For each outcome and planned comparison, linear mixed-effects models are used. Basic models test whether the second epoch differs from the first. Time-dependent models test whether this difference changes across air-training sessions and within-session time.

In [3]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

# Find the project root that contains the src folder
current = Path.cwd().resolve()

for p in [current] + list(current.parents):
    if (p / "src").exists():
        repo_root = p
        break
else:
    raise FileNotFoundError("Could not find a folder containing 'src'.")

if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

print("Current working directory:", current)
print("Added repo root:", repo_root)
print("src exists:", (repo_root / "src").exists())

from pathlib import Path
import numpy as np
import pandas as pd

import src.utils.pdata_io as pdio
from src.proc.extract_epoch_windows import load_epoch_windows

data_root, pdata_root, cc_data = pdio.load_project_context()

windows_df = load_epoch_windows(
    pdata_root=pdata_root,
    filename="behavior_epoch_windows.h5",
    key="windows/prepost_1s"
)

valid_windows = windows_df[windows_df["valid_window"]].copy()

print("All windows:", windows_df.shape)
print("Valid windows:", valid_windows.shape)

valid_windows.groupby(["phase", "epoch_name"]).size().reset_index(name="n_windows")

encoder_epoch_df = pd.read_hdf(
    Path(pdata_root) / "_cache" / "behavior_epoch_metrics.h5",
    key="encoder/prepost_1s_speedThresh_1cms"
)

from src.qc.qc_events import load_behavior_qc_tables

events_df, session_summary_df = load_behavior_qc_tables(
    pdata_root=pdata_root,
    filename="behavior_QC.h5"
)

from src.utils.pdata_organize import make_session_availability_summary

session_availability_df = make_session_availability_summary(
    events_df=events_df,
    windows_df=windows_df,
    min_session_duration_s=900,
    min_valid_events=3,
)

from src.utils.pdata_organize import add_day_bins_to_sessions

session_day_df = add_day_bins_to_sessions(
    session_availability_df,
    use_good_sessions_only=True,
)

Current working directory: /home/nmldata2/ccaw/Python/notebooks
Added repo root: /home/nmldata2/ccaw/Python
src exists: True
/home/nmldata2/ccaw/Python
[LOADED] Project context: /mnt/pdata/Classical_Conditioning/_cache/project_context.pkl
[LOADED] Epoch windows: /mnt/pdata/Classical_Conditioning/_cache/behavior_epoch_windows.h5
[KEY] windows/prepost_1s
All windows: (103980, 40)
Valid windows: (101861, 40)
[LOADED] Behavior QC tables: /mnt/pdata/Classical_Conditioning/_cache/behavior_QC.h5

In [4]:
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from pathlib import Path

air_phase = "air_training"

air_anchors = [
    "air_on",
    "air_on_mid",
    "air_off",
    "air_off_mid",
]

# Candidate outcome names. Keep only those present in encoder_epoch_df.
candidate_outcomes = [
    "frac_moving",
    "frac_forward",
    "frac_stationary",
    "mean_speed_path_cms",
    "mean_speed_net_cms",
    "distance_path_cm",
    "distance_net_cm",
    "dist_path_cm",
    "dist_net_cm",
]

air_outcomes = [
    c for c in candidate_outcomes
    if c in encoder_epoch_df.columns
]

print("Available air outcomes:")
print(air_outcomes)

print("\nDistance-like columns:")
print([c for c in encoder_epoch_df.columns if "dist" in c.lower() or "distance" in c.lower()])

Available air outcomes:
['frac_moving', 'frac_forward', 'frac_stationary', 'mean_speed_path_cms', 'mean_speed_net_cms', 'distance_path_cm', 'distance_net_cm']

Distance-like columns:
['distance_path_cm', 'distance_net_cm']

In [5]:
def prepare_air_window_df(
    encoder_epoch_df,
    phase="air_training",
    anchors=None,
    keep_overlap=True,
    require_good_session=True,
    require_valid_window=True,
):
    """
    Prepare long-format air-training window dataframe.

    One row = one pre/post window around one air-related anchor.
    """

    if anchors is None:
        anchors = [
            "air_on",
            "air_on_mid",
            "air_off",
            "air_off_mid",
        ]

    df = encoder_epoch_df.copy()

    df = df[
        (df["phase"] == phase) &
        (df["anchor_name"].isin(anchors)) &
        (df["window_position"].isin(["pre", "post"]))
    ].copy()

    if require_good_session and "good_session_basic" in df.columns:
        df = df[df["good_session_basic"] == True].copy()

    if require_valid_window and "valid_window" in df.columns:
        df = df[df["valid_window"] == True].copy()

    if not keep_overlap and "overlap_flag" in df.columns:
        df = df[df["overlap_flag"] == False].copy()

    # --------------------------------------------------
    # Create biological epoch labels
    # --------------------------------------------------
    label_map = {
        ("air_on", "pre"): "pre_air_on",
        ("air_on", "post"): "post_air_on",

        ("air_on_mid", "pre"): "pre_air_on_mid",
        ("air_on_mid", "post"): "post_air_on_mid",

        ("air_off", "pre"): "pre_air_off",
        ("air_off", "post"): "post_air_off",

        ("air_off_mid", "pre"): "pre_air_off_mid",
        ("air_off_mid", "post"): "post_air_off_mid",
    }

    df["epoch_label"] = [
        label_map.get((a, w), np.nan)
        for a, w in zip(df["anchor_name"], df["window_position"])
    ]

    df = df[df["epoch_label"].notna()].copy()

    # --------------------------------------------------
    # Random-effect IDs
    # --------------------------------------------------
    df["animal_day"] = (
        df["animal"].astype(str) + ":" +
        df["date"].astype(str)
    )

    # --------------------------------------------------
    # Session time
    # --------------------------------------------------
    if "session_time_min" not in df.columns:
        if "anchor_session_time_min" in df.columns:
            df["session_time_min"] = df["anchor_session_time_min"]
        elif "anchor_time_s" in df.columns:
            df["session_time_min"] = df["anchor_time_s"] / 60.0
        elif "session_time_s" in df.columns:
            df["session_time_min"] = df["session_time_s"] / 60.0
        else:
            df["session_time_min"] = np.nan

    # --------------------------------------------------
    # Exposure session
    # --------------------------------------------------
    if "phase_session_number" in df.columns:
        df["exposure_session"] = df["phase_session_number"]
    elif "phase_day_number_good" in df.columns:
        df["exposure_session"] = df["phase_day_number_good"]
    else:
        df["exposure_session"] = np.nan

    return df.reset_index(drop=True)

In [6]:
air_window_df = prepare_air_window_df(
    encoder_epoch_df,
    phase=air_phase,
    anchors=air_anchors,
    keep_overlap=True,
    require_good_session=True,
    require_valid_window=True,
)

print(air_window_df.shape)
print(air_window_df["epoch_label"].value_counts())

(28229, 63)
epoch_label
pre_air_off         3535
post_air_on_mid     3535
post_air_on         3535
pre_air_on_mid      3534
pre_air_on          3532
post_air_off        3525
pre_air_off_mid     3517
post_air_off_mid    3516
Name: count, dtype: int64

In [7]:
air_window_df[
    [
        "animal",
        "date",
        "phase",
        "anchor_name",
        "window_position",
        "epoch_label",
        "event_number",
        "session_time_min",
        "exposure_session",
    ]
].head(20)

,animal,date,phase,anchor_name,window_position,epoch_label,event_number,session_time_min,exposure_session
0,NML_04,2026_01_12,air_training,air_off_mid,post,post_air_off_mid,0,0.206890,1
1,NML_04,2026_01_12,air_training,air_off_mid,pre,pre_air_off_mid,0,0.206890,1
2,NML_04,2026_01_12,air_training,air_off,post,post_air_off,0,0.081173,1
3,NML_04,2026_01_12,air_training,air_off,pre,pre_air_off,0,0.081173,1
4,NML_04,2026_01_12,air_training,air_on_mid,post,post_air_on_mid,0,0.040587,1
5,NML_04,2026_01_12,air_training,air_on_mid,pre,pre_air_on_mid,0,0.040587,1
6,NML_04,2026_01_12,air_training,air_on,post,post_air_on,0,0.000000,1
7,NML_04,2026_01_12,air_training,air_off_mid,post,post_air_off_mid,1,0.525370,1
8,NML_04,2026_01_12,air_training,air_off_mid,pre,pre_air_off_mid,1,0.525370,1
9,NML_04,2026_01_12,air_training,air_off,post,post_air_off,1,0.399650,1
10,NML_04,2026_01_12,air_training,air_off,pre,pre_air_off,1,0.399650,1
11,NML_04,2026_01_12,air_training,air_on_mid,post,post_air_on_mid,1,0.366128,1
12,NML_04,2026_01_12,air_training,air_on_mid,pre,pre_air_on_mid,1,0.366128,1
13,NML_04,2026_01_12,air_training,air_on,post,post_air_on,1,0.332607,1
14,NML_04,2026_01_12,air_training,air_on,pre,pre_air_on,1,0.332607,1
15,NML_04,2026_01_12,air_training,air_off_mid,post,post_air_off_mid,2,0.813700,1
16,NML_04,2026_01_12,air_training,air_off_mid,pre,pre_air_off_mid,2,0.813700,1
17,NML_04,2026_01_12,air_training,air_off,post,post_air_off,2,0.687987,1
18,NML_04,2026_01_12,air_training,air_off,pre,pre_air_off,2,0.687987,1
19,NML_04,2026_01_12,air_training,air_on_mid,post,post_air_on_mid,2,0.669538,1

In [8]:
air_comparisons = [
    {
        "comparison": "air_onset_transition",
        "epoch1": "pre_air_on",
        "epoch2": "post_air_on",
        "epoch2_trial_shift": 0,
        "interpretation": "Air-onset transition",
    },
    {
        "comparison": "early_air_on_progression",
        "epoch1": "post_air_on",
        "epoch2": "pre_air_on_mid",
        "epoch2_trial_shift": 0,
        "interpretation": "Early air-on progression",
    },
    {
        "comparison": "air_on_mid_transition",
        "epoch1": "pre_air_on_mid",
        "epoch2": "post_air_on_mid",
        "epoch2_trial_shift": 0,
        "interpretation": "Air-on midpoint transition",
    },
    {
        "comparison": "late_air_on_progression",
        "epoch1": "post_air_on_mid",
        "epoch2": "pre_air_off",
        "epoch2_trial_shift": 0,
        "interpretation": "Late air-on progression",
    },
    {
        "comparison": "air_offset_transition",
        "epoch1": "pre_air_off",
        "epoch2": "post_air_off",
        "epoch2_trial_shift": 0,
        "interpretation": "Air-offset transition",
    },
    {
        "comparison": "early_air_off_recovery",
        "epoch1": "post_air_off",
        "epoch2": "pre_air_off_mid",
        "epoch2_trial_shift": 0,
        "interpretation": "Early air-off recovery",
    },
    {
        "comparison": "air_off_mid_transition",
        "epoch1": "pre_air_off_mid",
        "epoch2": "post_air_off_mid",
        "epoch2_trial_shift": 0,
        "interpretation": "Air-off midpoint transition",
    },
    {
        "comparison": "late_air_off_recovery_to_next_baseline",
        "epoch1": "post_air_off_mid",
        "epoch2": "pre_air_on",
        "epoch2_trial_shift": 1,
        "interpretation": "Late air-off recovery / next pre-air baseline",
    },
]

pd.DataFrame(air_comparisons)

,comparison,epoch1,epoch2,epoch2_trial_shift,interpretation
0,air_onset_transition,pre_air_on,post_air_on,0,Air-onset transition
1,early_air_on_progression,post_air_on,pre_air_on_mid,0,Early air-on progression
2,air_on_mid_transition,pre_air_on_mid,post_air_on_mid,0,Air-on midpoint transition
3,late_air_on_progression,post_air_on_mid,pre_air_off,0,Late air-on progression
4,air_offset_transition,pre_air_off,post_air_off,0,Air-offset transition
5,early_air_off_recovery,post_air_off,pre_air_off_mid,0,Early air-off recovery
6,air_off_mid_transition,pre_air_off_mid,post_air_off_mid,0,Air-off midpoint transition
7,late_air_off_recovery_to_next_baseline,post_air_off_mid,pre_air_on,1,Late air-off recovery / next pre-air baseline

In [9]:
def make_air_pair_df(
    air_window_df,
    comparison,
    epoch1,
    epoch2,
    epoch2_trial_shift=0,
    trial_col="event_number",
):
    """
    Build long-format paired dataframe for one planned comparison.

    epoch1 is the first window.
    epoch2 is the second window.

    If epoch2_trial_shift = 1, then epoch2 from trial N+1 is paired
    with epoch1 from trial N. This is used for:

        post_air_off_mid trial N vs pre_air_on trial N+1
    """

    df = air_window_df.copy()

    required_cols = [
        "animal",
        "date",
        trial_col,
        "epoch_label",
        "session_time_min",
        "exposure_session",
        "animal_day",
    ]

    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing columns: {missing}")

    e1 = df[df["epoch_label"] == epoch1].copy()
    e2 = df[df["epoch_label"] == epoch2].copy()

    # Pairing trial number
    e1["pair_trial"] = e1[trial_col].astype(int)
    e2["pair_trial"] = e2[trial_col].astype(int) - int(epoch2_trial_shift)

    pair_keys = ["animal", "date", "pair_trial"]

    # Keep only pairs present in both epochs
    common_pairs = (
        e1[pair_keys]
        .drop_duplicates()
        .merge(
            e2[pair_keys].drop_duplicates(),
            on=pair_keys,
            how="inner"
        )
    )

    e1 = e1.merge(common_pairs, on=pair_keys, how="inner")
    e2 = e2.merge(common_pairs, on=pair_keys, how="inner")

    # Pair-level time and exposure are taken from the first epoch
    pair_info = (
        e1[pair_keys + ["session_time_min", "exposure_session"]]
        .drop_duplicates(subset=pair_keys)
        .rename(
            columns={
                "session_time_min": "pair_session_time_min",
                "exposure_session": "pair_exposure_session",
            }
        )
    )

    e1 = e1.merge(pair_info, on=pair_keys, how="left")
    e2 = e2.merge(pair_info, on=pair_keys, how="left")

    e1["comparison"] = comparison
    e2["comparison"] = comparison

    e1["comparison_epoch"] = epoch1
    e2["comparison_epoch"] = epoch2

    e1["epoch2_indicator"] = 0
    e2["epoch2_indicator"] = 1

    pair_df = pd.concat([e1, e2], ignore_index=True)

    pair_df["pair_id"] = (
        pair_df["animal"].astype(str) + ":" +
        pair_df["date"].astype(str) + ":" +
        pair_df["comparison"].astype(str) + ":" +
        pair_df["pair_trial"].astype(str)
    )

    return pair_df.reset_index(drop=True)

In [10]:
air_pair_list = []

for comp in air_comparisons:
    tmp = make_air_pair_df(
        air_window_df,
        comparison=comp["comparison"],
        epoch1=comp["epoch1"],
        epoch2=comp["epoch2"],
        epoch2_trial_shift=comp["epoch2_trial_shift"],
    )
    air_pair_list.append(tmp)

air_pair_df = pd.concat(air_pair_list, ignore_index=True)

print(air_pair_df.shape)
print(air_pair_df["comparison"].value_counts())
print(air_pair_df.groupby(["comparison", "comparison_epoch"])["pair_id"].nunique())

(56292, 70)
comparison
late_air_on_progression                   7068
early_air_on_progression                  7066
air_on_mid_transition                     7066
air_onset_transition                      7062
air_offset_transition                     7048
early_air_off_recovery                    7034
air_off_mid_transition                    7032
late_air_off_recovery_to_next_baseline    6916
Name: count, dtype: int64
comparison                              comparison_epoch
air_off_mid_transition                  post_air_off_mid    3516
                                        pre_air_off_mid     3516
air_offset_transition                   post_air_off        3524
                                        pre_air_off         3524
air_on_mid_transition                   post_air_on_mid     3533
                                        pre_air_on_mid      3533
air_onset_transition                    post_air_on         3531
                                        pre_air_on          3531
early_air_off_recovery                  post_air_off        3517
                                        pre_air_off_mid     3517
early_air_on_progression                post_air_on         3533
                                        pre_air_on_mid      3533
late_air_off_recovery_to_next_baseline  post_air_off_mid    3458
                                        pre_air_on          3458
late_air_on_progression                 post_air_on_mid     3534
                                        pre_air_off         3534
Name: pair_id, dtype: int64

In [11]:
air_pair_df["pair_exposure_session_c"] = (
    air_pair_df["pair_exposure_session"] -
    air_pair_df["pair_exposure_session"].mean()
)

air_pair_df["pair_session_10m_c"] = (
    air_pair_df["pair_session_time_min"] -
    air_pair_df["pair_session_time_min"].mean()
) / 10.0

air_pair_df[
    [
        "animal",
        "date",
        "comparison",
        "comparison_epoch",
        "epoch2_indicator",
        "pair_trial",
        "pair_exposure_session",
        "pair_exposure_session_c",
        "pair_session_time_min",
        "pair_session_10m_c",
    ]
].head(20)

,animal,date,comparison,comparison_epoch,epoch2_indicator,pair_trial,pair_exposure_session,pair_exposure_session_c,pair_session_time_min,pair_session_10m_c
0,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,1,1,-7.11618,0.332607,-1.012639
1,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,2,1,-7.11618,0.651090,-0.980791
2,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,3,1,-7.11618,0.939413,-0.951959
3,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,4,1,-7.11618,1.221443,-0.923756
4,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,5,1,-7.11618,1.508487,-0.895051
5,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,6,1,-7.11618,1.947493,-0.851151
6,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,7,1,-7.11618,2.219347,-0.823965
7,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,8,1,-7.11618,2.502110,-0.795689
8,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,9,1,-7.11618,2.770740,-0.768826
9,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,10,1,-7.11618,3.063853,-0.739515
10,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,11,1,-7.11618,3.631090,-0.682791
11,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,12,1,-7.11618,4.251023,-0.620798
12,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,13,1,-7.11618,4.668273,-0.579073
13,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,14,1,-7.11618,5.013097,-0.544590
14,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,15,1,-7.11618,5.491523,-0.496748
15,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,16,1,-7.11618,5.830873,-0.462813
16,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,17,1,-7.11618,6.193020,-0.426598
17,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,18,1,-7.11618,6.576053,-0.388295
18,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,19,1,-7.11618,6.912354,-0.354665
19,NML_04,2026_01_12,air_onset_transition,pre_air_on,0,20,1,-7.11618,7.272097,-0.318690

In [20]:
def fit_air_basic_pair_model(
    air_pair_df,
    outcome,
    comparison,
):
    """
    Basic planned comparison using actual values.

    outcome ~ epoch2_indicator

    epoch2_indicator coefficient:
        value in second epoch - value in first epoch
    """

    df = air_pair_df.copy()
    df = df[df["comparison"] == comparison].copy()
    df = df[np.isfinite(df[outcome])].copy()

    model = smf.mixedlm(
        f"{outcome} ~ epoch2_indicator",
        data=df,
        groups=df["animal"],
        re_formula="1",
        vc_formula={
            "animal_day": "0 + C(animal_day)",
            "pair_id": "0 + C(pair_id)",
        }
    ).fit(
        reml=False,
        method="lbfgs",
        maxiter=1000,
    )

    return model

In [30]:
from joblib import Parallel, delayed, parallel_backend
import warnings
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf

In [31]:
def run_one_air_basic_model(outcome, comp, air_pair_df):
    """
    Fit one basic air-cycle planned-comparison model.

    Returns:
        key = (outcome, comparison)
        model = fitted statsmodels result or None
        status info
    """

    comparison = comp["comparison"]
    interpretation = comp["interpretation"]

    try:
        with warnings.catch_warnings(record=True) as w:
            warnings.simplefilter("always")

            model = fit_air_basic_pair_model(
                air_pair_df,
                outcome=outcome,
                comparison=comparison,
            )

            warning_text = " | ".join(
                sorted(set(str(x.message) for x in w))
            )

        status = {
            "outcome": outcome,
            "comparison": comparison,
            "interpretation": interpretation,
            "success": True,
            "converged": getattr(model, "converged", np.nan),
            "n_obs": int(model.nobs),
            "warnings": warning_text,
            "error": "",
        }

        return (outcome, comparison), model, status

    except Exception as e:
        status = {
            "outcome": outcome,
            "comparison": comparison,
            "interpretation": interpretation,
            "success": False,
            "converged": False,
            "n_obs": np.nan,
            "warnings": "",
            "error": str(e),
        }

        return (outcome, comparison), None, status

In [32]:
jobs = []

for outcome in air_outcomes:
    for comp in air_comparisons:
        jobs.append((outcome, comp))

len(jobs)

56

In [33]:
n_jobs = 4   # start with 4; increase only if memory is okay

with parallel_backend("loky", inner_max_num_threads=1):
    parallel_results = Parallel(
        n_jobs=n_jobs,
        verbose=10
    )(
        delayed(run_one_air_basic_model)(
            outcome,
            comp,
            air_pair_df
        )
        for outcome, comp in jobs
    )

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:  3.0min
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:  6.5min
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed: 10.0min
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed: 13.7min
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed: 20.4min
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed: 25.0min
[Parallel(n_jobs=4)]: Done  56 out of  56 | elapsed: 33.9min finished

In [34]:
air_basic_models = {}
status_rows = []

for key, model, status in parallel_results:
    status_rows.append(status)

    if model is not None:
        air_basic_models[key] = model

air_basic_status_df = pd.DataFrame(status_rows)

air_basic_status_df

,outcome,comparison,interpretation,success,converged,n_obs,warnings,error
0,frac_moving,air_onset_transition,Air-onset transition,True,True,7062,The Hessian matrix at the estimated parameter ...,
1,frac_moving,early_air_on_progression,Early air-on progression,True,True,7066,The Hessian matrix at the estimated parameter ...,
2,frac_moving,air_on_mid_transition,Air-on midpoint transition,True,True,7066,,
3,frac_moving,late_air_on_progression,Late air-on progression,True,True,7068,The Hessian matrix at the estimated parameter ...,
4,frac_moving,air_offset_transition,Air-offset transition,True,False,7048,"Gradient optimization failed, |grad| = 75.1800...",
5,frac_moving,early_air_off_recovery,Early air-off recovery,True,True,7034,The Hessian matrix at the estimated parameter ...,
6,frac_moving,air_off_mid_transition,Air-off midpoint transition,True,True,7032,The MLE may be on the boundary of the paramete...,
7,frac_moving,late_air_off_recovery_to_next_baseline,Late air-off recovery / next pre-air baseline,True,False,6916,"Gradient optimization failed, |grad| = 17.1077...",
8,frac_forward,air_onset_transition,Air-onset transition,True,False,7062,"Gradient optimization failed, |grad| = 73.9367...",
9,frac_forward,early_air_on_progression,Early air-on progression,True,True,7066,The MLE may be on the boundary of the paramete...,
10,frac_forward,air_on_mid_transition,Air-on midpoint transition,True,True,7066,,
11,frac_forward,late_air_on_progression,Late air-on progression,True,True,7068,The MLE may be on the boundary of the paramete...,
12,frac_forward,air_offset_transition,Air-offset transition,True,True,7048,The Hessian matrix at the estimated parameter ...,
13,frac_forward,early_air_off_recovery,Early air-off recovery,True,False,7034,"Gradient optimization failed, |grad| = 38.8941...",
14,frac_forward,air_off_mid_transition,Air-off midpoint transition,True,True,7032,The MLE may be on the boundary of the paramete...,
15,frac_forward,late_air_off_recovery_to_next_baseline,Late air-off recovery / next pre-air baseline,True,True,6916,The MLE may be on the boundary of the paramete...,
16,frac_stationary,air_onset_transition,Air-onset transition,True,True,7062,The Hessian matrix at the estimated parameter ...,
17,frac_stationary,early_air_on_progression,Early air-on progression,True,True,7066,The Hessian matrix at the estimated parameter ...,
18,frac_stationary,air_on_mid_transition,Air-on midpoint transition,True,True,7066,,
19,frac_stationary,late_air_on_progression,Late air-on progression,True,True,7068,The Hessian matrix at the estimated parameter ...,
20,frac_stationary,air_offset_transition,Air-offset transition,True,True,7048,The Hessian matrix at the estimated parameter ...,
21,frac_stationary,early_air_off_recovery,Early air-off recovery,True,True,7034,The Hessian matrix at the estimated parameter ...,
22,frac_stationary,air_off_mid_transition,Air-off midpoint transition,True,True,7032,The MLE may be on the boundary of the paramete...,
23,frac_stationary,late_air_off_recovery_to_next_baseline,Late air-off recovery / next pre-air baseline,True,False,6916,"Gradient optimization failed, |grad| = 17.1077...",
24,mean_speed_path_cms,air_onset_transition,Air-onset transition,True,True,7062,,
25,mean_speed_path_cms,early_air_on_progression,Early air-on progression,True,True,7066,The Hessian matrix at the estimated parameter ...,
26,mean_speed_path_cms,air_on_mid_transition,Air-on midpoint transition,True,False,7066,"Gradient optimization failed, |grad| = 141.583...",
27,mean_speed_path_cms,late_air_on_progression,Late air-on progression,True,True,7068,,
28,mean_speed_path_cms,air_offset_transition,Air-offset transition,True,True,7048,The Hessian matrix at the estimated parameter ...,
29,mean_speed_path_cms,early_air_off_recovery,Early air-off recovery,True,True,7034,The Hessian matrix at the estimated parameter ...,
30,mean_speed_path_cms,air_off_mid_transition,Air-off midpoint transition,True,True,7032,,
31,mean_speed_path_cms,late_air_off_recovery_to_next_baseline,Late air-off recovery / next pre-air baseline,True,True,6916,The Hessian matrix at the estimated parameter ...,
32,mean_speed_net_cms,air_onset_transition,Air-onset transition,True,True,7062,The Hessian matrix at the estimated parameter ...,
33,mean_speed_net_cms,early_air_on_progression,Early air-on progression,True,False,7066,"Gradient optimization failed, |grad| = 141.348...",
34,mean_speed_net_cms,air_on_mid_transition,Air-on midpoint transition,True,True,7066,The Hessian matrix at the estimated parameter ...,
35,mean_speed_net_cms,late_air_on_progression,Late air-on progression,True,True,7068,,
36,mean_speed_net_cms,air_offset_transition,Air-offset transition,True,True,7048,The Hessian matrix at the estimated parameter ...,
37,mean_speed_net_cms,early_air_off_recovery,Early air-off recovery,True,True,7034,The Hessian matrix at the estimated parameter ...,
38,mean_speed_net_cms,air_off_mid_transition,Air-off midpoint transition,True,True,7032,,
39,mean_speed_net_cms,late_air_off_recovery_to_next_baseline,Late air-off recovery / next pre-air baseline,True,True,6916,The Hessian matrix at the estimated parameter ...,
40,distance_path_cm,air_onset_transition,Air-onset transition,True,True,7062,,
41,distance_path_cm,early_air_on_progression,Early air-on progression,True,False,7066,"Gradient optimization failed, |grad| = 141.881...",
42,distance_path_cm,air_on_mid_transition,Air-on midpoint transition,True,True,7066,The Hessian matrix at the estimated parameter ...,
43,distance_path_cm,late_air_on_progression,Late air-on progression,True,True,7068,,
44,distance_path_cm,air_offset_transition,Air-offset transition,True,True,7048,The Hessian matrix at the estimated parameter ...,
45,distance_path_cm,early_air_off_recovery,Early air-off recovery,True,True,7034,The Hessian matrix at the estimated parameter ...,
46,distance_path_cm,air_off_mid_transition,Air-off midpoint transition,True,True,7032,,
47,distance_path_cm,late_air_off_recovery_to_next_baseline,Late air-off recovery / next pre-air baseline,True,True,6916,The Hessian matrix at the estimated parameter ...,
48,distance_net_cm,air_onset_transition,Air-onset transition,True,True,7062,The Hessian matrix at the estimated parameter ...,
49,distance_net_cm,early_air_on_progression,Early air-on progression,True,False,7066,"Gradient optimization failed, |grad| = 141.346...",
50,distance_net_cm,air_on_mid_transition,Air-on midpoint transition,True,False,7066,"Gradient optimization failed, |grad| = 137.762...",
51,distance_net_cm,late_air_on_progression,Late air-on progression,True,True,7068,,
52,distance_net_cm,air_offset_transition,Air-offset transition,True,False,7048,"Gradient optimization failed, |grad| = 69.9321...",
53,distance_net_cm,early_air_off_recovery,Early air-off recovery,True,True,7034,The Hessian matrix at the estimated parameter ...,
54,distance_net_cm,air_off_mid_transition,Air-off midpoint transition,True,True,7032,,
55,distance_net_cm,late_air_off_recovery_to_next_baseline,Late air-off recovery / next pre-air baseline,True,True,6916,The Hessian matrix at the estimated parameter ...,

In [35]:
air_basic_status_df[
    (air_basic_status_df["success"] == False) |
    (air_basic_status_df["converged"] == False)
]

,outcome,comparison,interpretation,success,converged,n_obs,warnings,error
4,frac_moving,air_offset_transition,Air-offset transition,True,False,7048,"Gradient optimization failed, |grad| = 75.1800...",
7,frac_moving,late_air_off_recovery_to_next_baseline,Late air-off recovery / next pre-air baseline,True,False,6916,"Gradient optimization failed, |grad| = 17.1077...",
8,frac_forward,air_onset_transition,Air-onset transition,True,False,7062,"Gradient optimization failed, |grad| = 73.9367...",
13,frac_forward,early_air_off_recovery,Early air-off recovery,True,False,7034,"Gradient optimization failed, |grad| = 38.8941...",
23,frac_stationary,late_air_off_recovery_to_next_baseline,Late air-off recovery / next pre-air baseline,True,False,6916,"Gradient optimization failed, |grad| = 17.1077...",
26,mean_speed_path_cms,air_on_mid_transition,Air-on midpoint transition,True,False,7066,"Gradient optimization failed, |grad| = 141.583...",
33,mean_speed_net_cms,early_air_on_progression,Early air-on progression,True,False,7066,"Gradient optimization failed, |grad| = 141.348...",
41,distance_path_cm,early_air_on_progression,Early air-on progression,True,False,7066,"Gradient optimization failed, |grad| = 141.881...",
49,distance_net_cm,early_air_on_progression,Early air-on progression,True,False,7066,"Gradient optimization failed, |grad| = 141.346...",
50,distance_net_cm,air_on_mid_transition,Air-on midpoint transition,True,False,7066,"Gradient optimization failed, |grad| = 137.762...",
52,distance_net_cm,air_offset_transition,Air-offset transition,True,False,7048,"Gradient optimization failed, |grad| = 69.9321...",

In [36]:
basic_rows = []

for outcome in air_outcomes:
    for comp in air_comparisons:
        key = (outcome, comp["comparison"])

        if key not in air_basic_models:
            continue

        basic_rows.append(
            extract_air_basic_result(
                air_basic_models[key],
                outcome=outcome,
                comparison=comp["comparison"],
                interpretation=comp["interpretation"],
            )
        )

air_basic_results_df = pd.DataFrame(basic_rows)

air_basic_results_df["outcome_order"] = air_basic_results_df["outcome"].map(outcome_order)
air_basic_results_df["comparison_order"] = air_basic_results_df["comparison"].map(comparison_order)

air_basic_results_df = (
    air_basic_results_df
    .sort_values(["outcome_order", "comparison_order"])
    .reset_index(drop=True)
)

air_basic_results_df

NameError: name 'extract_air_basic_result' is not defined

In [ ]:
air_basic_models = {}

for outcome in air_outcomes:
    for comp in air_comparisons:
        comparison = comp["comparison"]

        try:
            model = fit_air_basic_pair_model(
                air_pair_df,
                outcome=outcome,
                comparison=comparison,
            )

            air_basic_models[(outcome, comparison)] = model

            print("\n\n==============================")
            print(outcome, comparison)
            print(comp["interpretation"])
            print("==============================")
            print(model.summary())

        except Exception as e:
            print(f"[ERROR] {outcome}, {comparison}: {e}")

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_moving air_onset_transition
Air-onset transition
==============================
          Mixed Linear Model Regression Results
==========================================================
Model:             MixedLM Dependent Variable: frac_moving
No. Observations:  7062    Method:             ML
No. Groups:        5       Scale:              0.0867
Min. group size:   880     Log-Likelihood:     -1494.9130
Max. group size:   1690    Converged:          Yes
Mean group size:   1412.4
----------------------------------------------------------
                 Coef. Std.Err.   z    P>|z| [0.025 0.975]
----------------------------------------------------------
Intercept        0.290    0.126  2.307 0.021  0.044  0.536
epoch2_indicator 0.501    0.007 71.449 0.000  0.487  0.514
Group Var        0.078
animal_day Var   0.011    0.007
pair_id Var      0.000    0.004
==========================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2207: ConvergenceWarning: MixedLM optimization failed, trying a different optimizer may help.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2219: ConvergenceWarning: Gradient optimization failed, |grad| = 28.841050
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_moving early_air_on_progression
Early air-on progression
==============================
          Mixed Linear Model Regression Results
=========================================================
Model:            MixedLM Dependent Variable: frac_moving
No. Observations: 7066    Method:             ML
No. Groups:       5       Scale:              0.0514
Min. group size:  880     Log-Likelihood:     334.8360
Max. group size:  1690    Converged:          No
Mean group size:  1413.2
---------------------------------------------------------
                 Coef. Std.Err.   z   P>|z| [0.025 0.975]
---------------------------------------------------------
Intercept        0.772    0.079 9.719 0.000  0.617  0.928
epoch2_indicator 0.049    0.005 9.033 0.000  0.038  0.059
Group Var        0.031
animal_day Var   0.008    0.006
pair_id Var      0.000    0.004
=========================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_moving late_air_on_progression
Late air-on progression
==============================
          Mixed Linear Model Regression Results
==========================================================
Model:             MixedLM Dependent Variable: frac_moving
No. Observations:  7068    Method:             ML
No. Groups:        5       Scale:              0.0348
Min. group size:   880     Log-Likelihood:     1711.1737
Max. group size:   1690    Converged:          Yes
Mean group size:   1413.6
----------------------------------------------------------
                 Coef. Std.Err.   z    P>|z| [0.025 0.975]
----------------------------------------------------------
Intercept        0.857    0.079 10.843 0.000  0.702  1.012
epoch2_indicator 0.094    0.004 21.230 0.000  0.085  0.103
Group Var        0.031
animal_day Var   0.008    0.008
pair_id Var      0.000    0.003
==========================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_moving air_offset_transition
Air-offset transition
==============================
           Mixed Linear Model Regression Results
============================================================
Model:             MixedLM  Dependent Variable:  frac_moving
No. Observations:  7048     Method:              ML
No. Groups:        5        Scale:               0.0058
Min. group size:   872      Log-Likelihood:      8001.9831
Max. group size:   1688     Converged:           Yes
Mean group size:   1409.6
------------------------------------------------------------
                 Coef.  Std.Err.    z    P>|z| [0.025 0.975]
------------------------------------------------------------
Intercept         0.973    0.031  31.356 0.000  0.912  1.034
epoch2_indicator -0.046    0.002 -25.390 0.000 -0.050 -0.043
Group Var         0.005
animal_day Var    0.001    0.008
pair_id Var       0.000    0.001
============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_moving early_air_off_recovery
Early air-off recovery
==============================
           Mixed Linear Model Regression Results
============================================================
Model:             MixedLM  Dependent Variable:  frac_moving
No. Observations:  7034     Method:              ML
No. Groups:        5        Scale:               0.0847
Min. group size:   872      Log-Likelihood:      -1423.8593
Max. group size:   1678     Converged:           Yes
Mean group size:   1406.8
------------------------------------------------------------
                 Coef.  Std.Err.    z    P>|z| [0.025 0.975]
------------------------------------------------------------
Intercept         0.921    0.125   7.344 0.000  0.675  1.167
epoch2_indicator -0.515    0.007 -74.253 0.000 -0.529 -0.502
Group Var         0.077
animal_day Var    0.017    0.011
pair_id Var       0.000    0.006
============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2207: ConvergenceWarning: MixedLM optimization failed, trying a different optimizer may help.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2219: ConvergenceWarning: Gradient optimization failed, |grad| = 17.107760
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_moving late_air_off_recovery_to_next_baseline
Late air-off recovery / next pre-air baseline
==============================
           Mixed Linear Model Regression Results
============================================================
Model:             MixedLM  Dependent Variable:  frac_moving
No. Observations:  6916     Method:              ML
No. Groups:        5        Scale:               0.1163
Min. group size:   850      Log-Likelihood:      -3046.7933
Max. group size:   1658     Converged:           No
Mean group size:   1383.2
------------------------------------------------------------
                 Coef.  Std.Err.    z    P>|z| [0.025 0.975]
------------------------------------------------------------
Intercept         0.382    0.026  14.490 0.000  0.331  0.434
epoch2_indicator -0.102    0.008 -12.450 0.000 -0.118 -0.086
Group Var         0.001    0.004
animal_day Var    0.042    0.026
pair_id Var       0.022    0.008
============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_forward air_onset_transition
Air-onset transition
==============================
          Mixed Linear Model Regression Results
==========================================================
Model:            MixedLM Dependent Variable: frac_forward
No. Observations: 7062    Method:             ML
No. Groups:       5       Scale:              0.0969
Min. group size:  880     Log-Likelihood:     -1916.7732
Max. group size:  1690    Converged:          Yes
Mean group size:  1412.4
----------------------------------------------------------
                 Coef. Std.Err.   z    P>|z| [0.025 0.975]
----------------------------------------------------------
Intercept        0.268    0.126  2.124 0.034  0.021  0.516
epoch2_indicator 0.404    0.007 54.457 0.000  0.389  0.418
Group Var        0.078
animal_day Var   0.019    0.027
pair_id Var      0.000    0.005
==========================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_forward early_air_on_progression
Early air-on progression
==============================
          Mixed Linear Model Regression Results
==========================================================
Model:            MixedLM Dependent Variable: frac_forward
No. Observations: 7066    Method:             ML
No. Groups:       5       Scale:              0.0587
Min. group size:  880     Log-Likelihood:     -311.8226
Max. group size:  1690    Converged:          Yes
Mean group size:  1413.2
----------------------------------------------------------
                 Coef. Std.Err.   z    P>|z| [0.025 0.975]
----------------------------------------------------------
Intercept        0.656    0.041 15.891 0.000  0.575  0.737
epoch2_indicator 0.121    0.006 21.051 0.000  0.110  0.133
Group Var        0.007    0.022
animal_day Var   0.017    0.012
pair_id Var      0.003    0.005
==========================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_forward late_air_on_progression
Late air-on progression
==============================
          Mixed Linear Model Regression Results
==========================================================
Model:            MixedLM Dependent Variable: frac_forward
No. Observations: 7068    Method:             ML
No. Groups:       5       Scale:              0.0408
Min. group size:  880     Log-Likelihood:     1115.2366
Max. group size:  1690    Converged:          Yes
Mean group size:  1413.6
----------------------------------------------------------
                 Coef. Std.Err.   z    P>|z| [0.025 0.975]
----------------------------------------------------------
Intercept        0.826    0.046 18.150 0.000  0.737  0.915
epoch2_indicator 0.108    0.005 22.453 0.000  0.098  0.117
Group Var        0.009    0.107
animal_day Var   0.012    0.014
pair_id Var      0.000    0.004
==========================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_forward air_offset_transition
Air-offset transition
==============================
           Mixed Linear Model Regression Results
============================================================
Model:              MixedLM Dependent Variable: frac_forward
No. Observations:   7048    Method:             ML
No. Groups:         5       Scale:              0.0198
Min. group size:    872     Log-Likelihood:     3708.4476
Max. group size:    1688    Converged:          Yes
Mean group size:    1409.6
------------------------------------------------------------
                 Coef.  Std.Err.    z    P>|z| [0.025 0.975]
------------------------------------------------------------
Intercept         0.947    0.061  15.633 0.000  0.828  1.066
epoch2_indicator -0.116    0.003 -34.520 0.000 -0.122 -0.109
Group Var         0.018
animal_day Var    0.003    0.004
pair_id Var       0.000    0.003
============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_forward early_air_off_recovery
Early air-off recovery
==============================
           Mixed Linear Model Regression Results
============================================================
Model:              MixedLM Dependent Variable: frac_forward
No. Observations:   7034    Method:             ML
No. Groups:         5       Scale:              0.0887
Min. group size:    872     Log-Likelihood:     -1587.2717
Max. group size:    1678    Converged:          Yes
Mean group size:    1406.8
------------------------------------------------------------
                 Coef.  Std.Err.    z    P>|z| [0.025 0.975]
------------------------------------------------------------
Intercept         0.826    0.128   6.434 0.000  0.574  1.078
epoch2_indicator -0.453    0.007 -63.764 0.000 -0.467 -0.439
Group Var         0.081
animal_day Var    0.019    0.011
pair_id Var       0.000    0.006
============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_forward late_air_off_recovery_to_next_baseline
Late air-off recovery / next pre-air baseline
==============================
           Mixed Linear Model Regression Results
============================================================
Model:              MixedLM Dependent Variable: frac_forward
No. Observations:   6916    Method:             ML
No. Groups:         5       Scale:              0.1124
Min. group size:    850     Log-Likelihood:     -2904.2775
Max. group size:    1658    Converged:          Yes
Mean group size:    1383.2
------------------------------------------------------------
                 Coef.  Std.Err.    z    P>|z| [0.025 0.975]
------------------------------------------------------------
Intercept         0.362    0.039   9.271 0.000  0.285  0.438
epoch2_indicator -0.100    0.008 -12.420 0.000 -0.116 -0.084
Group Var         0.005    0.014
animal_day Var    0.034    0.018
pair_id Var       0.020    0.008
============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_stationary air_onset_transition
Air-onset transition
==============================
            Mixed Linear Model Regression Results
=============================================================
Model:            MixedLM Dependent Variable: frac_stationary
No. Observations: 7062    Method:             ML
No. Groups:       5       Scale:              0.0867
Min. group size:  880     Log-Likelihood:     -1494.9130
Max. group size:  1690    Converged:          Yes
Mean group size:  1412.4
-------------------------------------------------------------
                  Coef.  Std.Err.    z    P>|z| [0.025 0.975]
-------------------------------------------------------------
Intercept          0.710    0.126   5.648 0.000  0.464  0.956
epoch2_indicator  -0.501    0.007 -71.449 0.000 -0.514 -0.487
Group Var          0.078
animal_day Var     0.011    0.007
pair_id Var        0.000    0.004
=============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_stationary early_air_on_progression
Early air-on progression
==============================
            Mixed Linear Model Regression Results
=============================================================
Model:            MixedLM Dependent Variable: frac_stationary
No. Observations: 7066    Method:             ML
No. Groups:       5       Scale:              0.0514
Min. group size:  880     Log-Likelihood:     334.8360
Max. group size:  1690    Converged:          Yes
Mean group size:  1413.2
-------------------------------------------------------------
                   Coef.  Std.Err.   z    P>|z| [0.025 0.975]
-------------------------------------------------------------
Intercept           0.228    0.079  2.865 0.004  0.072  0.383
epoch2_indicator   -0.049    0.005 -9.033 0.000 -0.059 -0.038
Group Var           0.031
animal_day Var      0.008    0.006
pair_id Var         0.000    0.004
=============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_stationary late_air_on_progression
Late air-on progression
==============================
            Mixed Linear Model Regression Results
=============================================================
Model:            MixedLM Dependent Variable: frac_stationary
No. Observations: 7068    Method:             ML
No. Groups:       5       Scale:              0.0348
Min. group size:  880     Log-Likelihood:     1711.1737
Max. group size:  1690    Converged:          Yes
Mean group size:  1413.6
-------------------------------------------------------------
                  Coef.  Std.Err.    z    P>|z| [0.025 0.975]
-------------------------------------------------------------
Intercept          0.143    0.079   1.813 0.070 -0.012  0.298
epoch2_indicator  -0.094    0.004 -21.230 0.000 -0.103 -0.085
Group Var          0.031
animal_day Var     0.008    0.008
pair_id Var        0.000    0.003
=============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_stationary air_offset_transition
Air-offset transition
==============================
            Mixed Linear Model Regression Results
=============================================================
Model:            MixedLM Dependent Variable: frac_stationary
No. Observations: 7048    Method:             ML
No. Groups:       5       Scale:              0.0058
Min. group size:  872     Log-Likelihood:     8001.9831
Max. group size:  1688    Converged:          Yes
Mean group size:  1409.6
-------------------------------------------------------------
                    Coef. Std.Err.   z    P>|z| [0.025 0.975]
-------------------------------------------------------------
Intercept           0.027    0.031  0.874 0.382 -0.034  0.088
epoch2_indicator    0.046    0.002 25.390 0.000  0.043  0.050
Group Var           0.005
animal_day Var      0.001    0.008
pair_id Var         0.000    0.001
=============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_stationary early_air_off_recovery
Early air-off recovery
==============================
            Mixed Linear Model Regression Results
=============================================================
Model:            MixedLM Dependent Variable: frac_stationary
No. Observations: 7034    Method:             ML
No. Groups:       5       Scale:              0.0847
Min. group size:  872     Log-Likelihood:     -1423.8593
Max. group size:  1678    Converged:          Yes
Mean group size:  1406.8
-------------------------------------------------------------
                    Coef. Std.Err.   z    P>|z| [0.025 0.975]
-------------------------------------------------------------
Intercept           0.079    0.125  0.630 0.529 -0.167  0.325
epoch2_indicator    0.515    0.007 74.253 0.000  0.502  0.529
Group Var           0.077
animal_day Var      0.017    0.011
pair_id Var         0.000    0.006
=============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

==============================
frac_stationary late_air_off_recovery_to_next_baseline
Late air-off recovery / next pre-air baseline
==============================
            Mixed Linear Model Regression Results
=============================================================
Model:            MixedLM Dependent Variable: frac_stationary
No. Observations: 6916    Method:             ML
No. Groups:       5       Scale:              0.1163
Min. group size:  850     Log-Likelihood:     -3046.7933
Max. group size:  1658    Converged:          Yes
Mean group size:  1383.2
-------------------------------------------------------------
                    Coef. Std.Err.   z    P>|z| [0.025 0.975]
-------------------------------------------------------------
Intercept           0.618    0.026 23.412 0.000  0.566  0.669
epoch2_indicator    0.102    0.008 12.450 0.000  0.086  0.118
Group Var           0.001    0.004
animal_day Var      0.042    0.026
pair_id Var         0.022    0.008
=============================================================



==============================
mean_speed_path_cms air_onset_transition
Air-onset transition
==============================
              Mixed Linear Model Regression Results
=================================================================
Model:            MixedLM Dependent Variable: mean_speed_path_cms
No. Observations: 7062    Method:             ML
No. Groups:       5       Scale:              4.3942
Min. group size:  880     Log-Likelihood:     -15570.1983
Max. group size:  1690    Converged:          Yes
Mean group size:  1412.4
------------------------------------------------------------------
                    Coef.  Std.Err.    z     P>|z|  [0.025  0.975]
------------------------------------------------------------------
Intercept           1.334     0.230   5.793  0.000   0.883   1.786
epoch2_indicator    1.560     0.050  31.264  0.000   1.462   1.658
Group Var           0.165     0.079
animal_day Var      1.435     0.119
pair_id Var         0.257     0.040
=================================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
mean_speed_path_cms early_air_on_progression
Early air-on progression
==============================
              Mixed Linear Model Regression Results
=================================================================
Model:            MixedLM Dependent Variable: mean_speed_path_cms
No. Observations: 7066    Method:             ML
No. Groups:       5       Scale:              840.6374
Min. group size:  880     Log-Likelihood:     -33963.4231
Max. group size:  1690    Converged:          Yes
Mean group size:  1413.2
------------------------------------------------------------------
                   Coef.   Std.Err.    z    P>|z|   [0.025  0.975]
------------------------------------------------------------------
Intercept           2.942    11.885  0.248  0.804  -20.352  26.236
epoch2_indicator    2.470     0.690  3.581  0.000    1.118   3.822
Group Var         694.393
animal_day Var    162.078
pair_id Var         6.212     0.494
=================================================================



==============================
mean_speed_path_cms late_air_on_progression
Late air-on progression
==============================
              Mixed Linear Model Regression Results
=================================================================
Model:            MixedLM Dependent Variable: mean_speed_path_cms
No. Observations: 7068    Method:             ML
No. Groups:       5       Scale:              4.1392
Min. group size:  880     Log-Likelihood:     -16549.1009
Max. group size:  1690    Converged:          Yes
Mean group size:  1413.6
------------------------------------------------------------------
                    Coef.  Std.Err.    z     P>|z|  [0.025  0.975]
------------------------------------------------------------------
Intercept           5.249     0.395  13.282  0.000   4.474   6.023
epoch2_indicator    0.873     0.048  18.035  0.000   0.778   0.968
Group Var           0.494     0.240
animal_day Var      4.264     0.361
pair_id Var         2.384     0.074
=================================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
mean_speed_path_cms air_offset_transition
Air-offset transition
==============================
              Mixed Linear Model Regression Results
=================================================================
Model:            MixedLM Dependent Variable: mean_speed_path_cms
No. Observations: 7048    Method:             ML
No. Groups:       5       Scale:              53.1907
Min. group size:  872     Log-Likelihood:     -24133.4892
Max. group size:  1688    Converged:          Yes
Mean group size:  1409.6
------------------------------------------------------------------
                  Coef.   Std.Err.     z     P>|z|  [0.025  0.975]
------------------------------------------------------------------
Intercept          6.207     2.970    2.090  0.037   0.386  12.028
epoch2_indicator  -1.763     0.174  -10.148  0.000  -2.104  -1.423
Group Var         43.506
animal_day Var     7.814     0.418
pair_id Var        0.282     0.121
=================================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
mean_speed_path_cms early_air_off_recovery
Early air-off recovery
==============================
              Mixed Linear Model Regression Results
=================================================================
Model:            MixedLM Dependent Variable: mean_speed_path_cms
No. Observations: 7034    Method:             ML
No. Groups:       5       Scale:              53.4918
Min. group size:  872     Log-Likelihood:     -24093.1622
Max. group size:  1678    Converged:          Yes
Mean group size:  1406.8
------------------------------------------------------------------
                  Coef.   Std.Err.     z     P>|z|  [0.025  0.975]
------------------------------------------------------------------
Intercept          4.515     2.993    1.508  0.131  -1.351  10.381
epoch2_indicator  -2.693     0.174  -15.442  0.000  -3.035  -2.351
Group Var         44.361
animal_day Var     5.266     0.181
pair_id Var        0.292     0.127
=================================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
mean_speed_path_cms late_air_off_recovery_to_next_baseline
Late air-off recovery / next pre-air baseline
==============================
              Mixed Linear Model Regression Results
=================================================================
Model:            MixedLM Dependent Variable: mean_speed_path_cms
No. Observations: 6916    Method:             ML
No. Groups:       5       Scale:              4.2335
Min. group size:  850     Log-Likelihood:     -15430.2722
Max. group size:  1658    Converged:          Yes
Mean group size:  1383.2
------------------------------------------------------------------
                  Coef.   Std.Err.     z     P>|z|  [0.025  0.975]
------------------------------------------------------------------
Intercept          1.813     0.481    3.766  0.000   0.869   2.757
epoch2_indicator  -0.530     0.049  -10.709  0.000  -0.627  -0.433
Group Var          0.954
animal_day Var     3.039     0.262
pair_id Var        0.670     0.046
=================================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
mean_speed_net_cms air_onset_transition
Air-onset transition
==============================
             Mixed Linear Model Regression Results
================================================================
Model:            MixedLM Dependent Variable: mean_speed_net_cms
No. Observations: 7062    Method:             ML
No. Groups:       5       Scale:              5.2130
Min. group size:  880     Log-Likelihood:     -16012.5385
Max. group size:  1690    Converged:          Yes
Mean group size:  1412.4
-----------------------------------------------------------------
                   Coef.  Std.Err.    z     P>|z|  [0.025  0.975]
-----------------------------------------------------------------
Intercept          1.275     0.367   3.479  0.001   0.557   1.994
epoch2_indicator   1.269     0.054  23.352  0.000   1.162   1.375
Group Var          0.568
animal_day Var     1.473     0.123
pair_id Var        0.051     0.040
================================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2207: ConvergenceWarning: MixedLM optimization failed, trying a different optimizer may help.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2219: ConvergenceWarning: Gradient optimization failed, |grad| = 141.348597
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
mean_speed_net_cms early_air_on_progression
Early air-on progression
==============================
             Mixed Linear Model Regression Results
================================================================
Model:            MixedLM Dependent Variable: mean_speed_net_cms
No. Observations: 7066    Method:             ML
No. Groups:       5       Scale:              845.6667
Min. group size:  880     Log-Likelihood:     -33983.3363
Max. group size:  1690    Converged:          No
Mean group size:  1413.2
----------------------------------------------------------------
                      Coef.  Std.Err.   z   P>|z|  [0.025 0.975]
----------------------------------------------------------------
Intercept              2.357   11.921 0.198 0.843 -21.009 25.722
epoch2_indicator       1.274    0.692 1.841 0.066  -0.082  2.630
Group Var            698.920
animal_day Var       158.759
pair_id Var            6.185    0.496
================================================================



==============================
mean_speed_net_cms late_air_on_progression
Late air-on progression
==============================
             Mixed Linear Model Regression Results
================================================================
Model:            MixedLM Dependent Variable: mean_speed_net_cms
No. Observations: 7068    Method:             ML
No. Groups:       5       Scale:              4.6037
Min. group size:  880     Log-Likelihood:     -16876.3504
Max. group size:  1690    Converged:          Yes
Mean group size:  1413.6
-----------------------------------------------------------------
                   Coef.  Std.Err.    z     P>|z|  [0.025  0.975]
-----------------------------------------------------------------
Intercept          5.140     0.405  12.693  0.000   4.346   5.933
epoch2_indicator   0.924     0.051  18.108  0.000   0.824   1.024
Group Var          0.535     0.239
animal_day Var     4.216     0.339
pair_id Var        2.526     0.076
================================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2207: ConvergenceWarning: MixedLM optimization failed, trying a different optimizer may help.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2219: ConvergenceWarning: Gradient optimization failed, |grad| = 69.917509
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
mean_speed_net_cms air_offset_transition
Air-offset transition
==============================
             Mixed Linear Model Regression Results
================================================================
Model:            MixedLM Dependent Variable: mean_speed_net_cms
No. Observations: 7048    Method:             ML
No. Groups:       5       Scale:              53.9589
Min. group size:  872     Log-Likelihood:     -24182.6504
Max. group size:  1688    Converged:          No
Mean group size:  1409.6
----------------------------------------------------------------
                     Coef.  Std.Err.    z    P>|z| [0.025 0.975]
----------------------------------------------------------------
Intercept             6.117    2.996   2.042 0.041  0.245 11.989
epoch2_indicator     -2.333    0.175 -13.329 0.000 -2.676 -1.990
Group Var            44.302
animal_day Var        7.585    0.380
pair_id Var           0.287    0.123
================================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
mean_speed_net_cms early_air_off_recovery
Early air-off recovery
==============================
             Mixed Linear Model Regression Results
================================================================
Model:            MixedLM Dependent Variable: mean_speed_net_cms
No. Observations: 7034    Method:             ML
No. Groups:       5       Scale:              53.8856
Min. group size:  872     Log-Likelihood:     -24119.0702
Max. group size:  1678    Converged:          Yes
Mean group size:  1406.8
----------------------------------------------------------------
                     Coef.  Std.Err.    z    P>|z| [0.025 0.975]
----------------------------------------------------------------
Intercept             3.856    3.007   1.282 0.200 -2.038  9.749
epoch2_indicator     -2.130    0.175 -12.171 0.000 -2.474 -1.787
Group Var            44.775
animal_day Var        5.338    0.181
pair_id Var           0.293    0.127
================================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
mean_speed_net_cms late_air_off_recovery_to_next_baseline
Late air-off recovery / next pre-air baseline
==============================
             Mixed Linear Model Regression Results
================================================================
Model:            MixedLM Dependent Variable: mean_speed_net_cms
No. Observations: 6916    Method:             ML
No. Groups:       5       Scale:              4.8512
Min. group size:  850     Log-Likelihood:     -15550.8145
Max. group size:  1658    Converged:          Yes
Mean group size:  1383.2
----------------------------------------------------------------
                     Coef.  Std.Err.    z    P>|z| [0.025 0.975]
----------------------------------------------------------------
Intercept             1.757    0.777   2.260 0.024  0.234  3.280
epoch2_indicator     -0.530    0.053 -10.008 0.000 -0.634 -0.426
Group Var             2.926
animal_day Var        1.332    0.059
pair_id Var           0.219    0.038
================================================================



==============================
distance_path_cm air_onset_transition
Air-onset transition
==============================
            Mixed Linear Model Regression Results
==============================================================
Model:            MixedLM Dependent Variable: distance_path_cm
No. Observations: 7062    Method:             ML
No. Groups:       5       Scale:              4.3847
Min. group size:  880     Log-Likelihood:     -15566.7130
Max. group size:  1690    Converged:          Yes
Mean group size:  1412.4
--------------------------------------------------------------
                     Coef. Std.Err.   z    P>|z| [0.025 0.975]
--------------------------------------------------------------
Intercept            1.337    0.230  5.805 0.000  0.886  1.789
epoch2_indicator     1.571    0.050 31.532 0.000  1.474  1.669
Group Var            0.165    0.079
animal_day Var       1.438    0.119
pair_id Var          0.262    0.040
==============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2207: ConvergenceWarning: MixedLM optimization failed, trying a different optimizer may help.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2219: ConvergenceWarning: Gradient optimization failed, |grad| = 141.881487
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
distance_path_cm early_air_on_progression
Early air-on progression
==============================
            Mixed Linear Model Regression Results
==============================================================
Model:            MixedLM Dependent Variable: distance_path_cm
No. Observations: 7066    Method:             ML
No. Groups:       5       Scale:              840.6340
Min. group size:  880     Log-Likelihood:     -33963.4007
Max. group size:  1690    Converged:          No
Mean group size:  1413.2
--------------------------------------------------------------
                    Coef.  Std.Err.   z   P>|z|  [0.025 0.975]
--------------------------------------------------------------
Intercept            2.957   11.885 0.249 0.804 -20.337 26.251
epoch2_indicator     2.462    0.690 3.569 0.000   1.110  3.814
Group Var          694.394
animal_day Var     162.042
pair_id Var          6.212    0.494
==============================================================



==============================
distance_path_cm late_air_on_progression
Late air-on progression
==============================
            Mixed Linear Model Regression Results
==============================================================
Model:            MixedLM Dependent Variable: distance_path_cm
No. Observations: 7068    Method:             ML
No. Groups:       5       Scale:              4.1342
Min. group size:  880     Log-Likelihood:     -16544.0407
Max. group size:  1690    Converged:          Yes
Mean group size:  1413.6
--------------------------------------------------------------
                     Coef. Std.Err.   z    P>|z| [0.025 0.975]
--------------------------------------------------------------
Intercept            5.254    0.395 13.316 0.000  4.481  6.027
epoch2_indicator     0.861    0.048 17.810 0.000  0.767  0.956
Group Var            0.492    0.240
animal_day Var       4.261    0.361
pair_id Var          2.379    0.074
==============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
distance_path_cm air_offset_transition
Air-offset transition
==============================
            Mixed Linear Model Regression Results
==============================================================
Model:            MixedLM Dependent Variable: distance_path_cm
No. Observations: 7048    Method:             ML
No. Groups:       5       Scale:              53.3211
Min. group size:  872     Log-Likelihood:     -24142.2225
Max. group size:  1688    Converged:          Yes
Mean group size:  1409.6
--------------------------------------------------------------
                    Coef.  Std.Err.   z    P>|z| [0.025 0.975]
--------------------------------------------------------------
Intercept            6.201    2.974  2.085 0.037  0.373 12.029
epoch2_indicator    -1.735    0.174 -9.974 0.000 -2.076 -1.394
Group Var           43.614
animal_day Var       7.849    0.427
pair_id Var          0.283    0.122
==============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
distance_path_cm early_air_off_recovery
Early air-off recovery
==============================
            Mixed Linear Model Regression Results
==============================================================
Model:            MixedLM Dependent Variable: distance_path_cm
No. Observations: 7034    Method:             ML
No. Groups:       5       Scale:              53.6232
Min. group size:  872     Log-Likelihood:     -24102.0105
Max. group size:  1678    Converged:          Yes
Mean group size:  1406.8
--------------------------------------------------------------
                   Coef.  Std.Err.    z    P>|z| [0.025 0.975]
--------------------------------------------------------------
Intercept           4.537    2.997   1.514 0.130 -1.336 10.411
epoch2_indicator   -2.711    0.175 -15.526 0.000 -3.054 -2.369
Group Var          44.467
animal_day Var      5.309    0.185
pair_id Var         0.294    0.127
==============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
distance_path_cm late_air_off_recovery_to_next_baseline
Late air-off recovery / next pre-air baseline
==============================
            Mixed Linear Model Regression Results
==============================================================
Model:            MixedLM Dependent Variable: distance_path_cm
No. Observations: 6916    Method:             ML
No. Groups:       5       Scale:              4.2408
Min. group size:  850     Log-Likelihood:     -15430.8105
Max. group size:  1658    Converged:          Yes
Mean group size:  1383.2
--------------------------------------------------------------
                   Coef.  Std.Err.    z    P>|z| [0.025 0.975]
--------------------------------------------------------------
Intercept           1.816    0.538   3.374 0.001  0.761  2.871
epoch2_indicator   -0.530    0.050 -10.699 0.000 -0.627 -0.433
Group Var           1.243
animal_day Var      3.060    0.265
pair_id Var         0.661    0.046
==============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
distance_net_cm air_onset_transition
Air-onset transition
==============================
            Mixed Linear Model Regression Results
=============================================================
Model:            MixedLM Dependent Variable: distance_net_cm
No. Observations: 7062    Method:             ML
No. Groups:       5       Scale:              5.2048
Min. group size:  880     Log-Likelihood:     -16015.2540
Max. group size:  1690    Converged:          Yes
Mean group size:  1412.4
-------------------------------------------------------------
                    Coef. Std.Err.   z    P>|z| [0.025 0.975]
-------------------------------------------------------------
Intercept           1.276    0.384  3.321 0.001  0.523  2.028
epoch2_indicator    1.268    0.054 23.361 0.000  1.162  1.375
Group Var           0.643
animal_day Var      1.338    0.102
pair_id Var         0.068    0.040
=============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
distance_net_cm early_air_on_progression
Early air-on progression
==============================
            Mixed Linear Model Regression Results
=============================================================
Model:            MixedLM Dependent Variable: distance_net_cm
No. Observations: 7066    Method:             ML
No. Groups:       5       Scale:              845.6728
Min. group size:  880     Log-Likelihood:     -33983.3637
Max. group size:  1690    Converged:          Yes
Mean group size:  1413.2
-------------------------------------------------------------
                   Coef.  Std.Err.   z   P>|z|  [0.025 0.975]
-------------------------------------------------------------
Intercept           2.356   11.921 0.198 0.843 -21.009 25.721
epoch2_indicator    1.274    0.692 1.841 0.066  -0.082  2.630
Group Var         698.925
animal_day Var    158.768
pair_id Var         6.185    0.496
=============================================================



==============================
distance_net_cm late_air_on_progression
Late air-on progression
==============================
            Mixed Linear Model Regression Results
=============================================================
Model:            MixedLM Dependent Variable: distance_net_cm
No. Observations: 7068    Method:             ML
No. Groups:       5       Scale:              4.6135
Min. group size:  880     Log-Likelihood:     -16882.0678
Max. group size:  1690    Converged:          Yes
Mean group size:  1413.6
-------------------------------------------------------------
                    Coef. Std.Err.   z    P>|z| [0.025 0.975]
-------------------------------------------------------------
Intercept           5.139    0.405 12.689 0.000  4.345  5.933
epoch2_indicator    0.914    0.051 17.885 0.000  0.814  1.014
Group Var           0.535    0.239
animal_day Var      4.220    0.339
pair_id Var         2.526    0.076
=============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
distance_net_cm air_offset_transition
Air-offset transition
==============================
            Mixed Linear Model Regression Results
=============================================================
Model:            MixedLM Dependent Variable: distance_net_cm
No. Observations: 7048    Method:             ML
No. Groups:       5       Scale:              53.9681
Min. group size:  872     Log-Likelihood:     -24183.2492
Max. group size:  1688    Converged:          Yes
Mean group size:  1409.6
-------------------------------------------------------------
                  Coef.  Std.Err.    z    P>|z| [0.025 0.975]
-------------------------------------------------------------
Intercept          6.106    2.996   2.038 0.042  0.233 11.979
epoch2_indicator  -2.317    0.175 -13.240 0.000 -2.660 -1.974
Group Var         44.309
animal_day Var     7.586    0.380
pair_id Var        0.287    0.123
=============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
distance_net_cm early_air_off_recovery
Early air-off recovery
==============================
            Mixed Linear Model Regression Results
=============================================================
Model:            MixedLM Dependent Variable: distance_net_cm
No. Observations: 7034    Method:             ML
No. Groups:       5       Scale:              53.8904
Min. group size:  872     Log-Likelihood:     -24119.4034
Max. group size:  1678    Converged:          Yes
Mean group size:  1406.8
-------------------------------------------------------------
                  Coef.  Std.Err.    z    P>|z| [0.025 0.975]
-------------------------------------------------------------
Intercept          3.860    3.007   1.284 0.199 -2.034  9.754
epoch2_indicator  -2.136    0.175 -12.199 0.000 -2.479 -1.792
Group Var         44.779
animal_day Var     5.342    0.181
pair_id Var        0.293    0.127
=============================================================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

==============================
distance_net_cm late_air_off_recovery_to_next_baseline
Late air-off recovery / next pre-air baseline
==============================
            Mixed Linear Model Regression Results
=============================================================
Model:            MixedLM Dependent Variable: distance_net_cm
No. Observations: 6916    Method:             ML
No. Groups:       5       Scale:              4.3440
Min. group size:  850     Log-Likelihood:     -15524.3012
Max. group size:  1658    Converged:          Yes
Mean group size:  1383.2
-------------------------------------------------------------
                  Coef.  Std.Err.    z    P>|z| [0.025 0.975]
-------------------------------------------------------------
Intercept          1.754    0.774   2.265 0.024  0.236  3.271
epoch2_indicator  -0.530    0.050 -10.573 0.000 -0.628 -0.432
Group Var          2.810
animal_day Var     2.761    0.218
pair_id Var        0.699    0.047
=============================================================

In [ ]:
def extract_air_basic_result(model, outcome, comparison, interpretation):
    fe = model.fe_params
    bse = model.bse_fe
    pvals = model.pvalues.loc[fe.index]
    conf = model.conf_int().loc[fe.index]

    term = "epoch2_indicator"

    return {
        "outcome": outcome,
        "comparison": comparison,
        "interpretation": interpretation,
        "n_obs": int(model.nobs),
        "n_animals": len(model.model.group_labels),
        "estimate_epoch2_minus_epoch1": fe.get(term, np.nan),
        "SE": bse.get(term, np.nan),
        "z": fe.get(term, np.nan) / bse.get(term, np.nan),
        "p": pvals.get(term, np.nan),
        "ci_low": conf.loc[term, 0] if term in conf.index else np.nan,
        "ci_high": conf.loc[term, 1] if term in conf.index else np.nan,
        "converged": model.converged,
    }


basic_rows = []

for outcome in air_outcomes:
    for comp in air_comparisons:
        key = (outcome, comp["comparison"])
        if key not in air_basic_models:
            continue

        basic_rows.append(
            extract_air_basic_result(
                air_basic_models[key],
                outcome=outcome,
                comparison=comp["comparison"],
                interpretation=comp["interpretation"],
            )
        )

air_basic_results_df = pd.DataFrame(basic_rows)

air_basic_results_df

In [ ]:
outcome_order = {
    "frac_moving": 1,
    "frac_forward": 2,
    "frac_stationary": 3,
    "mean_speed_path_cms": 4,
    "mean_speed_net_cms": 5,
    "distance_path_cm": 6,
    "distance_net_cm": 7,
    "dist_path_cm": 6,
    "dist_net_cm": 7,
}

comparison_order = {
    "air_onset_transition": 1,
    "early_air_on_progression": 2,
    "late_air_on_progression": 3,
    "air_offset_transition": 4,
    "early_air_off_recovery": 5,
    "late_air_off_recovery_to_next_baseline": 6,
}

air_basic_results_df["outcome_order"] = air_basic_results_df["outcome"].map(outcome_order)
air_basic_results_df["comparison_order"] = air_basic_results_df["comparison"].map(comparison_order)

air_basic_results_df = (
    air_basic_results_df
    .sort_values(["outcome_order", "comparison_order"])
    .reset_index(drop=True)
)

air_basic_results_df

Omnibus Model

In [12]:
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from scipy import stats

# --------------------------------------------------
# Full air-cycle epoch order
# --------------------------------------------------

air_cycle_order = [
    "pre_air_on",
    "post_air_on",
    "pre_air_on_mid",
    "post_air_on_mid",
    "pre_air_off",
    "post_air_off",
    "pre_air_off_mid",
    "post_air_off_mid",
    "pre_air_on_next",
]


def make_air_cycle_df(air_window_df):
    """
    Build long-format full air-cycle dataframe.

    One cycle = trial N.

    Includes:
        pre_air_on from trial N
        ...
        post_air_off_mid from trial N
        pre_air_on_next from trial N+1
    """

    df = air_window_df.copy()

    # current-trial epochs
    cur = df[
        df["epoch_label"].isin([
            "pre_air_on",
            "post_air_on",
            "pre_air_on_mid",
            "post_air_on_mid",
            "pre_air_off",
            "post_air_off",
            "pre_air_off_mid",
            "post_air_off_mid",
        ])
    ].copy()

    cur["cycle_trial"] = cur["event_number"].astype(int)
    cur["air_cycle_epoch"] = cur["epoch_label"]

    # next pre-air baseline:
    # pre_air_on from trial N+1 gets assigned to cycle_trial N
    nxt = df[df["epoch_label"] == "pre_air_on"].copy()
    nxt["cycle_trial"] = nxt["event_number"].astype(int) - 1
    nxt["air_cycle_epoch"] = "pre_air_on_next"

    # keep only valid next-baseline rows
    nxt = nxt[nxt["cycle_trial"] >= 1].copy()

    air_cycle_df = pd.concat([cur, nxt], ignore_index=True)

    # cycle/session IDs
    air_cycle_df["animal_day"] = (
        air_cycle_df["animal"].astype(str) + ":" +
        air_cycle_df["date"].astype(str)
    )

    air_cycle_df["cycle_id"] = (
        air_cycle_df["animal"].astype(str) + ":" +
        air_cycle_df["date"].astype(str) + ":" +
        air_cycle_df["cycle_trial"].astype(str)
    )

    # --------------------------------------------------
    # Use pre_air_on of the cycle as the cycle-level time/session reference
    # --------------------------------------------------
    cycle_info = (
        air_cycle_df[air_cycle_df["air_cycle_epoch"] == "pre_air_on"]
        [["animal", "date", "cycle_trial", "session_time_min", "exposure_session"]]
        .drop_duplicates()
        .rename(columns={
            "session_time_min": "cycle_session_time_min",
            "exposure_session": "cycle_exposure_session",
        })
    )

    air_cycle_df = air_cycle_df.merge(
        cycle_info,
        on=["animal", "date", "cycle_trial"],
        how="left"
    )

    # ordered categorical
    air_cycle_df["air_cycle_epoch"] = pd.Categorical(
        air_cycle_df["air_cycle_epoch"],
        categories=air_cycle_order,
        ordered=True,
    )

    # center predictors for later time-dependent model
    air_cycle_df["cycle_exposure_session_c"] = (
        air_cycle_df["cycle_exposure_session"] -
        air_cycle_df["cycle_exposure_session"].mean()
    )

    air_cycle_df["cycle_session_10m_c"] = (
        air_cycle_df["cycle_session_time_min"] -
        air_cycle_df["cycle_session_time_min"].mean()
    ) / 10.0

    return air_cycle_df.reset_index(drop=True)


air_cycle_df = make_air_cycle_df(air_window_df)

print(air_cycle_df.shape)
print(air_cycle_df["air_cycle_epoch"].value_counts().sort_index())

(31609, 70)
air_cycle_epoch
pre_air_on          3532
post_air_on         3535
pre_air_on_mid      3534
post_air_on_mid     3535
pre_air_off         3535
post_air_off        3525
pre_air_off_mid     3517
post_air_off_mid    3516
pre_air_on_next     3380
Name: count, dtype: int64

In [13]:
air_cycle_df[
    [
        "animal", "date", "cycle_trial",
        "air_cycle_epoch",
        "event_number",
        "cycle_exposure_session",
        "cycle_session_time_min",
    ]
].head(30)

,animal,date,cycle_trial,air_cycle_epoch,event_number,cycle_exposure_session,cycle_session_time_min
0,NML_04,2026_01_12,0,post_air_off_mid,0,NaN,NaN
1,NML_04,2026_01_12,0,pre_air_off_mid,0,NaN,NaN
2,NML_04,2026_01_12,0,post_air_off,0,NaN,NaN
3,NML_04,2026_01_12,0,pre_air_off,0,NaN,NaN
4,NML_04,2026_01_12,0,post_air_on_mid,0,NaN,NaN
5,NML_04,2026_01_12,0,pre_air_on_mid,0,NaN,NaN
6,NML_04,2026_01_12,0,post_air_on,0,NaN,NaN
7,NML_04,2026_01_12,1,post_air_off_mid,1,1.0,0.332607
8,NML_04,2026_01_12,1,pre_air_off_mid,1,1.0,0.332607
9,NML_04,2026_01_12,1,post_air_off,1,1.0,0.332607
10,NML_04,2026_01_12,1,pre_air_off,1,1.0,0.332607
11,NML_04,2026_01_12,1,post_air_on_mid,1,1.0,0.332607
12,NML_04,2026_01_12,1,pre_air_on_mid,1,1.0,0.332607
13,NML_04,2026_01_12,1,post_air_on,1,1.0,0.332607
14,NML_04,2026_01_12,1,pre_air_on,1,1.0,0.332607
15,NML_04,2026_01_12,2,post_air_off_mid,2,1.0,0.651090
16,NML_04,2026_01_12,2,pre_air_off_mid,2,1.0,0.651090
17,NML_04,2026_01_12,2,post_air_off,2,1.0,0.651090
18,NML_04,2026_01_12,2,pre_air_off,2,1.0,0.651090
19,NML_04,2026_01_12,2,post_air_on_mid,2,1.0,0.651090
20,NML_04,2026_01_12,2,pre_air_on_mid,2,1.0,0.651090
21,NML_04,2026_01_12,2,post_air_on,2,1.0,0.651090
22,NML_04,2026_01_12,2,pre_air_on,2,1.0,0.651090
23,NML_04,2026_01_12,3,post_air_off_mid,3,1.0,0.939413
24,NML_04,2026_01_12,3,pre_air_off_mid,3,1.0,0.939413
25,NML_04,2026_01_12,3,post_air_off,3,1.0,0.939413
26,NML_04,2026_01_12,3,pre_air_off,3,1.0,0.939413
27,NML_04,2026_01_12,3,post_air_on_mid,3,1.0,0.939413
28,NML_04,2026_01_12,3,pre_air_on_mid,3,1.0,0.939413
29,NML_04,2026_01_12,3,post_air_on,3,1.0,0.939413

In [39]:
def fit_air_cycle_omnibus_model(
    air_cycle_df,
    outcome,
    include_cycle_random=True,
):
    """
    Omnibus model across the full air cycle.

    outcome ~ C(air_cycle_epoch)

    Reference epoch should be pre_air_on because it is the first category.
    """

    df = air_cycle_df.copy()
    df = df[np.isfinite(df[outcome])].copy()

    if include_cycle_random:
        vc = {
            "animal_day": "0 + C(animal_day)",
            "cycle_id": "0 + C(cycle_id)",
        }
    else:
        vc = {
            "animal_day": "0 + C(animal_day)",
        }

    model = smf.mixedlm(
        f"{outcome} ~ C(air_cycle_epoch)",
        data=df,
        groups=df["animal"],
        re_formula="1",
        vc_formula=vc,
    ).fit(
        reml=False,
        method="lbfgs",
        maxiter=1000,
    )

    return model

In [40]:
main_air_outcomes = [
    "frac_moving",
    "frac_forward",
    "mean_speed_path_cms",
    "mean_speed_net_cms",
]

main_air_outcomes = [
    x for x in main_air_outcomes
    if x in air_cycle_df.columns
]

air_cycle_models = {}

for outcome in main_air_outcomes:
    print("\n\n==============================")
    print(outcome)
    print("==============================")

    try:
        model = fit_air_cycle_omnibus_model(
            air_cycle_df,
            outcome=outcome,
            include_cycle_random=True,
        )

        air_cycle_models[outcome] = model
        print(model.summary())

    except Exception as e:
        print(f"[ERROR] {outcome}: {e}")

==============================
frac_moving
==============================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

                      Mixed Linear Model Regression Results
=================================================================================
Model:                    MixedLM         Dependent Variable:         frac_moving
No. Observations:         31609           Method:                     ML
No. Groups:               5               Scale:                      0.0919
Min. group size:          3918            Log-Likelihood:             -7889.2536
Max. group size:          7562            Converged:                  Yes
Mean group size:          6321.8
---------------------------------------------------------------------------------
                                       Coef.  Std.Err.   z    P>|z| [0.025 0.975]
---------------------------------------------------------------------------------
Intercept                               0.273    0.121  2.257 0.024  0.036  0.510
C(air_cycle_epoch)[T.post_air_on]       0.501    0.007 69.438 0.000  0.487  0.515
C(air_cycle_epoch)[T.pre_air_on_mid]    0.549    0.007 76.151 0.000  0.535  0.563
C(air_cycle_epoch)[T.post_air_on_mid]   0.595    0.007 82.458 0.000  0.581  0.609
C(air_cycle_epoch)[T.pre_air_off]       0.689    0.007 95.493 0.000  0.675  0.703
C(air_cycle_epoch)[T.post_air_off]      0.644    0.007 89.202 0.000  0.630  0.658
C(air_cycle_epoch)[T.pre_air_off_mid]   0.128    0.007 17.765 0.000  0.114  0.142
C(air_cycle_epoch)[T.post_air_off_mid]  0.102    0.007 14.141 0.000  0.088  0.116
C(air_cycle_epoch)[T.pre_air_on_next]  -0.005    0.007 -0.664 0.507 -0.019  0.009
Group Var                               0.070
animal_day Var                          0.042
cycle_id Var                            0.004    0.001
=================================================================================



==============================
frac_forward
==============================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

                      Mixed Linear Model Regression Results
=================================================================================
Model:                     MixedLM        Dependent Variable:        frac_forward
No. Observations:          31609          Method:                    ML
No. Groups:                5              Scale:                     0.1001
Min. group size:           3918           Log-Likelihood:            -9014.6526
Max. group size:           7562           Converged:                 Yes
Mean group size:           6321.8
---------------------------------------------------------------------------------
                                       Coef.  Std.Err.   z    P>|z| [0.025 0.975]
---------------------------------------------------------------------------------
Intercept                               0.252    0.024 10.625 0.000  0.206  0.299
C(air_cycle_epoch)[T.post_air_on]       0.403    0.008 53.614 0.000  0.389  0.418
C(air_cycle_epoch)[T.pre_air_on_mid]    0.524    0.008 69.690 0.000  0.510  0.539
C(air_cycle_epoch)[T.post_air_on_mid]   0.585    0.008 77.750 0.000  0.570  0.600
C(air_cycle_epoch)[T.pre_air_off]       0.693    0.008 92.066 0.000  0.678  0.708
C(air_cycle_epoch)[T.post_air_off]      0.579    0.008 76.828 0.000  0.564  0.593
C(air_cycle_epoch)[T.pre_air_off_mid]   0.126    0.008 16.688 0.000  0.111  0.141
C(air_cycle_epoch)[T.post_air_off_mid]  0.101    0.008 13.401 0.000  0.086  0.116
C(air_cycle_epoch)[T.pre_air_on_next]  -0.003    0.008 -0.420 0.674 -0.018  0.012
Group Var                               0.002    0.005
animal_day Var                          0.008    0.005
cycle_id Var                            0.003    0.001
=================================================================================



==============================
mean_speed_path_cms
==============================
                      Mixed Linear Model Regression Results
=================================================================================
Model:                  MixedLM      Dependent Variable:      mean_speed_path_cms
No. Observations:       31609        Method:                  ML
No. Groups:             5            Scale:                   207.5612
Min. group size:        3918         Log-Likelihood:          -129254.4554
Max. group size:        7562         Converged:               Yes
Mean group size:        6321.8
---------------------------------------------------------------------------------
                                       Coef.  Std.Err.   z    P>|z| [0.025 0.975]
---------------------------------------------------------------------------------
Intercept                               1.299    0.333  3.899 0.000  0.646  1.952
C(air_cycle_epoch)[T.post_air_on]       1.560    0.343  4.552 0.000  0.888  2.232
C(air_cycle_epoch)[T.pre_air_on_mid]    4.027    0.343 11.749 0.000  3.356  4.699
C(air_cycle_epoch)[T.post_air_on_mid]   4.225    0.343 12.327 0.000  3.553  4.897
C(air_cycle_epoch)[T.pre_air_off]       5.096    0.343 14.868 0.000  4.424  5.768
C(air_cycle_epoch)[T.post_air_off]      3.345    0.343  9.753 0.000  2.673  4.018
C(air_cycle_epoch)[T.pre_air_off_mid]   0.654    0.343  1.906 0.057 -0.018  1.327
C(air_cycle_epoch)[T.post_air_off_mid]  0.525    0.343  1.530 0.126 -0.148  1.198
C(air_cycle_epoch)[T.pre_air_on_next]  -0.010    0.347 -0.030 0.976 -0.690  0.669
Group Var                               0.102    0.013
animal_day Var                          2.334    0.033
cycle_id Var                            0.192    0.046
=================================================================================



==============================
mean_speed_net_cms
==============================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

                       Mixed Linear Model Regression Results
===================================================================================
Model:                   MixedLM       Dependent Variable:       mean_speed_net_cms
No. Observations:        31609         Method:                   ML
No. Groups:              5             Scale:                    209.2914
Min. group size:         3918          Log-Likelihood:           -129395.2857
Max. group size:         7562          Converged:                Yes
Mean group size:         6321.8
-----------------------------------------------------------------------------------
                                        Coef.  Std.Err.   z    P>|z|  [0.025 0.975]
-----------------------------------------------------------------------------------
Intercept                                1.134    6.116  0.185 0.853 -10.854 13.122
C(air_cycle_epoch)[T.post_air_on]        1.270    0.344  3.689 0.000   0.595  1.944
C(air_cycle_epoch)[T.pre_air_on_mid]     2.541    0.344  7.382 0.000   1.866  3.216
C(air_cycle_epoch)[T.post_air_on_mid]    4.176    0.344 12.134 0.000   3.502  4.851
C(air_cycle_epoch)[T.pre_air_off]        5.099    0.344 14.815 0.000   4.424  5.774
C(air_cycle_epoch)[T.post_air_off]       2.778    0.344  8.067 0.000   2.103  3.453
C(air_cycle_epoch)[T.pre_air_off_mid]    0.650    0.345  1.886 0.059  -0.025  1.325
C(air_cycle_epoch)[T.post_air_off_mid]   0.527    0.345  1.531 0.126  -0.148  1.203
C(air_cycle_epoch)[T.pre_air_on_next]   -0.010    0.348 -0.028 0.978  -0.692  0.673
Group Var                              186.567
animal_day Var                           2.666    0.037
cycle_id Var                             0.056    0.045
===================================================================================

In [41]:
air_adjacent_contrasts = [
    ("pre_air_on", "post_air_on", "Air-onset transition"),
    ("post_air_on", "pre_air_on_mid", "Early air-on progression"),
    ("pre_air_on_mid", "post_air_on_mid", "Air-on midpoint transition"),
    ("post_air_on_mid", "pre_air_off", "Late air-on progression"),
    ("pre_air_off", "post_air_off", "Air-offset transition"),
    ("post_air_off", "pre_air_off_mid", "Early air-off recovery"),
    ("pre_air_off_mid", "post_air_off_mid", "Air-off midpoint transition"),
    ("post_air_off_mid", "pre_air_on_next", "Late air-off recovery / next baseline"),
]


def _epoch_term_name(result, epoch):
    """
    Return the fixed-effect term name for an air_cycle_epoch level.

    Baseline level has no term and returns None.
    """
    if epoch == "pre_air_on":
        return None

    target = f"C(air_cycle_epoch)[T.{epoch}]"

    if target in result.fe_params.index:
        return target

    # fallback search
    matches = [
        term for term in result.fe_params.index
        if f"T.{epoch}" in term
    ]

    if len(matches) == 1:
        return matches[0]

    raise ValueError(f"Could not find term for epoch: {epoch}")


def contrast_air_cycle_epochs(result, epoch1, epoch2, label="contrast"):
    """
    Contrast epoch2 - epoch1 from omnibus air-cycle model.
    """

    fe = result.fe_params
    cov = result.cov_params().loc[fe.index, fe.index]

    L = pd.Series(0.0, index=fe.index)

    term1 = _epoch_term_name(result, epoch1)
    term2 = _epoch_term_name(result, epoch2)

    # epoch2 - epoch1
    if term2 is not None:
        L[term2] += 1.0
    if term1 is not None:
        L[term1] -= 1.0

    estimate = float(np.dot(L.values, fe.values))
    se = float(np.sqrt(np.dot(L.values, np.dot(cov.values, L.values))))
    z = estimate / se
    p = 2 * (1 - stats.norm.cdf(abs(z)))

    return {
        "contrast": label,
        "epoch1": epoch1,
        "epoch2": epoch2,
        "estimate_epoch2_minus_epoch1": estimate,
        "SE": se,
        "z": z,
        "p": p,
        "ci_low": estimate - 1.96 * se,
        "ci_high": estimate + 1.96 * se,
    }


def extract_air_cycle_adjacent_contrasts(model, outcome):
    rows = []

    for epoch1, epoch2, label in air_adjacent_contrasts:
        row = contrast_air_cycle_epochs(
            model,
            epoch1=epoch1,
            epoch2=epoch2,
            label=label,
        )
        row["outcome"] = outcome
        rows.append(row)

    return pd.DataFrame(rows)

In [42]:
air_cycle_contrast_tables = []

for outcome, model in air_cycle_models.items():
    tmp = extract_air_cycle_adjacent_contrasts(model, outcome)
    air_cycle_contrast_tables.append(tmp)

air_cycle_contrasts_df = pd.concat(
    air_cycle_contrast_tables,
    ignore_index=True
)

air_cycle_contrasts_df

,contrast,epoch1,epoch2,estimate_epoch2_minus_epoch1,SE,z,p,ci_low,ci_high,outcome
0,Air-onset transition,pre_air_on,post_air_on,0.500773,0.007212,69.437825,0.000000e+00,0.486638,0.514908,frac_moving
1,Early air-on progression,post_air_on,pre_air_on_mid,0.048449,0.007211,6.718941,1.830491e-11,0.034316,0.062582,frac_moving
2,Air-on midpoint transition,pre_air_on_mid,post_air_on_mid,0.045448,0.007211,6.302772,2.923688e-10,0.031315,0.059581,frac_moving
3,Late air-on progression,post_air_on_mid,pre_air_off,0.094007,0.007210,13.038056,0.000000e+00,0.079875,0.108140,frac_moving
4,Air-offset transition,pre_air_off,post_air_off,-0.044892,0.007216,-6.221477,4.924976e-10,-0.059034,-0.030749,frac_moving
5,Early air-off recovery,post_air_off,pre_air_off_mid,-0.515500,0.007225,-71.352740,0.000000e+00,-0.529660,-0.501340,frac_moving
6,Air-off midpoint transition,pre_air_off_mid,post_air_off_mid,-0.026158,0.007229,-3.618415,2.964125e-04,-0.040327,-0.011989,frac_moving
7,Late air-off recovery / next baseline,post_air_off_mid,pre_air_on_next,-0.106972,0.007304,-14.644814,0.000000e+00,-0.121289,-0.092655,frac_moving
8,Air-onset transition,pre_air_on,post_air_on,0.403463,0.007525,53.613893,0.000000e+00,0.388714,0.418213,frac_forward
9,Early air-on progression,post_air_on,pre_air_on_mid,0.121013,0.007524,16.083079,0.000000e+00,0.106266,0.135761,frac_forward
10,Air-on midpoint transition,pre_air_on_mid,post_air_on_mid,0.060618,0.007524,8.056350,8.881784e-16,0.045871,0.075366,frac_forward
11,Late air-on progression,post_air_on_mid,pre_air_off,0.107733,0.007524,14.319191,0.000000e+00,0.092987,0.122480,frac_forward
12,Air-offset transition,pre_air_off,post_air_off,-0.114251,0.007529,-15.174332,0.000000e+00,-0.129008,-0.099494,frac_forward
13,Early air-off recovery,post_air_off,pre_air_off_mid,-0.452833,0.007539,-60.067366,0.000000e+00,-0.467609,-0.438057,frac_forward
14,Air-off midpoint transition,pre_air_off_mid,post_air_off_mid,-0.024756,0.007543,-3.281786,1.031519e-03,-0.039541,-0.009971,frac_forward
15,Late air-off recovery / next baseline,post_air_off_mid,pre_air_on_next,-0.104189,0.007622,-13.670431,0.000000e+00,-0.119128,-0.089251,frac_forward
16,Air-onset transition,pre_air_on,post_air_on,1.560185,0.342757,4.551872,5.317058e-06,0.888382,2.231988,mean_speed_path_cms
17,Early air-on progression,post_air_on,pre_air_on_mid,2.467203,0.342708,7.199139,6.059597e-13,1.795495,3.138911,mean_speed_path_cms
18,Air-on midpoint transition,pre_air_on_mid,post_air_on_mid,0.197739,0.342708,0.576989,5.639467e-01,-0.473969,0.869447,mean_speed_path_cms
19,Late air-on progression,post_air_on_mid,pre_air_off,0.871060,0.342684,2.541878,1.102585e-02,0.199400,1.542721,mean_speed_path_cms
20,Air-offset transition,pre_air_off,post_air_off,-1.750802,0.342928,-5.105454,3.300010e-07,-2.422941,-1.078664,mean_speed_path_cms
21,Early air-off recovery,post_air_off,pre_air_off_mid,-2.691103,0.343365,-7.837441,4.662937e-15,-3.364098,-2.018107,mean_speed_path_cms
22,Air-off midpoint transition,pre_air_off_mid,post_air_off_mid,-0.129300,0.343584,-0.376327,7.066740e-01,-0.802724,0.544125,mean_speed_path_cms
23,Late air-off recovery / next baseline,post_air_off_mid,pre_air_on_next,-0.535300,0.347059,-1.542388,1.229793e-01,-1.215535,0.144936,mean_speed_path_cms
24,Air-onset transition,pre_air_on,post_air_on,1.269654,0.344182,3.688901,2.252252e-04,0.595057,1.944251,mean_speed_net_cms
25,Early air-on progression,post_air_on,pre_air_on_mid,1.271270,0.344133,3.694119,2.206502e-04,0.596768,1.945772,mean_speed_net_cms
26,Air-on midpoint transition,pre_air_on_mid,post_air_on_mid,1.635395,0.344133,4.752211,2.012047e-06,0.960893,2.309896,mean_speed_net_cms
27,Late air-on progression,post_air_on_mid,pre_air_off,0.922607,0.344109,2.681148,7.337012e-03,0.248153,1.597061,mean_speed_net_cms
28,Air-offset transition,pre_air_off,post_air_off,-2.320569,0.344354,-6.738904,1.595857e-11,-2.995504,-1.645635,mean_speed_net_cms
29,Early air-off recovery,post_air_off,pre_air_off_mid,-2.128362,0.344793,-6.172869,6.706167e-10,-2.804157,-1.452568,mean_speed_net_cms
30,Air-off midpoint transition,pre_air_off_mid,post_air_off_mid,-0.122502,0.345013,-0.355066,7.225400e-01,-0.798728,0.553723,mean_speed_net_cms
31,Late air-off recovery / next baseline,post_air_off_mid,pre_air_on_next,-0.537074,0.348507,-1.541068,1.233002e-01,-1.220148,0.146001,mean_speed_net_cms

In [43]:
def fit_air_cycle_time_model(
    air_cycle_df,
    outcome,
    include_cycle_random=True,
):
    """
    Time-dependent omnibus model.

    Tests whether air-cycle structure changes with:
        cycle_exposure_session_c
        cycle_session_10m_c
    """

    df = air_cycle_df.copy()

    df = df[
        np.isfinite(df[outcome]) &
        np.isfinite(df["cycle_exposure_session_c"]) &
        np.isfinite(df["cycle_session_10m_c"])
    ].copy()

    if include_cycle_random:
        vc = {
            "animal_day": "0 + C(animal_day)",
            "cycle_id": "0 + C(cycle_id)",
        }
    else:
        vc = {
            "animal_day": "0 + C(animal_day)",
        }

    formula = (
        f"{outcome} ~ C(air_cycle_epoch) * "
        f"cycle_exposure_session_c * cycle_session_10m_c"
    )

    model = smf.mixedlm(
        formula,
        data=df,
        groups=df["animal"],
        re_formula="1",
        vc_formula=vc,
    ).fit(
        reml=False,
        method="lbfgs",
        maxiter=1000,
    )

    return model

In [44]:
m_cycle_time_frac_moving = fit_air_cycle_time_model(
    air_cycle_df,
    outcome="frac_moving",
    include_cycle_random=True,
)

print(m_cycle_time_frac_moving.summary())

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

                                            Mixed Linear Model Regression Results
==============================================================================================================================
Model:                                   MixedLM                        Dependent Variable:                        frac_moving
No. Observations:                        31584                          Method:                                    ML
No. Groups:                              5                              Scale:                                     0.0887
Min. group size:                         3918                           Log-Likelihood:                            -7296.1970
Max. group size:                         7557                           Converged:                                 Yes
Mean group size:                         6316.8
------------------------------------------------------------------------------------------------------------------------------
                                                                                    Coef.  Std.Err.   z    P>|z| [0.025 0.975]
------------------------------------------------------------------------------------------------------------------------------
Intercept                                                                            0.281    0.022 12.941 0.000  0.238  0.323
C(air_cycle_epoch)[T.post_air_on]                                                    0.500    0.007 70.099 0.000  0.486  0.514
C(air_cycle_epoch)[T.pre_air_on_mid]                                                 0.547    0.007 76.830 0.000  0.534  0.561
C(air_cycle_epoch)[T.post_air_on_mid]                                                0.593    0.007 83.212 0.000  0.579  0.607
C(air_cycle_epoch)[T.pre_air_off]                                                    0.687    0.007 96.451 0.000  0.673  0.701
C(air_cycle_epoch)[T.post_air_off]                                                   0.642    0.007 90.023 0.000  0.628  0.656
C(air_cycle_epoch)[T.pre_air_off_mid]                                                0.128    0.007 17.900 0.000  0.114  0.142
C(air_cycle_epoch)[T.post_air_off_mid]                                               0.102    0.007 14.280 0.000  0.088  0.116
C(air_cycle_epoch)[T.pre_air_on_next]                                               -0.005    0.007 -0.641 0.522 -0.019  0.010
cycle_exposure_session_c                                                            -0.020    0.002 -9.385 0.000 -0.025 -0.016
C(air_cycle_epoch)[T.post_air_on]:cycle_exposure_session_c                           0.021    0.001 14.309 0.000  0.018  0.024
C(air_cycle_epoch)[T.pre_air_on_mid]:cycle_exposure_session_c                        0.024    0.001 16.298 0.000  0.021  0.027
C(air_cycle_epoch)[T.post_air_on_mid]:cycle_exposure_session_c                       0.021    0.001 14.278 0.000  0.018  0.024
C(air_cycle_epoch)[T.pre_air_off]:cycle_exposure_session_c                           0.019    0.001 13.310 0.000  0.017  0.022
C(air_cycle_epoch)[T.post_air_off]:cycle_exposure_session_c                          0.017    0.001 11.674 0.000  0.014  0.020
C(air_cycle_epoch)[T.pre_air_off_mid]:cycle_exposure_session_c                      -0.002    0.001 -1.550 0.121 -0.005  0.001
C(air_cycle_epoch)[T.post_air_off_mid]:cycle_exposure_session_c                     -0.003    0.001 -2.300 0.021 -0.006 -0.000
C(air_cycle_epoch)[T.pre_air_on_next]:cycle_exposure_session_c                      -0.001    0.001 -0.395 0.693 -0.003  0.002
cycle_session_10m_c                                                                 -0.038    0.008 -4.507 0.000 -0.054 -0.021
C(air_cycle_epoch)[T.post_air_on]:cycle_session_10m_c                                0.017    0.012  1.482 0.138 -0.006  0.040
C(air_cycle_epoch)[T.pre_air_on_mid]:cycle_session_10m_c                             0.036    0.012  3.125 0.002  0.013  0.059
C(air_cycle_epoch)[T.post_air_on_mid]:cycle_session_10m_c                            0.015    0.012  1.329 0.184 -0.007  0.038
C(air_cycle_epoch)[T.pre_air_off]:cycle_session_10m_c                                0.033    0.012  2.845 0.004  0.010  0.055
C(air_cycle_epoch)[T.post_air_off]:cycle_session_10m_c                               0.027    0.012  2.300 0.021  0.004  0.049
C(air_cycle_epoch)[T.pre_air_off_mid]:cycle_session_10m_c                            0.050    0.012  4.357 0.000  0.028  0.073
C(air_cycle_epoch)[T.post_air_off_mid]:cycle_session_10m_c                           0.042    0.012  3.584 0.000  0.019  0.064
C(air_cycle_epoch)[T.pre_air_on_next]:cycle_session_10m_c                            0.007    0.012  0.594 0.552 -0.016  0.030
cycle_exposure_session_c:cycle_session_10m_c                                         0.003    0.002  1.777 0.076 -0.000  0.006
C(air_cycle_epoch)[T.post_air_on]:cycle_exposure_session_c:cycle_session_10m_c      -0.004    0.002 -1.518 0.129 -0.008  0.001
C(air_cycle_epoch)[T.pre_air_on_mid]:cycle_exposure_session_c:cycle_session_10m_c   -0.005    0.002 -2.057 0.040 -0.010 -0.000
C(air_cycle_epoch)[T.post_air_on_mid]:cycle_exposure_session_c:cycle_session_10m_c  -0.005    0.002 -1.948 0.051 -0.009  0.000
C(air_cycle_epoch)[T.pre_air_off]:cycle_exposure_session_c:cycle_session_10m_c      -0.004    0.002 -1.653 0.098 -0.009  0.001
C(air_cycle_epoch)[T.post_air_off]:cycle_exposure_session_c:cycle_session_10m_c     -0.005    0.002 -2.068 0.039 -0.010 -0.000
C(air_cycle_epoch)[T.pre_air_off_mid]:cycle_exposure_session_c:cycle_session_10m_c  -0.001    0.002 -0.560 0.575 -0.006  0.003
C(air_cycle_epoch)[T.post_air_off_mid]:cycle_exposure_session_c:cycle_session_10m_c -0.001    0.002 -0.358 0.720 -0.006  0.004
C(air_cycle_epoch)[T.pre_air_on_next]:cycle_exposure_session_c:cycle_session_10m_c   0.002    0.002  0.837 0.403 -0.003  0.007
Group Var                                                                            0.002    0.005
animal_day Var                                                                       0.006    0.004
cycle_id Var                                                                         0.004    0.001
==============================================================================================================================

In [45]:
air_cycle_time_models = {}

for outcome in main_air_outcomes:
    print("\n\n==============================")
    print(outcome)
    print("==============================")

    try:
        model = fit_air_cycle_time_model(
            air_cycle_df,
            outcome=outcome,
            include_cycle_random=True,
        )

        air_cycle_time_models[outcome] = model
        print(model.summary())

    except Exception as e:
        print(f"[ERROR] {outcome}: {e}")

==============================
frac_moving
==============================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

                                            Mixed Linear Model Regression Results
==============================================================================================================================
Model:                                   MixedLM                        Dependent Variable:                        frac_moving
No. Observations:                        31584                          Method:                                    ML
No. Groups:                              5                              Scale:                                     0.0887
Min. group size:                         3918                           Log-Likelihood:                            -7296.1970
Max. group size:                         7557                           Converged:                                 Yes
Mean group size:                         6316.8
------------------------------------------------------------------------------------------------------------------------------
                                                                                    Coef.  Std.Err.   z    P>|z| [0.025 0.975]
------------------------------------------------------------------------------------------------------------------------------
Intercept                                                                            0.281    0.022 12.941 0.000  0.238  0.323
C(air_cycle_epoch)[T.post_air_on]                                                    0.500    0.007 70.099 0.000  0.486  0.514
C(air_cycle_epoch)[T.pre_air_on_mid]                                                 0.547    0.007 76.830 0.000  0.534  0.561
C(air_cycle_epoch)[T.post_air_on_mid]                                                0.593    0.007 83.212 0.000  0.579  0.607
C(air_cycle_epoch)[T.pre_air_off]                                                    0.687    0.007 96.451 0.000  0.673  0.701
C(air_cycle_epoch)[T.post_air_off]                                                   0.642    0.007 90.023 0.000  0.628  0.656
C(air_cycle_epoch)[T.pre_air_off_mid]                                                0.128    0.007 17.900 0.000  0.114  0.142
C(air_cycle_epoch)[T.post_air_off_mid]                                               0.102    0.007 14.280 0.000  0.088  0.116
C(air_cycle_epoch)[T.pre_air_on_next]                                               -0.005    0.007 -0.641 0.522 -0.019  0.010
cycle_exposure_session_c                                                            -0.020    0.002 -9.385 0.000 -0.025 -0.016
C(air_cycle_epoch)[T.post_air_on]:cycle_exposure_session_c                           0.021    0.001 14.309 0.000  0.018  0.024
C(air_cycle_epoch)[T.pre_air_on_mid]:cycle_exposure_session_c                        0.024    0.001 16.298 0.000  0.021  0.027
C(air_cycle_epoch)[T.post_air_on_mid]:cycle_exposure_session_c                       0.021    0.001 14.278 0.000  0.018  0.024
C(air_cycle_epoch)[T.pre_air_off]:cycle_exposure_session_c                           0.019    0.001 13.310 0.000  0.017  0.022
C(air_cycle_epoch)[T.post_air_off]:cycle_exposure_session_c                          0.017    0.001 11.674 0.000  0.014  0.020
C(air_cycle_epoch)[T.pre_air_off_mid]:cycle_exposure_session_c                      -0.002    0.001 -1.550 0.121 -0.005  0.001
C(air_cycle_epoch)[T.post_air_off_mid]:cycle_exposure_session_c                     -0.003    0.001 -2.300 0.021 -0.006 -0.000
C(air_cycle_epoch)[T.pre_air_on_next]:cycle_exposure_session_c                      -0.001    0.001 -0.395 0.693 -0.003  0.002
cycle_session_10m_c                                                                 -0.038    0.008 -4.507 0.000 -0.054 -0.021
C(air_cycle_epoch)[T.post_air_on]:cycle_session_10m_c                                0.017    0.012  1.482 0.138 -0.006  0.040
C(air_cycle_epoch)[T.pre_air_on_mid]:cycle_session_10m_c                             0.036    0.012  3.125 0.002  0.013  0.059
C(air_cycle_epoch)[T.post_air_on_mid]:cycle_session_10m_c                            0.015    0.012  1.329 0.184 -0.007  0.038
C(air_cycle_epoch)[T.pre_air_off]:cycle_session_10m_c                                0.033    0.012  2.845 0.004  0.010  0.055
C(air_cycle_epoch)[T.post_air_off]:cycle_session_10m_c                               0.027    0.012  2.300 0.021  0.004  0.049
C(air_cycle_epoch)[T.pre_air_off_mid]:cycle_session_10m_c                            0.050    0.012  4.357 0.000  0.028  0.073
C(air_cycle_epoch)[T.post_air_off_mid]:cycle_session_10m_c                           0.042    0.012  3.584 0.000  0.019  0.064
C(air_cycle_epoch)[T.pre_air_on_next]:cycle_session_10m_c                            0.007    0.012  0.594 0.552 -0.016  0.030
cycle_exposure_session_c:cycle_session_10m_c                                         0.003    0.002  1.777 0.076 -0.000  0.006
C(air_cycle_epoch)[T.post_air_on]:cycle_exposure_session_c:cycle_session_10m_c      -0.004    0.002 -1.518 0.129 -0.008  0.001
C(air_cycle_epoch)[T.pre_air_on_mid]:cycle_exposure_session_c:cycle_session_10m_c   -0.005    0.002 -2.057 0.040 -0.010 -0.000
C(air_cycle_epoch)[T.post_air_on_mid]:cycle_exposure_session_c:cycle_session_10m_c  -0.005    0.002 -1.948 0.051 -0.009  0.000
C(air_cycle_epoch)[T.pre_air_off]:cycle_exposure_session_c:cycle_session_10m_c      -0.004    0.002 -1.653 0.098 -0.009  0.001
C(air_cycle_epoch)[T.post_air_off]:cycle_exposure_session_c:cycle_session_10m_c     -0.005    0.002 -2.068 0.039 -0.010 -0.000
C(air_cycle_epoch)[T.pre_air_off_mid]:cycle_exposure_session_c:cycle_session_10m_c  -0.001    0.002 -0.560 0.575 -0.006  0.003
C(air_cycle_epoch)[T.post_air_off_mid]:cycle_exposure_session_c:cycle_session_10m_c -0.001    0.002 -0.358 0.720 -0.006  0.004
C(air_cycle_epoch)[T.pre_air_on_next]:cycle_exposure_session_c:cycle_session_10m_c   0.002    0.002  0.837 0.403 -0.003  0.007
Group Var                                                                            0.002    0.005
animal_day Var                                                                       0.006    0.004
cycle_id Var                                                                         0.004    0.001
==============================================================================================================================



==============================
frac_forward
==============================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2238: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

                                            Mixed Linear Model Regression Results
==============================================================================================================================
Model:                                    MixedLM                       Dependent Variable:                       frac_forward
No. Observations:                         31584                         Method:                                   ML
No. Groups:                               5                             Scale:                                    0.0956
Min. group size:                          3918                          Log-Likelihood:                           -8365.5809
Max. group size:                          7557                          Converged:                                Yes
Mean group size:                          6316.8
------------------------------------------------------------------------------------------------------------------------------
                                                                                    Coef.  Std.Err.   z    P>|z| [0.025 0.975]
------------------------------------------------------------------------------------------------------------------------------
Intercept                                                                            0.258    0.027  9.660 0.000  0.205  0.310
C(air_cycle_epoch)[T.post_air_on]                                                    0.403    0.007 54.437 0.000  0.388  0.417
C(air_cycle_epoch)[T.pre_air_on_mid]                                                 0.523    0.007 70.665 0.000  0.508  0.537
C(air_cycle_epoch)[T.post_air_on_mid]                                                0.583    0.007 78.844 0.000  0.569  0.598
C(air_cycle_epoch)[T.pre_air_off]                                                    0.691    0.007 93.477 0.000  0.677  0.706
C(air_cycle_epoch)[T.post_air_off]                                                   0.576    0.007 77.861 0.000  0.562  0.591
C(air_cycle_epoch)[T.pre_air_off_mid]                                                0.125    0.007 16.898 0.000  0.111  0.140
C(air_cycle_epoch)[T.post_air_off_mid]                                               0.101    0.007 13.580 0.000  0.086  0.115
C(air_cycle_epoch)[T.pre_air_on_next]                                               -0.003    0.007 -0.408 0.683 -0.018  0.012
cycle_exposure_session_c                                                            -0.020    0.002 -8.969 0.000 -0.025 -0.016
C(air_cycle_epoch)[T.post_air_on]:cycle_exposure_session_c                           0.027    0.002 18.146 0.000  0.024  0.030
C(air_cycle_epoch)[T.pre_air_on_mid]:cycle_exposure_session_c                        0.028    0.002 18.338 0.000  0.025  0.031
C(air_cycle_epoch)[T.post_air_on_mid]:cycle_exposure_session_c                       0.023    0.002 15.042 0.000  0.020  0.026
C(air_cycle_epoch)[T.pre_air_off]:cycle_exposure_session_c                           0.020    0.002 12.898 0.000  0.017  0.022
C(air_cycle_epoch)[T.post_air_off]:cycle_exposure_session_c                          0.014    0.002  8.973 0.000  0.011  0.017
C(air_cycle_epoch)[T.pre_air_off_mid]:cycle_exposure_session_c                      -0.003    0.002 -1.795 0.073 -0.006  0.000
C(air_cycle_epoch)[T.post_air_off_mid]:cycle_exposure_session_c                     -0.003    0.002 -2.205 0.027 -0.006 -0.000
C(air_cycle_epoch)[T.pre_air_on_next]:cycle_exposure_session_c                      -0.001    0.002 -0.425 0.671 -0.004  0.002
cycle_session_10m_c                                                                 -0.026    0.009 -2.956 0.003 -0.042 -0.009
C(air_cycle_epoch)[T.post_air_on]:cycle_session_10m_c                                0.036    0.012  3.007 0.003  0.013  0.059
C(air_cycle_epoch)[T.pre_air_on_mid]:cycle_session_10m_c                             0.042    0.012  3.479 0.001  0.018  0.065
C(air_cycle_epoch)[T.post_air_on_mid]:cycle_session_10m_c                            0.012    0.012  0.973 0.331 -0.012  0.035
C(air_cycle_epoch)[T.pre_air_off]:cycle_session_10m_c                                0.022    0.012  1.869 0.062 -0.001  0.046
C(air_cycle_epoch)[T.post_air_off]:cycle_session_10m_c                              -0.001    0.012 -0.068 0.946 -0.024  0.023
C(air_cycle_epoch)[T.pre_air_off_mid]:cycle_session_10m_c                            0.046    0.012  3.816 0.000  0.022  0.069
C(air_cycle_epoch)[T.post_air_off_mid]:cycle_session_10m_c                           0.035    0.012  2.900 0.004  0.011  0.058
C(air_cycle_epoch)[T.pre_air_on_next]:cycle_session_10m_c                            0.005    0.012  0.386 0.700 -0.019  0.029
cycle_exposure_session_c:cycle_session_10m_c                                         0.003    0.002  1.576 0.115 -0.001  0.006
C(air_cycle_epoch)[T.post_air_on]:cycle_exposure_session_c:cycle_session_10m_c      -0.002    0.002 -0.848 0.397 -0.007  0.003
C(air_cycle_epoch)[T.pre_air_on_mid]:cycle_exposure_session_c:cycle_session_10m_c   -0.005    0.002 -2.085 0.037 -0.010 -0.000
C(air_cycle_epoch)[T.post_air_on_mid]:cycle_exposure_session_c:cycle_session_10m_c  -0.005    0.002 -2.129 0.033 -0.010 -0.000
C(air_cycle_epoch)[T.pre_air_off]:cycle_exposure_session_c:cycle_session_10m_c      -0.004    0.002 -1.555 0.120 -0.009  0.001
C(air_cycle_epoch)[T.post_air_off]:cycle_exposure_session_c:cycle_session_10m_c     -0.006    0.002 -2.336 0.020 -0.011 -0.001
C(air_cycle_epoch)[T.pre_air_off_mid]:cycle_exposure_session_c:cycle_session_10m_c  -0.001    0.002 -0.572 0.567 -0.006  0.003
C(air_cycle_epoch)[T.post_air_off_mid]:cycle_exposure_session_c:cycle_session_10m_c -0.001    0.002 -0.526 0.599 -0.006  0.004
C(air_cycle_epoch)[T.pre_air_on_next]:cycle_exposure_session_c:cycle_session_10m_c   0.002    0.003  0.853 0.394 -0.003  0.007
Group Var                                                                            0.003    0.007
animal_day Var                                                                       0.006    0.004
cycle_id Var                                                                         0.003    0.001
==============================================================================================================================



==============================
mean_speed_path_cms
==============================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

                                             Mixed Linear Model Regression Results
================================================================================================================================
Model:                                 MixedLM                      Dependent Variable:                      mean_speed_path_cms
No. Observations:                      31584                        Method:                                  ML
No. Groups:                            5                            Scale:                                   206.6515
Min. group size:                       3918                         Log-Likelihood:                          -129080.2321
Max. group size:                       7557                         Converged:                               Yes
Mean group size:                       6316.8
--------------------------------------------------------------------------------------------------------------------------------
                                                                                     Coef.  Std.Err.   z    P>|z|  [0.025 0.975]
--------------------------------------------------------------------------------------------------------------------------------
Intercept                                                                             1.360    6.062  0.224 0.822 -10.521 13.241
C(air_cycle_epoch)[T.post_air_on]                                                     1.562    0.344  4.542 0.000   0.888  2.236
C(air_cycle_epoch)[T.pre_air_on_mid]                                                  3.917    0.344 11.391 0.000   3.243  4.591
C(air_cycle_epoch)[T.post_air_on_mid]                                                 4.230    0.344 12.301 0.000   3.556  4.904
C(air_cycle_epoch)[T.pre_air_off]                                                     5.088    0.344 14.797 0.000   4.414  5.762
C(air_cycle_epoch)[T.post_air_off]                                                    3.329    0.344  9.672 0.000   2.654  4.003
C(air_cycle_epoch)[T.pre_air_off_mid]                                                 0.645    0.344  1.874 0.061  -0.030  1.320
C(air_cycle_epoch)[T.post_air_off_mid]                                                0.517    0.344  1.503 0.133  -0.158  1.192
C(air_cycle_epoch)[T.pre_air_on_next]                                                -0.010    0.348 -0.028 0.977  -0.692  0.672
cycle_exposure_session_c                                                             -0.183    0.059 -3.107 0.002  -0.298 -0.067
C(air_cycle_epoch)[T.post_air_on]:cycle_exposure_session_c                            0.127    0.070  1.805 0.071  -0.011  0.265
C(air_cycle_epoch)[T.pre_air_on_mid]:cycle_exposure_session_c                         0.145    0.070  2.066 0.039   0.007  0.283
C(air_cycle_epoch)[T.post_air_on_mid]:cycle_exposure_session_c                        0.018    0.070  0.251 0.801  -0.120  0.155
C(air_cycle_epoch)[T.pre_air_off]:cycle_exposure_session_c                           -0.074    0.070 -1.049 0.294  -0.212  0.064
C(air_cycle_epoch)[T.post_air_off]:cycle_exposure_session_c                          -0.105    0.070 -1.498 0.134  -0.243  0.032
C(air_cycle_epoch)[T.pre_air_off_mid]:cycle_exposure_session_c                       -0.039    0.070 -0.549 0.583  -0.177  0.099
C(air_cycle_epoch)[T.post_air_off_mid]:cycle_exposure_session_c                      -0.038    0.070 -0.534 0.594  -0.175  0.100
C(air_cycle_epoch)[T.pre_air_on_next]:cycle_exposure_session_c                       -0.004    0.071 -0.057 0.955  -0.143  0.135
cycle_session_10m_c                                                                  -0.175    0.394 -0.445 0.656  -0.948  0.597
C(air_cycle_epoch)[T.post_air_on]:cycle_session_10m_c                                 0.012    0.557  0.022 0.983  -1.079  1.103
C(air_cycle_epoch)[T.pre_air_on_mid]:cycle_session_10m_c                              4.687    0.557  8.422 0.000   3.596  5.778
C(air_cycle_epoch)[T.post_air_on_mid]:cycle_session_10m_c                             0.146    0.557  0.263 0.793  -0.945  1.237
C(air_cycle_epoch)[T.pre_air_off]:cycle_session_10m_c                                 0.294    0.557  0.529 0.597  -0.796  1.385
C(air_cycle_epoch)[T.post_air_off]:cycle_session_10m_c                               -0.487    0.558 -0.874 0.382  -1.580  0.606
C(air_cycle_epoch)[T.pre_air_off_mid]:cycle_session_10m_c                             0.286    0.559  0.511 0.609  -0.809  1.380
C(air_cycle_epoch)[T.post_air_off_mid]:cycle_session_10m_c                            0.250    0.559  0.448 0.654  -0.845  1.345
C(air_cycle_epoch)[T.pre_air_on_next]:cycle_session_10m_c                             0.014    0.575  0.024 0.981  -1.113  1.140
cycle_exposure_session_c:cycle_session_10m_c                                         -0.000    0.082 -0.004 0.997  -0.160  0.160
C(air_cycle_epoch)[T.post_air_on]:cycle_exposure_session_c:cycle_session_10m_c        0.009    0.115  0.081 0.935  -0.216  0.235
C(air_cycle_epoch)[T.pre_air_on_mid]:cycle_exposure_session_c:cycle_session_10m_c    -0.338    0.115 -2.937 0.003  -0.564 -0.112
C(air_cycle_epoch)[T.post_air_on_mid]:cycle_exposure_session_c:cycle_session_10m_c    0.013    0.115  0.114 0.909  -0.213  0.239
C(air_cycle_epoch)[T.pre_air_off]:cycle_exposure_session_c:cycle_session_10m_c       -0.032    0.115 -0.279 0.780  -0.258  0.194
C(air_cycle_epoch)[T.post_air_off]:cycle_exposure_session_c:cycle_session_10m_c      -0.048    0.115 -0.415 0.678  -0.274  0.178
C(air_cycle_epoch)[T.pre_air_off_mid]:cycle_exposure_session_c:cycle_session_10m_c   -0.030    0.115 -0.262 0.793  -0.256  0.196
C(air_cycle_epoch)[T.post_air_off_mid]:cycle_exposure_session_c:cycle_session_10m_c  -0.024    0.115 -0.208 0.835  -0.250  0.202
C(air_cycle_epoch)[T.pre_air_on_next]:cycle_exposure_session_c:cycle_session_10m_c    0.010    0.119  0.082 0.935  -0.223  0.243
Group Var                                                                           183.324
animal_day Var                                                                        1.548    0.024
cycle_id Var                                                                          0.088    0.046
================================================================================================================================



==============================
mean_speed_net_cms
==============================

/home/nmldata2/miniconda3/envs/air_wheel/lib/python3.8/site-packages/statsmodels/regression/mixed_linear_model.py:2262: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)

                                             Mixed Linear Model Regression Results
================================================================================================================================
Model:                                  MixedLM                      Dependent Variable:                      mean_speed_net_cms
No. Observations:                       31584                        Method:                                  ML
No. Groups:                             5                            Scale:                                   208.5802
Min. group size:                        3918                         Log-Likelihood:                          -129229.2275
Max. group size:                        7557                         Converged:                               Yes
Mean group size:                        6316.8
--------------------------------------------------------------------------------------------------------------------------------
                                                                                     Coef.  Std.Err.   z    P>|z|  [0.025 0.975]
--------------------------------------------------------------------------------------------------------------------------------
Intercept                                                                             1.197    6.100  0.196 0.844 -10.758 13.152
C(air_cycle_epoch)[T.post_air_on]                                                     1.270    0.345  3.675 0.000   0.592  1.947
C(air_cycle_epoch)[T.pre_air_on_mid]                                                  2.640    0.345  7.643 0.000   1.963  3.317
C(air_cycle_epoch)[T.post_air_on_mid]                                                 4.179    0.345 12.097 0.000   3.502  4.856
C(air_cycle_epoch)[T.pre_air_off]                                                     5.090    0.345 14.733 0.000   4.413  5.767
C(air_cycle_epoch)[T.post_air_off]                                                    2.778    0.346  8.035 0.000   2.101  3.456
C(air_cycle_epoch)[T.pre_air_off_mid]                                                 0.641    0.346  1.853 0.064  -0.037  1.319
C(air_cycle_epoch)[T.post_air_off_mid]                                                0.520    0.346  1.503 0.133  -0.158  1.198
C(air_cycle_epoch)[T.pre_air_on_next]                                                -0.009    0.349 -0.026 0.980  -0.694  0.676
cycle_exposure_session_c                                                             -0.188    0.061 -3.105 0.002  -0.307 -0.069
C(air_cycle_epoch)[T.post_air_on]:cycle_exposure_session_c                            0.151    0.071  2.132 0.033   0.012  0.289
C(air_cycle_epoch)[T.pre_air_on_mid]:cycle_exposure_session_c                         0.184    0.071  2.606 0.009   0.046  0.322
C(air_cycle_epoch)[T.post_air_on_mid]:cycle_exposure_session_c                        0.028    0.071  0.401 0.689  -0.110  0.167
C(air_cycle_epoch)[T.pre_air_off]:cycle_exposure_session_c                           -0.072    0.071 -1.024 0.306  -0.211  0.066
C(air_cycle_epoch)[T.post_air_off]:cycle_exposure_session_c                          -0.150    0.071 -2.128 0.033  -0.289 -0.012
C(air_cycle_epoch)[T.pre_air_off_mid]:cycle_exposure_session_c                       -0.041    0.071 -0.575 0.566  -0.179  0.098
C(air_cycle_epoch)[T.post_air_off_mid]:cycle_exposure_session_c                      -0.038    0.071 -0.540 0.589  -0.177  0.100
C(air_cycle_epoch)[T.pre_air_on_next]:cycle_exposure_session_c                       -0.004    0.071 -0.061 0.951  -0.144  0.136
cycle_session_10m_c                                                                  -0.067    0.396 -0.168 0.867  -0.843  0.709
C(air_cycle_epoch)[T.post_air_on]:cycle_session_10m_c                                 0.145    0.559  0.260 0.795  -0.951  1.241
C(air_cycle_epoch)[T.pre_air_on_mid]:cycle_session_10m_c                             -3.327    0.559 -5.950 0.000  -4.423 -2.231
C(air_cycle_epoch)[T.post_air_on_mid]:cycle_session_10m_c                             0.163    0.559  0.291 0.771  -0.933  1.259
C(air_cycle_epoch)[T.pre_air_off]:cycle_session_10m_c                                 0.276    0.559  0.494 0.621  -0.820  1.372
C(air_cycle_epoch)[T.post_air_off]:cycle_session_10m_c                               -0.075    0.560 -0.133 0.894  -1.173  1.023
C(air_cycle_epoch)[T.pre_air_off_mid]:cycle_session_10m_c                             0.280    0.561  0.500 0.617  -0.820  1.380
C(air_cycle_epoch)[T.post_air_off_mid]:cycle_session_10m_c                            0.235    0.561  0.418 0.676  -0.866  1.335
C(air_cycle_epoch)[T.pre_air_on_next]:cycle_session_10m_c                             0.003    0.578  0.004 0.996  -1.130  1.135
cycle_exposure_session_c:cycle_session_10m_c                                         -0.004    0.082 -0.055 0.957  -0.165  0.156
C(air_cycle_epoch)[T.post_air_on]:cycle_exposure_session_c:cycle_session_10m_c        0.006    0.116  0.050 0.960  -0.221  0.233
C(air_cycle_epoch)[T.pre_air_on_mid]:cycle_exposure_session_c:cycle_session_10m_c     0.311    0.116  2.690 0.007   0.084  0.538
C(air_cycle_epoch)[T.post_air_on_mid]:cycle_exposure_session_c:cycle_session_10m_c    0.007    0.116  0.064 0.949  -0.219  0.234
C(air_cycle_epoch)[T.pre_air_off]:cycle_exposure_session_c:cycle_session_10m_c       -0.033    0.116 -0.288 0.774  -0.260  0.193
C(air_cycle_epoch)[T.post_air_off]:cycle_exposure_session_c:cycle_session_10m_c       0.008    0.116  0.066 0.948  -0.219  0.235
C(air_cycle_epoch)[T.pre_air_off_mid]:cycle_exposure_session_c:cycle_session_10m_c   -0.029    0.116 -0.251 0.802  -0.256  0.198
C(air_cycle_epoch)[T.post_air_off_mid]:cycle_exposure_session_c:cycle_session_10m_c  -0.024    0.116 -0.205 0.837  -0.251  0.203
C(air_cycle_epoch)[T.pre_air_on_next]:cycle_exposure_session_c:cycle_session_10m_c    0.011    0.119  0.090 0.928  -0.223  0.245
Group Var                                                                           185.591
animal_day Var                                                                        1.876    0.028
cycle_id Var                                                                          0.054    0.045
================================================================================================================================

In [ ]:
from pathlib import Path

air_results_dir = Path(pdata_root) / "results"
air_results_dir.mkdir(parents=True, exist_ok=True)

air_cycle_contrasts_df.to_csv(
    air_results_dir / "air_cycle_omnibus_adjacent_contrasts.csv",
    index=False,
)

In [1]:
%load_ext rpy2.ipython

In [14]:
%R -i air_cycle_df

In [15]:
%%R

library(lme4)
library(lmerTest)
library(emmeans)
library(broom.mixed)
library(dplyr)
library(performance)

air_cycle_df$animal <- factor(air_cycle_df$animal)
air_cycle_df$animal_day <- factor(air_cycle_df$animal_day)
air_cycle_df$cycle_id <- factor(air_cycle_df$cycle_id)

air_cycle_df$air_cycle_epoch <- factor(
  air_cycle_df$air_cycle_epoch,
  levels = c(
    "pre_air_on",
    "post_air_on",
    "pre_air_on_mid",
    "post_air_on_mid",
    "pre_air_off",
    "post_air_off",
    "pre_air_off_mid",
    "post_air_off_mid",
    "pre_air_on_next"
  )
)

R[write to console]: Loading required package: Matrix

R[write to console]:
Attaching package: ‘lmerTest’


R[write to console]: The following object is masked from ‘package:lme4’:

    lmer


R[write to console]: The following object is masked from ‘package:stats’:

    step


R[write to console]: Welcome to emmeans.
Caution: You lose important information if you filter this package's results.
See '? untidy'

R[write to console]:
Attaching package: ‘dplyr’


R[write to console]: The following objects are masked from ‘package:stats’:

    filter, lag


R[write to console]: The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [19]:
%%R

air_cycle_df$air_cycle_epoch <- factor(
  as.character(air_cycle_df$air_cycle_epoch),
  levels = c(
    "pre_air_on",
    "post_air_on",
    "pre_air_on_mid",
    "post_air_on_mid",
    "pre_air_off",
    "post_air_off",
    "pre_air_off_mid",
    "post_air_off_mid",
    "pre_air_on_next"
  ),
  ordered = FALSE
)

In [20]:
%%R

m_frac_moving <- lmer(
  frac_moving ~ air_cycle_epoch * cycle_exposure_session_c * cycle_session_10m_c +
    (1 | animal) +
    (1 | animal_day) +
    (1 | cycle_id),
  data = air_cycle_df,
  REML = FALSE
)

summary(m_frac_moving)

Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula:
frac_moving ~ air_cycle_epoch * cycle_exposure_session_c * cycle_session_10m_c +
    (1 | animal) + (1 | animal_day) + (1 | cycle_id)
   Data: air_cycle_df

      AIC       BIC    logLik -2*log(L)  df.resid
  14672.4   15006.8   -7296.2   14592.4     31544

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.4176 -0.6753  0.0390  0.5104  3.2582

Random effects:
 Groups     Name        Variance Std.Dev.
 cycle_id   (Intercept) 0.004092 0.06397
 animal_day (Intercept) 0.006146 0.07839
 animal     (Intercept) 0.001819 0.04264
 Residual               0.088748 0.29791
Number of obs: 31584, groups:  cycle_id, 3532; animal_day, 78; animal, 5

Fixed effects:
                                                                               Estimate
(Intercept)                                                                   2.807e-01
air_cycle_epochpost_air_on                                                    4.995e-01
air_cycle_epochpre_air_on_mid                                                 5.475e-01
air_cycle_epochpost_air_on_mid                                                5.930e-01
air_cycle_epochpre_air_off                                                    6.873e-01
air_cycle_epochpost_air_off                                                   6.421e-01
air_cycle_epochpre_air_off_mid                                                1.277e-01
air_cycle_epochpost_air_off_mid                                               1.019e-01
air_cycle_epochpre_air_on_next                                               -4.620e-03
cycle_exposure_session_c                                                     -2.049e-02
cycle_session_10m_c                                                          -3.767e-02
air_cycle_epochpost_air_on:cycle_exposure_session_c                           2.085e-02
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        2.375e-02
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       2.080e-02
air_cycle_epochpre_air_off:cycle_exposure_session_c                           1.939e-02
air_cycle_epochpost_air_off:cycle_exposure_session_c                          1.702e-02
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                      -2.260e-03
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                     -3.354e-03
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                      -5.829e-04
air_cycle_epochpost_air_on:cycle_session_10m_c                                1.709e-02
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             3.605e-02
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            1.533e-02
air_cycle_epochpre_air_off:cycle_session_10m_c                                3.281e-02
air_cycle_epochpost_air_off:cycle_session_10m_c                               2.658e-02
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            5.044e-02
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           4.151e-02
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            7.084e-03
cycle_exposure_session_c:cycle_session_10m_c                                  3.076e-03
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c      -3.623e-03
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   -4.909e-03
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c  -4.649e-03
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c      -3.945e-03
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c     -4.939e-03
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  -1.341e-03
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c -8.575e-04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   2.064e-03
                                                                             Std. Error
(Intercept)                                                                   2.173e-02
air_cycle_epochpost_air_on                                                    7.126e-03
air_cycle_epochpre_air_on_mid                                                 7.126e-03
air_cycle_epochpost_air_on_mid                                                7.126e-03
air_cycle_epochpre_air_off                                                    7.126e-03
air_cycle_epochpost_air_off                                                   7.132e-03
air_cycle_epochpre_air_off_mid                                                7.137e-03
air_cycle_epochpost_air_off_mid                                               7.137e-03
air_cycle_epochpre_air_on_next                                                7.210e-03
cycle_exposure_session_c                                                      2.174e-03
cycle_session_10m_c                                                           8.359e-03
air_cycle_epochpost_air_on:cycle_exposure_session_c                           1.457e-03
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        1.457e-03
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       1.457e-03
air_cycle_epochpre_air_off:cycle_exposure_session_c                           1.457e-03
air_cycle_epochpost_air_off:cycle_exposure_session_c                          1.458e-03
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       1.458e-03
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      1.458e-03
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       1.474e-03
air_cycle_epochpost_air_on:cycle_session_10m_c                                1.154e-02
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             1.153e-02
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            1.154e-02
air_cycle_epochpre_air_off:cycle_session_10m_c                                1.153e-02
air_cycle_epochpost_air_off:cycle_session_10m_c                               1.156e-02
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            1.158e-02
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           1.158e-02
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            1.192e-02
cycle_exposure_session_c:cycle_session_10m_c                                  1.731e-03
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       2.387e-03
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    2.387e-03
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   2.387e-03
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       2.387e-03
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      2.389e-03
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   2.392e-03
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  2.392e-03
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   2.466e-03
                                                                                     df
(Intercept)                                                                   5.488e+00
air_cycle_epochpost_air_on                                                    2.802e+04
air_cycle_epochpre_air_on_mid                                                 2.802e+04
air_cycle_epochpost_air_on_mid                                                2.802e+04
air_cycle_epochpre_air_off                                                    2.802e+04
air_cycle_epochpost_air_off                                                   2.803e+04
air_cycle_epochpre_air_off_mid                                                2.804e+04
air_cycle_epochpost_air_off_mid                                               2.804e+04
air_cycle_epochpre_air_on_next                                                2.813e+04
cycle_exposure_session_c                                                      1.140e+02
cycle_session_10m_c                                                           3.089e+04
air_cycle_epochpost_air_on:cycle_exposure_session_c                           2.802e+04
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        2.802e+04
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       2.802e+04
air_cycle_epochpre_air_off:cycle_exposure_session_c                           2.802e+04
air_cycle_epochpost_air_off:cycle_exposure_session_c                          2.803e+04
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       2.803e+04
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      2.803e+04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       2.813e+04
air_cycle_epochpost_air_on:cycle_session_10m_c                                2.803e+04
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             2.802e+04
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            2.803e+04
air_cycle_epochpre_air_off:cycle_session_10m_c                                2.802e+04
air_cycle_epochpost_air_off:cycle_session_10m_c                               2.805e+04
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            2.807e+04
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           2.807e+04
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            2.832e+04
cycle_exposure_session_c:cycle_session_10m_c                                  3.086e+04
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       2.802e+04
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    2.802e+04
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   2.802e+04
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       2.802e+04
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      2.804e+04
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   2.805e+04
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  2.805e+04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   2.832e+04
                                                                             t value
(Intercept)                                                                   12.918
air_cycle_epochpost_air_on                                                    70.099
air_cycle_epochpre_air_on_mid                                                 76.830
air_cycle_epochpost_air_on_mid                                                83.212
air_cycle_epochpre_air_off                                                    96.451
air_cycle_epochpost_air_off                                                   90.023
air_cycle_epochpre_air_off_mid                                                17.900
air_cycle_epochpost_air_off_mid                                               14.280
air_cycle_epochpre_air_on_next                                                -0.641
cycle_exposure_session_c                                                      -9.423
cycle_session_10m_c                                                           -4.507
air_cycle_epochpost_air_on:cycle_exposure_session_c                           14.309
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        16.298
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       14.278
air_cycle_epochpre_air_off:cycle_exposure_session_c                           13.310
air_cycle_epochpost_air_off:cycle_exposure_session_c                          11.674
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       -1.550
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      -2.300
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       -0.395
air_cycle_epochpost_air_on:cycle_session_10m_c                                 1.482
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                              3.125
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                             1.329
air_cycle_epochpre_air_off:cycle_session_10m_c                                 2.845
air_cycle_epochpost_air_off:cycle_session_10m_c                                2.300
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                             4.357
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                            3.584
air_cycle_epochpre_air_on_next:cycle_session_10m_c                             0.594
cycle_exposure_session_c:cycle_session_10m_c                                   1.777
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       -1.518
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    -2.057
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   -1.948
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       -1.653
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      -2.068
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   -0.560
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  -0.358
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c    0.837
                                                                             Pr(>|t|)
(Intercept)                                                                  2.57e-05
air_cycle_epochpost_air_on                                                    < 2e-16
air_cycle_epochpre_air_on_mid                                                 < 2e-16
air_cycle_epochpost_air_on_mid                                                < 2e-16
air_cycle_epochpre_air_off                                                    < 2e-16
air_cycle_epochpost_air_off                                                   < 2e-16
air_cycle_epochpre_air_off_mid                                                < 2e-16
air_cycle_epochpost_air_off_mid                                               < 2e-16
air_cycle_epochpre_air_on_next                                               0.521666
cycle_exposure_session_c                                                     6.17e-16
cycle_session_10m_c                                                          6.61e-06
air_cycle_epochpost_air_on:cycle_exposure_session_c                           < 2e-16
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        < 2e-16
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       < 2e-16
air_cycle_epochpre_air_off:cycle_exposure_session_c                           < 2e-16
air_cycle_epochpost_air_off:cycle_exposure_session_c                          < 2e-16
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                      0.121180
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                     0.021456
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                      0.692505
air_cycle_epochpost_air_on:cycle_session_10m_c                               0.138448
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                            0.001777
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                           0.183825
air_cycle_epochpre_air_off:cycle_session_10m_c                               0.004444
air_cycle_epochpost_air_off:cycle_session_10m_c                              0.021440
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                           1.33e-05
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                          0.000339
air_cycle_epochpre_air_on_next:cycle_session_10m_c                           0.552481
cycle_exposure_session_c:cycle_session_10m_c                                 0.075549
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c      0.128987
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   0.039702
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c  0.051418
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c      0.098335
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c     0.038684
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  0.575162
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c 0.719998
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c  0.402539

(Intercept)                                                                  ***
air_cycle_epochpost_air_on                                                   ***
air_cycle_epochpre_air_on_mid                                                ***
air_cycle_epochpost_air_on_mid                                               ***
air_cycle_epochpre_air_off                                                   ***
air_cycle_epochpost_air_off                                                  ***
air_cycle_epochpre_air_off_mid                                               ***
air_cycle_epochpost_air_off_mid                                              ***
air_cycle_epochpre_air_on_next
cycle_exposure_session_c                                                     ***
cycle_session_10m_c                                                          ***
air_cycle_epochpost_air_on:cycle_exposure_session_c                          ***
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                       ***
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                      ***
air_cycle_epochpre_air_off:cycle_exposure_session_c                          ***
air_cycle_epochpost_air_off:cycle_exposure_session_c                         ***
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                     *
air_cycle_epochpre_air_on_next:cycle_exposure_session_c
air_cycle_epochpost_air_on:cycle_session_10m_c
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                            **
air_cycle_epochpost_air_on_mid:cycle_session_10m_c
air_cycle_epochpre_air_off:cycle_session_10m_c                               **
air_cycle_epochpost_air_off:cycle_session_10m_c                              *
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                           ***
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                          ***
air_cycle_epochpre_air_on_next:cycle_session_10m_c
cycle_exposure_session_c:cycle_session_10m_c                                 .
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   *
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c  .
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c      .
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c     *
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

R[write to console]:
Correlation matrix not shown by default, as p = 36 > 12.
Use print(object, correlation=TRUE)  or
    vcov(object)        if you need it

In [23]:
%%R
emm_frac_moving <- emmeans(
  m_frac_moving,
  ~ air_cycle_epoch,
  at = list(
    cycle_exposure_session_c = 0,
    cycle_session_10m_c = 0
  )
)

R[write to console]: Note: D.f. calculations have been disabled because the number of observations exceeds 3000.
To enable adjustments, add the argument 'pbkrtest.limit = 31584' (or larger)
[or, globally, 'set emm_options(pbkrtest.limit = 31584)' or larger];
but be warned that this may result in large computation time and memory use.

R[write to console]: Note: D.f. calculations have been disabled because the number of observations exceeds 3000.
To enable adjustments, add the argument 'lmerTest.limit = 31584' (or larger)
[or, globally, 'set emm_options(lmerTest.limit = 31584)' or larger];
but be warned that this may result in large computation time and memory use.

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

In [24]:
%%R

emm_frac_moving <- emmeans(m_frac_moving, ~ air_cycle_epoch)

contrast_list <- list(
  air_onset_transition = c(-1, 1, 0, 0, 0, 0, 0, 0, 0),
  early_air_on_progression = c(0, -1, 1, 0, 0, 0, 0, 0, 0),
  air_on_mid_transition = c(0, 0, -1, 1, 0, 0, 0, 0, 0),
  late_air_on_progression = c(0, 0, 0, -1, 1, 0, 0, 0, 0),
  air_offset_transition = c(0, 0, 0, 0, -1, 1, 0, 0, 0),
  early_air_off_recovery = c(0, 0, 0, 0, 0, -1, 1, 0, 0),
  air_off_mid_transition = c(0, 0, 0, 0, 0, 0, -1, 1, 0),
  late_air_off_recovery_to_next_baseline = c(0, 0, 0, 0, 0, 0, 0, -1, 1)
)

contrast(emm_frac_moving, contrast_list)

R[write to console]: Note: D.f. calculations have been disabled because the number of observations exceeds 3000.
To enable adjustments, add the argument 'pbkrtest.limit = 31584' (or larger)
[or, globally, 'set emm_options(pbkrtest.limit = 31584)' or larger];
but be warned that this may result in large computation time and memory use.

R[write to console]: Note: D.f. calculations have been disabled because the number of observations exceeds 3000.
To enable adjustments, add the argument 'lmerTest.limit = 31584' (or larger)
[or, globally, 'set emm_options(lmerTest.limit = 31584)' or larger];
but be warned that this may result in large computation time and memory use.

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

 contrast                               estimate      SE  df z.ratio p.value
 air_onset_transition                     0.4995 0.00713 Inf  70.099  <.0001
 early_air_on_progression                 0.0479 0.00713 Inf   6.726  <.0001
 air_on_mid_transition                    0.0455 0.00713 Inf   6.387  <.0001
 late_air_on_progression                  0.0943 0.00713 Inf  13.233  <.0001
 air_offset_transition                   -0.0452 0.00713 Inf  -6.343  <.0001
 early_air_off_recovery                  -0.5143 0.00714 Inf -72.006  <.0001
 air_off_mid_transition                  -0.0258 0.00715 Inf  -3.614  0.0003
 late_air_off_recovery_to_next_baseline  -0.1065 0.00722 Inf -14.754  <.0001

Degrees-of-freedom method: asymptotic

In [25]:
%%R

r2(m_frac_moving)

# R2 for Mixed Models

  Conditional R2: 0.511
     Marginal R2: 0.445

In [27]:
%%R -o air_cycle_contrasts_R -o air_cycle_r2_R -o air_cycle_fixed_R

library(lme4)
library(lmerTest)
library(emmeans)
library(broom.mixed)
library(dplyr)
library(performance)

# Use asymptotic df for large models
emm_options(lmer.df = "asymptotic")

# --------------------------------------------------
# Make sure grouping variables are factors
# --------------------------------------------------

air_cycle_df$animal <- factor(air_cycle_df$animal)
air_cycle_df$animal_day <- factor(air_cycle_df$animal_day)
air_cycle_df$cycle_id <- factor(air_cycle_df$cycle_id)

# Important: unordered factor, with pre_air_on as reference
air_cycle_df$air_cycle_epoch <- factor(
  as.character(air_cycle_df$air_cycle_epoch),
  levels = c(
    "pre_air_on",
    "post_air_on",
    "pre_air_on_mid",
    "post_air_on_mid",
    "pre_air_off",
    "post_air_off",
    "pre_air_off_mid",
    "post_air_off_mid",
    "pre_air_on_next"
  ),
  ordered = FALSE
)

# --------------------------------------------------
# Outcomes to analyze
# --------------------------------------------------

air_outcomes_R <- c(
  "frac_moving",
  "frac_forward",
  "mean_speed_path_cms",
  "mean_speed_net_cms",
  "distance_path_cm",
  "distance_net_cm"
)

# Keep only outcomes that actually exist
air_outcomes_R <- air_outcomes_R[air_outcomes_R %in% names(air_cycle_df)]

print(air_outcomes_R)

# --------------------------------------------------
# Planned adjacent contrasts
# --------------------------------------------------

contrast_list <- list(
  air_onset_transition = c(-1, 1, 0, 0, 0, 0, 0, 0, 0),
  early_air_on_progression = c(0, -1, 1, 0, 0, 0, 0, 0, 0),
  air_on_mid_transition = c(0, 0, -1, 1, 0, 0, 0, 0, 0),
  late_air_on_progression = c(0, 0, 0, -1, 1, 0, 0, 0, 0),
  air_offset_transition = c(0, 0, 0, 0, -1, 1, 0, 0, 0),
  early_air_off_recovery = c(0, 0, 0, 0, 0, -1, 1, 0, 0),
  air_off_mid_transition = c(0, 0, 0, 0, 0, 0, -1, 1, 0),
  late_air_off_recovery_to_next_baseline = c(0, 0, 0, 0, 0, 0, 0, -1, 1)
)

# --------------------------------------------------
# Function to fit one outcome model
# --------------------------------------------------

fit_air_cycle_outcome <- function(outcome_name) {

  cat("\n\n==============================\n")
  cat(outcome_name, "\n")
  cat("==============================\n")

  formula_text <- paste0(
    outcome_name,
    " ~ air_cycle_epoch * cycle_exposure_session_c * cycle_session_10m_c + ",
    "(1 | animal) + (1 | animal_day) + (1 | cycle_id)"
  )

  m <- lmer(
    as.formula(formula_text),
    data = air_cycle_df,
    REML = FALSE,
    control = lmerControl(
      optimizer = "bobyqa",
      optCtrl = list(maxfun = 2e5)
    )
  )

  print(summary(m))

  # Estimated marginal means at mean exposure session and mean session time
  emm <- emmeans(
    m,
    ~ air_cycle_epoch,
    at = list(
      cycle_exposure_session_c = 0,
      cycle_session_10m_c = 0
    ),
    lmer.df = "asymptotic"
  )

  # Planned adjacent contrasts
  con <- as.data.frame(
    contrast(
      emm,
      contrast_list,
      adjust = "none"
    )
  )

  con$outcome <- outcome_name

  # R2
  r2tmp <- as.data.frame(performance::r2(m))
  r2tmp$outcome <- outcome_name

  # Fixed effects table
  fixed <- broom.mixed::tidy(
    m,
    effects = "fixed",
    conf.int = TRUE
  )
  fixed$outcome <- outcome_name

  return(
    list(
      model = m,
      contrasts = con,
      r2 = r2tmp,
      fixed = fixed
    )
  )
}

# --------------------------------------------------
# Run all outcomes
# --------------------------------------------------

air_models_R <- list()
contrast_list_out <- list()
r2_list_out <- list()
fixed_list_out <- list()

for (outcome_name in air_outcomes_R) {

  result <- fit_air_cycle_outcome(outcome_name)

  air_models_R[[outcome_name]] <- result$model
  contrast_list_out[[outcome_name]] <- result$contrasts
  r2_list_out[[outcome_name]] <- result$r2
  fixed_list_out[[outcome_name]] <- result$fixed
}

air_cycle_contrasts_R <- bind_rows(contrast_list_out)
air_cycle_r2_R <- bind_rows(r2_list_out)
air_cycle_fixed_R <- bind_rows(fixed_list_out)

air_cycle_contrasts_R <- air_cycle_contrasts_R %>%
  select(outcome, contrast, estimate, SE, df, z.ratio, p.value)

air_cycle_r2_R <- air_cycle_r2_R %>%
  relocate(outcome)

air_cycle_fixed_R <- air_cycle_fixed_R %>%
  relocate(outcome)

print(air_cycle_contrasts_R)
print(air_cycle_r2_R)

[1] "frac_moving"         "frac_forward"        "mean_speed_path_cms"
[4] "mean_speed_net_cms"  "distance_path_cm"    "distance_net_cm"


==============================
frac_moving
==============================
Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: as.formula(formula_text)
   Data: air_cycle_df
Control: lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e+05))

      AIC       BIC    logLik -2*log(L)  df.resid
  14672.4   15006.8   -7296.2   14592.4     31544

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.4176 -0.6753  0.0390  0.5104  3.2582

Random effects:
 Groups     Name        Variance Std.Dev.
 cycle_id   (Intercept) 0.004092 0.06397
 animal_day (Intercept) 0.006146 0.07839
 animal     (Intercept) 0.001819 0.04265
 Residual               0.088748 0.29791
Number of obs: 31584, groups:  cycle_id, 3532; animal_day, 78; animal, 5

Fixed effects:
                                                                               Estimate
(Intercept)                                                                   2.807e-01
air_cycle_epochpost_air_on                                                    4.995e-01
air_cycle_epochpre_air_on_mid                                                 5.475e-01
air_cycle_epochpost_air_on_mid                                                5.930e-01
air_cycle_epochpre_air_off                                                    6.873e-01
air_cycle_epochpost_air_off                                                   6.421e-01
air_cycle_epochpre_air_off_mid                                                1.277e-01
air_cycle_epochpost_air_off_mid                                               1.019e-01
air_cycle_epochpre_air_on_next                                               -4.620e-03
cycle_exposure_session_c                                                     -2.049e-02
cycle_session_10m_c                                                          -3.767e-02
air_cycle_epochpost_air_on:cycle_exposure_session_c                           2.085e-02
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        2.375e-02
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       2.080e-02
air_cycle_epochpre_air_off:cycle_exposure_session_c                           1.939e-02
air_cycle_epochpost_air_off:cycle_exposure_session_c                          1.702e-02
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                      -2.260e-03
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                     -3.354e-03
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                      -5.829e-04
air_cycle_epochpost_air_on:cycle_session_10m_c                                1.709e-02
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             3.605e-02
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            1.533e-02
air_cycle_epochpre_air_off:cycle_session_10m_c                                3.281e-02
air_cycle_epochpost_air_off:cycle_session_10m_c                               2.658e-02
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            5.044e-02
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           4.151e-02
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            7.084e-03
cycle_exposure_session_c:cycle_session_10m_c                                  3.076e-03
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c      -3.623e-03
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   -4.909e-03
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c  -4.649e-03
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c      -3.945e-03
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c     -4.939e-03
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  -1.341e-03
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c -8.575e-04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   2.064e-03
                                                                             Std. Error
(Intercept)                                                                   2.173e-02
air_cycle_epochpost_air_on                                                    7.126e-03
air_cycle_epochpre_air_on_mid                                                 7.126e-03
air_cycle_epochpost_air_on_mid                                                7.126e-03
air_cycle_epochpre_air_off                                                    7.126e-03
air_cycle_epochpost_air_off                                                   7.132e-03
air_cycle_epochpre_air_off_mid                                                7.137e-03
air_cycle_epochpost_air_off_mid                                               7.137e-03
air_cycle_epochpre_air_on_next                                                7.210e-03
cycle_exposure_session_c                                                      2.174e-03
cycle_session_10m_c                                                           8.359e-03
air_cycle_epochpost_air_on:cycle_exposure_session_c                           1.457e-03
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        1.457e-03
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       1.457e-03
air_cycle_epochpre_air_off:cycle_exposure_session_c                           1.457e-03
air_cycle_epochpost_air_off:cycle_exposure_session_c                          1.458e-03
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       1.458e-03
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      1.458e-03
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       1.474e-03
air_cycle_epochpost_air_on:cycle_session_10m_c                                1.154e-02
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             1.153e-02
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            1.154e-02
air_cycle_epochpre_air_off:cycle_session_10m_c                                1.153e-02
air_cycle_epochpost_air_off:cycle_session_10m_c                               1.156e-02
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            1.158e-02
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           1.158e-02
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            1.192e-02
cycle_exposure_session_c:cycle_session_10m_c                                  1.731e-03
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       2.387e-03
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    2.387e-03
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   2.387e-03
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       2.387e-03
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      2.389e-03
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   2.392e-03
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  2.392e-03
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   2.466e-03
                                                                                     df
(Intercept)                                                                   5.488e+00
air_cycle_epochpost_air_on                                                    2.802e+04
air_cycle_epochpre_air_on_mid                                                 2.802e+04
air_cycle_epochpost_air_on_mid                                                2.802e+04
air_cycle_epochpre_air_off                                                    2.802e+04
air_cycle_epochpost_air_off                                                   2.803e+04
air_cycle_epochpre_air_off_mid                                                2.804e+04
air_cycle_epochpost_air_off_mid                                               2.804e+04
air_cycle_epochpre_air_on_next                                                2.813e+04
cycle_exposure_session_c                                                      1.140e+02
cycle_session_10m_c                                                           3.089e+04
air_cycle_epochpost_air_on:cycle_exposure_session_c                           2.802e+04
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        2.802e+04
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       2.802e+04
air_cycle_epochpre_air_off:cycle_exposure_session_c                           2.802e+04
air_cycle_epochpost_air_off:cycle_exposure_session_c                          2.803e+04
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       2.803e+04
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      2.803e+04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       2.813e+04
air_cycle_epochpost_air_on:cycle_session_10m_c                                2.803e+04
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             2.802e+04
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            2.803e+04
air_cycle_epochpre_air_off:cycle_session_10m_c                                2.802e+04
air_cycle_epochpost_air_off:cycle_session_10m_c                               2.805e+04
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            2.807e+04
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           2.807e+04
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            2.832e+04
cycle_exposure_session_c:cycle_session_10m_c                                  3.086e+04
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       2.802e+04
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    2.802e+04
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   2.802e+04
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       2.802e+04
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      2.804e+04
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   2.805e+04
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  2.805e+04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   2.832e+04
                                                                             t value
(Intercept)                                                                   12.918
air_cycle_epochpost_air_on                                                    70.099
air_cycle_epochpre_air_on_mid                                                 76.830
air_cycle_epochpost_air_on_mid                                                83.212
air_cycle_epochpre_air_off                                                    96.451
air_cycle_epochpost_air_off                                                   90.023
air_cycle_epochpre_air_off_mid                                                17.900
air_cycle_epochpost_air_off_mid                                               14.280
air_cycle_epochpre_air_on_next                                                -0.641
cycle_exposure_session_c                                                      -9.423
cycle_session_10m_c                                                           -4.507
air_cycle_epochpost_air_on:cycle_exposure_session_c                           14.309
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        16.298
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       14.278
air_cycle_epochpre_air_off:cycle_exposure_session_c                           13.310
air_cycle_epochpost_air_off:cycle_exposure_session_c                          11.674
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       -1.550
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      -2.300
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       -0.395
air_cycle_epochpost_air_on:cycle_session_10m_c                                 1.482
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                              3.125
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                             1.329
air_cycle_epochpre_air_off:cycle_session_10m_c                                 2.845
air_cycle_epochpost_air_off:cycle_session_10m_c                                2.300
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                             4.357
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                            3.584
air_cycle_epochpre_air_on_next:cycle_session_10m_c                             0.594
cycle_exposure_session_c:cycle_session_10m_c                                   1.777
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       -1.518
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    -2.057
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   -1.948
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       -1.653
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      -2.068
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   -0.560
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  -0.358
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c    0.837
                                                                             Pr(>|t|)
(Intercept)                                                                  2.57e-05
air_cycle_epochpost_air_on                                                    < 2e-16
air_cycle_epochpre_air_on_mid                                                 < 2e-16
air_cycle_epochpost_air_on_mid                                                < 2e-16
air_cycle_epochpre_air_off                                                    < 2e-16
air_cycle_epochpost_air_off                                                   < 2e-16
air_cycle_epochpre_air_off_mid                                                < 2e-16
air_cycle_epochpost_air_off_mid                                               < 2e-16
air_cycle_epochpre_air_on_next                                               0.521666
cycle_exposure_session_c                                                     6.17e-16
cycle_session_10m_c                                                          6.61e-06
air_cycle_epochpost_air_on:cycle_exposure_session_c                           < 2e-16
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        < 2e-16
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       < 2e-16
air_cycle_epochpre_air_off:cycle_exposure_session_c                           < 2e-16
air_cycle_epochpost_air_off:cycle_exposure_session_c                          < 2e-16
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                      0.121180
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                     0.021456
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                      0.692505
air_cycle_epochpost_air_on:cycle_session_10m_c                               0.138448
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                            0.001777
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                           0.183825
air_cycle_epochpre_air_off:cycle_session_10m_c                               0.004444
air_cycle_epochpost_air_off:cycle_session_10m_c                              0.021440
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                           1.33e-05
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                          0.000339
air_cycle_epochpre_air_on_next:cycle_session_10m_c                           0.552481
cycle_exposure_session_c:cycle_session_10m_c                                 0.075549
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c      0.128987
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   0.039702
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c  0.051418
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c      0.098335
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c     0.038684
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  0.575162
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c 0.719998
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c  0.402539

(Intercept)                                                                  ***
air_cycle_epochpost_air_on                                                   ***
air_cycle_epochpre_air_on_mid                                                ***
air_cycle_epochpost_air_on_mid                                               ***
air_cycle_epochpre_air_off                                                   ***
air_cycle_epochpost_air_off                                                  ***
air_cycle_epochpre_air_off_mid                                               ***
air_cycle_epochpost_air_off_mid                                              ***
air_cycle_epochpre_air_on_next
cycle_exposure_session_c                                                     ***
cycle_session_10m_c                                                          ***
air_cycle_epochpost_air_on:cycle_exposure_session_c                          ***
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                       ***
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                      ***
air_cycle_epochpre_air_off:cycle_exposure_session_c                          ***
air_cycle_epochpost_air_off:cycle_exposure_session_c                         ***
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                     *
air_cycle_epochpre_air_on_next:cycle_exposure_session_c
air_cycle_epochpost_air_on:cycle_session_10m_c
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                            **
air_cycle_epochpost_air_on_mid:cycle_session_10m_c
air_cycle_epochpre_air_off:cycle_session_10m_c                               **
air_cycle_epochpost_air_off:cycle_session_10m_c                              *
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                           ***
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                          ***
air_cycle_epochpre_air_on_next:cycle_session_10m_c
cycle_exposure_session_c:cycle_session_10m_c                                 .
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   *
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c  .
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c      .
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c     *
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

R[write to console]:
Correlation matrix not shown by default, as p = 36 > 12.
Use print(summary(m), correlation=TRUE)  or
    vcov(summary(m))        if you need it


R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
frac_forward
==============================
Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: as.formula(formula_text)
   Data: air_cycle_df
Control: lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e+05))

      AIC       BIC    logLik -2*log(L)  df.resid
  16811.2   17145.6   -8365.6   16731.2     31544

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.2639 -0.7028  0.0238  0.5834  3.2957

Random effects:
 Groups     Name        Variance Std.Dev.
 cycle_id   (Intercept) 0.003468 0.05889
 animal_day (Intercept) 0.006467 0.08042
 animal     (Intercept) 0.002991 0.05469
 Residual               0.095637 0.30925
Number of obs: 31584, groups:  cycle_id, 3532; animal_day, 78; animal, 5

Fixed effects:
                                                                               Estimate
(Intercept)                                                                   2.576e-01
air_cycle_epochpost_air_on                                                    4.027e-01
air_cycle_epochpre_air_on_mid                                                 5.227e-01
air_cycle_epochpost_air_on_mid                                                5.833e-01
air_cycle_epochpre_air_off                                                    6.915e-01
air_cycle_epochpost_air_off                                                   5.765e-01
air_cycle_epochpre_air_off_mid                                                1.252e-01
air_cycle_epochpost_air_off_mid                                               1.006e-01
air_cycle_epochpre_air_on_next                                               -3.055e-03
cycle_exposure_session_c                                                     -2.013e-02
cycle_session_10m_c                                                          -2.552e-02
air_cycle_epochpost_air_on:cycle_exposure_session_c                           2.744e-02
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        2.773e-02
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       2.275e-02
air_cycle_epochpre_air_off:cycle_exposure_session_c                           1.951e-02
air_cycle_epochpost_air_off:cycle_exposure_session_c                          1.358e-02
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                      -2.717e-03
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                     -3.339e-03
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                      -6.502e-04
air_cycle_epochpost_air_on:cycle_session_10m_c                                3.601e-02
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             4.166e-02
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            1.165e-02
air_cycle_epochpre_air_off:cycle_session_10m_c                                2.238e-02
air_cycle_epochpost_air_off:cycle_session_10m_c                              -8.175e-04
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            4.586e-02
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           3.486e-02
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            4.772e-03
cycle_exposure_session_c:cycle_session_10m_c                                  2.818e-03
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c      -2.100e-03
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   -5.164e-03
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c  -5.275e-03
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c      -3.852e-03
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c     -5.792e-03
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  -1.422e-03
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c -1.306e-03
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   2.182e-03
                                                                             Std. Error
(Intercept)                                                                   2.669e-02
air_cycle_epochpost_air_on                                                    7.398e-03
air_cycle_epochpre_air_on_mid                                                 7.397e-03
air_cycle_epochpost_air_on_mid                                                7.398e-03
air_cycle_epochpre_air_off                                                    7.397e-03
air_cycle_epochpost_air_off                                                   7.404e-03
air_cycle_epochpre_air_off_mid                                                7.409e-03
air_cycle_epochpost_air_off_mid                                               7.409e-03
air_cycle_epochpre_air_on_next                                                7.485e-03
cycle_exposure_session_c                                                      2.236e-03
cycle_session_10m_c                                                           8.636e-03
air_cycle_epochpost_air_on:cycle_exposure_session_c                           1.512e-03
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        1.512e-03
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       1.512e-03
air_cycle_epochpre_air_off:cycle_exposure_session_c                           1.512e-03
air_cycle_epochpost_air_off:cycle_exposure_session_c                          1.513e-03
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       1.514e-03
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      1.514e-03
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       1.530e-03
air_cycle_epochpost_air_on:cycle_session_10m_c                                1.197e-02
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             1.197e-02
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            1.197e-02
air_cycle_epochpre_air_off:cycle_session_10m_c                                1.197e-02
air_cycle_epochpost_air_off:cycle_session_10m_c                               1.200e-02
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            1.202e-02
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           1.202e-02
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            1.238e-02
cycle_exposure_session_c:cycle_session_10m_c                                  1.788e-03
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       2.478e-03
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    2.477e-03
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   2.478e-03
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       2.477e-03
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      2.480e-03
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   2.483e-03
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  2.483e-03
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   2.559e-03
                                                                                     df
(Intercept)                                                                   5.351e+00
air_cycle_epochpost_air_on                                                    2.802e+04
air_cycle_epochpre_air_on_mid                                                 2.802e+04
air_cycle_epochpost_air_on_mid                                                2.802e+04
air_cycle_epochpre_air_off                                                    2.802e+04
air_cycle_epochpost_air_off                                                   2.803e+04
air_cycle_epochpre_air_off_mid                                                2.803e+04
air_cycle_epochpost_air_off_mid                                               2.803e+04
air_cycle_epochpre_air_on_next                                                2.813e+04
cycle_exposure_session_c                                                      1.140e+02
cycle_session_10m_c                                                           3.109e+04
air_cycle_epochpost_air_on:cycle_exposure_session_c                           2.802e+04
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        2.802e+04
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       2.802e+04
air_cycle_epochpre_air_off:cycle_exposure_session_c                           2.802e+04
air_cycle_epochpost_air_off:cycle_exposure_session_c                          2.802e+04
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       2.803e+04
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      2.803e+04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       2.813e+04
air_cycle_epochpost_air_on:cycle_session_10m_c                                2.802e+04
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             2.802e+04
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            2.802e+04
air_cycle_epochpre_air_off:cycle_session_10m_c                                2.802e+04
air_cycle_epochpost_air_off:cycle_session_10m_c                               2.804e+04
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            2.806e+04
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           2.806e+04
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            2.833e+04
cycle_exposure_session_c:cycle_session_10m_c                                  3.107e+04
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       2.802e+04
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    2.802e+04
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   2.802e+04
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       2.802e+04
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      2.803e+04
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   2.804e+04
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  2.804e+04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   2.832e+04
                                                                             t value
(Intercept)                                                                    9.651
air_cycle_epochpost_air_on                                                    54.437
air_cycle_epochpre_air_on_mid                                                 70.665
air_cycle_epochpost_air_on_mid                                                78.844
air_cycle_epochpre_air_off                                                    93.477
air_cycle_epochpost_air_off                                                   77.861
air_cycle_epochpre_air_off_mid                                                16.898
air_cycle_epochpost_air_off_mid                                               13.580
air_cycle_epochpre_air_on_next                                                -0.408
cycle_exposure_session_c                                                      -9.000
cycle_session_10m_c                                                           -2.956
air_cycle_epochpost_air_on:cycle_exposure_session_c                           18.145
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        18.338
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       15.042
air_cycle_epochpre_air_off:cycle_exposure_session_c                           12.898
air_cycle_epochpost_air_off:cycle_exposure_session_c                           8.973
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       -1.795
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      -2.205
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       -0.425
air_cycle_epochpost_air_on:cycle_session_10m_c                                 3.007
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                              3.479
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                             0.973
air_cycle_epochpre_air_off:cycle_session_10m_c                                 1.869
air_cycle_epochpost_air_off:cycle_session_10m_c                               -0.068
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                             3.816
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                            2.900
air_cycle_epochpre_air_on_next:cycle_session_10m_c                             0.386
cycle_exposure_session_c:cycle_session_10m_c                                   1.576
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       -0.848
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    -2.085
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   -2.129
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       -1.555
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      -2.336
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   -0.572
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  -0.526
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c    0.853
                                                                             Pr(>|t|)
(Intercept)                                                                  0.000139
air_cycle_epochpost_air_on                                                    < 2e-16
air_cycle_epochpre_air_on_mid                                                 < 2e-16
air_cycle_epochpost_air_on_mid                                                < 2e-16
air_cycle_epochpre_air_off                                                    < 2e-16
air_cycle_epochpost_air_off                                                   < 2e-16
air_cycle_epochpre_air_off_mid                                                < 2e-16
air_cycle_epochpost_air_off_mid                                               < 2e-16
air_cycle_epochpre_air_on_next                                               0.683111
cycle_exposure_session_c                                                     5.89e-15
cycle_session_10m_c                                                          0.003122
air_cycle_epochpost_air_on:cycle_exposure_session_c                           < 2e-16
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        < 2e-16
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       < 2e-16
air_cycle_epochpre_air_off:cycle_exposure_session_c                           < 2e-16
air_cycle_epochpost_air_off:cycle_exposure_session_c                          < 2e-16
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                      0.072718
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                     0.027441
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                      0.670853
air_cycle_epochpost_air_on:cycle_session_10m_c                               0.002638
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                            0.000503
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                           0.330799
air_cycle_epochpre_air_off:cycle_session_10m_c                               0.061612
air_cycle_epochpost_air_off:cycle_session_10m_c                              0.945675
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                           0.000136
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                          0.003734
air_cycle_epochpre_air_on_next:cycle_session_10m_c                           0.699812
cycle_exposure_session_c:cycle_session_10m_c                                 0.114992
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c      0.396690
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   0.037121
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c  0.033244
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c      0.119947
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c     0.019517
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  0.567018
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c 0.599022
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c  0.393813

(Intercept)                                                                  ***
air_cycle_epochpost_air_on                                                   ***
air_cycle_epochpre_air_on_mid                                                ***
air_cycle_epochpost_air_on_mid                                               ***
air_cycle_epochpre_air_off                                                   ***
air_cycle_epochpost_air_off                                                  ***
air_cycle_epochpre_air_off_mid                                               ***
air_cycle_epochpost_air_off_mid                                              ***
air_cycle_epochpre_air_on_next
cycle_exposure_session_c                                                     ***
cycle_session_10m_c                                                          **
air_cycle_epochpost_air_on:cycle_exposure_session_c                          ***
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                       ***
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                      ***
air_cycle_epochpre_air_off:cycle_exposure_session_c                          ***
air_cycle_epochpost_air_off:cycle_exposure_session_c                         ***
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                      .
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                     *
air_cycle_epochpre_air_on_next:cycle_exposure_session_c
air_cycle_epochpost_air_on:cycle_session_10m_c                               **
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                            ***
air_cycle_epochpost_air_on_mid:cycle_session_10m_c
air_cycle_epochpre_air_off:cycle_session_10m_c                               .
air_cycle_epochpost_air_off:cycle_session_10m_c
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                           ***
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                          **
air_cycle_epochpre_air_on_next:cycle_session_10m_c
cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   *
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c  *
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c     *
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

R[write to console]:
Correlation matrix not shown by default, as p = 36 > 12.
Use print(summary(m), correlation=TRUE)  or
    vcov(summary(m))        if you need it


R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
mean_speed_path_cms
==============================
Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: as.formula(formula_text)
   Data: air_cycle_df
Control: lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e+05))

      AIC       BIC    logLik -2*log(L)  df.resid
 258215.7  258550.1 -129067.9  258135.7     31544

Scaled residuals:
    Min      1Q  Median      3Q     Max
 -1.360  -0.107  -0.031   0.088 169.383

Random effects:
 Groups     Name        Variance Std.Dev.
 cycle_id   (Intercept)   0.2219  0.4711
 animal_day (Intercept)   1.5455  1.2432
 animal     (Intercept)   0.3456  0.5879
 Residual               206.5536 14.3720
Number of obs: 31584, groups:  cycle_id, 3532; animal_day, 78; animal, 5

Fixed effects:
                                                                               Estimate
(Intercept)                                                                   1.370e+00
air_cycle_epochpost_air_on                                                    1.562e+00
air_cycle_epochpre_air_on_mid                                                 3.917e+00
air_cycle_epochpost_air_on_mid                                                4.230e+00
air_cycle_epochpre_air_off                                                    5.088e+00
air_cycle_epochpost_air_off                                                   3.329e+00
air_cycle_epochpre_air_off_mid                                                6.453e-01
air_cycle_epochpost_air_off_mid                                               5.175e-01
air_cycle_epochpre_air_on_next                                               -9.257e-03
cycle_exposure_session_c                                                     -1.749e-01
cycle_session_10m_c                                                          -1.773e-01
air_cycle_epochpost_air_on:cycle_exposure_session_c                           1.269e-01
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        1.453e-01
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       1.768e-02
air_cycle_epochpre_air_off:cycle_exposure_session_c                          -7.375e-02
air_cycle_epochpost_air_off:cycle_exposure_session_c                         -1.053e-01
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                      -3.859e-02
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                     -3.754e-02
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                      -4.002e-03
air_cycle_epochpost_air_on:cycle_session_10m_c                                1.218e-02
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             4.687e+00
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            1.463e-01
air_cycle_epochpre_air_off:cycle_session_10m_c                                2.944e-01
air_cycle_epochpost_air_off:cycle_session_10m_c                              -4.872e-01
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            2.857e-01
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           2.503e-01
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            1.588e-02
cycle_exposure_session_c:cycle_session_10m_c                                  2.827e-04
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       9.341e-03
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   -3.382e-01
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   1.317e-02
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c      -3.216e-02
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c     -4.781e-02
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  -3.019e-02
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c -2.395e-02
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   9.567e-03
                                                                             Std. Error
(Intercept)                                                                   3.872e-01
air_cycle_epochpost_air_on                                                    3.438e-01
air_cycle_epochpre_air_on_mid                                                 3.438e-01
air_cycle_epochpost_air_on_mid                                                3.438e-01
air_cycle_epochpre_air_off                                                    3.438e-01
air_cycle_epochpost_air_off                                                   3.441e-01
air_cycle_epochpre_air_off_mid                                                3.443e-01
air_cycle_epochpost_air_off_mid                                               3.443e-01
air_cycle_epochpre_air_on_next                                                3.477e-01
cycle_exposure_session_c                                                      5.856e-02
cycle_session_10m_c                                                           3.941e-01
air_cycle_epochpost_air_on:cycle_exposure_session_c                           7.029e-02
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        7.029e-02
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       7.029e-02
air_cycle_epochpre_air_off:cycle_exposure_session_c                           7.029e-02
air_cycle_epochpost_air_off:cycle_exposure_session_c                          7.032e-02
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       7.035e-02
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      7.035e-02
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       7.108e-02
air_cycle_epochpost_air_on:cycle_session_10m_c                                5.565e-01
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             5.564e-01
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            5.565e-01
air_cycle_epochpre_air_off:cycle_session_10m_c                                5.564e-01
air_cycle_epochpost_air_off:cycle_session_10m_c                               5.575e-01
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            5.585e-01
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           5.586e-01
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            5.747e-01
cycle_exposure_session_c:cycle_session_10m_c                                  8.158e-02
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       1.151e-01
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    1.151e-01
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   1.151e-01
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       1.151e-01
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      1.152e-01
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   1.154e-01
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  1.154e-01
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   1.188e-01
                                                                                     df
(Intercept)                                                                   1.190e+01
air_cycle_epochpost_air_on                                                    2.726e+04
air_cycle_epochpre_air_on_mid                                                 2.726e+04
air_cycle_epochpost_air_on_mid                                                2.726e+04
air_cycle_epochpre_air_off                                                    2.726e+04
air_cycle_epochpost_air_off                                                   2.727e+04
air_cycle_epochpre_air_off_mid                                                2.728e+04
air_cycle_epochpost_air_off_mid                                               2.728e+04
air_cycle_epochpre_air_on_next                                                2.742e+04
cycle_exposure_session_c                                                      6.012e+02
cycle_session_10m_c                                                           3.155e+04
air_cycle_epochpost_air_on:cycle_exposure_session_c                           2.726e+04
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        2.726e+04
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       2.726e+04
air_cycle_epochpre_air_off:cycle_exposure_session_c                           2.726e+04
air_cycle_epochpost_air_off:cycle_exposure_session_c                          2.726e+04
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       2.727e+04
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      2.727e+04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       2.742e+04
air_cycle_epochpost_air_on:cycle_session_10m_c                                2.726e+04
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             2.726e+04
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            2.726e+04
air_cycle_epochpre_air_off:cycle_session_10m_c                                2.726e+04
air_cycle_epochpost_air_off:cycle_session_10m_c                               2.729e+04
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            2.731e+04
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           2.732e+04
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            2.772e+04
cycle_exposure_session_c:cycle_session_10m_c                                  3.156e+04
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       2.726e+04
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    2.726e+04
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   2.726e+04
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       2.726e+04
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      2.727e+04
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   2.729e+04
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  2.729e+04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   2.771e+04
                                                                             t value
(Intercept)                                                                    3.538
air_cycle_epochpost_air_on                                                     4.543
air_cycle_epochpre_air_on_mid                                                 11.394
air_cycle_epochpost_air_on_mid                                                12.304
air_cycle_epochpre_air_off                                                    14.800
air_cycle_epochpost_air_off                                                    9.675
air_cycle_epochpre_air_off_mid                                                 1.874
air_cycle_epochpost_air_off_mid                                                1.503
air_cycle_epochpre_air_on_next                                                -0.027
cycle_exposure_session_c                                                      -2.987
cycle_session_10m_c                                                           -0.450
air_cycle_epochpost_air_on:cycle_exposure_session_c                            1.805
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                         2.067
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                        0.252
air_cycle_epochpre_air_off:cycle_exposure_session_c                           -1.049
air_cycle_epochpost_air_off:cycle_exposure_session_c                          -1.498
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       -0.549
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      -0.534
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       -0.056
air_cycle_epochpost_air_on:cycle_session_10m_c                                 0.022
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                              8.424
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                             0.263
air_cycle_epochpre_air_off:cycle_session_10m_c                                 0.529
air_cycle_epochpost_air_off:cycle_session_10m_c                               -0.874
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                             0.512
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                            0.448
air_cycle_epochpre_air_on_next:cycle_session_10m_c                             0.028
cycle_exposure_session_c:cycle_session_10m_c                                   0.003
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c        0.081
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    -2.938
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    0.114
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       -0.279
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      -0.415
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   -0.262
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  -0.208
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c    0.080
                                                                             Pr(>|t|)
(Intercept)                                                                   0.00413
air_cycle_epochpost_air_on                                                   5.57e-06
air_cycle_epochpre_air_on_mid                                                 < 2e-16
air_cycle_epochpost_air_on_mid                                                < 2e-16
air_cycle_epochpre_air_off                                                    < 2e-16
air_cycle_epochpost_air_off                                                   < 2e-16
air_cycle_epochpre_air_off_mid                                                0.06088
air_cycle_epochpost_air_off_mid                                               0.13282
air_cycle_epochpre_air_on_next                                                0.97876
cycle_exposure_session_c                                                      0.00293
cycle_session_10m_c                                                           0.65285
air_cycle_epochpost_air_on:cycle_exposure_session_c                           0.07109
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        0.03875
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       0.80141
air_cycle_epochpre_air_off:cycle_exposure_session_c                           0.29411
air_cycle_epochpost_air_off:cycle_exposure_session_c                          0.13413
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       0.58333
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      0.59367
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       0.95511
air_cycle_epochpost_air_on:cycle_session_10m_c                                0.98254
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             < 2e-16
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            0.79268
air_cycle_epochpre_air_off:cycle_session_10m_c                                0.59671
air_cycle_epochpost_air_off:cycle_session_10m_c                               0.38221
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            0.60896
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           0.65408
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            0.97795
cycle_exposure_session_c:cycle_session_10m_c                                  0.99724
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       0.93534
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    0.00331
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   0.90892
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       0.77996
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      0.67822
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   0.79359
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  0.83561
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   0.93584

(Intercept)                                                                  **
air_cycle_epochpost_air_on                                                   ***
air_cycle_epochpre_air_on_mid                                                ***
air_cycle_epochpost_air_on_mid                                               ***
air_cycle_epochpre_air_off                                                   ***
air_cycle_epochpost_air_off                                                  ***
air_cycle_epochpre_air_off_mid                                               .
air_cycle_epochpost_air_off_mid
air_cycle_epochpre_air_on_next
cycle_exposure_session_c                                                     **
cycle_session_10m_c
air_cycle_epochpost_air_on:cycle_exposure_session_c                          .
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                       *
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c
air_cycle_epochpre_air_off:cycle_exposure_session_c
air_cycle_epochpost_air_off:cycle_exposure_session_c
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c
air_cycle_epochpre_air_on_next:cycle_exposure_session_c
air_cycle_epochpost_air_on:cycle_session_10m_c
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                            ***
air_cycle_epochpost_air_on_mid:cycle_session_10m_c
air_cycle_epochpre_air_off:cycle_session_10m_c
air_cycle_epochpost_air_off:cycle_session_10m_c
air_cycle_epochpre_air_off_mid:cycle_session_10m_c
air_cycle_epochpost_air_off_mid:cycle_session_10m_c
air_cycle_epochpre_air_on_next:cycle_session_10m_c
cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   **
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

R[write to console]:
Correlation matrix not shown by default, as p = 36 > 12.
Use print(summary(m), correlation=TRUE)  or
    vcov(summary(m))        if you need it


R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
mean_speed_net_cms
==============================
Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: as.formula(formula_text)
   Data: air_cycle_df
Control: lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e+05))

      AIC       BIC    logLik -2*log(L)  df.resid
 258515.4  258849.8 -129217.7  258435.4     31544

Scaled residuals:
     Min       1Q   Median       3Q      Max
-168.993   -0.108   -0.026    0.109    1.478

Random effects:
 Groups     Name        Variance Std.Dev.
 cycle_id   (Intercept)   0.8129  0.9016
 animal_day (Intercept)   1.8348  1.3545
 animal     (Intercept)   0.7018  0.8377
 Residual               207.8779 14.4180
Number of obs: 31584, groups:  cycle_id, 3532; animal_day, 78; animal, 5

Fixed effects:
                                                                               Estimate
(Intercept)                                                                   1.216e+00
air_cycle_epochpost_air_on                                                    1.270e+00
air_cycle_epochpre_air_on_mid                                                 2.640e+00
air_cycle_epochpost_air_on_mid                                                4.179e+00
air_cycle_epochpre_air_off                                                    5.090e+00
air_cycle_epochpost_air_off                                                   2.778e+00
air_cycle_epochpre_air_off_mid                                                6.414e-01
air_cycle_epochpost_air_off_mid                                               5.201e-01
air_cycle_epochpre_air_on_next                                               -1.099e-02
cycle_exposure_session_c                                                     -1.799e-01
cycle_session_10m_c                                                          -6.649e-02
air_cycle_epochpost_air_on:cycle_exposure_session_c                           1.506e-01
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        1.840e-01
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       2.829e-02
air_cycle_epochpre_air_off:cycle_exposure_session_c                          -7.234e-02
air_cycle_epochpost_air_off:cycle_exposure_session_c                         -1.504e-01
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                      -4.058e-02
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                     -3.812e-02
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                      -4.126e-03
air_cycle_epochpost_air_on:cycle_session_10m_c                                1.452e-01
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                            -3.327e+00
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            1.628e-01
air_cycle_epochpre_air_off:cycle_session_10m_c                                2.763e-01
air_cycle_epochpost_air_off:cycle_session_10m_c                              -7.438e-02
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            2.807e-01
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           2.350e-01
air_cycle_epochpre_air_on_next:cycle_session_10m_c                           -1.139e-02
cycle_exposure_session_c:cycle_session_10m_c                                 -4.011e-03
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       5.776e-03
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    3.112e-01
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   7.380e-03
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c      -3.327e-02
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      7.677e-03
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  -2.908e-02
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c -2.376e-02
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   1.184e-02
                                                                             Std. Error
(Intercept)                                                                   4.751e-01
air_cycle_epochpost_air_on                                                    3.449e-01
air_cycle_epochpre_air_on_mid                                                 3.449e-01
air_cycle_epochpost_air_on_mid                                                3.449e-01
air_cycle_epochpre_air_off                                                    3.449e-01
air_cycle_epochpost_air_off                                                   3.452e-01
air_cycle_epochpre_air_off_mid                                                3.454e-01
air_cycle_epochpost_air_off_mid                                               3.454e-01
air_cycle_epochpre_air_on_next                                                3.489e-01
cycle_exposure_session_c                                                      6.028e-02
cycle_session_10m_c                                                           3.960e-01
air_cycle_epochpost_air_on:cycle_exposure_session_c                           7.051e-02
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        7.051e-02
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       7.051e-02
air_cycle_epochpre_air_off:cycle_exposure_session_c                           7.051e-02
air_cycle_epochpost_air_off:cycle_exposure_session_c                          7.055e-02
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       7.058e-02
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      7.058e-02
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       7.131e-02
air_cycle_epochpost_air_on:cycle_session_10m_c                                5.583e-01
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             5.582e-01
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            5.583e-01
air_cycle_epochpre_air_off:cycle_session_10m_c                                5.582e-01
air_cycle_epochpost_air_off:cycle_session_10m_c                               5.593e-01
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            5.603e-01
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           5.604e-01
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            5.766e-01
cycle_exposure_session_c:cycle_session_10m_c                                  8.196e-02
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       1.155e-01
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    1.155e-01
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   1.155e-01
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       1.155e-01
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      1.156e-01
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   1.158e-01
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  1.158e-01
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   1.192e-01
                                                                                     df
(Intercept)                                                                   8.282e+00
air_cycle_epochpost_air_on                                                    2.728e+04
air_cycle_epochpre_air_on_mid                                                 2.728e+04
air_cycle_epochpost_air_on_mid                                                2.728e+04
air_cycle_epochpre_air_off                                                    2.728e+04
air_cycle_epochpost_air_off                                                   2.729e+04
air_cycle_epochpre_air_off_mid                                                2.730e+04
air_cycle_epochpost_air_off_mid                                               2.730e+04
air_cycle_epochpre_air_on_next                                                2.744e+04
cycle_exposure_session_c                                                      4.963e+02
cycle_session_10m_c                                                           3.153e+04
air_cycle_epochpost_air_on:cycle_exposure_session_c                           2.728e+04
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        2.728e+04
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       2.728e+04
air_cycle_epochpre_air_off:cycle_exposure_session_c                           2.728e+04
air_cycle_epochpost_air_off:cycle_exposure_session_c                          2.728e+04
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       2.729e+04
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      2.729e+04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       2.743e+04
air_cycle_epochpost_air_on:cycle_session_10m_c                                2.728e+04
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             2.728e+04
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            2.728e+04
air_cycle_epochpre_air_off:cycle_session_10m_c                                2.728e+04
air_cycle_epochpost_air_off:cycle_session_10m_c                               2.731e+04
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            2.733e+04
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           2.733e+04
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            2.772e+04
cycle_exposure_session_c:cycle_session_10m_c                                  3.154e+04
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       2.728e+04
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    2.728e+04
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   2.728e+04
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       2.728e+04
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      2.729e+04
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   2.731e+04
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  2.731e+04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   2.771e+04
                                                                             t value
(Intercept)                                                                    2.560
air_cycle_epochpost_air_on                                                     3.681
air_cycle_epochpre_air_on_mid                                                  7.656
air_cycle_epochpost_air_on_mid                                                12.117
air_cycle_epochpre_air_off                                                    14.758
air_cycle_epochpost_air_off                                                    8.050
air_cycle_epochpre_air_off_mid                                                 1.857
air_cycle_epochpost_air_off_mid                                                1.506
air_cycle_epochpre_air_on_next                                                -0.032
cycle_exposure_session_c                                                      -2.984
cycle_session_10m_c                                                           -0.168
air_cycle_epochpost_air_on:cycle_exposure_session_c                            2.136
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                         2.610
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                        0.401
air_cycle_epochpre_air_off:cycle_exposure_session_c                           -1.026
air_cycle_epochpost_air_off:cycle_exposure_session_c                          -2.131
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       -0.575
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      -0.540
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       -0.058
air_cycle_epochpost_air_on:cycle_session_10m_c                                 0.260
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             -5.960
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                             0.292
air_cycle_epochpre_air_off:cycle_session_10m_c                                 0.495
air_cycle_epochpost_air_off:cycle_session_10m_c                               -0.133
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                             0.501
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                            0.419
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            -0.020
cycle_exposure_session_c:cycle_session_10m_c                                  -0.049
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c        0.050
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c     2.694
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    0.064
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       -0.288
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c       0.066
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   -0.251
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  -0.205
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c    0.099
                                                                             Pr(>|t|)
(Intercept)                                                                  0.032745
air_cycle_epochpost_air_on                                                   0.000233
air_cycle_epochpre_air_on_mid                                                1.99e-14
air_cycle_epochpost_air_on_mid                                                < 2e-16
air_cycle_epochpre_air_off                                                    < 2e-16
air_cycle_epochpost_air_off                                                  8.65e-16
air_cycle_epochpre_air_off_mid                                               0.063327
air_cycle_epochpost_air_off_mid                                              0.132159
air_cycle_epochpre_air_on_next                                               0.974868
cycle_exposure_session_c                                                     0.002983
cycle_session_10m_c                                                          0.866647
air_cycle_epochpost_air_on:cycle_exposure_session_c                          0.032690
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                       0.009060
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                      0.688245
air_cycle_epochpre_air_off:cycle_exposure_session_c                          0.304958
air_cycle_epochpost_air_off:cycle_exposure_session_c                         0.033069
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                      0.565295
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                     0.589114
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                      0.953859
air_cycle_epochpost_air_on:cycle_session_10m_c                               0.794847
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                            2.55e-09
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                           0.770598
air_cycle_epochpre_air_off:cycle_session_10m_c                               0.620544
air_cycle_epochpost_air_off:cycle_session_10m_c                              0.894209
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                           0.616374
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                          0.675000
air_cycle_epochpre_air_on_next:cycle_session_10m_c                           0.984236
cycle_exposure_session_c:cycle_session_10m_c                                 0.960967
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c      0.960122
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   0.007055
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c  0.949059
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c      0.773280
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c     0.947055
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  0.801694
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c 0.837413
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c  0.920909

(Intercept)                                                                  *
air_cycle_epochpost_air_on                                                   ***
air_cycle_epochpre_air_on_mid                                                ***
air_cycle_epochpost_air_on_mid                                               ***
air_cycle_epochpre_air_off                                                   ***
air_cycle_epochpost_air_off                                                  ***
air_cycle_epochpre_air_off_mid                                               .
air_cycle_epochpost_air_off_mid
air_cycle_epochpre_air_on_next
cycle_exposure_session_c                                                     **
cycle_session_10m_c
air_cycle_epochpost_air_on:cycle_exposure_session_c                          *
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                       **
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c
air_cycle_epochpre_air_off:cycle_exposure_session_c
air_cycle_epochpost_air_off:cycle_exposure_session_c                         *
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c
air_cycle_epochpre_air_on_next:cycle_exposure_session_c
air_cycle_epochpost_air_on:cycle_session_10m_c
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                            ***
air_cycle_epochpost_air_on_mid:cycle_session_10m_c
air_cycle_epochpre_air_off:cycle_session_10m_c
air_cycle_epochpost_air_off:cycle_session_10m_c
air_cycle_epochpre_air_off_mid:cycle_session_10m_c
air_cycle_epochpost_air_off_mid:cycle_session_10m_c
air_cycle_epochpre_air_on_next:cycle_session_10m_c
cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   **
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

R[write to console]:
Correlation matrix not shown by default, as p = 36 > 12.
Use print(summary(m), correlation=TRUE)  or
    vcov(summary(m))        if you need it


R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
distance_path_cm
==============================
Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: as.formula(formula_text)
   Data: air_cycle_df
Control: lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e+05))

      AIC       BIC    logLik -2*log(L)  df.resid
 258219.2  258553.7 -129069.6  258139.2     31544

Scaled residuals:
    Min      1Q  Median      3Q     Max
 -1.361  -0.107  -0.031   0.088 169.374

Random effects:
 Groups     Name        Variance Std.Dev.
 cycle_id   (Intercept)   0.2209  0.4700
 animal_day (Intercept)   1.5460  1.2434
 animal     (Intercept)   0.3441  0.5866
 Residual               206.5776 14.3728
Number of obs: 31584, groups:  cycle_id, 3532; animal_day, 78; animal, 5

Fixed effects:
                                                                               Estimate
(Intercept)                                                                   1.374e+00
air_cycle_epochpost_air_on                                                    1.574e+00
air_cycle_epochpre_air_on_mid                                                 3.921e+00
air_cycle_epochpost_air_on_mid                                                4.231e+00
air_cycle_epochpre_air_off                                                    5.078e+00
air_cycle_epochpost_air_off                                                   3.347e+00
air_cycle_epochpre_air_off_mid                                                6.453e-01
air_cycle_epochpost_air_off_mid                                               5.175e-01
air_cycle_epochpre_air_on_next                                               -9.415e-03
cycle_exposure_session_c                                                     -1.750e-01
cycle_session_10m_c                                                          -1.787e-01
air_cycle_epochpost_air_on:cycle_exposure_session_c                           1.265e-01
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        1.449e-01
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       1.744e-02
air_cycle_epochpre_air_off:cycle_exposure_session_c                          -7.390e-02
air_cycle_epochpost_air_off:cycle_exposure_session_c                         -1.046e-01
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                      -3.860e-02
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                     -3.761e-02
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                      -3.975e-03
air_cycle_epochpost_air_on:cycle_session_10m_c                                1.150e-02
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             4.687e+00
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            1.465e-01
air_cycle_epochpre_air_off:cycle_session_10m_c                                2.963e-01
air_cycle_epochpost_air_off:cycle_session_10m_c                              -4.846e-01
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            2.862e-01
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           2.510e-01
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            1.607e-02
cycle_exposure_session_c:cycle_session_10m_c                                  2.780e-04
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       9.645e-03
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   -3.381e-01
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   1.307e-02
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c      -3.217e-02
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c     -4.778e-02
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  -3.015e-02
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c -2.374e-02
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   9.503e-03
                                                                             Std. Error
(Intercept)                                                                   3.868e-01
air_cycle_epochpost_air_on                                                    3.438e-01
air_cycle_epochpre_air_on_mid                                                 3.438e-01
air_cycle_epochpost_air_on_mid                                                3.438e-01
air_cycle_epochpre_air_off                                                    3.438e-01
air_cycle_epochpost_air_off                                                   3.441e-01
air_cycle_epochpre_air_off_mid                                                3.443e-01
air_cycle_epochpost_air_off_mid                                               3.443e-01
air_cycle_epochpre_air_on_next                                                3.477e-01
cycle_exposure_session_c                                                      5.857e-02
cycle_session_10m_c                                                           3.941e-01
air_cycle_epochpost_air_on:cycle_exposure_session_c                           7.029e-02
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        7.029e-02
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       7.029e-02
air_cycle_epochpre_air_off:cycle_exposure_session_c                           7.029e-02
air_cycle_epochpost_air_off:cycle_exposure_session_c                          7.033e-02
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       7.036e-02
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      7.036e-02
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       7.109e-02
air_cycle_epochpost_air_on:cycle_session_10m_c                                5.565e-01
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             5.564e-01
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            5.565e-01
air_cycle_epochpre_air_off:cycle_session_10m_c                                5.564e-01
air_cycle_epochpost_air_off:cycle_session_10m_c                               5.575e-01
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            5.585e-01
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           5.586e-01
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            5.747e-01
cycle_exposure_session_c:cycle_session_10m_c                                  8.158e-02
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       1.151e-01
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    1.151e-01
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   1.151e-01
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       1.151e-01
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      1.152e-01
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   1.154e-01
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  1.154e-01
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   1.189e-01
                                                                                     df
(Intercept)                                                                   1.193e+01
air_cycle_epochpost_air_on                                                    2.726e+04
air_cycle_epochpre_air_on_mid                                                 2.726e+04
air_cycle_epochpost_air_on_mid                                                2.726e+04
air_cycle_epochpre_air_off                                                    2.726e+04
air_cycle_epochpost_air_off                                                   2.727e+04
air_cycle_epochpre_air_off_mid                                                2.728e+04
air_cycle_epochpost_air_off_mid                                               2.728e+04
air_cycle_epochpre_air_on_next                                                2.742e+04
cycle_exposure_session_c                                                      6.013e+02
cycle_session_10m_c                                                           3.155e+04
air_cycle_epochpost_air_on:cycle_exposure_session_c                           2.726e+04
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        2.726e+04
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       2.726e+04
air_cycle_epochpre_air_off:cycle_exposure_session_c                           2.726e+04
air_cycle_epochpost_air_off:cycle_exposure_session_c                          2.726e+04
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       2.727e+04
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      2.727e+04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       2.742e+04
air_cycle_epochpost_air_on:cycle_session_10m_c                                2.726e+04
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             2.726e+04
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            2.726e+04
air_cycle_epochpre_air_off:cycle_session_10m_c                                2.726e+04
air_cycle_epochpost_air_off:cycle_session_10m_c                               2.729e+04
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            2.731e+04
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           2.732e+04
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            2.772e+04
cycle_exposure_session_c:cycle_session_10m_c                                  3.156e+04
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       2.726e+04
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    2.726e+04
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   2.726e+04
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       2.726e+04
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      2.727e+04
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   2.729e+04
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  2.729e+04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   2.771e+04
                                                                             t value
(Intercept)                                                                    3.551
air_cycle_epochpost_air_on                                                     4.577
air_cycle_epochpre_air_on_mid                                                 11.404
air_cycle_epochpost_air_on_mid                                                12.307
air_cycle_epochpre_air_off                                                    14.770
air_cycle_epochpost_air_off                                                    9.727
air_cycle_epochpre_air_off_mid                                                 1.874
air_cycle_epochpost_air_off_mid                                                1.503
air_cycle_epochpre_air_on_next                                                -0.027
cycle_exposure_session_c                                                      -2.987
cycle_session_10m_c                                                           -0.453
air_cycle_epochpost_air_on:cycle_exposure_session_c                            1.800
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                         2.062
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                        0.248
air_cycle_epochpre_air_off:cycle_exposure_session_c                           -1.051
air_cycle_epochpost_air_off:cycle_exposure_session_c                          -1.487
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       -0.549
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      -0.535
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       -0.056
air_cycle_epochpost_air_on:cycle_session_10m_c                                 0.021
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                              8.423
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                             0.263
air_cycle_epochpre_air_off:cycle_session_10m_c                                 0.533
air_cycle_epochpost_air_off:cycle_session_10m_c                               -0.869
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                             0.512
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                            0.449
air_cycle_epochpre_air_on_next:cycle_session_10m_c                             0.028
cycle_exposure_session_c:cycle_session_10m_c                                   0.003
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c        0.084
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    -2.936
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    0.113
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       -0.279
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      -0.415
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   -0.261
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  -0.206
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c    0.080
                                                                             Pr(>|t|)
(Intercept)                                                                   0.00402
air_cycle_epochpost_air_on                                                   4.74e-06
air_cycle_epochpre_air_on_mid                                                 < 2e-16
air_cycle_epochpost_air_on_mid                                                < 2e-16
air_cycle_epochpre_air_off                                                    < 2e-16
air_cycle_epochpost_air_off                                                   < 2e-16
air_cycle_epochpre_air_off_mid                                                0.06089
air_cycle_epochpost_air_off_mid                                               0.13284
air_cycle_epochpre_air_on_next                                                0.97840
cycle_exposure_session_c                                                      0.00293
cycle_session_10m_c                                                           0.65031
air_cycle_epochpost_air_on:cycle_exposure_session_c                           0.07192
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        0.03921
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       0.80410
air_cycle_epochpre_air_off:cycle_exposure_session_c                           0.29311
air_cycle_epochpost_air_off:cycle_exposure_session_c                          0.13698
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       0.58323
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      0.59297
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       0.95541
air_cycle_epochpost_air_on:cycle_session_10m_c                                0.98352
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             < 2e-16
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            0.79235
air_cycle_epochpre_air_off:cycle_session_10m_c                                0.59434
air_cycle_epochpost_air_off:cycle_session_10m_c                               0.38479
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            0.60840
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           0.65320
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            0.97770
cycle_exposure_session_c:cycle_session_10m_c                                  0.99728
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       0.93325
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    0.00332
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   0.90966
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       0.77993
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      0.67843
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   0.79387
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  0.83702
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   0.93627

(Intercept)                                                                  **
air_cycle_epochpost_air_on                                                   ***
air_cycle_epochpre_air_on_mid                                                ***
air_cycle_epochpost_air_on_mid                                               ***
air_cycle_epochpre_air_off                                                   ***
air_cycle_epochpost_air_off                                                  ***
air_cycle_epochpre_air_off_mid                                               .
air_cycle_epochpost_air_off_mid
air_cycle_epochpre_air_on_next
cycle_exposure_session_c                                                     **
cycle_session_10m_c
air_cycle_epochpost_air_on:cycle_exposure_session_c                          .
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                       *
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c
air_cycle_epochpre_air_off:cycle_exposure_session_c
air_cycle_epochpost_air_off:cycle_exposure_session_c
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c
air_cycle_epochpre_air_on_next:cycle_exposure_session_c
air_cycle_epochpost_air_on:cycle_session_10m_c
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                            ***
air_cycle_epochpost_air_on_mid:cycle_session_10m_c
air_cycle_epochpre_air_off:cycle_session_10m_c
air_cycle_epochpost_air_off:cycle_session_10m_c
air_cycle_epochpre_air_off_mid:cycle_session_10m_c
air_cycle_epochpost_air_off_mid:cycle_session_10m_c
air_cycle_epochpre_air_on_next:cycle_session_10m_c
cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   **
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

R[write to console]:
Correlation matrix not shown by default, as p = 36 > 12.
Use print(summary(m), correlation=TRUE)  or
    vcov(summary(m))        if you need it


R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
distance_net_cm
==============================
Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: as.formula(formula_text)
   Data: air_cycle_df
Control: lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e+05))

      AIC       BIC    logLik -2*log(L)  df.resid
 258516.3  258850.7 -129218.2  258436.3     31544

Scaled residuals:
     Min       1Q   Median       3Q      Max
-168.990   -0.108   -0.026    0.109    1.480

Random effects:
 Groups     Name        Variance Std.Dev.
 cycle_id   (Intercept)   0.8122  0.9012
 animal_day (Intercept)   1.8341  1.3543
 animal     (Intercept)   0.7018  0.8377
 Residual               207.8850 14.4182
Number of obs: 31584, groups:  cycle_id, 3532; animal_day, 78; animal, 5

Fixed effects:
                                                                               Estimate
(Intercept)                                                                   1.216e+00
air_cycle_epochpost_air_on                                                    1.269e+00
air_cycle_epochpre_air_on_mid                                                 2.640e+00
air_cycle_epochpost_air_on_mid                                                4.179e+00
air_cycle_epochpre_air_off                                                    5.079e+00
air_cycle_epochpost_air_off                                                   2.783e+00
air_cycle_epochpre_air_off_mid                                                6.408e-01
air_cycle_epochpost_air_off_mid                                               5.200e-01
air_cycle_epochpre_air_on_next                                               -1.097e-02
cycle_exposure_session_c                                                     -1.799e-01
cycle_session_10m_c                                                          -6.631e-02
air_cycle_epochpost_air_on:cycle_exposure_session_c                           1.507e-01
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        1.842e-01
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       2.819e-02
air_cycle_epochpre_air_off:cycle_exposure_session_c                          -7.244e-02
air_cycle_epochpost_air_off:cycle_exposure_session_c                         -1.503e-01
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                      -4.051e-02
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                     -3.807e-02
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                      -4.112e-03
air_cycle_epochpost_air_on:cycle_session_10m_c                                1.449e-01
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                            -3.326e+00
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            1.619e-01
air_cycle_epochpre_air_off:cycle_session_10m_c                                2.762e-01
air_cycle_epochpost_air_off:cycle_session_10m_c                              -7.491e-02
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            2.805e-01
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           2.348e-01
air_cycle_epochpre_air_on_next:cycle_session_10m_c                           -1.143e-02
cycle_exposure_session_c:cycle_session_10m_c                                 -3.962e-03
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       5.729e-03
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    3.111e-01
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   7.327e-03
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c      -3.321e-02
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      7.688e-03
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  -2.908e-02
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c -2.372e-02
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   1.180e-02
                                                                             Std. Error
(Intercept)                                                                   4.751e-01
air_cycle_epochpost_air_on                                                    3.449e-01
air_cycle_epochpre_air_on_mid                                                 3.449e-01
air_cycle_epochpost_air_on_mid                                                3.449e-01
air_cycle_epochpre_air_off                                                    3.449e-01
air_cycle_epochpost_air_off                                                   3.452e-01
air_cycle_epochpre_air_off_mid                                                3.454e-01
air_cycle_epochpost_air_off_mid                                               3.454e-01
air_cycle_epochpre_air_on_next                                                3.489e-01
cycle_exposure_session_c                                                      6.027e-02
cycle_session_10m_c                                                           3.960e-01
air_cycle_epochpost_air_on:cycle_exposure_session_c                           7.052e-02
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        7.051e-02
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       7.052e-02
air_cycle_epochpre_air_off:cycle_exposure_session_c                           7.051e-02
air_cycle_epochpost_air_off:cycle_exposure_session_c                          7.055e-02
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       7.058e-02
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      7.058e-02
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       7.131e-02
air_cycle_epochpost_air_on:cycle_session_10m_c                                5.583e-01
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             5.582e-01
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            5.583e-01
air_cycle_epochpre_air_off:cycle_session_10m_c                                5.582e-01
air_cycle_epochpost_air_off:cycle_session_10m_c                               5.593e-01
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            5.603e-01
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           5.604e-01
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            5.766e-01
cycle_exposure_session_c:cycle_session_10m_c                                  8.196e-02
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       1.155e-01
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    1.155e-01
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   1.155e-01
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       1.155e-01
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      1.156e-01
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   1.158e-01
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  1.158e-01
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   1.192e-01
                                                                                     df
(Intercept)                                                                   8.283e+00
air_cycle_epochpost_air_on                                                    2.728e+04
air_cycle_epochpre_air_on_mid                                                 2.728e+04
air_cycle_epochpost_air_on_mid                                                2.728e+04
air_cycle_epochpre_air_off                                                    2.728e+04
air_cycle_epochpost_air_off                                                   2.729e+04
air_cycle_epochpre_air_off_mid                                                2.730e+04
air_cycle_epochpost_air_off_mid                                               2.730e+04
air_cycle_epochpre_air_on_next                                                2.744e+04
cycle_exposure_session_c                                                      4.964e+02
cycle_session_10m_c                                                           3.153e+04
air_cycle_epochpost_air_on:cycle_exposure_session_c                           2.728e+04
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                        2.728e+04
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                       2.728e+04
air_cycle_epochpre_air_off:cycle_exposure_session_c                           2.728e+04
air_cycle_epochpost_air_off:cycle_exposure_session_c                          2.728e+04
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       2.729e+04
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      2.729e+04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       2.743e+04
air_cycle_epochpost_air_on:cycle_session_10m_c                                2.728e+04
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             2.728e+04
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                            2.728e+04
air_cycle_epochpre_air_off:cycle_session_10m_c                                2.728e+04
air_cycle_epochpost_air_off:cycle_session_10m_c                               2.731e+04
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                            2.733e+04
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                           2.733e+04
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            2.772e+04
cycle_exposure_session_c:cycle_session_10m_c                                  3.154e+04
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c       2.728e+04
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    2.728e+04
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   2.728e+04
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       2.728e+04
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c      2.729e+04
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   2.731e+04
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  2.731e+04
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c   2.771e+04
                                                                             t value
(Intercept)                                                                    2.559
air_cycle_epochpost_air_on                                                     3.680
air_cycle_epochpre_air_on_mid                                                  7.654
air_cycle_epochpost_air_on_mid                                                12.116
air_cycle_epochpre_air_off                                                    14.727
air_cycle_epochpost_air_off                                                    8.063
air_cycle_epochpre_air_off_mid                                                 1.855
air_cycle_epochpost_air_off_mid                                                1.505
air_cycle_epochpre_air_on_next                                                -0.031
cycle_exposure_session_c                                                      -2.985
cycle_session_10m_c                                                           -0.167
air_cycle_epochpost_air_on:cycle_exposure_session_c                            2.137
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                         2.612
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                        0.400
air_cycle_epochpre_air_off:cycle_exposure_session_c                           -1.027
air_cycle_epochpost_air_off:cycle_exposure_session_c                          -2.130
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                       -0.574
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                      -0.539
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                       -0.058
air_cycle_epochpost_air_on:cycle_session_10m_c                                 0.260
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                             -5.959
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                             0.290
air_cycle_epochpre_air_off:cycle_session_10m_c                                 0.495
air_cycle_epochpost_air_off:cycle_session_10m_c                               -0.134
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                             0.501
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                            0.419
air_cycle_epochpre_air_on_next:cycle_session_10m_c                            -0.020
cycle_exposure_session_c:cycle_session_10m_c                                  -0.048
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c        0.050
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c     2.694
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c    0.063
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c       -0.288
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c       0.067
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c   -0.251
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  -0.205
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c    0.099
                                                                             Pr(>|t|)
(Intercept)                                                                  0.032756
air_cycle_epochpost_air_on                                                   0.000234
air_cycle_epochpre_air_on_mid                                                2.02e-14
air_cycle_epochpost_air_on_mid                                                < 2e-16
air_cycle_epochpre_air_off                                                    < 2e-16
air_cycle_epochpost_air_off                                                  7.78e-16
air_cycle_epochpre_air_off_mid                                               0.063576
air_cycle_epochpost_air_off_mid                                              0.132259
air_cycle_epochpre_air_on_next                                               0.974918
cycle_exposure_session_c                                                     0.002980
cycle_session_10m_c                                                          0.867003
air_cycle_epochpost_air_on:cycle_exposure_session_c                          0.032572
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                       0.009001
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c                      0.689347
air_cycle_epochpre_air_off:cycle_exposure_session_c                          0.304269
air_cycle_epochpost_air_off:cycle_exposure_session_c                         0.033157
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c                      0.566001
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c                     0.589669
air_cycle_epochpre_air_on_next:cycle_exposure_session_c                      0.954019
air_cycle_epochpost_air_on:cycle_session_10m_c                               0.795216
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                            2.57e-09
air_cycle_epochpost_air_on_mid:cycle_session_10m_c                           0.771891
air_cycle_epochpre_air_off:cycle_session_10m_c                               0.620757
air_cycle_epochpost_air_off:cycle_session_10m_c                              0.893461
air_cycle_epochpre_air_off_mid:cycle_session_10m_c                           0.616586
air_cycle_epochpost_air_off_mid:cycle_session_10m_c                          0.675259
air_cycle_epochpre_air_on_next:cycle_session_10m_c                           0.984188
cycle_exposure_session_c:cycle_session_10m_c                                 0.961452
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c      0.960442
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   0.007073
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c  0.949421
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c      0.773722
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c     0.946980
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c  0.801635
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c 0.837659
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c  0.921180

(Intercept)                                                                  *
air_cycle_epochpost_air_on                                                   ***
air_cycle_epochpre_air_on_mid                                                ***
air_cycle_epochpost_air_on_mid                                               ***
air_cycle_epochpre_air_off                                                   ***
air_cycle_epochpost_air_off                                                  ***
air_cycle_epochpre_air_off_mid                                               .
air_cycle_epochpost_air_off_mid
air_cycle_epochpre_air_on_next
cycle_exposure_session_c                                                     **
cycle_session_10m_c
air_cycle_epochpost_air_on:cycle_exposure_session_c                          *
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c                       **
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c
air_cycle_epochpre_air_off:cycle_exposure_session_c
air_cycle_epochpost_air_off:cycle_exposure_session_c                         *
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c
air_cycle_epochpre_air_on_next:cycle_exposure_session_c
air_cycle_epochpost_air_on:cycle_session_10m_c
air_cycle_epochpre_air_on_mid:cycle_session_10m_c                            ***
air_cycle_epochpost_air_on_mid:cycle_session_10m_c
air_cycle_epochpre_air_off:cycle_session_10m_c
air_cycle_epochpost_air_off:cycle_session_10m_c
air_cycle_epochpre_air_off_mid:cycle_session_10m_c
air_cycle_epochpost_air_off_mid:cycle_session_10m_c
air_cycle_epochpre_air_on_next:cycle_session_10m_c
cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_on:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c   **
air_cycle_epochpost_air_on_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_off:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_off:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpost_air_off_mid:cycle_exposure_session_c:cycle_session_10m_c
air_cycle_epochpre_air_on_next:cycle_exposure_session_c:cycle_session_10m_c
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

R[write to console]:
Correlation matrix not shown by default, as p = 36 > 12.
Use print(summary(m), correlation=TRUE)  or
    vcov(summary(m))        if you need it


R[write to console]: NOTE: Results may be misleading due to involvement in interactions

               outcome                               contrast    estimate
1          frac_moving                   air_onset_transition  0.49954039
2          frac_moving               early_air_on_progression  0.04793399
3          frac_moving                  air_on_mid_transition  0.04551561
4          frac_moving                late_air_on_progression  0.09430300
5          frac_moving                  air_offset_transition -0.04523749
6          frac_moving                 early_air_off_recovery -0.51430726
7          frac_moving                 air_off_mid_transition -0.02583070
8          frac_moving late_air_off_recovery_to_next_baseline -0.10653793
9         frac_forward                   air_onset_transition  0.40270597
10        frac_forward               early_air_on_progression  0.12001430
11        frac_forward                  air_on_mid_transition  0.06053917
12        frac_forward                late_air_on_progression  0.10820582
13        frac_forward                  air_offset_transition -0.11500483
14        frac_forward                 early_air_off_recovery -0.45126790
15        frac_forward                 air_off_mid_transition -0.02457746
16        frac_forward late_air_off_recovery_to_next_baseline -0.10367048
17 mean_speed_path_cms                   air_onset_transition  1.56183079
18 mean_speed_path_cms               early_air_on_progression  2.35496643
19 mean_speed_path_cms                  air_on_mid_transition  0.31318304
20 mean_speed_path_cms                late_air_on_progression  0.85789406
21 mean_speed_path_cms                  air_offset_transition -1.75906150
22 mean_speed_path_cms                 early_air_off_recovery -2.68347459
23 mean_speed_path_cms                 air_off_mid_transition -0.12780808
24 mean_speed_path_cms late_air_off_recovery_to_next_baseline -0.52678735
25  mean_speed_net_cms                   air_onset_transition  1.26960236
26  mean_speed_net_cms               early_air_on_progression  1.37061340
27  mean_speed_net_cms                  air_on_mid_transition  1.53887441
28  mean_speed_net_cms                late_air_on_progression  0.91066421
29  mean_speed_net_cms                  air_offset_transition -2.31132811
30  mean_speed_net_cms                 early_air_off_recovery -2.13705653
31  mean_speed_net_cms                 air_off_mid_transition -0.12128939
32  mean_speed_net_cms late_air_off_recovery_to_next_baseline -0.53107069
33    distance_path_cm                   air_onset_transition  1.57363405
34    distance_path_cm               early_air_on_progression  2.34704792
35    distance_path_cm                  air_on_mid_transition  0.31071091
36    distance_path_cm                late_air_on_progression  0.84655737
37    distance_path_cm                  air_offset_transition -1.73109279
38    distance_path_cm                 early_air_off_recovery -2.70151602
39    distance_path_cm                 air_off_mid_transition -0.12780667
40    distance_path_cm late_air_off_recovery_to_next_baseline -0.52694935
41     distance_net_cm                   air_onset_transition  1.26908801
42     distance_net_cm               early_air_on_progression  1.37048241
43     distance_net_cm                  air_on_mid_transition  1.53908457
44     distance_net_cm                late_air_on_progression  0.90028995
45     distance_net_cm                  air_offset_transition -2.29598354
46     distance_net_cm                 early_air_off_recovery -2.14218400
47     distance_net_cm                 air_off_mid_transition -0.12082304
48     distance_net_cm late_air_off_recovery_to_next_baseline -0.53092289
            SE  df     z.ratio      p.value
1  0.007126226 Inf  70.0988679 0.000000e+00
2  0.007126226 Inf   6.7264197 1.738886e-11
3  0.007126226 Inf   6.3870568 1.691089e-10
4  0.007126226 Inf  13.2332318 5.640872e-40
5  0.007132100 Inf  -6.3428015 2.256241e-10
6  0.007142534 Inf -72.0062737 0.000000e+00
7  0.007147367 Inf  -3.6140165 3.014898e-04
8  0.007220930 Inf -14.7540459 2.897602e-49
9  0.007397639 Inf  54.4370940 0.000000e+00
10 0.007397639 Inf  16.2233241 3.450063e-59
11 0.007397639 Inf   8.1835793 2.755349e-16
12 0.007397639 Inf  14.6270748 1.887286e-48
13 0.007403698 Inf -15.5334318 2.060512e-54
14 0.007414542 Inf -60.8625467 0.000000e+00
15 0.007419585 Inf  -3.3125116 9.246230e-04
16 0.007495553 Inf -13.8309317 1.658584e-43
17 0.343792525 Inf   4.5429458 5.547353e-06
18 0.343792525 Inf   6.8499640 7.386857e-12
19 0.343792525 Inf   0.9109652 3.623137e-01
20 0.343792525 Inf   2.4953831 1.258212e-02
21 0.344065273 Inf  -5.1125808 3.177870e-07
22 0.344572417 Inf  -7.7878392 6.816483e-15
23 0.344812416 Inf  -0.3706597 7.108910e-01
24 0.348251044 Inf  -1.5126655 1.303646e-01
25 0.344892900 Inf   3.6811496 2.321847e-04
26 0.344892900 Inf   3.9740262 7.066780e-05
27 0.344892900 Inf   4.4618907 8.123968e-06
28 0.344892900 Inf   2.6404261 8.280185e-03
29 0.345167347 Inf  -6.6962536 2.138305e-11
30 0.345675840 Inf  -6.1822560 6.319194e-10
31 0.345916064 Inf  -0.3506324 7.258641e-01
32 0.349375094 Inf  -1.5200588 1.284962e-01
33 0.343812474 Inf   4.5770127 4.716629e-06
34 0.343812474 Inf   6.8265351 8.699002e-12
35 0.343812474 Inf   0.9037220 3.661428e-01
36 0.343812474 Inf   2.4622649 1.380627e-02
37 0.344085236 Inf  -5.0309999 4.879284e-07
38 0.344592410 Inf  -7.8397433 4.514685e-15
39 0.344832424 Inf  -0.3706341 7.109100e-01
40 0.348271235 Inf  -1.5130430 1.302687e-01
41 0.344898781 Inf   3.6795955 2.336042e-04
42 0.344898781 Inf   3.9735786 7.080079e-05
43 0.344898781 Inf   4.4624239 8.103770e-06
44 0.344898781 Inf   2.6103019 9.046234e-03
45 0.345173232 Inf  -6.6516848 2.897568e-11
46 0.345681734 Inf  -6.1969835 5.755553e-10
47 0.345921963 Inf  -0.3492783 7.268804e-01
48 0.349381040 Inf  -1.5196099 1.286090e-01
              outcome R2_conditional R2_marginal optional
1         frac_moving     0.51142766  0.44505439    FALSE
2        frac_forward     0.47557249  0.40468974    FALSE
3 mean_speed_path_cms     0.03545923  0.02559215    FALSE
4  mean_speed_net_cms     0.03703745  0.02152139    FALSE
5    distance_path_cm     0.03543874  0.02558202    FALSE
6     distance_net_cm     0.03699865  0.02148866    FALSE

In [28]:
%%R -o air_cycle_emmeans_R -o air_cycle_contrasts_R -o air_cycle_r2_R -o air_cycle_fixed_R -o air_cycle_session_trends_R -o air_cycle_session_time_trends_R -o air_cycle_model_info_R

library(lme4)
library(lmerTest)
library(emmeans)
library(broom.mixed)
library(dplyr)
library(performance)

# --------------------------------------------------
# Use asymptotic df for emmeans because models are large
# --------------------------------------------------
emm_options(lmer.df = "asymptotic")

# --------------------------------------------------
# Prepare factors
# --------------------------------------------------

air_cycle_df$animal <- factor(air_cycle_df$animal)
air_cycle_df$animal_day <- factor(air_cycle_df$animal_day)
air_cycle_df$cycle_id <- factor(air_cycle_df$cycle_id)

air_cycle_df$air_cycle_epoch <- factor(
  as.character(air_cycle_df$air_cycle_epoch),
  levels = c(
    "pre_air_on",
    "post_air_on",
    "pre_air_on_mid",
    "post_air_on_mid",
    "pre_air_off",
    "post_air_off",
    "pre_air_off_mid",
    "post_air_off_mid",
    "pre_air_on_next"
  ),
  ordered = FALSE
)

# --------------------------------------------------
# Outcomes
# --------------------------------------------------

air_outcomes_R <- c(
  "frac_moving",
  "frac_forward",
  "mean_speed_path_cms",
  "mean_speed_net_cms",
  "distance_path_cm",
  "distance_net_cm"
)

air_outcomes_R <- air_outcomes_R[air_outcomes_R %in% names(air_cycle_df)]

print(air_outcomes_R)

# --------------------------------------------------
# Planned adjacent contrasts across the air cycle
# --------------------------------------------------

contrast_list <- list(
  air_onset_transition = c(-1, 1, 0, 0, 0, 0, 0, 0, 0),
  early_air_on_progression = c(0, -1, 1, 0, 0, 0, 0, 0, 0),
  air_on_mid_transition = c(0, 0, -1, 1, 0, 0, 0, 0, 0),
  late_air_on_progression = c(0, 0, 0, -1, 1, 0, 0, 0, 0),
  air_offset_transition = c(0, 0, 0, 0, -1, 1, 0, 0, 0),
  early_air_off_recovery = c(0, 0, 0, 0, 0, -1, 1, 0, 0),
  air_off_mid_transition = c(0, 0, 0, 0, 0, 0, -1, 1, 0),
  late_air_off_recovery_to_next_baseline = c(0, 0, 0, 0, 0, 0, 0, -1, 1)
)

# --------------------------------------------------
# Function: fit model and extract all clean outputs
# --------------------------------------------------

fit_air_cycle_outcome <- function(outcome_name) {

  cat("\n\n==============================\n")
  cat("Fitting outcome:", outcome_name, "\n")
  cat("==============================\n")

  formula_text <- paste0(
    outcome_name,
    " ~ air_cycle_epoch * cycle_exposure_session_c * cycle_session_10m_c + ",
    "(1 | animal) + (1 | animal_day) + (1 | cycle_id)"
  )

  m <- lmer(
    as.formula(formula_text),
    data = air_cycle_df,
    REML = FALSE,
    control = lmerControl(
      optimizer = "bobyqa",
      optCtrl = list(maxfun = 2e5)
    )
  )

  # --------------------------------------------------
  # Model info
  # --------------------------------------------------

  model_info <- data.frame(
    outcome = outcome_name,
    n_obs = nobs(m),
    n_animals = nlevels(air_cycle_df$animal),
    n_animal_day = nlevels(air_cycle_df$animal_day),
    n_cycle_id = nlevels(air_cycle_df$cycle_id),
    AIC = AIC(m),
    BIC = BIC(m),
    logLik = as.numeric(logLik(m)),
    singular = isSingular(m),
    stringsAsFactors = FALSE
  )

  # --------------------------------------------------
  # EMMs at mean exposure session and mean session time
  # --------------------------------------------------

  emm <- emmeans(
    m,
    ~ air_cycle_epoch,
    at = list(
      cycle_exposure_session_c = 0,
      cycle_session_10m_c = 0
    ),
    lmer.df = "asymptotic"
  )

  emm_df <- as.data.frame(emm)
  emm_df$outcome <- outcome_name

  # --------------------------------------------------
  # Planned adjacent contrasts at mean exposure/session time
  # --------------------------------------------------

  contrast_df <- as.data.frame(
    contrast(
      emm,
      contrast_list,
      adjust = "none"
    )
  )

  contrast_df$outcome <- outcome_name

  # --------------------------------------------------
  # R2
  # --------------------------------------------------

  r2_obj <- performance::r2_nakagawa(m)

  r2_df <- data.frame(
    outcome = outcome_name,
    R2_marginal = r2_obj$R2_marginal,
    R2_conditional = r2_obj$R2_conditional,
    stringsAsFactors = FALSE
  )

  # --------------------------------------------------
  # Fixed effects
  # --------------------------------------------------

  fixed_df <- broom.mixed::tidy(
    m,
    effects = "fixed",
    conf.int = TRUE
  )

  fixed_df$outcome <- outcome_name

  # --------------------------------------------------
  # Session/exposure-session trends by air-cycle epoch
  # Evaluated at mean within-session time
  # --------------------------------------------------

  session_trends <- emtrends(
    m,
    ~ air_cycle_epoch,
    var = "cycle_exposure_session_c",
    at = list(
      cycle_session_10m_c = 0
    ),
    lmer.df = "asymptotic"
  )

  session_trends_df <- as.data.frame(session_trends)
  session_trends_df$outcome <- outcome_name

  # --------------------------------------------------
  # Within-session-time trends by air-cycle epoch
  # Evaluated at mean exposure session
  # --------------------------------------------------

  session_time_trends <- emtrends(
    m,
    ~ air_cycle_epoch,
    var = "cycle_session_10m_c",
    at = list(
      cycle_exposure_session_c = 0
    ),
    lmer.df = "asymptotic"
  )

  session_time_trends_df <- as.data.frame(session_time_trends)
  session_time_trends_df$outcome <- outcome_name

  return(
    list(
      model = m,
      model_info = model_info,
      emmeans = emm_df,
      contrasts = contrast_df,
      r2 = r2_df,
      fixed = fixed_df,
      session_trends = session_trends_df,
      session_time_trends = session_time_trends_df
    )
  )
}

# --------------------------------------------------
# Run all models
# --------------------------------------------------

air_models_R <- list()
model_info_list <- list()
emmeans_list <- list()
contrasts_list <- list()
r2_list <- list()
fixed_list <- list()
session_trends_list <- list()
session_time_trends_list <- list()

for (outcome_name in air_outcomes_R) {

  result <- fit_air_cycle_outcome(outcome_name)

  air_models_R[[outcome_name]] <- result$model
  model_info_list[[outcome_name]] <- result$model_info
  emmeans_list[[outcome_name]] <- result$emmeans
  contrasts_list[[outcome_name]] <- result$contrasts
  r2_list[[outcome_name]] <- result$r2
  fixed_list[[outcome_name]] <- result$fixed
  session_trends_list[[outcome_name]] <- result$session_trends
  session_time_trends_list[[outcome_name]] <- result$session_time_trends
}

# --------------------------------------------------
# Combine output tables
# --------------------------------------------------

air_cycle_model_info_R <- bind_rows(model_info_list)
air_cycle_emmeans_R <- bind_rows(emmeans_list)
air_cycle_contrasts_R <- bind_rows(contrasts_list)
air_cycle_r2_R <- bind_rows(r2_list)
air_cycle_fixed_R <- bind_rows(fixed_list)
air_cycle_session_trends_R <- bind_rows(session_trends_list)
air_cycle_session_time_trends_R <- bind_rows(session_time_trends_list)

# --------------------------------------------------
# Reorder columns
# --------------------------------------------------

air_cycle_emmeans_R <- air_cycle_emmeans_R %>%
  relocate(outcome)

air_cycle_contrasts_R <- air_cycle_contrasts_R %>%
  relocate(outcome) %>%
  select(outcome, contrast, estimate, SE, df, z.ratio, p.value)

air_cycle_fixed_R <- air_cycle_fixed_R %>%
  relocate(outcome)

air_cycle_session_trends_R <- air_cycle_session_trends_R %>%
  relocate(outcome)

air_cycle_session_time_trends_R <- air_cycle_session_time_trends_R %>%
  relocate(outcome)

# --------------------------------------------------
# Print clean summaries
# --------------------------------------------------

cat("\n\n=== Model info ===\n")
print(air_cycle_model_info_R)

cat("\n\n=== Adjacent contrasts ===\n")
print(air_cycle_contrasts_R)

cat("\n\n=== R2 ===\n")
print(air_cycle_r2_R)

cat("\n\n=== Exposure-session trends by epoch ===\n")
print(air_cycle_session_trends_R)

cat("\n\n=== Within-session-time trends by epoch ===\n")
print(air_cycle_session_time_trends_R)

[1] "frac_moving"         "frac_forward"        "mean_speed_path_cms"
[4] "mean_speed_net_cms"  "distance_path_cm"    "distance_net_cm"


==============================
Fitting outcome: frac_moving
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: frac_forward
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: mean_speed_path_cms
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: mean_speed_net_cms
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: distance_path_cm
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: distance_net_cm
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

=== Model info ===
              outcome n_obs n_animals n_animal_day n_cycle_id       AIC
1         frac_moving 31584         5           78       3536  14672.39
2        frac_forward 31584         5           78       3536  16811.16
3 mean_speed_path_cms 31584         5           78       3536 258215.73
4  mean_speed_net_cms 31584         5           78       3536 258515.36
5    distance_path_cm 31584         5           78       3536 258219.24
6     distance_net_cm 31584         5           78       3536 258516.32
        BIC      logLik singular
1  15006.81   -7296.197    FALSE
2  17145.58   -8365.581    FALSE
3 258550.15 -129067.866    FALSE
4 258849.78 -129217.682    FALSE
5 258553.66 -129069.622    FALSE
6 258850.74 -129218.159    FALSE


=== Adjacent contrasts ===
               outcome                               contrast    estimate
1          frac_moving                   air_onset_transition  0.49954039
2          frac_moving               early_air_on_progression  0.04793399
3          frac_moving                  air_on_mid_transition  0.04551561
4          frac_moving                late_air_on_progression  0.09430300
5          frac_moving                  air_offset_transition -0.04523749
6          frac_moving                 early_air_off_recovery -0.51430726
7          frac_moving                 air_off_mid_transition -0.02583070
8          frac_moving late_air_off_recovery_to_next_baseline -0.10653793
9         frac_forward                   air_onset_transition  0.40270597
10        frac_forward               early_air_on_progression  0.12001430
11        frac_forward                  air_on_mid_transition  0.06053917
12        frac_forward                late_air_on_progression  0.10820582
13        frac_forward                  air_offset_transition -0.11500483
14        frac_forward                 early_air_off_recovery -0.45126790
15        frac_forward                 air_off_mid_transition -0.02457746
16        frac_forward late_air_off_recovery_to_next_baseline -0.10367048
17 mean_speed_path_cms                   air_onset_transition  1.56183079
18 mean_speed_path_cms               early_air_on_progression  2.35496643
19 mean_speed_path_cms                  air_on_mid_transition  0.31318304
20 mean_speed_path_cms                late_air_on_progression  0.85789406
21 mean_speed_path_cms                  air_offset_transition -1.75906150
22 mean_speed_path_cms                 early_air_off_recovery -2.68347459
23 mean_speed_path_cms                 air_off_mid_transition -0.12780808
24 mean_speed_path_cms late_air_off_recovery_to_next_baseline -0.52678735
25  mean_speed_net_cms                   air_onset_transition  1.26960236
26  mean_speed_net_cms               early_air_on_progression  1.37061340
27  mean_speed_net_cms                  air_on_mid_transition  1.53887441
28  mean_speed_net_cms                late_air_on_progression  0.91066421
29  mean_speed_net_cms                  air_offset_transition -2.31132811
30  mean_speed_net_cms                 early_air_off_recovery -2.13705653
31  mean_speed_net_cms                 air_off_mid_transition -0.12128939
32  mean_speed_net_cms late_air_off_recovery_to_next_baseline -0.53107069
33    distance_path_cm                   air_onset_transition  1.57363405
34    distance_path_cm               early_air_on_progression  2.34704792
35    distance_path_cm                  air_on_mid_transition  0.31071091
36    distance_path_cm                late_air_on_progression  0.84655737
37    distance_path_cm                  air_offset_transition -1.73109279
38    distance_path_cm                 early_air_off_recovery -2.70151602
39    distance_path_cm                 air_off_mid_transition -0.12780667
40    distance_path_cm late_air_off_recovery_to_next_baseline -0.52694935
41     distance_net_cm                   air_onset_transition  1.26908801
42     distance_net_cm               early_air_on_progression  1.37048241
43     distance_net_cm                  air_on_mid_transition  1.53908457
44     distance_net_cm                late_air_on_progression  0.90028995
45     distance_net_cm                  air_offset_transition -2.29598354
46     distance_net_cm                 early_air_off_recovery -2.14218400
47     distance_net_cm                 air_off_mid_transition -0.12082304
48     distance_net_cm late_air_off_recovery_to_next_baseline -0.53092289
            SE  df     z.ratio      p.value
1  0.007126226 Inf  70.0988679 0.000000e+00
2  0.007126226 Inf   6.7264197 1.738886e-11
3  0.007126226 Inf   6.3870568 1.691089e-10
4  0.007126226 Inf  13.2332318 5.640872e-40
5  0.007132100 Inf  -6.3428015 2.256241e-10
6  0.007142534 Inf -72.0062737 0.000000e+00
7  0.007147367 Inf  -3.6140165 3.014898e-04
8  0.007220930 Inf -14.7540459 2.897602e-49
9  0.007397639 Inf  54.4370940 0.000000e+00
10 0.007397639 Inf  16.2233241 3.450063e-59
11 0.007397639 Inf   8.1835793 2.755349e-16
12 0.007397639 Inf  14.6270748 1.887286e-48
13 0.007403698 Inf -15.5334318 2.060512e-54
14 0.007414542 Inf -60.8625467 0.000000e+00
15 0.007419585 Inf  -3.3125116 9.246230e-04
16 0.007495553 Inf -13.8309317 1.658584e-43
17 0.343792525 Inf   4.5429458 5.547353e-06
18 0.343792525 Inf   6.8499640 7.386857e-12
19 0.343792525 Inf   0.9109652 3.623137e-01
20 0.343792525 Inf   2.4953831 1.258212e-02
21 0.344065273 Inf  -5.1125808 3.177870e-07
22 0.344572417 Inf  -7.7878392 6.816483e-15
23 0.344812416 Inf  -0.3706597 7.108910e-01
24 0.348251044 Inf  -1.5126655 1.303646e-01
25 0.344892900 Inf   3.6811496 2.321847e-04
26 0.344892900 Inf   3.9740262 7.066780e-05
27 0.344892900 Inf   4.4618907 8.123968e-06
28 0.344892900 Inf   2.6404261 8.280185e-03
29 0.345167347 Inf  -6.6962536 2.138305e-11
30 0.345675840 Inf  -6.1822560 6.319194e-10
31 0.345916064 Inf  -0.3506324 7.258641e-01
32 0.349375094 Inf  -1.5200588 1.284962e-01
33 0.343812474 Inf   4.5770127 4.716629e-06
34 0.343812474 Inf   6.8265351 8.699002e-12
35 0.343812474 Inf   0.9037220 3.661428e-01
36 0.343812474 Inf   2.4622649 1.380627e-02
37 0.344085236 Inf  -5.0309999 4.879284e-07
38 0.344592410 Inf  -7.8397433 4.514685e-15
39 0.344832424 Inf  -0.3706341 7.109100e-01
40 0.348271235 Inf  -1.5130430 1.302687e-01
41 0.344898781 Inf   3.6795955 2.336042e-04
42 0.344898781 Inf   3.9735786 7.080079e-05
43 0.344898781 Inf   4.4624239 8.103770e-06
44 0.344898781 Inf   2.6103019 9.046234e-03
45 0.345173232 Inf  -6.6516848 2.897568e-11
46 0.345681734 Inf  -6.1969835 5.755553e-10
47 0.345921963 Inf  -0.3492783 7.268804e-01
48 0.349381040 Inf  -1.5196099 1.286090e-01


=== R2 ===
                            outcome R2_marginal R2_conditional
Marginal R2...1         frac_moving  0.44505439     0.51142766
Marginal R2...2        frac_forward  0.40468974     0.47557249
Marginal R2...3 mean_speed_path_cms  0.02559215     0.03545923
Marginal R2...4  mean_speed_net_cms  0.02152139     0.03703745
Marginal R2...5    distance_path_cm  0.02558202     0.03543874
Marginal R2...6     distance_net_cm  0.02148866     0.03699865


=== Exposure-session trends by epoch ===
               outcome  air_cycle_epoch cycle_exposure_session_c.trend
1          frac_moving       pre_air_on                  -0.0204897495
2          frac_moving      post_air_on                   0.0003590950
3          frac_moving   pre_air_on_mid                   0.0032563370
4          frac_moving  post_air_on_mid                   0.0003126051
5          frac_moving      pre_air_off                  -0.0010976590
6          frac_moving     post_air_off                  -0.0034736158
7          frac_moving  pre_air_off_mid                  -0.0227500386
8          frac_moving post_air_off_mid                  -0.0238439536
9          frac_moving  pre_air_on_next                  -0.0210726472
10        frac_forward       pre_air_on                  -0.0201255760
11        frac_forward      post_air_on                   0.0073192617
12        frac_forward   pre_air_on_mid                   0.0076094715
13        frac_forward  post_air_on_mid                   0.0026251845
14        frac_forward      pre_air_off                  -0.0006184695
15        frac_forward     post_air_off                  -0.0065481281
16        frac_forward  pre_air_off_mid                  -0.0228425134
17        frac_forward post_air_off_mid                  -0.0234641732
18        frac_forward  pre_air_on_next                  -0.0207758016
19 mean_speed_path_cms       pre_air_on                  -0.1749221757
20 mean_speed_path_cms      post_air_on                  -0.0480484973
21 mean_speed_path_cms   pre_air_on_mid                  -0.0296382429
22 mean_speed_path_cms  post_air_on_mid                  -0.1572427284
23 mean_speed_path_cms      pre_air_off                  -0.2486674994
24 mean_speed_path_cms     post_air_off                  -0.2802666838
25 mean_speed_path_cms  pre_air_off_mid                  -0.2135139047
26 mean_speed_path_cms post_air_off_mid                  -0.2124585554
27 mean_speed_path_cms  pre_air_on_next                  -0.1789239532
28  mean_speed_net_cms       pre_air_on                  -0.1798783018
29  mean_speed_net_cms      post_air_on                  -0.0292594377
30  mean_speed_net_cms   pre_air_on_mid                   0.0041628169
31  mean_speed_net_cms  post_air_on_mid                  -0.1515845520
32  mean_speed_net_cms      pre_air_off                  -0.2522173664
33  mean_speed_net_cms     post_air_off                  -0.3302377681
34  mean_speed_net_cms  pre_air_off_mid                  -0.2204614397
35  mean_speed_net_cms post_air_off_mid                  -0.2180000020
36  mean_speed_net_cms  pre_air_on_next                  -0.1840046019
37    distance_path_cm       pre_air_on                  -0.1749671999
38    distance_path_cm      post_air_on                  -0.0484577913
39    distance_path_cm   pre_air_on_mid                  -0.0300190689
40    distance_path_cm  post_air_on_mid                  -0.1575304397
41    distance_path_cm      pre_air_off                  -0.2488703439
42    distance_path_cm     post_air_off                  -0.2795522344
43    distance_path_cm  pre_air_off_mid                  -0.2135707083
44    distance_path_cm post_air_off_mid                  -0.2125769403
45    distance_path_cm  pre_air_on_next                  -0.1789420062
46     distance_net_cm       pre_air_on                  -0.1798939440
47     distance_net_cm      post_air_on                  -0.0291700027
48     distance_net_cm   pre_air_on_mid                   0.0043072363
49     distance_net_cm  post_air_on_mid                  -0.1517053107
50     distance_net_cm      pre_air_off                  -0.2523372693
51     distance_net_cm     post_air_off                  -0.3301804814
52     distance_net_cm  pre_air_off_mid                  -0.2204040677
53     distance_net_cm post_air_off_mid                  -0.2179594558
54     distance_net_cm  pre_air_on_next                  -0.1840060220
            SE  df    asymp.LCL     asymp.UCL
1  0.002174522 Inf -0.024751735 -0.0162277640
2  0.002174538 Inf -0.003902921  0.0046211109
3  0.002174522 Inf -0.001005648  0.0075183224
4  0.002174538 Inf -0.003949411  0.0045746210
5  0.002174522 Inf -0.005359644  0.0031643264
6  0.002175272 Inf -0.007737071  0.0007898391
7  0.002175731 Inf -0.027014392 -0.0184856848
8  0.002175731 Inf -0.028108308 -0.0195795995
9  0.002186831 Inf -0.025358756 -0.0167865382
10 0.002236247 Inf -0.024508539 -0.0157426130
11 0.002236263 Inf  0.002936267  0.0117022562
12 0.002236247 Inf  0.003226509  0.0119924344
13 0.002236263 Inf -0.001757810  0.0070081791
14 0.002236247 Inf -0.005001432  0.0037644934
15 0.002237031 Inf -0.010932629 -0.0021636273
16 0.002237509 Inf -0.027227950 -0.0184570770
17 0.002237509 Inf -0.027849610 -0.0190787364
18 0.002249090 Inf -0.025183936 -0.0163676671
19 0.058563607 Inf -0.289704736 -0.0601396157
20 0.058564926 Inf -0.162833643  0.0667366489
21 0.058563607 Inf -0.144420803  0.0851443172
22 0.058564926 Inf -0.272027875 -0.0424575822
23 0.058563607 Inf -0.363450060 -0.1338849394
24 0.058613605 Inf -0.395147239 -0.1653861285
25 0.058652135 Inf -0.328469977 -0.0985578321
26 0.058652153 Inf -0.327414663 -0.0975024480
27 0.059556104 Inf -0.295651772 -0.0621961346
28 0.060276916 Inf -0.298018886 -0.0617377179
29 0.060278202 Inf -0.147402542  0.0888836669
30 0.060276916 Inf -0.113977767  0.1223034008
31 0.060278202 Inf -0.269727657 -0.0334414475
32 0.060276916 Inf -0.370357950 -0.1340767825
33 0.060327395 Inf -0.448477290 -0.2119982464
34 0.060365108 Inf -0.338774877 -0.1021480023
35 0.060365124 Inf -0.336313472 -0.0996865324
36 0.061254493 Inf -0.304061201 -0.0639480023
37 0.058568185 Inf -0.289758733 -0.0601756670
38 0.058569504 Inf -0.163251910  0.0663363279
39 0.058568185 Inf -0.144810602  0.0847724640
40 0.058569504 Inf -0.272324559 -0.0427363205
41 0.058568185 Inf -0.363661877 -0.1340788110
42 0.058618180 Inf -0.394441756 -0.1646627132
43 0.058656711 Inf -0.328535750 -0.0986056664
44 0.058656729 Inf -0.327542017 -0.0976118636
45 0.059560703 Inf -0.295678839 -0.0622051730
46 0.060274300 Inf -0.298029402 -0.0617584858
47 0.060275587 Inf -0.147307982  0.0889679762
48 0.060274300 Inf -0.113828222  0.1224426945
49 0.060275587 Inf -0.269843290 -0.0335673318
50 0.060274300 Inf -0.370472727 -0.1342018111
51 0.060324782 Inf -0.448414881 -0.2119460814
52 0.060362498 Inf -0.338712389 -0.1020957465
53 0.060362514 Inf -0.336267809 -0.0996511024
54 0.061251944 Inf -0.304057626 -0.0639544182


=== Within-session-time trends by epoch ===
               outcome  air_cycle_epoch cycle_session_10m_c.trend          SE
1          frac_moving       pre_air_on              -0.037670387 0.008359041
2          frac_moving      post_air_on              -0.020579117 0.008362069
3          frac_moving   pre_air_on_mid              -0.001624154 0.008359041
4          frac_moving  post_air_on_mid              -0.022338676 0.008362069
5          frac_moving      pre_air_off              -0.004858292 0.008359041
6          frac_moving     post_air_off              -0.011085611 0.008392704
7          frac_moving  pre_air_off_mid               0.012770037 0.008421025
8          frac_moving post_air_off_mid               0.003834883 0.008424169
9          frac_moving  pre_air_on_next              -0.030586542 0.008893491
10        frac_forward       pre_air_on              -0.025524123 0.008635557
11        frac_forward      post_air_on               0.010487361 0.008638691
12        frac_forward   pre_air_on_mid               0.016132090 0.008635557
13        frac_forward  post_air_on_mid              -0.013878454 0.008638691
14        frac_forward      pre_air_off              -0.003145745 0.008635557
15        frac_forward     post_air_off              -0.026341613 0.008670437
16        frac_forward  pre_air_off_mid               0.020340149 0.008699798
17        frac_forward post_air_off_mid               0.009336213 0.008703059
18        frac_forward  pre_air_on_next              -0.020751992 0.009189912
19 mean_speed_path_cms       pre_air_on              -0.177275033 0.394116167
20 mean_speed_path_cms      post_air_on              -0.165097399 0.394259547
21 mean_speed_path_cms   pre_air_on_mid               4.509776487 0.394116167
22 mean_speed_path_cms  post_air_on_mid              -0.031003879 0.394259547
23 mean_speed_path_cms      pre_air_off               0.117143819 0.394116167
24 mean_speed_path_cms     post_air_off              -0.664455778 0.395706619
25 mean_speed_path_cms  pre_air_off_mid               0.108415261 0.397055342
26 mean_speed_path_cms post_air_off_mid               0.073029047 0.397205192
27 mean_speed_path_cms  pre_air_on_next              -0.161391220 0.419621806
28  mean_speed_net_cms       pre_air_on              -0.066491472 0.395968762
29  mean_speed_net_cms      post_air_on               0.078675504 0.396112798
30  mean_speed_net_cms   pre_air_on_mid              -3.393402451 0.395968762
31  mean_speed_net_cms  post_air_on_mid               0.096301780 0.396112798
32  mean_speed_net_cms      pre_air_off               0.209855961 0.395968762
33  mean_speed_net_cms     post_air_off              -0.140868371 0.397567879
34  mean_speed_net_cms  pre_air_off_mid               0.214201256 0.398922874
35  mean_speed_net_cms post_air_off_mid               0.168472112 0.399073399
36  mean_speed_net_cms  pre_air_on_next              -0.077883593 0.421590959
37    distance_path_cm       pre_air_on              -0.178674415 0.394138061
38    distance_path_cm      post_air_on              -0.167176508 0.394281450
39    distance_path_cm   pre_air_on_mid               4.508354600 0.394138061
40    distance_path_cm  post_air_on_mid              -0.032161683 0.394281450
41    distance_path_cm      pre_air_off               0.117664404 0.394138061
42    distance_path_cm     post_air_off              -0.663248395 0.395728600
43    distance_path_cm  pre_air_off_mid               0.107486157 0.397077398
44    distance_path_cm post_air_off_mid               0.072321377 0.397227257
45    distance_path_cm  pre_air_on_next              -0.162605727 0.419645125
46     distance_net_cm       pre_air_on              -0.066312979 0.395974796
47     distance_net_cm      post_air_on               0.078589643 0.396118834
48     distance_net_cm   pre_air_on_mid              -3.392592711 0.395974796
49     distance_net_cm  post_air_on_mid               0.095539084 0.396118834
50     distance_net_cm      pre_air_off               0.209870492 0.395974796
51     distance_net_cm     post_air_off              -0.141220220 0.397573935
52     distance_net_cm  pre_air_off_mid               0.214215656 0.398928951
53     distance_net_cm post_air_off_mid               0.168455970 0.399079479
54     distance_net_cm  pre_air_on_next              -0.077740073 0.421597388
    df     asymp.LCL    asymp.UCL
1  Inf -0.0540538066 -0.021286967
2  Inf -0.0369684702 -0.004189764
3  Inf -0.0180075737  0.014759265
4  Inf -0.0387280292 -0.005949323
5  Inf -0.0212417115  0.011525128
6  Inf -0.0275350075  0.005363786
7  Inf -0.0037348678  0.029274942
8  Inf -0.0126761858  0.020345951
9  Inf -0.0480174647 -0.013155620
10 Inf -0.0424495041 -0.008598743
11 Inf -0.0064441623  0.027418884
12 Inf -0.0007932902  0.033057471
13 Inf -0.0308099771  0.003053070
14 Inf -0.0200711255  0.013779636
15 Inf -0.0433353566 -0.009347870
16 Inf  0.0032888589  0.037391439
17 Inf -0.0077214691  0.026393896
18 Inf -0.0387638890 -0.002740094
19 Inf -0.9497285260  0.595178460
20 Inf -0.9378319116  0.607637113
21 Inf  3.7373229937  5.282229980
22 Inf -0.8037383910  0.741730634
23 Inf -0.6553096745  0.889597312
24 Inf -1.4400265001  0.111114944
25 Inf -0.6697989089  0.886629430
26 Inf -0.7054788239  0.851536918
27 Inf -0.9838348468  0.661052407
28 Inf -0.8425759837  0.709593040
29 Inf -0.6976913130  0.855042322
30 Inf -4.1694869629 -2.617317940
31 Inf -0.6800650377  0.872668597
32 Inf -0.5662285509  0.985940472
33 Inf -0.9200870943  0.638350353
34 Inf -0.5676732093  0.996075722
35 Inf -0.6136973774  0.950641601
36 Inf -0.9041866880  0.748419502
37 Inf -0.9511708204  0.593821990
38 Inf -0.9399539492  0.605600933
39 Inf  3.7358581947  5.280851005
40 Inf -0.8049391239  0.740615758
41 Inf -0.6548320010  0.890160810
42 Inf -1.4388621996  0.112365409
43 Inf -0.6707712417  0.885743556
44 Inf -0.7062297402  0.850872494
45 Inf -0.9850950584  0.659883605
46 Inf -0.8424093173  0.709783360
47 Inf -0.6977890060  0.854968292
48 Inf -4.1686890497 -2.616496372
49 Inf -0.6808395647  0.871917733
50 Inf -0.5662258466  0.985966831
51 Inf -0.9204508148  0.638010374
52 Inf -0.5676707206  0.996102033
53 Inf -0.6137254347  0.950637375
54 Inf -0.9040557690  0.748575623