In [2]:
import sys
from pathlib import Path

repo_root = Path.cwd().parent
sys.path.append(str(repo_root))

import src.utils.config as config
import src.utils.data_io as dio

print(config.PROJECT_ROOT)
print(config.RAW_BASE)
print(config.PROC_BASE)

CODE_BASE = Path(config.CODE_BASE).expanduser()
sys.path.append(str(CODE_BASE))

print("Added to path:", CODE_BASE)

# make the data dictionary which contains list of all animals and sessions and
# file names of videos h264 and mat files

data_root = config.RAW_BASE # this variable now contains the path to the raw data directory, which is defined in the config file. It is used to build the classical conditioning data dictionary using the dio.build_classical_conditioning_dict function. The resulting cc_data variable will contain the structured information about the animals, sessions, and file names for the classical conditioning experiments.
cc_data = dio.build_classical_conditioning_dict(data_root)

pdata_root = config.PROC_BASE # this variable now contains the path to the processed data directory, which is defined in the config file. It is used to build the processed data dictionary using the pdio.build_processed_data_dict function. The resulting pdata variable will contain the structured information about the animals, sessions, and file names for the processed data of the classical conditioning experiments.
print(data_root)
print(pdata_root)

/home/nmldata2/ccaw/Python
/home/nmldata2/ccaw/Python
/mnt/data/Classical_Conditioning
/mnt/pdata/Classical_Conditioning
Added to path: /home/nmldata2/ccaw/Python
/mnt/data/Classical_Conditioning
/mnt/pdata/Classical_Conditioning

In [12]:
import src.utils.pdata_io as pdio

pdio.save_project_context(
    cc_data=cc_data,
    data_root=data_root,
    pdata_root=pdata_root,
)

[SAVED] Project context: /mnt/pdata/Classical_Conditioning/_cache/project_context.pkl

PosixPath('/mnt/pdata/Classical_Conditioning/_cache/project_context.pkl')

In [13]:
from vis.data_struct import view_cc_data

cc_sessions, cc_phase_summary, cc_animal_phase_summary = view_cc_data(
    cc_data,
    print_summary=True,
    show_dates=False
)

============================================================
CC DATA SUMMARY
============================================================
Number of animals: 5
Number of total sessions: 272
Number of phases: 4

Phases present:
  - air_training: 81 sessions across 5 animals
  - habituation: 86 sessions across 5 animals
  - tone_air_training: 50 sessions across 5 animals
  - unknown: 55 sessions across 5 animals

Animal x phase summary:

,animal,phase,n_sessions,first_date,last_date,n_recording_paths,n_existing_recordings,total_video_files,calendar_span_days,n_missing_calendar_days,missing_calendar_dates
0,NML_04,air_training,15,2026_01_12,2026_01_27,15,15,45,16,1,2026_01_19
1,NML_04,habituation,16,2025_12_27,2026_01_11,16,16,48,16,0,
2,NML_04,tone_air_training,10,2026_01_28,2026_02_06,10,10,30,10,0,
3,NML_04,unknown,11,2026_02_07,2026_02_17,11,11,33,11,0,
4,NML_05,air_training,15,2026_01_12,2026_01_27,15,15,45,16,1,2026_01_19
5,NML_05,habituation,16,2025_12_27,2026_01_11,16,16,48,16,0,
6,NML_05,tone_air_training,10,2026_01_28,2026_02_06,10,10,30,10,0,
7,NML_05,unknown,11,2026_02_07,2026_02_17,11,11,33,11,0,
8,NML_06,air_training,15,2026_01_12,2026_01_27,15,15,45,16,1,2026_01_19
9,NML_06,habituation,16,2025_12_27,2026_01_11,16,16,48,16,0,
10,NML_06,tone_air_training,10,2026_01_28,2026_02_06,10,10,30,10,0,
11,NML_06,unknown,11,2026_02_07,2026_02_17,11,11,33,11,0,
12,NML_07,air_training,18,2026_02_21,2026_03_11,17,17,54,19,1,2026_02_24
13,NML_07,habituation,19,2026_02_02,2026_02_20,19,19,57,19,0,
14,NML_07,tone_air_training,10,2026_03_12,2026_03_21,10,10,30,10,0,
15,NML_07,unknown,11,2026_03_23,2026_04_02,11,11,33,11,0,
16,NML_08,air_training,18,2026_02_21,2026_03_11,17,17,54,19,1,2026_02_24
17,NML_08,habituation,19,2026_02_02,2026_02_20,19,19,57,19,0,
18,NML_08,tone_air_training,10,2026_03_12,2026_03_21,10,10,30,10,0,
19,NML_08,unknown,11,2026_03_23,2026_04_02,11,11,33,11,0,

In [10]:
cc_animal_phase_summary

,animal,phase,n_sessions,first_date,last_date,n_recording_paths,n_existing_recordings,total_video_files,calendar_span_days,n_missing_calendar_days,missing_calendar_dates
0,NML_04,air_training,15,2026_01_12,2026_01_27,15,15,45,16,1,2026_01_19
1,NML_04,habituation,16,2025_12_27,2026_01_11,16,16,48,16,0,
2,NML_04,tone_air_training,10,2026_01_28,2026_02_06,10,10,30,10,0,
3,NML_04,unknown,11,2026_02_07,2026_02_17,11,11,33,11,0,
4,NML_05,air_training,15,2026_01_12,2026_01_27,15,15,45,16,1,2026_01_19
5,NML_05,habituation,16,2025_12_27,2026_01_11,16,16,48,16,0,
6,NML_05,tone_air_training,10,2026_01_28,2026_02_06,10,10,30,10,0,
7,NML_05,unknown,11,2026_02_07,2026_02_17,11,11,33,11,0,
8,NML_06,air_training,15,2026_01_12,2026_01_27,15,15,45,16,1,2026_01_19
9,NML_06,habituation,16,2025_12_27,2026_01_11,16,16,48,16,0,
10,NML_06,tone_air_training,10,2026_01_28,2026_02_06,10,10,30,10,0,
11,NML_06,unknown,11,2026_02_07,2026_02_17,11,11,33,11,0,
12,NML_07,air_training,18,2026_02_21,2026_03_11,17,17,54,19,1,2026_02_24
13,NML_07,habituation,19,2026_02_02,2026_02_20,19,19,57,19,0,
14,NML_07,tone_air_training,10,2026_03_12,2026_03_21,10,10,30,10,0,
15,NML_07,unknown,11,2026_03_23,2026_04_02,11,11,33,11,0,
16,NML_08,air_training,18,2026_02_21,2026_03_11,17,17,54,19,1,2026_02_24
17,NML_08,habituation,19,2026_02_02,2026_02_20,19,19,57,19,0,
18,NML_08,tone_air_training,10,2026_03_12,2026_03_21,10,10,30,10,0,
19,NML_08,unknown,11,2026_03_23,2026_04_02,11,11,33,11,0,