In [6]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

# Find the project root that contains the src folder
current = Path.cwd().resolve()

for p in [current] + list(current.parents):
    if (p / "src").exists():
        repo_root = p
        break
else:
    raise FileNotFoundError("Could not find a folder containing 'src'.")

if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

print("Current working directory:", current)
print("Added repo root:", repo_root)
print("src exists:", (repo_root / "src").exists())

from pathlib import Path
import numpy as np
import pandas as pd

import src.utils.pdata_io as pdio
from src.proc.extract_epoch_windows import load_epoch_windows

data_root, pdata_root, cc_data = pdio.load_project_context()

windows_df = load_epoch_windows(
    pdata_root=pdata_root,
    filename="behavior_epoch_windows.h5",
    key="windows/prepost_1s"
)

valid_windows = windows_df[windows_df["valid_window"]].copy()

print("All windows:", windows_df.shape)
print("Valid windows:", valid_windows.shape)

valid_windows.groupby(["phase", "epoch_name"]).size().reset_index(name="n_windows")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Current working directory: /home/nmldata2/ccaw/Python/notebooks
Added repo root: /home/nmldata2/ccaw/Python
src exists: True
[LOADED] Project context: /mnt/pdata/Classical_Conditioning/_cache/project_context.pkl
[LOADED] Epoch windows: /mnt/pdata/Classical_Conditioning/_cache/behavior_epoch_windows.h5
[KEY] windows/prepost_1s
All windows: (103980, 29)
Valid windows: (83023, 29)

                phase               epoch_name  n_windows
0        air_training      air_off_mid_post_1s       3379
1        air_training       air_off_mid_pre_1s       3379
2        air_training          air_off_post_1s       2838
3        air_training           air_off_pre_1s       2454
4        air_training       air_on_mid_post_1s       1762
5        air_training        air_on_mid_pre_1s       1134
6        air_training           air_on_post_1s       2465
7        air_training            air_on_pre_1s       3225
8        air_training  pseudo_tone_off_post_1s       1150
9        air_training   pseudo_tone_off_pre_1s       1762
10       air_training   pseudo_tone_on_post_1s       3379
11       air_training    pseudo_tone_on_pre_1s       3380
12        habituation      LED_off_mid_post_1s       2915
13        habituation       LED_off_mid_pre_1s       2915
14        habituation          LED_off_post_1s       2915
15        habituation           LED_off_pre_1s       2915
16        habituation       LED_on_mid_post_1s       2915
17        habituation        LED_on_mid_pre_1s       2915
18        habituation           LED_on_post_1s       2915
19        habituation            LED_on_pre_1s       2915
20        habituation  pseudo_tone_off_post_1s       2915
21        habituation   pseudo_tone_off_pre_1s       2915
22        habituation   pseudo_tone_on_post_1s       2915
23        habituation    pseudo_tone_on_pre_1s       2915
24  tone_air_training      air_off_mid_post_1s       1685
25  tone_air_training       air_off_mid_pre_1s       1685
26  tone_air_training          air_off_post_1s       1637
27  tone_air_training           air_off_pre_1s       1552
28  tone_air_training       air_on_mid_post_1s       1362
29  tone_air_training        air_on_mid_pre_1s        923
30  tone_air_training           air_on_post_1s       1552
31  tone_air_training            air_on_pre_1s       1685
32  tone_air_training         tone_off_post_1s        923
33  tone_air_training          tone_off_pre_1s       1362
34  tone_air_training          tone_on_post_1s       1685
35  tone_air_training           tone_on_pre_1s       1685

In [5]:
valid_windows

,animal,date,phase,event_number,anchor_name,anchor_type,anchor_time_s,window_position,window_s,epoch_name,...,session_duration_s,session_time_bin,parent_event_valid,valid_window_basic,valid_window,overlap_flag,overlap_s,overlap_with,anchor_warning,invalid_reason
12,NML_04,2026_01_12,air_training,1,pseudo_tone_on,pseudo,16.956400,post,1.0,pseudo_tone_on_post_1s,...,1308.9,early,True,True,True,False,0.0,,,
13,NML_04,2026_01_12,air_training,1,pseudo_tone_on,pseudo,16.956400,pre,1.0,pseudo_tone_on_pre_1s,...,1308.9,early,True,True,True,False,0.0,,,
14,NML_04,2026_01_12,air_training,1,air_on,main,19.956400,post,1.0,air_on_post_1s,...,1308.9,early,True,True,True,False,0.0,,,
15,NML_04,2026_01_12,air_training,1,air_on,main,19.956400,pre,1.0,air_on_pre_1s,...,1308.9,early,True,True,True,False,0.0,,,
20,NML_04,2026_01_12,air_training,1,air_off,main,23.979000,post,1.0,air_off_post_1s,...,1308.9,early,True,True,True,False,0.0,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103963,NML_08,2026_03_21,tone_air_training,47,air_on_mid,middle,1194.077209,pre,1.0,air_on_mid_pre_1s,...,1232.7,late,True,True,True,False,0.0,,,
103964,NML_08,2026_03_21,tone_air_training,47,air_off,main,1198.325439,post,1.0,air_off_post_1s,...,1232.7,late,True,True,True,False,0.0,,,
103965,NML_08,2026_03_21,tone_air_training,47,air_off,main,1198.325439,pre,1.0,air_off_pre_1s,...,1232.7,late,True,True,True,False,0.0,,,
103966,NML_08,2026_03_21,tone_air_training,47,air_off_mid,middle,1207.316895,post,1.0,air_off_mid_post_1s,...,1232.7,late,True,True,True,False,0.0,,,
103967,NML_08,2026_03_21,tone_air_training,47,air_off_mid,middle,1207.316895,pre,1.0,air_off_mid_pre_1s,...,1232.7,late,True,True,True,False,0.0,,,

In [4]:

from src.proc.behavior_metrics import compute_encoder_metrics_for_windows


encoder_epoch_df = compute_encoder_metrics_for_windows(
    valid_windows,
    speed_thresh=0.5
)

encoder_epoch_df.head()

,animal,date,phase,event_number,anchor_name,anchor_type,anchor_time_s,window_position,window_s,epoch_name,...,max_speed_net_cms,distance_path_cm,distance_net_cm,net_direction_bias,frac_stationary,frac_moving,frac_forward,frac_backward,frac_low_net_movement,dominant_locomotor_state
0,NML_04,2026_01_12,air_training,1,air_off_mid,middle,31.5222,post,1.0,air_off_mid_post_1s,...,5.780530,2.111150,1.407434,0.680638,0.0808,0.9192,0.6118,0.3074,0.0,forward
1,NML_04,2026_01_12,air_training,1,air_off_mid,middle,31.5222,pre,1.0,air_off_mid_pre_1s,...,5.277876,1.482832,1.130973,0.755565,0.3230,0.6770,0.4804,0.1966,0.0,forward
2,NML_04,2026_01_12,air_training,1,air_off,main,23.9790,post,1.0,air_off_post_1s,...,14.074335,8.721061,8.721061,1.000000,0.0000,1.0000,1.0000,0.0000,0.0,forward
3,NML_04,2026_01_12,air_training,1,air_off,main,23.9790,pre,1.0,air_off_pre_1s,...,13.571680,5.101946,4.850619,0.951624,0.0340,0.9660,0.8530,0.1130,0.0,forward
4,NML_04,2026_01_12,air_training,1,air_on,main,19.9564,post,1.0,air_on_post_1s,...,0.753982,0.402124,-0.201062,-0.487133,0.5560,0.4440,0.0924,0.3516,0.0,stationary

In [ ]:
# encoder_epoch_df = pd.read_hdf(
#     Path(pdata_root) / "_cache" / "behavior_epoch_metrics.h5",
#     key="encoder/prepost_1s_speedThresh_1cms"
# )

from src.proc.behavior_metrics import add_normalized_phase_day

encoder_epoch_df = add_normalized_phase_day(encoder_epoch_df)
encoder_epoch_df.head()

,animal,date,phase,event_number,anchor_name,anchor_type,anchor_time_s,window_position,window_s,epoch_name,...,net_direction_bias,frac_stationary,frac_moving,frac_forward,frac_backward,frac_low_net_movement,dominant_locomotor_state,phase_session_number,n_sessions_in_phase,normalized_phase_day
0,NML_04,2026_01_12,air_training,1,air_off_mid,middle,31.5222,post,1.0,air_off_mid_post_1s,...,0.680638,0.0808,0.9192,0.6118,0.3074,0.0,forward,1.0,15.0,0.0
1,NML_04,2026_01_12,air_training,1,air_off_mid,middle,31.5222,pre,1.0,air_off_mid_pre_1s,...,0.755565,0.3230,0.6770,0.4804,0.1966,0.0,forward,1.0,15.0,0.0
2,NML_04,2026_01_12,air_training,1,air_off,main,23.9790,post,1.0,air_off_post_1s,...,1.000000,0.0000,1.0000,1.0000,0.0000,0.0,forward,1.0,15.0,0.0
3,NML_04,2026_01_12,air_training,1,air_off,main,23.9790,pre,1.0,air_off_pre_1s,...,0.951624,0.0340,0.9660,0.8530,0.1130,0.0,forward,1.0,15.0,0.0
4,NML_04,2026_01_12,air_training,1,air_on,main,19.9564,post,1.0,air_on_post_1s,...,-0.487133,0.5560,0.4440,0.0924,0.3516,0.0,stationary,1.0,15.0,0.0

In [8]:
cache_dir = Path(pdata_root) / "_cache"
cache_dir.mkdir(parents=True, exist_ok=True)

encoder_metrics_file = cache_dir / "behavior_epoch_metrics.h5"

encoder_epoch_df.to_hdf(
    encoder_metrics_file,
    key="encoder/prepost_1s_speedThresh_1cms",
    mode="w",
    format="table"
)

print("Saved:", encoder_metrics_file)

Saved: /mnt/pdata/Classical_Conditioning/_cache/behavior_epoch_metrics.h5

In [6]:
encoder_epoch_df.groupby(
    ["phase", "epoch_name"]
).size().reset_index(name="n_windows")

                phase               epoch_name  n_windows
0        air_training      air_off_mid_post_1s       3379
1        air_training       air_off_mid_pre_1s       3379
2        air_training          air_off_post_1s       2838
3        air_training           air_off_pre_1s       2454
4        air_training       air_on_mid_post_1s       1762
5        air_training        air_on_mid_pre_1s       1134
6        air_training           air_on_post_1s       2465
7        air_training            air_on_pre_1s       3225
8        air_training  pseudo_tone_off_post_1s       1150
9        air_training   pseudo_tone_off_pre_1s       1762
10       air_training   pseudo_tone_on_post_1s       3379
11       air_training    pseudo_tone_on_pre_1s       3380
12        habituation      LED_off_mid_post_1s       2915
13        habituation       LED_off_mid_pre_1s       2915
14        habituation          LED_off_post_1s       2915
15        habituation           LED_off_pre_1s       2915
16        habituation       LED_on_mid_post_1s       2915
17        habituation        LED_on_mid_pre_1s       2915
18        habituation           LED_on_post_1s       2915
19        habituation            LED_on_pre_1s       2915
20        habituation  pseudo_tone_off_post_1s       2915
21        habituation   pseudo_tone_off_pre_1s       2915
22        habituation   pseudo_tone_on_post_1s       2915
23        habituation    pseudo_tone_on_pre_1s       2915
24  tone_air_training      air_off_mid_post_1s       1685
25  tone_air_training       air_off_mid_pre_1s       1685
26  tone_air_training          air_off_post_1s       1637
27  tone_air_training           air_off_pre_1s       1552
28  tone_air_training       air_on_mid_post_1s       1362
29  tone_air_training        air_on_mid_pre_1s        923
30  tone_air_training           air_on_post_1s       1552
31  tone_air_training            air_on_pre_1s       1685
32  tone_air_training         tone_off_post_1s        923
33  tone_air_training          tone_off_pre_1s       1362
34  tone_air_training          tone_on_post_1s       1685
35  tone_air_training           tone_on_pre_1s       1685

In [7]:
speed_summary = (
    encoder_epoch_df
    .groupby(["phase", "epoch_name"])
    .agg(
        mean_path_speed=("mean_speed_path_cms", "mean"),
        sem_path_speed=("mean_speed_path_cms", lambda x: x.std() / np.sqrt(len(x))),
        mean_net_speed=("mean_speed_net_cms", "mean"),
        n=("mean_speed_path_cms", "count"),
    )
    .reset_index()
)

speed_summary

,phase,epoch_name,mean_path_speed,sem_path_speed,mean_net_speed,n
0,air_training,air_off_mid_post_1s,2.021128,0.053808,1.963205,3379
1,air_training,air_off_mid_pre_1s,2.158887,0.054162,2.095409,3379
2,air_training,air_off_post_1s,4.334152,0.212683,3.580176,2838
3,air_training,air_off_pre_1s,6.035266,0.048383,5.964671,2454
4,air_training,air_on_mid_post_1s,4.521962,0.068697,4.401002,1762
5,air_training,air_on_mid_pre_1s,3.528038,0.082097,3.401191,1134
6,air_training,air_on_post_1s,2.632072,0.038650,2.326716,2465
7,air_training,air_on_pre_1s,1.428689,0.050584,1.370447,3225
8,air_training,pseudo_tone_off_post_1s,3.810288,0.086504,3.709521,1150
9,air_training,pseudo_tone_off_pre_1s,4.001601,0.071583,3.884586,1762
10,air_training,pseudo_tone_on_post_1s,1.562666,0.049495,1.503614,3379
11,air_training,pseudo_tone_on_pre_1s,1.623350,0.049543,1.568160,3380
12,habituation,LED_off_mid_post_1s,1.567504,0.062993,1.369307,2915
13,habituation,LED_off_mid_pre_1s,1.591007,0.063399,1.395196,2915
14,habituation,LED_off_post_1s,1.683670,0.062997,1.477723,2915
15,habituation,LED_off_pre_1s,1.735510,0.065667,1.546038,2915
16,habituation,LED_on_mid_post_1s,1.601131,0.065255,1.389472,2915
17,habituation,LED_on_mid_pre_1s,1.597020,0.064950,1.388308,2915
18,habituation,LED_on_post_1s,1.117324,0.039325,0.823163,2915
19,habituation,LED_on_pre_1s,1.613994,0.063275,1.399598,2915
20,habituation,pseudo_tone_off_post_1s,1.464098,0.058071,1.229679,2915
21,habituation,pseudo_tone_off_pre_1s,1.322322,0.050119,1.053557,2915
22,habituation,pseudo_tone_on_post_1s,1.637324,0.064042,1.449809,2915
23,habituation,pseudo_tone_on_pre_1s,1.623052,0.064076,1.410228,2915
24,tone_air_training,air_off_mid_post_1s,0.669349,0.033818,0.583315,1685
25,tone_air_training,air_off_mid_pre_1s,0.875805,0.038217,0.801021,1685
26,tone_air_training,air_off_post_1s,3.355689,0.032246,2.884546,1637
27,tone_air_training,air_off_pre_1s,5.437257,0.054076,5.344483,1552
28,tone_air_training,air_on_mid_post_1s,5.600367,0.088184,5.519678,1362
29,tone_air_training,air_on_mid_pre_1s,4.594919,0.100631,4.490330,923
30,tone_air_training,air_on_post_1s,2.692555,0.041763,2.512749,1552
31,tone_air_training,air_on_pre_1s,0.545313,0.032635,0.480589,1685
32,tone_air_training,tone_off_post_1s,5.209446,0.086508,5.168670,923
33,tone_air_training,tone_off_pre_1s,5.325374,0.074655,5.286937,1362
34,tone_air_training,tone_on_post_1s,0.719709,0.028725,0.559666,1685
35,tone_air_training,tone_on_pre_1s,0.473453,0.028418,0.387149,1685

In [8]:
state_summary = (
    encoder_epoch_df
    .groupby(["phase", "epoch_name"])
    .agg(
        frac_stationary=("frac_stationary", "mean"),
        frac_moving=("frac_moving", "mean"),
        frac_forward=("frac_forward", "mean"),
        frac_backward=("frac_backward", "mean"),
        frac_low_net=("frac_low_net_movement", "mean"),
        n=("frac_stationary", "count"),
    )
    .reset_index()
)

state_summary

,phase,epoch_name,frac_stationary,frac_moving,frac_forward,frac_backward,frac_low_net,n
0,air_training,air_off_mid_post_1s,0.607812,0.392188,0.371419,0.020769,0.0,3379
1,air_training,air_off_mid_pre_1s,0.578787,0.421213,0.399322,0.021891,0.0,3379
2,air_training,air_off_post_1s,0.072125,0.927875,0.830184,0.097692,0.0,2838
3,air_training,air_off_pre_1s,0.018368,0.981632,0.963370,0.018262,0.0,2454
4,air_training,air_on_mid_post_1s,0.184558,0.815442,0.782435,0.033007,0.0,1762
5,air_training,air_on_mid_pre_1s,0.286352,0.713648,0.680032,0.033616,0.0,1134
6,air_training,air_on_post_1s,0.231413,0.768587,0.657500,0.111088,0.0,2465
7,air_training,air_on_pre_1s,0.717806,0.282194,0.263233,0.018961,0.0,3225
8,air_training,pseudo_tone_off_post_1s,0.256447,0.743553,0.710656,0.032897,0.0,1150
9,air_training,pseudo_tone_off_pre_1s,0.189851,0.810149,0.767818,0.042330,0.0,1762
10,air_training,pseudo_tone_on_post_1s,0.686130,0.313870,0.294028,0.019842,0.0,3379
11,air_training,pseudo_tone_on_pre_1s,0.672353,0.327647,0.308347,0.019300,0.0,3380
12,habituation,LED_off_mid_post_1s,0.710785,0.289215,0.230830,0.058385,0.0,2915
13,habituation,LED_off_mid_pre_1s,0.706793,0.293207,0.233746,0.059461,0.0,2915
14,habituation,LED_off_post_1s,0.680382,0.319618,0.256137,0.063481,0.0,2915
15,habituation,LED_off_pre_1s,0.688589,0.311411,0.256306,0.055105,0.0,2915
16,habituation,LED_on_mid_post_1s,0.707024,0.292976,0.232031,0.060945,0.0,2915
17,habituation,LED_on_mid_pre_1s,0.711676,0.288324,0.228184,0.060140,0.0,2915
18,habituation,LED_on_post_1s,0.704919,0.295081,0.219094,0.075988,0.0,2915
19,habituation,LED_on_pre_1s,0.703182,0.296818,0.236503,0.060314,0.0,2915
20,habituation,pseudo_tone_off_post_1s,0.709689,0.290311,0.225752,0.064558,0.0,2915
21,habituation,pseudo_tone_off_pre_1s,0.703380,0.296620,0.223988,0.072632,0.0,2915
22,habituation,pseudo_tone_on_post_1s,0.697008,0.302992,0.245650,0.057343,0.0,2915
23,habituation,pseudo_tone_on_pre_1s,0.701149,0.298851,0.235810,0.063041,0.0,2915
24,tone_air_training,air_off_mid_post_1s,0.771889,0.228111,0.199646,0.028465,0.0,1685
25,tone_air_training,air_off_mid_pre_1s,0.712244,0.287756,0.260770,0.026986,0.0,1685
26,tone_air_training,air_off_post_1s,0.083584,0.916416,0.796654,0.119762,0.0,1637
27,tone_air_training,air_off_pre_1s,0.024962,0.975038,0.952112,0.022925,0.0,1552
28,tone_air_training,air_on_mid_post_1s,0.138794,0.861206,0.837767,0.023439,0.0,1362
29,tone_air_training,air_on_mid_pre_1s,0.196595,0.803405,0.771422,0.031983,0.0,923
30,tone_air_training,air_on_post_1s,0.230464,0.769536,0.697645,0.071891,0.0,1552
31,tone_air_training,air_on_pre_1s,0.830539,0.169461,0.148268,0.021194,0.0,1685
32,tone_air_training,tone_off_post_1s,0.088931,0.911069,0.895808,0.015262,0.0,923
33,tone_air_training,tone_off_pre_1s,0.083892,0.916108,0.900270,0.015838,0.0,1362
34,tone_air_training,tone_on_post_1s,0.683806,0.316194,0.253272,0.062922,0.0,1685
35,tone_air_training,tone_on_pre_1s,0.837197,0.162803,0.136522,0.026281,0.0,1685