In [1]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

# Find the project root that contains the src folder
current = Path.cwd().resolve()

for p in [current] + list(current.parents):
    if (p / "src").exists():
        repo_root = p
        break
else:
    raise FileNotFoundError("Could not find a folder containing 'src'.")

if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

print("Current working directory:", current)
print("Added repo root:", repo_root)
print("src exists:", (repo_root / "src").exists())

from pathlib import Path
import numpy as np
import pandas as pd

import src.utils.pdata_io as pdio
from src.proc.extract_epoch_windows import load_epoch_windows

data_root, pdata_root, cc_data = pdio.load_project_context()

windows_df = load_epoch_windows(
    pdata_root=pdata_root,
    filename="behavior_epoch_windows.h5",
    key="windows/prepost_1s"
)

valid_windows = windows_df[windows_df["valid_window"]].copy()

print("All windows:", windows_df.shape)
print("Valid windows:", valid_windows.shape)

valid_windows.groupby(["phase", "epoch_name"]).size().reset_index(name="n_windows")

encoder_epoch_df = pd.read_hdf(
    Path(pdata_root) / "_cache" / "behavior_epoch_metrics.h5",
    key="encoder/prepost_1s_speedThresh_1cms"
)

from src.qc.qc_events import load_behavior_qc_tables

events_df, session_summary_df = load_behavior_qc_tables(
    pdata_root=pdata_root,
    filename="behavior_QC.h5"
)

from src.utils.pdata_organize import make_session_availability_summary

session_availability_df = make_session_availability_summary(
    events_df=events_df,
    windows_df=windows_df,
    min_session_duration_s=900,
    min_valid_events=3,
)

from src.utils.pdata_organize import add_day_bins_to_sessions

session_day_df = add_day_bins_to_sessions(
    session_availability_df,
    use_good_sessions_only=True,
)

Current working directory: /home/nmldata2/ccaw/Python/notebooks
Added repo root: /home/nmldata2/ccaw/Python
src exists: True
/home/nmldata2/ccaw/Python
[LOADED] Project context: /mnt/pdata/Classical_Conditioning/_cache/project_context.pkl
[LOADED] Epoch windows: /mnt/pdata/Classical_Conditioning/_cache/behavior_epoch_windows.h5
[KEY] windows/prepost_1s
All windows: (103980, 40)
Valid windows: (101861, 40)
[LOADED] Behavior QC tables: /mnt/pdata/Classical_Conditioning/_cache/behavior_QC.h5

In [2]:
# --------------------------------------------------
# Inspect phase and anchor names
# --------------------------------------------------

print("Phases:")
print(encoder_epoch_df["phase"].value_counts())

anchor_col = "anchor_name" if "anchor_name" in encoder_epoch_df.columns else "epoch_name"
print("\nUsing anchor column:", anchor_col)

print("\nAnchors by phase:")
display(
    encoder_epoch_df
    .groupby(["phase", anchor_col])
    .size()
    .reset_index(name="n")
    .sort_values(["phase", anchor_col])
)

print("\nWindow positions:")
print(encoder_epoch_df["window_position"].value_counts())

Phases:
phase
air_training         42362
habituation          38237
tone_air_training    21262
Name: count, dtype: int64

Using anchor column: anchor_name

Anchors by phase:

                phase      anchor_name     n
0        air_training          air_off  7060
1        air_training      air_off_mid  7033
2        air_training           air_on  7067
3        air_training       air_on_mid  7069
4        air_training  pseudo_tone_off  7070
5        air_training   pseudo_tone_on  7063
6         habituation          LED_off  6373
7         habituation      LED_off_mid  6327
8         habituation           LED_on  6390
9         habituation       LED_on_mid  6386
10        habituation  pseudo_tone_off  6381
11        habituation   pseudo_tone_on  6380
12  tone_air_training          air_off  3543
13  tone_air_training      air_off_mid  3520
14  tone_air_training           air_on  3550
15  tone_air_training       air_on_mid  3550
16  tone_air_training         tone_off  3549
17  tone_air_training          tone_on  3550

Window positions:
window_position
pre     50952
post    50909
Name: count, dtype: int64

In [3]:
# --------------------------------------------------
# Choose tone-air phase
# --------------------------------------------------

tone_phase_candidates = [
    p for p in encoder_epoch_df["phase"].dropna().unique()
    if "tone" in str(p).lower()
]

print("Tone phase candidates:", tone_phase_candidates)

tone_air_phase = tone_phase_candidates[0]
print("Using tone-air phase:", tone_air_phase)

Tone phase candidates: ['tone_air_training']
Using tone-air phase: tone_air_training

In [4]:
# --------------------------------------------------
# Prepare tone-air window dataframe
# --------------------------------------------------

tone_air_anchors = [
    "tone_on",
    "air_on",
    "tone_off",
    "air_on_mid",
    "air_off",
    "air_off_mid",
]

tone_air_epoch_map = {
    ("tone_on", "pre"): "pre_tone_on",
    ("tone_on", "post"): "post_tone_on",

    ("air_on", "pre"): "pre_air_on",
    ("air_on", "post"): "post_air_on",

    ("tone_off", "pre"): "pre_tone_off",
    ("tone_off", "post"): "post_tone_off",

    ("air_on_mid", "pre"): "pre_air_on_mid",
    ("air_on_mid", "post"): "post_air_on_mid",

    ("air_off", "pre"): "pre_air_off",
    ("air_off", "post"): "post_air_off",

    ("air_off_mid", "pre"): "pre_air_off_mid",
    ("air_off_mid", "post"): "post_air_off_mid",
}

tone_air_cycle_order = [
    "pre_tone_on",
    "post_tone_on",
    "pre_air_on",
    "post_air_on",
    "pre_tone_off",
    "post_tone_off",
    "pre_air_on_mid",
    "post_air_on_mid",
    "pre_air_off",
    "post_air_off",
    "pre_air_off_mid",
    "post_air_off_mid",
    "pre_tone_on_next",
]


def prepare_tone_air_window_df(
    encoder_epoch_df,
    phase,
    anchors,
    anchor_col="anchor_name",
    keep_overlap=True,
    require_good_session=True,
    require_valid_window=True,
):
    """
    Prepare long-format tone-air training window dataframe.

    One row = one pre/post window around a tone-air anchor.
    """

    df = encoder_epoch_df.copy()

    df = df[
        (df["phase"] == phase) &
        (df[anchor_col].isin(anchors)) &
        (df["window_position"].isin(["pre", "post"]))
    ].copy()

    if require_good_session and "good_session_basic" in df.columns:
        df = df[df["good_session_basic"] == True].copy()

    if require_valid_window and "valid_window" in df.columns:
        df = df[df["valid_window"] == True].copy()

    if not keep_overlap and "overlap_flag" in df.columns:
        df = df[df["overlap_flag"] == False].copy()

    # biological epoch labels
    df["tone_air_epoch_label"] = [
        tone_air_epoch_map.get((a, w), np.nan)
        for a, w in zip(df[anchor_col], df["window_position"])
    ]

    df = df[df["tone_air_epoch_label"].notna()].copy()

    # IDs
    df["animal_day"] = (
        df["animal"].astype(str) + ":" +
        df["date"].astype(str)
    )

    # Session time
    if "session_time_min" not in df.columns:
        if "anchor_session_time_min" in df.columns:
            df["session_time_min"] = df["anchor_session_time_min"]
        elif "anchor_time_s" in df.columns:
            df["session_time_min"] = df["anchor_time_s"] / 60.0
        elif "session_time_s" in df.columns:
            df["session_time_min"] = df["session_time_s"] / 60.0
        else:
            df["session_time_min"] = np.nan

    # Exposure session number
    if "phase_session_number" in df.columns:
        df["tone_air_session"] = df["phase_session_number"]
    elif "phase_day_number_good" in df.columns:
        df["tone_air_session"] = df["phase_day_number_good"]
    else:
        # Try merging from session_day_df
        merge_cols = [
            c for c in [
                "animal",
                "date",
                "phase",
                "phase_day_number_good",
                "phase_session_number",
            ]
            if c in session_day_df.columns
        ]

        sess_tmp = session_day_df[merge_cols].drop_duplicates().copy()

        df = df.merge(
            sess_tmp,
            on=[c for c in ["animal", "date", "phase"] if c in merge_cols],
            how="left",
            suffixes=("", "_sess")
        )

        if "phase_session_number" in df.columns:
            df["tone_air_session"] = df["phase_session_number"]
        elif "phase_day_number_good" in df.columns:
            df["tone_air_session"] = df["phase_day_number_good"]
        else:
            df["tone_air_session"] = np.nan

    return df.reset_index(drop=True)


tone_air_window_df = prepare_tone_air_window_df(
    encoder_epoch_df=encoder_epoch_df,
    phase=tone_air_phase,
    anchors=tone_air_anchors,
    anchor_col=anchor_col,
    keep_overlap=True,
    require_good_session=True,
    require_valid_window=True,
)

print(tone_air_window_df.shape)

display(
    tone_air_window_df["tone_air_epoch_label"]
    .value_counts()
    .reindex([x for x in tone_air_cycle_order if x != "pre_tone_on_next"])
)

(21154, 63)

tone_air_epoch_label
pre_tone_on         1766
post_tone_on        1766
pre_air_on          1766
post_air_on         1766
pre_tone_off        1766
post_tone_off       1765
pre_air_on_mid      1766
post_air_on_mid     1766
pre_air_off         1766
post_air_off        1759
pre_air_off_mid     1751
post_air_off_mid    1751
Name: count, dtype: int64

In [5]:
# --------------------------------------------------
# Build full tone-air cycle dataframe
# --------------------------------------------------

def make_tone_air_cycle_df(
    tone_air_window_df,
    trial_col="event_number",
    require_complete_cycles=True,
):
    """
    Build long-format full tone-air cycle dataframe.

    One cycle = trial N.

    Includes:
        all tone/air epochs from trial N
        plus pre_tone_on from trial N+1 as pre_tone_on_next
    """

    df = tone_air_window_df.copy()

    if trial_col not in df.columns:
        raise ValueError(f"{trial_col} not found in dataframe.")

    current_epochs = [
        "pre_tone_on",
        "post_tone_on",
        "pre_air_on",
        "post_air_on",
        "pre_tone_off",
        "post_tone_off",
        "pre_air_on_mid",
        "post_air_on_mid",
        "pre_air_off",
        "post_air_off",
        "pre_air_off_mid",
        "post_air_off_mid",
    ]

    # Current-trial epochs
    cur = df[df["tone_air_epoch_label"].isin(current_epochs)].copy()
    cur["cycle_trial"] = cur[trial_col].astype(int)
    cur["tone_air_cycle_epoch"] = cur["tone_air_epoch_label"]

    # Next pre-tone baseline:
    # pre_tone_on from trial N+1 becomes pre_tone_on_next for cycle N
    nxt = df[df["tone_air_epoch_label"] == "pre_tone_on"].copy()
    nxt["cycle_trial"] = nxt[trial_col].astype(int) - 1
    nxt["tone_air_cycle_epoch"] = "pre_tone_on_next"
    nxt = nxt[nxt["cycle_trial"] >= 1].copy()

    cycle_df = pd.concat([cur, nxt], ignore_index=True)

    # IDs
    cycle_df["animal_day"] = (
        cycle_df["animal"].astype(str) + ":" +
        cycle_df["date"].astype(str)
    )

    cycle_df["cycle_id"] = (
        cycle_df["animal"].astype(str) + ":" +
        cycle_df["date"].astype(str) + ":" +
        cycle_df["cycle_trial"].astype(str)
    )

    # Cycle-level time/session reference = pre_tone_on of that cycle
    cycle_info = (
        cycle_df[cycle_df["tone_air_cycle_epoch"] == "pre_tone_on"]
        [["animal", "date", "cycle_trial", "session_time_min", "tone_air_session"]]
        .drop_duplicates()
        .rename(columns={
            "session_time_min": "cycle_session_time_min",
            "tone_air_session": "cycle_tone_air_session",
        })
    )

    cycle_df = cycle_df.merge(
        cycle_info,
        on=["animal", "date", "cycle_trial"],
        how="left"
    )

    # Optional: keep only complete cycles
    if require_complete_cycles:
        counts = (
            cycle_df
            .groupby("cycle_id")["tone_air_cycle_epoch"]
            .nunique()
        )

        complete_cycle_ids = counts[counts == len(tone_air_cycle_order)].index

        cycle_df = cycle_df[
            cycle_df["cycle_id"].isin(complete_cycle_ids)
        ].copy()

    # Ordered categorical
    cycle_df["tone_air_cycle_epoch"] = pd.Categorical(
        cycle_df["tone_air_cycle_epoch"],
        categories=tone_air_cycle_order,
        ordered=True,
    )

    # Center predictors
    cycle_df["tone_air_session_c"] = (
        cycle_df["cycle_tone_air_session"] -
        cycle_df["cycle_tone_air_session"].mean()
    )

    cycle_df["cycle_session_10m_c"] = (
        cycle_df["cycle_session_time_min"] -
        cycle_df["cycle_session_time_min"].mean()
    ) / 10.0

    return cycle_df.reset_index(drop=True)


tone_air_cycle_df = make_tone_air_cycle_df(
    tone_air_window_df,
    trial_col="event_number",
    require_complete_cycles=True,
)

print(tone_air_cycle_df.shape)

display(
    tone_air_cycle_df["tone_air_cycle_epoch"]
    .value_counts()
    .sort_index()
)

(21762, 70)

tone_air_cycle_epoch
pre_tone_on         1674
post_tone_on        1674
pre_air_on          1674
post_air_on         1674
pre_tone_off        1674
post_tone_off       1674
pre_air_on_mid      1674
post_air_on_mid     1674
pre_air_off         1674
post_air_off        1674
pre_air_off_mid     1674
post_air_off_mid    1674
pre_tone_on_next    1674
Name: count, dtype: int64

In [6]:
# --------------------------------------------------
# Sanity checks
# --------------------------------------------------

print("Animals:", tone_air_cycle_df["animal"].nunique())
print("Animal-days:", tone_air_cycle_df["animal_day"].nunique())
print("Cycles:", tone_air_cycle_df["cycle_id"].nunique())
print("Observations:", len(tone_air_cycle_df))

display(
    tone_air_cycle_df[
        [
            "animal",
            "date",
            "cycle_trial",
            "tone_air_cycle_epoch",
            anchor_col,
            "window_position",
            "event_number",
            "cycle_tone_air_session",
            "cycle_session_time_min",
        ]
    ].head(40)
)

display(
    tone_air_cycle_df
    .groupby(["animal", "date"])["cycle_id"]
    .nunique()
    .reset_index(name="n_cycles")
    .head()
)

Animals: 5
Animal-days: 49
Cycles: 1674
Observations: 21762

,animal,date,cycle_trial,tone_air_cycle_epoch,anchor_name,window_position,event_number,cycle_tone_air_session,cycle_session_time_min
0,NML_04,2026_01_28,1,post_air_off_mid,air_off_mid,post,1,1.0,1.398697
1,NML_04,2026_01_28,1,pre_air_off_mid,air_off_mid,pre,1,1.0,1.398697
2,NML_04,2026_01_28,1,post_air_off,air_off,post,1,1.0,1.398697
3,NML_04,2026_01_28,1,pre_air_off,air_off,pre,1,1.0,1.398697
4,NML_04,2026_01_28,1,post_air_on_mid,air_on_mid,post,1,1.0,1.398697
5,NML_04,2026_01_28,1,pre_air_on_mid,air_on_mid,pre,1,1.0,1.398697
6,NML_04,2026_01_28,1,post_air_on,air_on,post,1,1.0,1.398697
7,NML_04,2026_01_28,1,pre_air_on,air_on,pre,1,1.0,1.398697
8,NML_04,2026_01_28,1,post_tone_off,tone_off,post,1,1.0,1.398697
9,NML_04,2026_01_28,1,pre_tone_off,tone_off,pre,1,1.0,1.398697
10,NML_04,2026_01_28,1,post_tone_on,tone_on,post,1,1.0,1.398697
11,NML_04,2026_01_28,1,pre_tone_on,tone_on,pre,1,1.0,1.398697
12,NML_04,2026_01_28,2,post_air_off_mid,air_off_mid,post,2,1.0,1.929357
13,NML_04,2026_01_28,2,pre_air_off_mid,air_off_mid,pre,2,1.0,1.929357
14,NML_04,2026_01_28,2,post_air_off,air_off,post,2,1.0,1.929357
15,NML_04,2026_01_28,2,pre_air_off,air_off,pre,2,1.0,1.929357
16,NML_04,2026_01_28,2,post_air_on_mid,air_on_mid,post,2,1.0,1.929357
17,NML_04,2026_01_28,2,pre_air_on_mid,air_on_mid,pre,2,1.0,1.929357
18,NML_04,2026_01_28,2,post_air_on,air_on,post,2,1.0,1.929357
19,NML_04,2026_01_28,2,pre_air_on,air_on,pre,2,1.0,1.929357
20,NML_04,2026_01_28,2,post_tone_off,tone_off,post,2,1.0,1.929357
21,NML_04,2026_01_28,2,pre_tone_off,tone_off,pre,2,1.0,1.929357
22,NML_04,2026_01_28,2,post_tone_on,tone_on,post,2,1.0,1.929357
23,NML_04,2026_01_28,2,pre_tone_on,tone_on,pre,2,1.0,1.929357
24,NML_04,2026_01_28,3,post_air_off_mid,air_off_mid,post,3,1.0,2.285977
25,NML_04,2026_01_28,3,pre_air_off_mid,air_off_mid,pre,3,1.0,2.285977
26,NML_04,2026_01_28,3,post_air_off,air_off,post,3,1.0,2.285977
27,NML_04,2026_01_28,3,pre_air_off,air_off,pre,3,1.0,2.285977
28,NML_04,2026_01_28,3,post_air_on_mid,air_on_mid,post,3,1.0,2.285977
29,NML_04,2026_01_28,3,pre_air_on_mid,air_on_mid,pre,3,1.0,2.285977
30,NML_04,2026_01_28,3,post_air_on,air_on,post,3,1.0,2.285977
31,NML_04,2026_01_28,3,pre_air_on,air_on,pre,3,1.0,2.285977
32,NML_04,2026_01_28,3,post_tone_off,tone_off,post,3,1.0,2.285977
33,NML_04,2026_01_28,3,pre_tone_off,tone_off,pre,3,1.0,2.285977
34,NML_04,2026_01_28,3,post_tone_on,tone_on,post,3,1.0,2.285977
35,NML_04,2026_01_28,3,pre_tone_on,tone_on,pre,3,1.0,2.285977
36,NML_04,2026_01_28,4,post_air_off_mid,air_off_mid,post,4,1.0,2.649487
37,NML_04,2026_01_28,4,pre_air_off_mid,air_off_mid,pre,4,1.0,2.649487
38,NML_04,2026_01_28,4,post_air_off,air_off,post,4,1.0,2.649487
39,NML_04,2026_01_28,4,pre_air_off,air_off,pre,4,1.0,2.649487

   animal        date  n_cycles
0  NML_04  2026_01_28        38
1  NML_04  2026_01_29        36
2  NML_04  2026_01_30        38
3  NML_04  2026_01_31        31
4  NML_04  2026_02_01        30

In [7]:
%load_ext rpy2.ipython

In [8]:
%%R -i tone_air_cycle_df -o tone_air_emmeans_R -o tone_air_contrasts_R -o tone_air_r2_R -o tone_air_fixed_R -o tone_air_session_trends_R -o tone_air_session_time_trends_R -o tone_air_model_info_R

library(lme4)
library(lmerTest)
library(emmeans)
library(broom.mixed)
library(dplyr)
library(performance)

# Use asymptotic df for emmeans because models are large
emm_options(lmer.df = "asymptotic")

# --------------------------------------------------
# Prepare factors
# --------------------------------------------------

tone_air_cycle_df$animal <- factor(tone_air_cycle_df$animal)
tone_air_cycle_df$animal_day <- factor(tone_air_cycle_df$animal_day)
tone_air_cycle_df$cycle_id <- factor(tone_air_cycle_df$cycle_id)

tone_air_cycle_df$tone_air_cycle_epoch <- factor(
  as.character(tone_air_cycle_df$tone_air_cycle_epoch),
  levels = c(
    "pre_tone_on",
    "post_tone_on",
    "pre_air_on",
    "post_air_on",
    "pre_tone_off",
    "post_tone_off",
    "pre_air_on_mid",
    "post_air_on_mid",
    "pre_air_off",
    "post_air_off",
    "pre_air_off_mid",
    "post_air_off_mid",
    "pre_tone_on_next"
  ),
  ordered = FALSE
)

# --------------------------------------------------
# Outcomes
# --------------------------------------------------

tone_air_outcomes_R <- c(
  "frac_moving",
  "frac_forward",
  "mean_speed_path_cms",
  "mean_speed_net_cms",
  "distance_path_cm",
  "distance_net_cm"
)

tone_air_outcomes_R <- tone_air_outcomes_R[
  tone_air_outcomes_R %in% names(tone_air_cycle_df)
]

print(tone_air_outcomes_R)

# --------------------------------------------------
# Planned adjacent contrasts
# 13 epochs, so each contrast vector has length 13
# --------------------------------------------------

tone_air_contrast_list <- list(
  tone_onset_transition =
    c(-1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),

  tone_to_air_anticipatory_interval =
    c(0, -1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),

  air_onset_transition =
    c(0, 0, -1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0),

  early_air_on_to_tone_offset =
    c(0, 0, 0, -1, 1, 0, 0, 0, 0, 0, 0, 0, 0),

  tone_offset_transition =
    c(0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0, 0, 0),

  post_tone_offset_air_on_progression =
    c(0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0, 0),

  air_on_mid_transition =
    c(0, 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0),

  late_air_on_progression =
    c(0, 0, 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0),

  air_offset_transition =
    c(0, 0, 0, 0, 0, 0, 0, 0, -1, 1, 0, 0, 0),

  early_air_off_recovery =
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1, 0, 0),

  air_off_mid_transition =
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1, 0),

  late_air_off_recovery_to_next_baseline =
    c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1)
)

# --------------------------------------------------
# Fit one outcome and extract tables
# --------------------------------------------------

fit_tone_air_cycle_outcome <- function(outcome_name) {

  cat("\n\n==============================\n")
  cat("Fitting outcome:", outcome_name, "\n")
  cat("==============================\n")

  formula_text <- paste0(
    outcome_name,
    " ~ tone_air_cycle_epoch * tone_air_session_c * cycle_session_10m_c + ",
    "(1 | animal) + (1 | animal_day) + (1 | cycle_id)"
  )

  m <- lmer(
    as.formula(formula_text),
    data = tone_air_cycle_df,
    REML = FALSE,
    control = lmerControl(
      optimizer = "bobyqa",
      optCtrl = list(maxfun = 2e5)
    )
  )

  model_info <- data.frame(
    outcome = outcome_name,
    n_obs = nobs(m),
    n_animals = nlevels(tone_air_cycle_df$animal),
    n_animal_day = nlevels(tone_air_cycle_df$animal_day),
    n_cycle_id = nlevels(tone_air_cycle_df$cycle_id),
    AIC = AIC(m),
    BIC = BIC(m),
    logLik = as.numeric(logLik(m)),
    singular = isSingular(m),
    stringsAsFactors = FALSE
  )

  emm <- emmeans(
    m,
    ~ tone_air_cycle_epoch,
    at = list(
      tone_air_session_c = 0,
      cycle_session_10m_c = 0
    ),
    lmer.df = "asymptotic"
  )

  emm_df <- as.data.frame(emm)
  emm_df$outcome <- outcome_name

  contrast_df <- as.data.frame(
    contrast(
      emm,
      tone_air_contrast_list,
      adjust = "none"
    )
  )
  contrast_df$outcome <- outcome_name

  r2_obj <- performance::r2_nakagawa(m)

  r2_df <- data.frame(
    outcome = outcome_name,
    R2_marginal = r2_obj$R2_marginal,
    R2_conditional = r2_obj$R2_conditional,
    stringsAsFactors = FALSE
  )

  fixed_df <- broom.mixed::tidy(
    m,
    effects = "fixed",
    conf.int = TRUE
  )
  fixed_df$outcome <- outcome_name

  session_trends <- emtrends(
    m,
    ~ tone_air_cycle_epoch,
    var = "tone_air_session_c",
    at = list(
      cycle_session_10m_c = 0
    ),
    lmer.df = "asymptotic"
  )

  session_trends_df <- as.data.frame(session_trends)
  session_trends_df$outcome <- outcome_name

  session_time_trends <- emtrends(
    m,
    ~ tone_air_cycle_epoch,
    var = "cycle_session_10m_c",
    at = list(
      tone_air_session_c = 0
    ),
    lmer.df = "asymptotic"
  )

  session_time_trends_df <- as.data.frame(session_time_trends)
  session_time_trends_df$outcome <- outcome_name

  return(
    list(
      model = m,
      model_info = model_info,
      emmeans = emm_df,
      contrasts = contrast_df,
      r2 = r2_df,
      fixed = fixed_df,
      session_trends = session_trends_df,
      session_time_trends = session_time_trends_df
    )
  )
}

# --------------------------------------------------
# Run all models
# --------------------------------------------------

tone_air_models_R <- list()
model_info_list <- list()
emmeans_list <- list()
contrasts_list <- list()
r2_list <- list()
fixed_list <- list()
session_trends_list <- list()
session_time_trends_list <- list()

for (outcome_name in tone_air_outcomes_R) {

  result <- fit_tone_air_cycle_outcome(outcome_name)

  tone_air_models_R[[outcome_name]] <- result$model
  model_info_list[[outcome_name]] <- result$model_info
  emmeans_list[[outcome_name]] <- result$emmeans
  contrasts_list[[outcome_name]] <- result$contrasts
  r2_list[[outcome_name]] <- result$r2
  fixed_list[[outcome_name]] <- result$fixed
  session_trends_list[[outcome_name]] <- result$session_trends
  session_time_trends_list[[outcome_name]] <- result$session_time_trends
}

# --------------------------------------------------
# Combine output tables
# --------------------------------------------------

tone_air_model_info_R <- bind_rows(model_info_list)
tone_air_emmeans_R <- bind_rows(emmeans_list)
tone_air_contrasts_R <- bind_rows(contrasts_list)
tone_air_r2_R <- bind_rows(r2_list)
tone_air_fixed_R <- bind_rows(fixed_list)
tone_air_session_trends_R <- bind_rows(session_trends_list)
tone_air_session_time_trends_R <- bind_rows(session_time_trends_list)

# --------------------------------------------------
# Reorder columns
# --------------------------------------------------

tone_air_emmeans_R <- tone_air_emmeans_R %>%
  relocate(outcome)

tone_air_contrasts_R <- tone_air_contrasts_R %>%
  relocate(outcome) %>%
  select(outcome, contrast, estimate, SE, df, z.ratio, p.value)

tone_air_fixed_R <- tone_air_fixed_R %>%
  relocate(outcome)

tone_air_session_trends_R <- tone_air_session_trends_R %>%
  relocate(outcome)

tone_air_session_time_trends_R <- tone_air_session_time_trends_R %>%
  relocate(outcome)

# --------------------------------------------------
# Print summaries
# --------------------------------------------------

cat("\n\n=== Tone-air model info ===\n")
print(tone_air_model_info_R)

cat("\n\n=== Tone-air adjacent contrasts ===\n")
print(tone_air_contrasts_R)

cat("\n\n=== Tone-air R2 ===\n")
print(tone_air_r2_R)

cat("\n\n=== Tone-air exposure-session trends by epoch ===\n")
print(tone_air_session_trends_R)

cat("\n\n=== Tone-air within-session-time trends by epoch ===\n")
print(tone_air_session_time_trends_R)

R[write to console]: Loading required package: Matrix

R[write to console]:
Attaching package: ‘lmerTest’


R[write to console]: The following object is masked from ‘package:lme4’:

    lmer


R[write to console]: The following object is masked from ‘package:stats’:

    step


R[write to console]: Welcome to emmeans.
Caution: You lose important information if you filter this package's results.
See '? untidy'

R[write to console]:
Attaching package: ‘dplyr’


R[write to console]: The following objects are masked from ‘package:stats’:

    filter, lag


R[write to console]: The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

[1] "frac_moving"         "frac_forward"        "mean_speed_path_cms"
[4] "mean_speed_net_cms"  "distance_path_cm"    "distance_net_cm"


==============================
Fitting outcome: frac_moving
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: frac_forward
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: mean_speed_path_cms
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: mean_speed_net_cms
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: distance_path_cm
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: distance_net_cm
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

=== Tone-air model info ===
              outcome n_obs n_animals n_animal_day n_cycle_id       AIC
1         frac_moving 21762         5           49       1674  4687.568
2        frac_forward 21762         5           49       1674  4238.129
3 mean_speed_path_cms 21762         5           49       1674 91855.438
4  mean_speed_net_cms 21762         5           49       1674 92756.242
5    distance_path_cm 21762         5           49       1674 91849.102
6     distance_net_cm 21762         5           49       1674 92781.938
        BIC     logLik singular
1  5134.892  -2287.784    FALSE
2  4685.453  -2063.065    FALSE
3 92302.762 -45871.719    FALSE
4 93203.565 -46322.121    FALSE
5 92296.425 -45868.551    FALSE
6 93229.262 -46334.969    FALSE


=== Tone-air adjacent contrasts ===
               outcome                               contrast     estimate
1          frac_moving                  tone_onset_transition  0.152895125
2          frac_moving      tone_to_air_anticipatory_interval -0.146154024
3          frac_moving                   air_onset_transition  0.607870332
4          frac_moving            early_air_on_to_tone_offset  0.151776692
5          frac_moving                 tone_offset_transition  0.017986857
6          frac_moving    post_tone_offset_air_on_progression -0.059841213
7          frac_moving                  air_on_mid_transition -0.002017591
8          frac_moving                late_air_on_progression  0.090970296
9          frac_moving                  air_offset_transition -0.059384625
10         frac_moving                 early_air_off_recovery -0.628275457
11         frac_moving                 air_off_mid_transition -0.060502885
12         frac_moving late_air_off_recovery_to_next_baseline -0.066735045
13        frac_forward                  tone_onset_transition  0.116048793
14        frac_forward      tone_to_air_anticipatory_interval -0.104372983
15        frac_forward                   air_onset_transition  0.554861218
16        frac_forward            early_air_on_to_tone_offset  0.212722870
17        frac_forward                 tone_offset_transition  0.021294736
18        frac_forward    post_tone_offset_air_on_progression -0.070172721
19        frac_forward                  air_on_mid_transition -0.001576444
20        frac_forward                late_air_on_progression  0.089537139
21        frac_forward                  air_offset_transition -0.155237615
22        frac_forward                 early_air_off_recovery -0.537642965
23        frac_forward                 air_off_mid_transition -0.062136984
24        frac_forward late_air_off_recovery_to_next_baseline -0.065077755
25 mean_speed_path_cms                  tone_onset_transition  0.244550913
26 mean_speed_path_cms      tone_to_air_anticipatory_interval -0.171486028
27 mean_speed_path_cms                   air_onset_transition  2.327098293
28 mean_speed_path_cms            early_air_on_to_tone_offset  3.024713812
29 mean_speed_path_cms                 tone_offset_transition  0.474322853
30 mean_speed_path_cms    post_tone_offset_air_on_progression -0.163370312
31 mean_speed_path_cms                  air_on_mid_transition -0.239995556
32 mean_speed_path_cms                late_air_on_progression -0.364263395
33 mean_speed_path_cms                  air_offset_transition -2.221769263
34 mean_speed_path_cms                 early_air_off_recovery -2.505107918
35 mean_speed_path_cms                 air_off_mid_transition -0.208000805
36 mean_speed_path_cms late_air_off_recovery_to_next_baseline -0.206930073
37  mean_speed_net_cms                  tone_onset_transition  0.170036844
38  mean_speed_net_cms      tone_to_air_anticipatory_interval -0.076327731
39  mean_speed_net_cms                   air_onset_transition  2.209413810
40  mean_speed_net_cms            early_air_on_to_tone_offset  3.174251935
41  mean_speed_net_cms                 tone_offset_transition  0.481864986
42  mean_speed_net_cms    post_tone_offset_air_on_progression -0.199620829
43  mean_speed_net_cms                  air_on_mid_transition -0.245007231
44  mean_speed_net_cms                late_air_on_progression -0.383782429
45  mean_speed_net_cms                  air_offset_transition -2.593279527
46  mean_speed_net_cms                 early_air_off_recovery -2.121733957
47  mean_speed_net_cms                 air_off_mid_transition -0.218248119
48  mean_speed_net_cms late_air_off_recovery_to_next_baseline -0.209505360
49    distance_path_cm                  tone_onset_transition  0.249011906
50    distance_path_cm      tone_to_air_anticipatory_interval -0.175738995
51    distance_path_cm                   air_onset_transition  2.334724606
52    distance_path_cm            early_air_on_to_tone_offset  3.017526641
53    distance_path_cm                 tone_offset_transition  0.472060991
54    distance_path_cm    post_tone_offset_air_on_progression -0.160975722
55    distance_path_cm                  air_on_mid_transition -0.239959760
56    distance_path_cm                late_air_on_progression -0.374260814
57    distance_path_cm                  air_offset_transition -2.189413784
58    distance_path_cm                 early_air_off_recovery -2.527651984
59    distance_path_cm                 air_off_mid_transition -0.208534815
60    distance_path_cm late_air_off_recovery_to_next_baseline -0.207117395
61     distance_net_cm                  tone_onset_transition  0.170321844
62     distance_net_cm      tone_to_air_anticipatory_interval -0.076523228
63     distance_net_cm                   air_onset_transition  2.208276311
64     distance_net_cm            early_air_on_to_tone_offset  3.176738957
65     distance_net_cm                 tone_offset_transition  0.479478363
66     distance_net_cm    post_tone_offset_air_on_progression -0.198818693
67     distance_net_cm                  air_on_mid_transition -0.245531069
68     distance_net_cm                late_air_on_progression -0.395015051
69     distance_net_cm                  air_offset_transition -2.576373230
70     distance_net_cm                 early_air_off_recovery -2.126690375
71     distance_net_cm                 air_off_mid_transition -0.218666877
72     distance_net_cm late_air_off_recovery_to_next_baseline -0.209117305
            SE  df     z.ratio       p.value
1  0.009121723 Inf  16.7616488  4.655327e-63
2  0.009121723 Inf -16.0226326  8.880930e-58
3  0.009121723 Inf  66.6398554  0.000000e+00
4  0.009121723 Inf  16.6390367  3.634173e-62
5  0.009121723 Inf   1.9718704  4.862440e-02
6  0.009121723 Inf  -6.5602968  5.370079e-11
7  0.009121723 Inf  -0.2211853  8.249481e-01
8  0.009121723 Inf   9.9729285  2.002360e-23
9  0.009121723 Inf  -6.5102417  7.502996e-11
10 0.009121723 Inf -68.8768367  0.000000e+00
11 0.009121723 Inf  -6.6328349  3.293001e-11
12 0.009121723 Inf  -7.3160566  2.553641e-13
13 0.009010155 Inf  12.8797777  5.850385e-38
14 0.009010155 Inf -11.5839275  4.971498e-31
15 0.009010155 Inf  61.5817616  0.000000e+00
16 0.009010155 Inf  23.6092354 3.097990e-123
17 0.009010155 Inf   2.3634150  1.810738e-02
18 0.009010155 Inf  -7.7881813  6.798058e-15
19 0.009010155 Inf  -0.1749631  8.611087e-01
20 0.009010155 Inf   9.9373584  2.863191e-23
21 0.009010155 Inf -17.2291836  1.603992e-66
22 0.009010155 Inf -59.6707786  0.000000e+00
23 0.009010155 Inf  -6.8963280  5.336391e-12
24 0.009010155 Inf  -7.2227120  5.096087e-13
25 0.066937091 Inf   3.6534440  2.587463e-04
26 0.066937091 Inf  -2.5618984  1.041018e-02
27 0.066937091 Inf  34.7654528 8.096687e-265
28 0.066937091 Inf  45.1874102  0.000000e+00
29 0.066937091 Inf   7.0860989  1.379452e-12
30 0.066937091 Inf  -2.4406545  1.466067e-02
31 0.066937091 Inf  -3.5853897  3.365753e-04
32 0.066937091 Inf  -5.4418767  5.272218e-08
33 0.066937091 Inf -33.1919003 1.409004e-241
34 0.066937091 Inf -37.4248098 1.543427e-306
35 0.066937091 Inf  -3.1074073  1.887362e-03
36 0.066937091 Inf  -3.0914112  1.992076e-03
37 0.068319818 Inf   2.4888363  1.281620e-02
38 0.068319818 Inf  -1.1172122  2.639036e-01
39 0.068319818 Inf  32.3392811 1.962871e-229
40 0.068319818 Inf  46.4616565  0.000000e+00
41 0.068319818 Inf   7.0530777  1.750031e-12
42 0.068319818 Inf  -2.9218583  3.479498e-03
43 0.068319818 Inf  -3.5861809  3.355562e-04
44 0.068319818 Inf  -5.6174392  1.938083e-08
45 0.068319818 Inf -37.9579394  0.000000e+00
46 0.068319818 Inf -31.0559075 9.494677e-212
47 0.068319818 Inf  -3.1945067  1.400700e-03
48 0.068319818 Inf  -3.0665386  2.165528e-03
49 0.066931532 Inf   3.7203975  1.989095e-04
50 0.066931532 Inf  -2.6256532  8.648287e-03
51 0.066931532 Inf  34.8822823 1.380210e-266
52 0.066931532 Inf  45.0837824  0.000000e+00
53 0.066931532 Inf   7.0528938  1.752346e-12
54 0.066931532 Inf  -2.4050805  1.616890e-02
55 0.066931532 Inf  -3.5851526  3.368811e-04
56 0.066931532 Inf  -5.5916965  2.248617e-08
57 0.066931532 Inf -32.7112454 1.080777e-234
58 0.066931532 Inf -37.7647410  0.000000e+00
59 0.066931532 Inf  -3.1156438  1.835438e-03
60 0.066931532 Inf  -3.0944667  1.971671e-03
61 0.068363532 Inf   2.4914137  1.272359e-02
62 0.068363532 Inf  -1.1193574  2.629877e-01
63 0.068363532 Inf  32.3019633 6.564608e-229
64 0.068363532 Inf  46.4683268  0.000000e+00
65 0.068363532 Inf   7.0136570  2.321682e-12
66 0.068363532 Inf  -2.9082566  3.634500e-03
67 0.068363532 Inf  -3.5915504  3.287166e-04
68 0.068363532 Inf  -5.7781545  7.552444e-09
69 0.068363532 Inf -37.6863680  0.000000e+00
70 0.068363532 Inf -31.1085502 1.845567e-212
71 0.068363532 Inf  -3.1985895  1.381017e-03
72 0.068363532 Inf  -3.0589014  2.221503e-03


=== Tone-air R2 ===
                            outcome R2_marginal R2_conditional
Marginal R2...1         frac_moving   0.6174080      0.6433808
Marginal R2...2        frac_forward   0.6148106      0.6502489
Marginal R2...3 mean_speed_path_cms   0.5809397      0.6507310
Marginal R2...4  mean_speed_net_cms   0.5701544      0.6481242
Marginal R2...5    distance_path_cm   0.5809964      0.6505155
Marginal R2...6     distance_net_cm   0.5697429      0.6476593


=== Tone-air exposure-session trends by epoch ===
               outcome tone_air_cycle_epoch tone_air_session_c.trend
1          frac_moving          pre_tone_on            -0.0049840127
2          frac_moving         post_tone_on            -0.0046154881
3          frac_moving           pre_air_on            -0.0034072912
4          frac_moving          post_air_on            -0.0046265030
5          frac_moving         pre_tone_off            -0.0070670463
6          frac_moving        post_tone_off            -0.0037820847
7          frac_moving       pre_air_on_mid            -0.0055741618
8          frac_moving      post_air_on_mid            -0.0060990039
9          frac_moving          pre_air_off             0.0001378639
10         frac_moving         post_air_off            -0.0040889395
11         frac_moving      pre_air_off_mid             0.0064490172
12         frac_moving     post_air_off_mid             0.0017121424
13         frac_moving     pre_tone_on_next            -0.0046314622
14        frac_forward          pre_tone_on            -0.0070930115
15        frac_forward         post_tone_on            -0.0083938083
16        frac_forward           pre_air_on            -0.0063202404
17        frac_forward          post_air_on            -0.0077135012
18        frac_forward         pre_tone_off            -0.0079999699
19        frac_forward        post_tone_off            -0.0047620505
20        frac_forward       pre_air_on_mid            -0.0050816363
21        frac_forward      post_air_on_mid            -0.0051732339
22        frac_forward          pre_air_off             0.0010751111
23        frac_forward         post_air_off            -0.0046241377
24        frac_forward      pre_air_off_mid             0.0032489120
25        frac_forward     post_air_off_mid             0.0007452261
26        frac_forward     pre_tone_on_next            -0.0070114383
27 mean_speed_path_cms          pre_tone_on            -0.0395067049
28 mean_speed_path_cms         post_tone_on            -0.0396162874
29 mean_speed_path_cms           pre_air_on            -0.0352255272
30 mean_speed_path_cms          post_air_on            -0.0810417761
31 mean_speed_path_cms         pre_tone_off            -0.0917424796
32 mean_speed_path_cms        post_tone_off            -0.0534551309
33 mean_speed_path_cms       pre_air_on_mid             0.0103762974
34 mean_speed_path_cms      post_air_on_mid            -0.0109647589
35 mean_speed_path_cms          pre_air_off            -0.1035884175
36 mean_speed_path_cms         post_air_off            -0.0684769454
37 mean_speed_path_cms      pre_air_off_mid            -0.0028540639
38 mean_speed_path_cms     post_air_off_mid            -0.0142829750
39 mean_speed_path_cms     pre_tone_on_next            -0.0369515978
40  mean_speed_net_cms          pre_tone_on            -0.0510124891
41  mean_speed_net_cms         post_tone_on            -0.0540203463
42  mean_speed_net_cms           pre_air_on            -0.0453993552
43  mean_speed_net_cms          post_air_on            -0.0933579581
44  mean_speed_net_cms         pre_tone_off            -0.0958216374
45  mean_speed_net_cms        post_tone_off            -0.0574804208
46  mean_speed_net_cms       pre_air_on_mid             0.0120339197
47  mean_speed_net_cms      post_air_on_mid            -0.0064823234
48  mean_speed_net_cms          pre_air_off            -0.0955837022
49  mean_speed_net_cms         post_air_off            -0.0709636377
50  mean_speed_net_cms      pre_air_off_mid            -0.0142154657
51  mean_speed_net_cms     post_air_off_mid            -0.0172721141
52  mean_speed_net_cms     pre_tone_on_next            -0.0490243837
53    distance_path_cm          pre_tone_on            -0.0395319433
54    distance_path_cm         post_tone_on            -0.0394891400
55    distance_path_cm           pre_air_on            -0.0348735968
56    distance_path_cm          post_air_on            -0.0810445718
57    distance_path_cm         pre_tone_off            -0.0916440077
58    distance_path_cm        post_tone_off            -0.0535334834
59    distance_path_cm       pre_air_on_mid             0.0101439392
60    distance_path_cm      post_air_on_mid            -0.0114558250
61    distance_path_cm          pre_air_off            -0.1041513634
62    distance_path_cm         post_air_off            -0.0685989575
63    distance_path_cm      pre_air_off_mid            -0.0026967501
64    distance_path_cm     post_air_off_mid            -0.0143439585
65    distance_path_cm     pre_tone_on_next            -0.0369438067
66     distance_net_cm          pre_tone_on            -0.0510433838
67     distance_net_cm         post_tone_on            -0.0541086068
68     distance_net_cm           pre_air_on            -0.0452422092
69     distance_net_cm          post_air_on            -0.0935161453
70     distance_net_cm         pre_tone_off            -0.0957356616
71     distance_net_cm        post_tone_off            -0.0574735285
72     distance_net_cm       pre_air_on_mid             0.0121254911
73     distance_net_cm      post_air_on_mid            -0.0065885152
74     distance_net_cm          pre_air_off            -0.0956233334
75     distance_net_cm         post_air_off            -0.0710660155
76     distance_net_cm      pre_air_off_mid            -0.0142457921
77     distance_net_cm     post_air_off_mid            -0.0173434734
78     distance_net_cm     pre_tone_on_next            -0.0490381842
            SE  df    asymp.LCL     asymp.UCL
1  0.003059616 Inf -0.010980749  1.012724e-03
2  0.003059616 Inf -0.010612224  1.381248e-03
3  0.003059616 Inf -0.009404027  2.589445e-03
4  0.003059616 Inf -0.010623239  1.370233e-03
5  0.003059616 Inf -0.013063782 -1.070310e-03
6  0.003059616 Inf -0.009778821  2.214652e-03
7  0.003059616 Inf -0.011570898  4.225744e-04
8  0.003059616 Inf -0.012095740 -1.022677e-04
9  0.003059616 Inf -0.005858872  6.134600e-03
10 0.003059616 Inf -0.010085676  1.907797e-03
11 0.003059616 Inf  0.000452281  1.244575e-02
12 0.003059616 Inf -0.004284594  7.708879e-03
13 0.003059616 Inf -0.010628198  1.365274e-03
14 0.003182701 Inf -0.013330992 -8.550315e-04
15 0.003182701 Inf -0.014631788 -2.155828e-03
16 0.003182701 Inf -0.012558220 -8.226036e-05
17 0.003182701 Inf -0.013951481 -1.475521e-03
18 0.003182701 Inf -0.014237950 -1.761990e-03
19 0.003182701 Inf -0.011000031  1.475930e-03
20 0.003182701 Inf -0.011319616  1.156344e-03
21 0.003182701 Inf -0.011411214  1.064746e-03
22 0.003182701 Inf -0.005162869  7.313091e-03
23 0.003182701 Inf -0.010862118  1.613842e-03
24 0.003182701 Inf -0.002989068  9.486892e-03
25 0.003182701 Inf -0.005492754  6.983206e-03
26 0.003182701 Inf -0.013249418 -7.734583e-04
27 0.029670304 Inf -0.097659433  1.864602e-02
28 0.029670304 Inf -0.097769015  1.853644e-02
29 0.029670304 Inf -0.093378255  2.292720e-02
30 0.029670304 Inf -0.139194504 -2.288905e-02
31 0.029670304 Inf -0.149895207 -3.358975e-02
32 0.029670304 Inf -0.111607859  4.697597e-03
33 0.029670304 Inf -0.047776430  6.852903e-02
34 0.029670304 Inf -0.069117487  4.718797e-02
35 0.029670304 Inf -0.161741145 -4.543569e-02
36 0.029670304 Inf -0.126629673 -1.032422e-02
37 0.029670304 Inf -0.061006792  5.529866e-02
38 0.029670304 Inf -0.072435703  4.386975e-02
39 0.029670304 Inf -0.095104326  2.120113e-02
40 0.031197520 Inf -0.112158505  1.013353e-02
41 0.031197520 Inf -0.115166362  7.125670e-03
42 0.031197520 Inf -0.106545371  1.574666e-02
43 0.031197520 Inf -0.154503974 -3.221194e-02
44 0.031197520 Inf -0.156967653 -3.467562e-02
45 0.031197520 Inf -0.118626437  3.665595e-03
46 0.031197520 Inf -0.049112096  7.317994e-02
47 0.031197520 Inf -0.067628339  5.466369e-02
48 0.031197520 Inf -0.156729718 -3.443769e-02
49 0.031197520 Inf -0.132109654 -9.817622e-03
50 0.031197520 Inf -0.075361482  4.693055e-02
51 0.031197520 Inf -0.078418130  4.387390e-02
52 0.031197520 Inf -0.110170400  1.212163e-02
53 0.029663205 Inf -0.097670756  1.860687e-02
54 0.029663205 Inf -0.097627953  1.864967e-02
55 0.029663205 Inf -0.093012409  2.326522e-02
56 0.029663205 Inf -0.139183384 -2.290576e-02
57 0.029663205 Inf -0.149782820 -3.350520e-02
58 0.029663205 Inf -0.111672296  4.605329e-03
59 0.029663205 Inf -0.047994873  6.828275e-02
60 0.029663205 Inf -0.069594638  4.668299e-02
61 0.029663205 Inf -0.162290176 -4.601255e-02
62 0.029663205 Inf -0.126737770 -1.046014e-02
63 0.029663205 Inf -0.060835563  5.544206e-02
64 0.029663205 Inf -0.072482771  4.379485e-02
65 0.029663205 Inf -0.095082619  2.119501e-02
66 0.031201705 Inf -0.112197602  1.011083e-02
67 0.031201705 Inf -0.115262824  7.045611e-03
68 0.031201705 Inf -0.106396427  1.591201e-02
69 0.031201705 Inf -0.154670363 -3.236193e-02
70 0.031201705 Inf -0.156889879 -3.458144e-02
71 0.031201705 Inf -0.118627746  3.680689e-03
72 0.031201705 Inf -0.049028727  7.327971e-02
73 0.031201705 Inf -0.067742733  5.456570e-02
74 0.031201705 Inf -0.156777551 -3.446912e-02
75 0.031201705 Inf -0.132220233 -9.911798e-03
76 0.031201705 Inf -0.075400010  4.690843e-02
77 0.031201705 Inf -0.078497691  4.381074e-02
78 0.031201705 Inf -0.110192402  1.211603e-02


=== Tone-air within-session-time trends by epoch ===
               outcome tone_air_cycle_epoch cycle_session_10m_c.trend
1          frac_moving          pre_tone_on              -0.003861813
2          frac_moving         post_tone_on              -0.004520578
3          frac_moving           pre_air_on              -0.003851215
4          frac_moving          post_air_on               0.012366548
5          frac_moving         pre_tone_off              -0.005229477
6          frac_moving        post_tone_off              -0.015193926
7          frac_moving       pre_air_on_mid              -0.042992605
8          frac_moving      post_air_on_mid              -0.044545293
9          frac_moving          pre_air_off              -0.009843285
10         frac_moving         post_air_off              -0.005877663

In [9]:
import numpy as np
import pandas as pd
from pathlib import Path

# --------------------------------------------------
# Choose outcomes
# --------------------------------------------------

tone_air_outcomes = [
    "frac_moving",
    "frac_forward",
    "mean_speed_path_cms",
    "mean_speed_net_cms",
    "distance_path_cm",
    "distance_net_cm",
]

tone_air_outcomes = [
    x for x in tone_air_outcomes
    if x in tone_air_cycle_df.columns
]

print(tone_air_outcomes)

# --------------------------------------------------
# Copy dataframe
# --------------------------------------------------

df = tone_air_cycle_df.copy()

# --------------------------------------------------
# Fixed session-time bins
# --------------------------------------------------
# These are based on absolute minutes within the session.

df["session_time_bin"] = pd.cut(
    df["cycle_session_time_min"],
    bins=[0, 6, 12, np.inf],
    labels=["early_0_6min", "middle_6_12min", "late_12plus_min"],
    right=False
)

print(df["session_time_bin"].value_counts(dropna=False))

# --------------------------------------------------
# Optional: create tone-air training bins
# --------------------------------------------------
# This is better for RM-ANOVA than using every session as a separate factor.

df["tone_air_training_bin"] = pd.qcut(
    df["cycle_tone_air_session"],
    q=3,
    labels=["early_training", "middle_training", "late_training"],
    duplicates="drop"
)

print(df["tone_air_training_bin"].value_counts(dropna=False))

# --------------------------------------------------
# Aggregate to animal × training bin × session-time bin × epoch
# --------------------------------------------------

group_cols_training_bin = [
    "animal",
    "tone_air_training_bin",
    "session_time_bin",
    "tone_air_cycle_epoch",
]

tone_air_rm_trainingbin_df = (
    df
    .dropna(subset=group_cols_training_bin)
    .groupby(group_cols_training_bin, observed=True)[tone_air_outcomes]
    .mean()
    .reset_index()
)

print(tone_air_rm_trainingbin_df.shape)
display(tone_air_rm_trainingbin_df.head())

# --------------------------------------------------
# Aggregate to animal × session/day × session-time bin × epoch
# --------------------------------------------------
# Use this if you really want day/session as a factor.

group_cols_day = [
    "animal",
    "cycle_tone_air_session",
    "session_time_bin",
    "tone_air_cycle_epoch",
]

tone_air_rm_day_df = (
    df
    .dropna(subset=group_cols_day)
    .groupby(group_cols_day, observed=True)[tone_air_outcomes]
    .mean()
    .reset_index()
)

tone_air_rm_day_df["tone_air_session_factor"] = (
    tone_air_rm_day_df["cycle_tone_air_session"]
    .astype(int)
    .astype(str)
)

print(tone_air_rm_day_df.shape)
display(tone_air_rm_day_df.head())

['frac_moving', 'frac_forward', 'mean_speed_path_cms', 'mean_speed_net_cms', 'distance_path_cm', 'distance_net_cm']
session_time_bin
late_12plus_min    7761
early_0_6min       7475
middle_6_12min     6526
Name: count, dtype: int64
tone_air_training_bin
early_training     9282
middle_training    6357
late_training      6123
Name: count, dtype: int64
(585, 10)

,animal,tone_air_training_bin,session_time_bin,tone_air_cycle_epoch,frac_moving,frac_forward,mean_speed_path_cms,mean_speed_net_cms,distance_path_cm,distance_net_cm
0,NML_04,early_training,early_0_6min,pre_tone_on,0.249893,0.183751,0.437058,0.284843,0.444570,0.283721
1,NML_04,early_training,early_0_6min,post_tone_on,0.338347,0.242347,0.597375,0.375043,0.609329,0.375874
2,NML_04,early_training,early_0_6min,pre_air_on,0.083764,0.053129,0.123882,0.041815,0.128456,0.040212
3,NML_04,early_training,early_0_6min,post_air_on,0.725689,0.533271,2.252345,1.842409,2.268649,1.843068
4,NML_04,early_training,early_0_6min,pre_tone_off,0.920098,0.871418,4.970649,4.848736,4.982985,4.850061

(1885, 11)

,animal,cycle_tone_air_session,session_time_bin,tone_air_cycle_epoch,frac_moving,frac_forward,mean_speed_path_cms,mean_speed_net_cms,distance_path_cm,distance_net_cm,tone_air_session_factor
0,NML_04,1.0,early_0_6min,pre_tone_on,0.336164,0.303491,0.510547,0.418204,0.514079,0.413548,1
1,NML_04,1.0,early_0_6min,post_tone_on,0.284455,0.246836,0.596798,0.457800,0.612325,0.461529,1
2,NML_04,1.0,early_0_6min,pre_air_on,0.070727,0.042364,0.116849,0.005470,0.118809,0.004570,1
3,NML_04,1.0,early_0_6min,post_air_on,0.674945,0.508127,2.069965,1.642781,2.081448,1.647337,1
4,NML_04,1.0,early_0_6min,pre_tone_off,0.890582,0.845200,4.618073,4.453741,4.622140,4.443926,1

In [10]:
%%R -i tone_air_rm_trainingbin_df -o tone_air_rm_anova_trainingbin_R

library(dplyr)

# Install afex if needed:
# install.packages("afex")

library(afex)
library(emmeans)

afex_options(type = 3)

tone_air_rm_trainingbin_df$animal <- factor(tone_air_rm_trainingbin_df$animal)

tone_air_rm_trainingbin_df$tone_air_cycle_epoch <- factor(
  as.character(tone_air_rm_trainingbin_df$tone_air_cycle_epoch),
  levels = c(
    "pre_tone_on",
    "post_tone_on",
    "pre_air_on",
    "post_air_on",
    "pre_tone_off",
    "post_tone_off",
    "pre_air_on_mid",
    "post_air_on_mid",
    "pre_air_off",
    "post_air_off",
    "pre_air_off_mid",
    "post_air_off_mid",
    "pre_tone_on_next"
  )
)

tone_air_rm_trainingbin_df$session_time_bin <- factor(
  tone_air_rm_trainingbin_df$session_time_bin,
  levels = c("early_0_6min", "middle_6_12min", "late_12plus_min")
)

tone_air_rm_trainingbin_df$tone_air_training_bin <- factor(
  tone_air_rm_trainingbin_df$tone_air_training_bin,
  levels = c("early_training", "middle_training", "late_training")
)

outcomes <- c(
  "frac_moving",
  "frac_forward",
  "mean_speed_path_cms",
  "mean_speed_net_cms",
  "distance_path_cm",
  "distance_net_cm"
)

outcomes <- outcomes[outcomes %in% names(tone_air_rm_trainingbin_df)]

rm_results <- list()

for (outcome in outcomes) {

  cat("\n\n==============================\n")
  cat(outcome, "\n")
  cat("==============================\n")

  aov_model <- aov_ez(
    id = "animal",
    dv = outcome,
    data = tone_air_rm_trainingbin_df,
    within = c(
      "tone_air_cycle_epoch",
      "tone_air_training_bin",
      "session_time_bin"
    ),
    anova_table = list(correction = "GG", es = "pes")
  )

  print(aov_model)

  rm_results[[outcome]] <- aov_model
}

# Convert ANOVA tables to one dataframe
anova_tables <- list()

for (outcome in outcomes) {
  tmp <- as.data.frame(rm_results[[outcome]]$anova_table)
  tmp$effect <- rownames(tmp)
  tmp$outcome <- outcome
  rownames(tmp) <- NULL
  anova_tables[[outcome]] <- tmp
}

tone_air_rm_anova_trainingbin_R <- bind_rows(anova_tables)

tone_air_rm_anova_trainingbin_R <- tone_air_rm_anova_trainingbin_R %>%
  relocate(outcome, effect)

print(tone_air_rm_anova_trainingbin_R)

R[write to console]: ************
Welcome to afex. For support visit: http://afex.singmann.science/

R[write to console]: - Functions for ANOVAs: aov_car(), aov_ez(), and aov_4()
- Methods for calculating p-values with mixed(): 'S', 'KR', 'LRT', and 'PB'
- 'afex_aov' and 'mixed' objects can be passed to emmeans() for follow-up tests
- Get and set global package options with: afex_options()
- Set sum-to-zero contrasts globally: set_sum_contrasts()
- For example analyses see: browseVignettes("afex")
************

R[write to console]:
Attaching package: ‘afex’


R[write to console]: The following object is masked from ‘package:lme4’:

    lmer

==============================
frac_moving
==============================
Anova Table (Type 3 tests)

Response: frac_moving
                                                       Effect         df  MSE
1                                        tone_air_cycle_epoch     12, 48 0.14
2                                       tone_air_training_bin 1.13, 4.52 0.07
3                                            session_time_bin 1.17, 4.67 0.04
4                  tone_air_cycle_epoch:tone_air_training_bin     24, 96 0.01
5                       tone_air_cycle_epoch:session_time_bin     24, 96 0.01
6                      tone_air_training_bin:session_time_bin 2.27, 9.10 0.01
7 tone_air_cycle_epoch:tone_air_training_bin:session_time_bin    48, 192 0.00
          F  pes p.value
1 35.90 *** .900   <.001
2      1.26 .239    .328
3      1.28 .242    .325
4    1.62 + .288    .053
5  3.83 *** .489   <.001
6      0.96 .193    .431
7    1.58 * .283    .016
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1

Sphericity correction method: GG


==============================
frac_forward
==============================
Anova Table (Type 3 tests)

Response: frac_forward
                                                       Effect         df  MSE
1                                        tone_air_cycle_epoch     12, 48 0.14
2                                       tone_air_training_bin 1.23, 4.93 0.08
3                                            session_time_bin 1.15, 4.60 0.04
4                  tone_air_cycle_epoch:tone_air_training_bin     24, 96 0.01
5                       tone_air_cycle_epoch:session_time_bin     24, 96 0.01
6                      tone_air_training_bin:session_time_bin 2.37, 9.47 0.02
7 tone_air_cycle_epoch:tone_air_training_bin:session_time_bin    48, 192 0.00
          F  pes p.value
1 35.55 *** .899   <.001
2      1.20 .231    .341
3      1.70 .299    .260
4      1.14 .222    .315
5  3.89 *** .493   <.001
6      1.31 .247    .320
7    1.62 * .289    .012
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1

Sphericity correction method: GG


==============================
mean_speed_path_cms
==============================
Anova Table (Type 3 tests)

Response: mean_speed_path_cms
                                                       Effect         df   MSE
1                                        tone_air_cycle_epoch     12, 48 11.50
2                                       tone_air_training_bin 1.02, 4.09 13.53
3                                            session_time_bin 1.16, 4.66  6.90
4                  tone_air_cycle_epoch:tone_air_training_bin     24, 96  1.24
5                       tone_air_cycle_epoch:session_time_bin     24, 96  0.62
6                      tone_air_training_bin:session_time_bin 1.62, 6.48  2.36
7 tone_air_cycle_epoch:tone_air_training_bin:session_time_bin    48, 192  0.19
          F  pes p.value
1 20.58 *** .837   <.001
2      0.61 .133    .480
3      3.23 .447    .136
4      0.33 .077    .998
5  2.62 *** .396   <.001
6      2.26 .361    .182
7    1.38 + .256    .067
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1

Sphericity correction method: GG


==============================
mean_speed_net_cms
==============================
Anova Table (Type 3 tests)

Response: mean_speed_net_cms
                                                       Effect         df   MSE
1                                        tone_air_cycle_epoch     12, 48 11.54
2                                       tone_air_training_bin 1.03, 4.13 15.33
3                                            session_time_bin 1.18, 4.70  6.89
4                  tone_air_cycle_epoch:tone_air_training_bin     24, 96  1.27
5                       tone_air_cycle_epoch:session_time_bin     24, 96  0.64
6                      tone_air_training_bin:session_time_bin 1.68, 6.73  2.38
7 tone_air_cycle_epoch:tone_air_training_bin:session_time_bin    48, 192  0.19
          F  pes p.value
1 20.91 *** .839   <.001
2      0.63 .135    .477
3      3.33 .454    .131
4      0.26 .061   >.999
5  2.59 *** .393   <.001
6      2.37 .372    .169
7    1.46 * .268    .039
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1

Sphericity correction method: GG


==============================
distance_path_cm
==============================
Anova Table (Type 3 tests)

Response: distance_path_cm
                                                       Effect         df   MSE
1                                        tone_air_cycle_epoch     12, 48 11.48
2                                       tone_air_training_bin 1.02, 4.09 13.51
3                                            session_time_bin 1.16, 4.66  6.89
4                  tone_air_cycle_epoch:tone_air_training_bin     24, 96  1.24
5                       tone_air_cycle_epoch:session_time_bin     24, 96  0.62
6                      tone_air_training_bin:session_time_bin 1.62, 6.46  2.36
7 tone_air_cycle_epoch:tone_air_training_bin:session_time_bin    48, 192  0.19
          F  pes p.value
1 20.59 *** .837   <.001
2      0.62 .134    .478
3      3.24 .448    .136
4      0.34 .077    .998
5  2.63 *** .396   <.001
6      2.25 .360    .183
7    1.37 + .256    .070
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1

Sphericity correction method: GG


==============================
distance_net_cm
==============================
Anova Table (Type 3 tests)

Response: distance_net_cm
                                                       Effect         df   MSE
1                                        tone_air_cycle_epoch     12, 48 11.54
2                                       tone_air_training_bin 1.03, 4.13 15.33
3                                            session_time_bin 1.18, 4.70  6.88
4                  tone_air_cycle_epoch:tone_air_training_bin     24, 96  1.27
5                       tone_air_cycle_epoch:session_time_bin     24, 96  0.64
6                      tone_air_training_bin:session_time_bin 1.68, 6.73  2.38
7 tone_air_cycle_epoch:tone_air_training_bin:session_time_bin    48, 192  0.19
          F  pes p.value
1 20.89 *** .839   <.001
2      0.63 .136    .477
3      3.34 .455    .130
4      0.26 .061   >.999
5  2.59 *** .393   <.001
6      2.37 .372    .168
7    1.46 * .267    .039
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1

Sphericity correction method: GG
               outcome
1          frac_moving
2          frac_moving
3          frac_moving
4          frac_moving
5          frac_moving
6          frac_moving
7          frac_moving
8         frac_forward
9         frac_forward
10        frac_forward
11        frac_forward
12        frac_forward
13        frac_forward
14        frac_forward
15 mean_speed_path_cms
16 mean_speed_path_cms
17 mean_speed_path_cms
18 mean_speed_path_cms
19 mean_speed_path_cms
20 mean_speed_path_cms
21 mean_speed_path_cms
22  mean_speed_net_cms
23  mean_speed_net_cms
24  mean_speed_net_cms
25  mean_speed_net_cms
26  mean_speed_net_cms
27  mean_speed_net_cms
28  mean_speed_net_cms
29    distance_path_cm
30    distance_path_cm
31    distance_path_cm
32    distance_path_cm
33    distance_path_cm
34    distance_path_cm
35    distance_path_cm
36     distance_net_cm
37     distance_net_cm
38     distance_net_cm
39     distance_net_cm
40     distance_net_cm
41     distance_net_cm
42     distance_net_cm
                                                        effect    num Df
1                                         tone_air_cycle_epoch 12.000000
2                                        tone_air_training_bin  1.131206
3                                             session_time_bin  1.168092
4                   tone_air_cycle_epoch:tone_air_training_bin 24.000000
5                        tone_air_cycle_epoch:session_time_bin 24.000000
6                       tone_air_training_bin:session_time_bin  2.274618
7  tone_air_cycle_epoch:tone_air_training_bin:session_time_bin 48.000000
8                                         tone_air_cycle_epoch 12.000000
9                                        tone_air_training_bin  1.233232
10                                            session_time_bin  1.149370
11                  tone_air_cycle_epoch:tone_air_training_bin 24.000000
12                       tone_air_cycle_epoch:session_time_bin 24.000000
13                      tone_air_training_bin:session_time_bin  2.366868
14 tone_air_cycle_epoch:tone_air_training_bin:session_time_bin 48.000000
15                                        tone_air_cycle_epoch 12.000000
16                                       tone_air_training_bin  1.022077
17                                            session_time_bin  1.163960
18                  tone_air_cycle_epoch:tone_air_training_bin 24.000000
19                       tone_air_cycle_epoch:session_time_bin 24.000000
20                      tone_air_training_bin:session_time_bin  1.621178
21 tone_air_cycle_epoch:tone_air_training_bin:session_time_bin 48.000000
22                                        tone_air_cycle_epoch 12.000000
23                                       tone_air_training_bin  1.033741
24                                            session_time_bin  1.175619
25                  tone_air_cycle_epoch:tone_air_training_bin 24.000000
26                       tone_air_cycle_epoch:session_time_bin 24.000000
27                      tone_air_training_bin:session_time_bin  1.682217
28 tone_air_cycle_epoch:tone_air_training_bin:session_time_bin 48.000000
29                                        tone_air_cycle_epoch 12.000000
30                                       tone_air_training_bin  1.021711
31                                            session_time_bin  1.164310
32                  tone_air_cycle_epoch:tone_air_training_bin 24.000000
33                       tone_air_cycle_epoch:session_time_bin 24.000000
34                      tone_air_training_bin:session_time_bin  1.615466
35 tone_air_cycle_epoch:tone_air_training_bin:session_time_bin 48.000000
36                                        tone_air_cycle_epoch 12.000000
37                                       tone_air_training_bin  1.033645
38                                            session_time_bin  1.175365
39                  tone_air_cycle_epoch:tone_air_training_bin 24.000000
40                       tone_air_cycle_epoch:session_time_bin 24.000000
41                      tone_air_training_bin:session_time_bin  1.681934
42 tone_air_cycle_epoch:tone_air_training_bin:session_time_bin 48.000000
       den Df          MSE          F        pes       Pr(>F)
1   48.000000  0.136339264 35.8950054 0.89973682 7.627141e-20
2    4.524826  0.070288433  1.2576314 0.23920114 3.278806e-01
3    4.672367  0.043159148  1.2763889 0.24190576 3.251246e-01
4   96.000000  0.010384857  1.6193063 0.28816837 5.261143e-02
5   96.000000  0.007805531  3.8313383 0.48923162 1.375008e-06
6    9.098473  0.013628538  0.9569709 0.19305559 4.307313e-01
7  192.000000  0.004818326  1.5820978 0.28342352 1.616607e-02
8   48.000000  0.136553984 35.5461335 0.89885231 9.372817e-20
9    4.932927  0.080965512  1.1997439 0.23073135 3.411215e-01
10   4.597480  0.044219736  1.7025115 0.29855469 2.598392e-01
11  96.000000  0.011166624  1.1432450 0.22228088 3.145900e-01
12  96.000000  0.007916507  3.8867478 0.49282009 1.058020e-06
13   9.467470  0.016348757  1.3137406 0.24723462 3.195570e-01
14 192.000000  0.004566665  1.6236247 0.28871498 1.179562e-02
15  48.000000 11.495363588 20.5756657 0.83723737 6.071137e-15
16   4.088307 13.531138588  0.6142388 0.13311812 4.796814e-01
17   4.655839  6.904124219  3.2302464 0.44676851 1.362134e-01
18  96.000000  1.242464927  0.3317191 0.07657908 9.984842e-01
19  96.000000  0.618178983  2.6235809 0.39609706 4.789681e-04
20   6.484712  2.357084913  2.2552488 0.36053703 1.818161e-01
21 192.000000  0.187897506  1.3791943 0.25639422 6.742491e-02
22  48.000000 11.539241870 20.9091840 0.83941666 4.447735e-15
23   4.134963 15.325705004  0.6261249 0.13534543 4.770483e-01
24   4.702475  6.892077437  3.3325681 0.45448853 1.305543e-01
25  96.000000  1.267555619  0.2594854 0.06091942 9.998024e-01
26  96.000000  0.639307069  2.5898778 0.39300847 5.646905e-04
27   6.728869  2.378012423  2.3652410 0.37158703 1.686724e-01
28 192.000000  0.187721008  1.4620415 0.26767308 3.856842e-02
29  48.000000 11.478069758 20.5901070 0.83733296 5.989392e-15
30   4.086843 13.512744768  0.6188576 0.13398499 4.780760e-01
31   4.657239  6.890995610  3.2411047 0.44759810 1.356558e-01
32  96.000000  1.241248029  0.3352445 0.07733000 9.983530e-01
33  96.000000  0.617864454  2.6267115 0.39638236 4.716957e-04
34   6.461862  2.361625799  2.2467833 0.35967044 1.828942e-01
35 192.000000  0.188213416  1.3733875 0.25559063 7.001750e-02
36  48.000000 11.537704938 20.8926581 0.83931005 4.516416e-15
37   4.134582 15.331770293  0.6270257 0.13551377 4.767346e-01
38   4.701459  6.883536570  3.3379112 0.45488575 1.303194e-01
39  96.000000  1.267809640  0.2595473 0.06093306 9.998020e-01
40  96.000000  0.639439082  2.5912227 0.39313233 5.609941e-04
41   6.727737  2.377247051  2.3707627 0.37213169 1.681688e-01
42 192.000000  0.187908675  1.4590249 0.26726841 3.938585e-02

In [12]:
%%R

library(dplyr)

tone_air_session_trends_R <- tone_air_session_trends_R %>%
  mutate(
    z.ratio = tone_air_session_c.trend / SE,
    p.value = 2 * (1 - pnorm(abs(z.ratio)))
  )

tone_air_session_time_trends_R <- tone_air_session_time_trends_R %>%
  mutate(
    z.ratio = cycle_session_10m_c.trend / SE,
    p.value = 2 * (1 - pnorm(abs(z.ratio)))
  )

print(tone_air_session_trends_R)
print(tone_air_session_time_trends_R)

               outcome tone_air_cycle_epoch tone_air_session_c.trend
1          frac_moving          pre_tone_on            -0.0049840127
2          frac_moving         post_tone_on            -0.0046154881
3          frac_moving           pre_air_on            -0.0034072912
4          frac_moving          post_air_on            -0.0046265030
5          frac_moving         pre_tone_off            -0.0070670463
6          frac_moving        post_tone_off            -0.0037820847
7          frac_moving       pre_air_on_mid            -0.0055741618
8          frac_moving      post_air_on_mid            -0.0060990039
9          frac_moving          pre_air_off             0.0001378639
10         frac_moving         post_air_off            -0.0040889395
11         frac_moving      pre_air_off_mid             0.0064490172
12         frac_moving     post_air_off_mid             0.0017121424
13         frac_moving     pre_tone_on_next            -0.0046314622
14        frac_forward          pre_tone_on            -0.0070930115
15        frac_forward         post_tone_on            -0.0083938083
16        frac_forward           pre_air_on            -0.0063202404
17        frac_forward          post_air_on            -0.0077135012
18        frac_forward         pre_tone_off            -0.0079999699
19        frac_forward        post_tone_off            -0.0047620505
20        frac_forward       pre_air_on_mid            -0.0050816363
21        frac_forward      post_air_on_mid            -0.0051732339
22        frac_forward          pre_air_off             0.0010751111
23        frac_forward         post_air_off            -0.0046241377
24        frac_forward      pre_air_off_mid             0.0032489120
25        frac_forward     post_air_off_mid             0.0007452261
26        frac_forward     pre_tone_on_next            -0.0070114383
27 mean_speed_path_cms          pre_tone_on            -0.0395067049
28 mean_speed_path_cms         post_tone_on            -0.0396162874
29 mean_speed_path_cms           pre_air_on            -0.0352255272
30 mean_speed_path_cms          post_air_on            -0.0810417761
31 mean_speed_path_cms         pre_tone_off            -0.0917424796
32 mean_speed_path_cms        post_tone_off            -0.0534551309
33 mean_speed_path_cms       pre_air_on_mid             0.0103762974
34 mean_speed_path_cms      post_air_on_mid            -0.0109647589
35 mean_speed_path_cms          pre_air_off            -0.1035884175
36 mean_speed_path_cms         post_air_off            -0.0684769454
37 mean_speed_path_cms      pre_air_off_mid            -0.0028540639
38 mean_speed_path_cms     post_air_off_mid            -0.0142829750
39 mean_speed_path_cms     pre_tone_on_next            -0.0369515978
40  mean_speed_net_cms          pre_tone_on            -0.0510124891
41  mean_speed_net_cms         post_tone_on            -0.0540203463
42  mean_speed_net_cms           pre_air_on            -0.0453993552
43  mean_speed_net_cms          post_air_on            -0.0933579581
44  mean_speed_net_cms         pre_tone_off            -0.0958216374
45  mean_speed_net_cms        post_tone_off            -0.0574804208
46  mean_speed_net_cms       pre_air_on_mid             0.0120339197
47  mean_speed_net_cms      post_air_on_mid            -0.0064823234
48  mean_speed_net_cms          pre_air_off            -0.0955837022
49  mean_speed_net_cms         post_air_off            -0.0709636377
50  mean_speed_net_cms      pre_air_off_mid            -0.0142154657
51  mean_speed_net_cms     post_air_off_mid            -0.0172721141
52  mean_speed_net_cms     pre_tone_on_next            -0.0490243837
53    distance_path_cm          pre_tone_on            -0.0395319433
54    distance_path_cm         post_tone_on            -0.0394891400
55    distance_path_cm           pre_air_on            -0.0348735968
56    distance_path_cm          post_air_on            -0.0810445718
57    distance_path_cm         pre_tone_off            -0.0916440077
58    distance_path_cm        post_tone_off            -0.0535334834
59    distance_path_cm       pre_air_on_mid             0.0101439392
60    distance_path_cm      post_air_on_mid            -0.0114558250
61    distance_path_cm          pre_air_off            -0.1041513634
62    distance_path_cm         post_air_off            -0.0685989575
63    distance_path_cm      pre_air_off_mid            -0.0026967501
64    distance_path_cm     post_air_off_mid            -0.0143439585
65    distance_path_cm     pre_tone_on_next            -0.0369438067
66     distance_net_cm          pre_tone_on            -0.0510433838
67     distance_net_cm         post_tone_on            -0.0541086068
68     distance_net_cm           pre_air_on            -0.0452422092
69     distance_net_cm          post_air_on            -0.0935161453
70     distance_net_cm         pre_tone_off            -0.0957356616
71     distance_net_cm        post_tone_off            -0.0574735285
72     distance_net_cm       pre_air_on_mid             0.0121254911
73     distance_net_cm      post_air_on_mid            -0.0065885152
74     distance_net_cm          pre_air_off            -0.0956233334
75     distance_net_cm         post_air_off            -0.0710660155
76     distance_net_cm      pre_air_off_mid            -0.0142457921
77     distance_net_cm     post_air_off_mid            -0.0173434734
78     distance_net_cm     pre_tone_on_next            -0.0490381842
            SE  df    asymp.LCL     asymp.UCL     z.ratio      p.value
1  0.003059616 Inf -0.010980749  1.012724e-03 -1.62896700 0.1033200059
2  0.003059616 Inf -0.010612224  1.381248e-03 -1.50851900 0.1314217488
3  0.003059616 Inf -0.009404027  2.589445e-03 -1.11363377 0.2654363329
4  0.003059616 Inf -0.010623239  1.370233e-03 -1.51211908 0.1305035716
5  0.003059616 Inf -0.013063782 -1.070310e-03 -2.30978247 0.0209002003
6  0.003059616 Inf -0.009778821  2.214652e-03 -1.23613070 0.2164099845
7  0.003059616 Inf -0.011570898  4.225744e-04 -1.82185043 0.0684776829
8  0.003059616 Inf -0.012095740 -1.022677e-04 -1.99338901 0.0462188668
9  0.003059616 Inf -0.005858872  6.134600e-03  0.04505922 0.9640601028
10 0.003059616 Inf -0.010085676  1.907797e-03 -1.33642265 0.1814111676
11 0.003059616 Inf  0.000452281  1.244575e-02  2.10778682 0.0350494338
12 0.003059616 Inf -0.004284594  7.708879e-03  0.55959397 0.5757564209
13 0.003059616 Inf -0.010628198  1.365274e-03 -1.51373993 0.1300918135
14 0.003182701 Inf -0.013330992 -8.550315e-04 -2.22861360 0.0258396256
15 0.003182701 Inf -0.014631788 -2.155828e-03 -2.63732201 0.0083563466
16 0.003182701 Inf -0.012558220 -8.226036e-05 -1.98581007 0.0470544176
17 0.003182701 Inf -0.013951481 -1.475521e-03 -2.42357054 0.0153687683
18 0.003182701 Inf -0.014237950 -1.761990e-03 -2.51357856 0.0119513156
19 0.003182701 Inf -0.011000031  1.475930e-03 -1.49622914 0.1345939541
20 0.003182701 Inf -0.011319616  1.156344e-03 -1.59664252 0.1103454141
21 0.003182701 Inf -0.011411214  1.064746e-03 -1.62542236 0.1040725956
22 0.003182701 Inf -0.005162869  7.313091e-03  0.33779831 0.7355151813
23 0.003182701 Inf -0.010862118  1.613842e-03 -1.45289716 0.1462523108
24 0.003182701 Inf -0.002989068  9.486892e-03  1.02080330 0.3073476427
25 0.003182701 Inf -0.005492754  6.983206e-03  0.23414892 0.8148693699
26 0.003182701 Inf -0.013249418 -7.734583e-04 -2.20298342 0.0275959173
27 0.029670304 Inf -0.097659433  1.864602e-02 -1.33152342 0.1830168454
28 0.029670304 Inf -0.097769015  1.853644e-02 -1.33521676 0.1818054146
29 0.029670304 Inf -0.093378255  2.292720e-02 -1.18723175 0.2351362209
30 0.029670304 Inf -0.139194504 -2.288905e-02 -2.73141035 0.0063063896
31 0.029670304 Inf -0.149895207 -3.358975e-02 -3.09206400 0.0019876999
32 0.029670304 Inf -0.111607859  4.697597e-03 -1.80163744 0.0716024672
33 0.029670304 Inf -0.047776430  6.852903e-02  0.34971995 0.7265488788
34 0.029670304 Inf -0.069117487  4.718797e-02 -0.36955330 0.7117153505
35 0.029670304 Inf -0.161741145 -4.543569e-02 -3.49131632 0.0004806468
36 0.029670304 Inf -0.126629673 -1.032422e-02 -2.30792865 0.0210031051
37 0.029670304 Inf -0.061006792  5.529866e-02 -0.09619261 0.9233676019
38 0.029670304 Inf -0.072435703  4.386975e-02 -0.48138957 0.6302396476
39 0.029670304 Inf -0.095104326  2.120113e-02 -1.24540677 0.2129822656
40 0.031197520 Inf -0.112158505  1.013353e-02 -1.63514564 0.1020185207
41 0.031197520 Inf -0.115166362  7.125670e-03 -1.73155898 0.0833521147
42 0.031197520 Inf -0.106545371  1.574666e-02 -1.45522320 0.1456074799
43 0.031197520 Inf -0.154503974 -3.221194e-02 -2.99248009 0.0027672071
44 0.031197520 Inf -0.156967653 -3.467562e-02 -3.07145045 0.0021302152
45 0.031197520 Inf -0.118626437  3.665595e-03 -1.84246762 0.0654067788
46 0.031197520 Inf -0.049112096  7.317994e-02  0.38573321 0.6996942634
47 0.031197520 Inf -0.067628339  5.466369e-02 -0.20778329 0.8353981794
48 0.031197520 Inf -0.156729718 -3.443769e-02 -3.06382371 0.0021852764
49 0.031197520 Inf -0.132109654 -9.817622e-03 -2.27465636 0.0229265524
50 0.031197520 Inf -0.075361482  4.693055e-02 -0.45566012 0.6486344069
51 0.031197520 Inf -0.078418130  4.387390e-02 -0.55363740 0.5798270217
52 0.031197520 Inf -0.110170400  1.212163e-02 -1.57141925 0.1160852979
53 0.029663205 Inf -0.097670756  1.860687e-02 -1.33269294 0.1826325911
54 0.029663205 Inf -0.097627953  1.864967e-02 -1.33124996 0.1831067762
55 0.029663205 Inf -0.093012409  2.326522e-02 -1.17565170 0.2397340881
56 0.029663205 Inf -0.139183384 -2.290576e-02 -2.73215834 0.0062920893
57 0.029663205 Inf -0.149782820 -3.350520e-02 -3.08948440 0.0020050424
58 0.029663205 Inf -0.111672296  4.605329e-03 -1.80471005 0.0711200662
59 0.029663205 Inf -0.047994873  6.828275e-02  0.34197044 0.7323731349
60 0.029663205 Inf -0.069594638  4.668299e-02 -0.38619647 0.6993511662
61 0.029663205 Inf -0.162290176 -4.601255e-02 -3.51112986 0.0004462064
62 0.029663205 Inf -0.126737770 -1.046014e-02 -2.31259429 0.0207449556
63 0.029663205 Inf -0.060835563  5.544206e-02 -0.09091230 0.9275622774
64 0.029663205 Inf -0.072482771  4.379485e-02 -0.48356065 0.6286977066
65 0.029663205 Inf -0.095082619  2.119501e-02 -1.24544220 0.2129692493
66 0.031201705 Inf -0.112197602  1.011083e-02 -1.63591650 0.1018570637
67 0.031201705 Inf -0.115262824  7.045611e-03 -1.73415546 0.0828905034
68 0.031201705 Inf -0.106396427  1.591201e-02 -1.44999158 0.1470608682
69 0.031201705 Inf -0.154670363 -3.236193e-02 -2.99714858 0.0027251786
70 0.031201705 Inf -0.156889879 -3.458144e-02 -3.06828303 0.0021529260
71 0.031201705 Inf -0.118627746  3.680689e-03 -1.84199962 0.0654752051
72 0.031201705 Inf -0.049028727  7.327971e-02  0.38861630 0.6975600068
73 0.031201705 Inf -0.067742733  5.456570e-02 -0.21115882 0.8327633423
74 0.031201705 Inf -0.156777551 -3.446912e-02 -3.06468297 0.0021790084
75 0.031201705 Inf -0.132220233 -9.911798e-03 -2.27763245 0.0227484852
76 0.031201705 Inf -0.075400010  4.690843e-02 -0.45657095 0.6479794620
77 0.031201705 Inf -0.078497691  4.381074e-02 -0.55585018 0.5783132754
78 0.031201705 Inf -0.110192402  1.211603e-02 -1.57165079 0.1160315595
               outcome tone_air_cycle_epoch cycle_session_10m_c.trend
1          frac_moving          pre_tone_on              -0.003861813
2          frac_moving         post_tone_on              -0.004520578
3          frac_moving           pre_air_on              -0.003851215
4          frac_moving          post_air_on               0.012366548
5          frac_moving         pre_tone_off              -0.005229477
6          frac_moving        post_tone_off              -0.015193926
7          frac_moving       pre_air_on_mid              -0.042992605
8          frac_moving      post_air_on_mid              -0.044545293
9          frac_moving          pre_air_off              -0.009843285
10         frac_moving         post_air_off              -0.005877663
11         frac_moving      pre_air_off_mid               0.092666476
12         frac_moving     post_air_off_mid               0.063802713
13         frac_moving     pre_tone_on_next              -0.003339183
14        frac_forward          pre_tone_on              -0.001094647
15        frac_forward         post_tone_on               0.002430872
16        frac_forward           pre_air_on              -0.004996492
17        frac_forward          post_air_on               0.049218888
18        frac_forward         pre_tone_off              -0.007449335
19        frac_forward        post_tone_off              -0.013192360
20        frac_forward       pre_air_on_mid              -0.044385090
21        frac_forward      post_air_on_mid              -0.042995806
22        frac_forward          pre_air_off              -0.013636623
23        frac_forward         post_air_off              -0.034596547
24        frac_forward      pre_air_off_mid               0.095026894
25        frac_forward     post_air_off_mid               0.066884786
26        frac_forward     pre_tone_on_next               0.001836263
27 mean_speed_path_cms          pre_tone_on              -0.099172820
28 mean_speed_path_cms         post_tone_on              -0.128250943
29 mean_speed_path_cms           pre_air_on              -0.163851036
30 mean_speed_path_cms          post_air_on              -0.395081324
31 mean_speed_path_cms         pre_tone_off              -0.864277735
32 mean_speed_path_cms        post_tone_off               0.195538596
33 mean_speed_path_cms       pre_air_on_mid              -0.343227460
34 mean_speed_path_cms      post_air_on_mid              -0.256644469
35 mean_speed_path_cms          pre_air_off              -0.628080528
36 mean_speed_path_cms         post_air_off              -0.484941119
37 mean_speed_path_cms      pre_air_off_mid               0.223148671
38 mean_speed_path_cms     post_air_off_mid               0.094823478
39 mean_speed_path_cms     pre_tone_on_next              -0.069626399
40  mean_speed_net_cms          pre_tone_on              -0.100294351
41  mean_speed_net_cms         post_tone_on              -0.108693324
42  mean_speed_net_cms           pre_air_on              -0.161615258
43  mean_speed_net_cms          post_air_on              -0.299402589
44  mean_speed_net_cms         pre_tone_off              -0.870703599
45  mean_speed_net_cms        post_tone_off               0.198119476
46  mean_speed_net_cms       pre_air_on_mid              -0.353352041
47  mean_speed_net_cms      post_air_on_mid              -0.254833452
48  mean_speed_net_cms          pre_air_off              -0.651355220
49  mean_speed_net_cms         post_air_off              -0.616290464
50  mean_speed_net_cms      pre_air_off_mid               0.218002672
51  mean_speed_net_cms     post_air_off_mid               0.094187258
52  mean_speed_net_cms     pre_tone_on_next              -0.059770824
53    distance_path_cm          pre_tone_on              -0.100534509
54    distance_path_cm         post_tone_on              -0.128864143
55    distance_path_cm           pre_air_on              -0.163901653
56    distance_path_cm          post_air_on              -0.397858767
57    distance_path_cm         pre_tone_off              -0.865007900
58    distance_path_cm        post_tone_off               0.195934459
59    distance_path_cm       pre_air_on_mid              -0.346009835
60    distance_path_cm      post_air_on_mid              -0.256060369
61    distance_path_cm          pre_air_off              -0.628008829
62    distance_path_cm         post_air_off              -0.483751231
63    distance_path_cm      pre_air_off_mid               0.223461547
64    distance_path_cm     post_air_off_mid               0.094167068
65    distance_path_cm     pre_tone_on_next              -0.070962598
66     distance_net_cm          pre_tone_on              -0.100461520
67     distance_net_cm         post_tone_on              -0.108697044
68     distance_net_cm           pre_air_on              -0.161549379
69     distance_net_cm          post_air_on              -0.299122244
70     distance_net_cm         pre_tone_off              -0.871303118
71     distance_net_cm        post_tone_off               0.199256661
72     distance_net_cm       pre_air_on_mid              -0.355191968
73     distance_net_cm      post_air_on_mid              -0.253914596
74     distance_net_cm          pre_air_off              -0.652187270
75     distance_net_cm         post_air_off              -0.616173311
76     distance_net_cm      pre_air_off_mid               0.218823897
77     distance_net_cm     post_air_off_mid               0.094005700
78     distance_net_cm     pre_tone_on_next              -0.059847231
           SE  df   asymp.LCL    asymp.UCL      z.ratio      p.value
1  0.01142421 Inf -0.02625285  0.018529220  -0.33803777 7.353347e-01
2  0.01142421 Inf -0.02691161  0.017870455  -0.39570173 6.923251e-01
3  0.01142421 Inf -0.02624225  0.018539818  -0.33711007 7.360339e-01
4  0.01142421 Inf -0.01002449  0.034757582   1.08248639 2.790365e-01
5  0.01142421 Inf -0.02762051  0.017161557  -0.45775405 6.471292e-01
6  0.01142421 Inf -0.03758496  0.007197107  -1.32997648 1.835260e-01
7  0.01142421 Inf -0.06538364 -0.020601571  -3.76329018 1.676924e-04
8  0.01142421 Inf -0.06693633 -0.022154259  -3.89920231 9.651011e-05
9  0.01142421 Inf -0.03223432  0.012547749  -0.86161649 3.888986e-01
10 0.01142421 Inf -0.02826870  0.016513371  -0.51449201 6.069080e-01
11 0.01142421 Inf  0.07027544  0.115057510   8.11141457 4.440892e-16
12 0.01142421 Inf  0.04141168  0.086193746   5.58487034 2.338746e-08
13 0.01142421 Inf -0.02573022  0.019051850  -0.29229015 7.700648e-01
14 0.01131656 Inf -0.02327469  0.021085393  -0.09672972 9.229410e-01
15 0.01131656 Inf -0.01974917  0.024610912   0.21480670 8.299180e-01
16 0.01131656 Inf -0.02717653  0.017183548  -0.44152060 6.588361e-01
17 0.01131656 Inf  0.02703885  0.071398928   4.34928189 1.365841e-05
18 0.01131656 Inf -0.02962938  0.014730705  -0.65826883 5.103654e-01
19 0.01131656 Inf -0.03537240  0.008987681  -1.16575756 2.437125e-01
20 0.01131656 Inf -0.06656513 -0.022205050  -3.92213801 8.776670e-05
21 0.01131656 Inf -0.06517585 -0.020815766  -3.79937237 1.450630e-04
22 0.01131656 Inf -0.03581666  0.008543418  -1.20501536 2.281974e-01
23 0.01131656 Inf -0.05677659 -0.012416506  -3.05716241 2.234432e-03
24 0.01131656 Inf  0.07284685  0.117206934   8.39715741 0.000000e+00
25 0.01131656 Inf  0.04470475  0.089064826   5.91034868 3.413843e-09
26 0.01131656 Inf -0.02034378  0.024016303   0.16226341 8.710984e-01
27 0.08516014 Inf -0.26608364  0.067737996  -1.16454499 2.442032e-01
28 0.08516014 Inf -0.29516176  0.038659874  -1.50599724 1.320679e-01
29 0.08516014 Inf -0.33076185  0.003059781  -1.92403426 5.435029e-02
30 0.08516014 Inf -0.56199214 -0.228170507  -4.63927492 3.496337e-06
31 0.08516014 Inf -1.03118855 -0.697366918 -10.14885233 0.000000e+00
32 0.08516014 Inf  0.02862778  0.362449412   2.29612803 2.166856e-02
33 0.08516014 Inf -0.51013828 -0.176316644  -4.03037666 5.568754e-05
34 0.08516014 Inf -0.42355529 -0.089733652  -3.01366877 2.581094e-03
35 0.08516014 Inf -0.79499135 -0.461169711  -7.37528722 1.640910e-13
36 0.08516014 Inf -0.65185194 -0.318030302  -5.69446095 1.237623e-08
37 0.08516014 Inf  0.05623785  0.390059488   2.62034161 8.784173e-03
38 0.08516014 Inf -0.07208734  0.261734295   1.11347249 2.655056e-01
39 0.08516014 Inf -0.23653722  0.097284418  -0.81759371 4.135892e-01
40 0.08694576 Inf -0.27070490  0.070116198  -1.15352786 2.486938e-01
41 0.08694576 Inf -0.27910387  0.061717224  -1.25012801 2.112528e-01
42 0.08694576 Inf -0.33202581  0.008795291  -1.85880561 6.305470e-02
43 0.08694576 Inf -0.46981314 -0.128992040  -3.44355614 5.741174e-04
44 0.08694576 Inf -1.04111415 -0.700293050 -10.01433132 0.000000e+00
45 0.08694576 Inf  0.02770893  0.368530025   2.27865611 2.268752e-02
46 0.08694576 Inf -0.52376259 -0.182941492  -4.06405166 4.822814e-05
47 0.08694576 Inf -0.42524400 -0.084422904  -2.93094760 3.379298e-03
48 0.08694576 Inf -0.82176577 -0.480944671  -7.49151259 6.816769e-14

In [13]:
import numpy as np
import pandas as pd
from pathlib import Path

# --------------------------------------------------
# Identify anchor column
# --------------------------------------------------

anchor_col = "anchor_name" if "anchor_name" in encoder_epoch_df.columns else "epoch_name"
print("Using anchor column:", anchor_col)

print("\nPhases:")
print(encoder_epoch_df["phase"].value_counts())

print("\nAnchors by phase:")
display(
    encoder_epoch_df
    .groupby(["phase", anchor_col])
    .size()
    .reset_index(name="n")
    .sort_values(["phase", anchor_col])
)

# --------------------------------------------------
# Detect air and tone-air phases
# --------------------------------------------------

phases = encoder_epoch_df["phase"].dropna().astype(str).unique().tolist()

air_phase_candidates = [
    p for p in phases
    if ("air" in p.lower()) and ("tone" not in p.lower())
]

tone_air_phase_candidates = [
    p for p in phases
    if ("tone" in p.lower()) and ("air" in p.lower())
]

print("Air phase candidates:", air_phase_candidates)
print("Tone-air phase candidates:", tone_air_phase_candidates)

air_phase = air_phase_candidates[0]
tone_air_phase = tone_air_phase_candidates[0]

print("Using air phase:", air_phase)
print("Using tone-air phase:", tone_air_phase)

# --------------------------------------------------
# Helper to find anchors
# --------------------------------------------------

def find_anchor(df, phase, candidates, anchor_col):
    available = (
        df.loc[df["phase"] == phase, anchor_col]
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    for c in candidates:
        if c in available:
            return c

    raise ValueError(
        f"No anchor found for phase={phase}. "
        f"Tried {candidates}. Available anchors: {available}"
    )

tone_on_anchor = find_anchor(
    encoder_epoch_df,
    tone_air_phase,
    candidates=[
        "tone_on",
        "tone_onset",
        "tone_on_3s_before_air",
        "Tone_on",
        "Tone_ON",
    ],
    anchor_col=anchor_col,
)

pseudo_tone_on_anchor = find_anchor(
    encoder_epoch_df,
    air_phase,
    candidates=[
        "pseudo_tone_on",
        "pseudo_tone",
        "pseudo_tone_onset",
        "pseudo_tone_ON",
        "matched_pseudo_tone_on",
    ],
    anchor_col=anchor_col,
)

print("tone_on anchor:", tone_on_anchor)
print("pseudo_tone_on anchor:", pseudo_tone_on_anchor)

Using anchor column: anchor_name

Phases:
phase
air_training         42362
habituation          38237
tone_air_training    21262
Name: count, dtype: int64

Anchors by phase:

                phase      anchor_name     n
0        air_training          air_off  7060
1        air_training      air_off_mid  7033
2        air_training           air_on  7067
3        air_training       air_on_mid  7069
4        air_training  pseudo_tone_off  7070
5        air_training   pseudo_tone_on  7063
6         habituation          LED_off  6373
7         habituation      LED_off_mid  6327
8         habituation           LED_on  6390
9         habituation       LED_on_mid  6386
10        habituation  pseudo_tone_off  6381
11        habituation   pseudo_tone_on  6380
12  tone_air_training          air_off  3543
13  tone_air_training      air_off_mid  3520
14  tone_air_training           air_on  3550
15  tone_air_training       air_on_mid  3550
16  tone_air_training         tone_off  3549
17  tone_air_training          tone_on  3550

Air phase candidates: ['air_training']
Tone-air phase candidates: ['tone_air_training']
Using air phase: air_training
Using tone-air phase: tone_air_training
tone_on anchor: tone_on
pseudo_tone_on anchor: pseudo_tone_on

In [14]:
def prepare_cue_on_vs_pseudo_df(
    encoder_epoch_df,
    air_phase,
    tone_air_phase,
    pseudo_tone_on_anchor,
    tone_on_anchor,
    anchor_col,
    require_good_session=True,
    require_valid_window=True,
    require_complete_prepost=True,
):
    """
    Builds dataframe comparing:
        pseudo-tone-on during air training
        real tone-on during tone-air training

    One row = one pre or post window around cue/pseudo-cue onset.
    """

    df = encoder_epoch_df.copy()

    # --------------------------------------------------
    # Pseudo-tone-on from air training
    # --------------------------------------------------

    pseudo_df = df[
        (df["phase"] == air_phase) &
        (df[anchor_col].astype(str) == pseudo_tone_on_anchor) &
        (df["window_position"].isin(["pre", "post"]))
    ].copy()

    pseudo_df["cue_type"] = "pseudo_tone_on"

    # --------------------------------------------------
    # Real tone-on from tone-air training
    # --------------------------------------------------

    tone_df = df[
        (df["phase"] == tone_air_phase) &
        (df[anchor_col].astype(str) == tone_on_anchor) &
        (df["window_position"].isin(["pre", "post"]))
    ].copy()

    tone_df["cue_type"] = "tone_on"

    # --------------------------------------------------
    # Combine
    # --------------------------------------------------

    cue_df = pd.concat([pseudo_df, tone_df], ignore_index=True)

    # --------------------------------------------------
    # Optional filters
    # --------------------------------------------------

    if require_good_session and "good_session_basic" in cue_df.columns:
        cue_df = cue_df[cue_df["good_session_basic"] == True].copy()

    if require_valid_window and "valid_window" in cue_df.columns:
        cue_df = cue_df[cue_df["valid_window"] == True].copy()

    # --------------------------------------------------
    # IDs
    # --------------------------------------------------

    cue_df["animal_day"] = (
        cue_df["animal"].astype(str) + ":" +
        cue_df["date"].astype(str)
    )

    trial_col = "event_number"

    if trial_col not in cue_df.columns:
        raise ValueError("event_number column not found.")

    cue_df["cue_event_id"] = (
        cue_df["cue_type"].astype(str) + ":" +
        cue_df["animal"].astype(str) + ":" +
        cue_df["date"].astype(str) + ":" +
        cue_df[trial_col].astype(str)
    )

    # --------------------------------------------------
    # Session time
    # --------------------------------------------------

    if "session_time_min" not in cue_df.columns:
        if "anchor_session_time_min" in cue_df.columns:
            cue_df["session_time_min"] = cue_df["anchor_session_time_min"]
        elif "anchor_time_s" in cue_df.columns:
            cue_df["session_time_min"] = cue_df["anchor_time_s"] / 60.0
        elif "session_time_s" in cue_df.columns:
            cue_df["session_time_min"] = cue_df["session_time_s"] / 60.0
        else:
            cue_df["session_time_min"] = np.nan

    # Centered and scaled in 10-min units
    cue_df["session_time_10m_c"] = (
        cue_df["session_time_min"] -
        cue_df["session_time_min"].mean()
    ) / 10.0

    # --------------------------------------------------
    # Phase/session number
    # --------------------------------------------------

    if "phase_session_number" in cue_df.columns:
        cue_df["phase_session"] = cue_df["phase_session_number"]
    elif "phase_day_number_good" in cue_df.columns:
        cue_df["phase_session"] = cue_df["phase_day_number_good"]
    elif "phase_day" in cue_df.columns:
        cue_df["phase_session"] = cue_df["phase_day"]
    else:
        raise ValueError(
            "Could not find phase session/day column. "
            "Expected phase_session_number, phase_day_number_good, or phase_day."
        )

    # Important:
    # Center session WITHIN cue type because pseudo-tone and real tone
    # come from different behavioral phases.
    cue_df["phase_session_c"] = (
        cue_df["phase_session"] -
        cue_df.groupby("cue_type")["phase_session"].transform("mean")
    )

    # --------------------------------------------------
    # Ordered factors
    # --------------------------------------------------

    cue_df["cue_type"] = pd.Categorical(
        cue_df["cue_type"],
        categories=["pseudo_tone_on", "tone_on"],
        ordered=True,
    )

    cue_df["window_position"] = pd.Categorical(
        cue_df["window_position"],
        categories=["pre", "post"],
        ordered=True,
    )

    # --------------------------------------------------
    # Keep only events that have both pre and post rows
    # --------------------------------------------------

    if require_complete_prepost:
        counts = (
            cue_df
            .groupby("cue_event_id")["window_position"]
            .nunique()
        )

        complete_event_ids = counts[counts == 2].index

        cue_df = cue_df[
            cue_df["cue_event_id"].isin(complete_event_ids)
        ].copy()

    return cue_df.reset_index(drop=True)


cue_on_df = prepare_cue_on_vs_pseudo_df(
    encoder_epoch_df=encoder_epoch_df,
    air_phase=air_phase,
    tone_air_phase=tone_air_phase,
    pseudo_tone_on_anchor=pseudo_tone_on_anchor,
    tone_on_anchor=tone_on_anchor,
    anchor_col=anchor_col,
)

print("cue_on_df shape:", cue_on_df.shape)

display(
    cue_on_df
    .groupby(["cue_type", "window_position"])
    .size()
    .reset_index(name="n_windows")
)

display(
    cue_on_df
    .groupby(["cue_type", "animal"])["cue_event_id"]
    .nunique()
    .reset_index(name="n_events")
)

display(
    cue_on_df[
        [
            "animal",
            "date",
            "phase",
            "cue_type",
            anchor_col,
            "event_number",
            "window_position",
            "phase_session",
            "phase_session_c",
            "session_time_min",
            "session_time_10m_c",
            "cue_event_id",
        ]
    ].head(20)
)

cue_on_df shape: (10594, 66)

         cue_type window_position  n_windows
0  pseudo_tone_on             pre       3531
1  pseudo_tone_on            post       3531
2         tone_on             pre       1766
3         tone_on            post       1766

         cue_type  animal  n_events
0  pseudo_tone_on  NML_04       800
1  pseudo_tone_on  NML_05       440
2  pseudo_tone_on  NML_06       634
3  pseudo_tone_on  NML_07       813
4  pseudo_tone_on  NML_08       844
5         tone_on  NML_04       307
6         tone_on  NML_05       180
7         tone_on  NML_06       446
8         tone_on  NML_07       355
9         tone_on  NML_08       478

,animal,date,phase,cue_type,anchor_name,event_number,window_position,phase_session,phase_session_c,session_time_min,session_time_10m_c,cue_event_id
0,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,1,post,1,-7.118788,0.282607,-0.976135,pseudo_tone_on:NML_04:2026_01_12:1
1,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,1,pre,1,-7.118788,0.282607,-0.976135,pseudo_tone_on:NML_04:2026_01_12:1
2,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,2,post,1,-7.118788,0.601090,-0.944287,pseudo_tone_on:NML_04:2026_01_12:2
3,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,2,pre,1,-7.118788,0.601090,-0.944287,pseudo_tone_on:NML_04:2026_01_12:2
4,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,3,post,1,-7.118788,0.889413,-0.915455,pseudo_tone_on:NML_04:2026_01_12:3
5,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,3,pre,1,-7.118788,0.889413,-0.915455,pseudo_tone_on:NML_04:2026_01_12:3
6,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,4,post,1,-7.118788,1.171443,-0.887252,pseudo_tone_on:NML_04:2026_01_12:4
7,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,4,pre,1,-7.118788,1.171443,-0.887252,pseudo_tone_on:NML_04:2026_01_12:4
8,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,5,post,1,-7.118788,1.458487,-0.858547,pseudo_tone_on:NML_04:2026_01_12:5
9,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,5,pre,1,-7.118788,1.458487,-0.858547,pseudo_tone_on:NML_04:2026_01_12:5
10,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,6,post,1,-7.118788,1.897493,-0.814647,pseudo_tone_on:NML_04:2026_01_12:6
11,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,6,pre,1,-7.118788,1.897493,-0.814647,pseudo_tone_on:NML_04:2026_01_12:6
12,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,7,post,1,-7.118788,2.169347,-0.787461,pseudo_tone_on:NML_04:2026_01_12:7
13,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,7,pre,1,-7.118788,2.169347,-0.787461,pseudo_tone_on:NML_04:2026_01_12:7
14,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,8,post,1,-7.118788,2.452110,-0.759185,pseudo_tone_on:NML_04:2026_01_12:8
15,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,8,pre,1,-7.118788,2.452110,-0.759185,pseudo_tone_on:NML_04:2026_01_12:8
16,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,9,post,1,-7.118788,2.720740,-0.732322,pseudo_tone_on:NML_04:2026_01_12:9
17,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,9,pre,1,-7.118788,2.720740,-0.732322,pseudo_tone_on:NML_04:2026_01_12:9
18,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,10,post,1,-7.118788,3.013853,-0.703011,pseudo_tone_on:NML_04:2026_01_12:10
19,NML_04,2026_01_12,air_training,pseudo_tone_on,pseudo_tone_on,10,pre,1,-7.118788,3.013853,-0.703011,pseudo_tone_on:NML_04:2026_01_12:10

In [15]:
%%R -i cue_on_df -o cue_on_model_info_R -o cue_on_prepost_R -o cue_on_difference_of_differences_R -o cue_on_window_cue_diffs_R -o cue_on_phase_session_response_trends_R -o cue_on_session_time_response_trends_R -o cue_on_fixed_R -o cue_on_r2_R

library(lme4)
library(lmerTest)
library(emmeans)
library(broom.mixed)
library(dplyr)
library(performance)

emm_options(lmer.df = "asymptotic")

# --------------------------------------------------
# Prepare factors
# --------------------------------------------------

cue_on_df$animal <- factor(cue_on_df$animal)
cue_on_df$animal_day <- factor(cue_on_df$animal_day)
cue_on_df$cue_event_id <- factor(cue_on_df$cue_event_id)

cue_on_df$cue_type <- factor(
  as.character(cue_on_df$cue_type),
  levels = c("pseudo_tone_on", "tone_on")
)

cue_on_df$window_position <- factor(
  as.character(cue_on_df$window_position),
  levels = c("pre", "post")
)

# --------------------------------------------------
# Outcomes
# --------------------------------------------------

cue_outcomes_R <- c(
  "frac_moving",
  "frac_forward",
  "mean_speed_path_cms",
  "mean_speed_net_cms",
  "distance_path_cm",
  "distance_net_cm"
)

cue_outcomes_R <- cue_outcomes_R[cue_outcomes_R %in% names(cue_on_df)]

print(cue_outcomes_R)

# --------------------------------------------------
# Function to fit one outcome
# --------------------------------------------------

fit_cue_on_outcome <- function(outcome_name) {

  cat("\n\n==============================\n")
  cat("Fitting outcome:", outcome_name, "\n")
  cat("==============================\n")

  formula_text <- paste0(
    outcome_name,
    " ~ cue_type * window_position * phase_session_c + ",
    "cue_type * window_position * session_time_10m_c + ",
    "(1 | animal) + (1 | animal_day) + (1 | cue_event_id)"
  )

  m <- lmer(
    as.formula(formula_text),
    data = cue_on_df,
    REML = FALSE,
    control = lmerControl(
      optimizer = "bobyqa",
      optCtrl = list(maxfun = 2e5)
    )
  )

  # --------------------------------------------------
  # Model info
  # --------------------------------------------------

  model_info <- data.frame(
    outcome = outcome_name,
    n_obs = nobs(m),
    n_animals = nlevels(cue_on_df$animal),
    n_animal_day = nlevels(cue_on_df$animal_day),
    n_events = nlevels(cue_on_df$cue_event_id),
    AIC = AIC(m),
    BIC = BIC(m),
    logLik = as.numeric(logLik(m)),
    singular = isSingular(m),
    stringsAsFactors = FALSE
  )

  # --------------------------------------------------
  # Fixed effects
  # --------------------------------------------------

  fixed_df <- broom.mixed::tidy(
    m,
    effects = "fixed",
    conf.int = TRUE
  )
  fixed_df$outcome <- outcome_name

  # --------------------------------------------------
  # Estimated marginal means at reference:
  # phase_session_c = 0
  # session_time_10m_c = 0
  # --------------------------------------------------

  emm <- emmeans(
    m,
    ~ window_position | cue_type,
    at = list(
      phase_session_c = 0,
      session_time_10m_c = 0
    ),
    lmer.df = "asymptotic"
  )

  # Pre/post effect separately for pseudo-tone and real tone
  prepost <- as.data.frame(
    contrast(
      emm,
      method = list(post_minus_pre = c(-1, 1)),
      by = "cue_type",
      adjust = "none"
    )
  )
  prepost$outcome <- outcome_name

  # Difference-of-differences:
  # (tone post-pre) - (pseudo post-pre)
  did <- as.data.frame(
    contrast(
      contrast(
        emm,
        method = list(post_minus_pre = c(-1, 1)),
        by = "cue_type",
        adjust = "none"
      ),
      method = list(tone_minus_pseudo = c(-1, 1)),
      by = NULL,
      adjust = "none"
    )
  )
  did$outcome <- outcome_name

  # Tone vs pseudo separately at pre and post windows
  emm2 <- emmeans(
    m,
    ~ cue_type | window_position,
    at = list(
      phase_session_c = 0,
      session_time_10m_c = 0
    ),
    lmer.df = "asymptotic"
  )

  cue_diffs <- as.data.frame(
    contrast(
      emm2,
      method = list(tone_minus_pseudo = c(-1, 1)),
      by = "window_position",
      adjust = "none"
    )
  )
  cue_diffs$outcome <- outcome_name

  # --------------------------------------------------
  # Does post-pre response change across phase session?
  # --------------------------------------------------

  trend_phase <- emtrends(
    m,
    ~ window_position | cue_type,
    var = "phase_session_c",
    at = list(
      session_time_10m_c = 0
    ),
    lmer.df = "asymptotic"
  )

  phase_response_trends <- as.data.frame(
    contrast(
      trend_phase,
      method = list(post_minus_pre_slope = c(-1, 1)),
      by = "cue_type",
      adjust = "none"
    )
  )
  phase_response_trends$outcome <- outcome_name

  # Difference in phase-session response slope:
  # tone response slope - pseudo response slope
  phase_response_did <- as.data.frame(
    contrast(
      contrast(
        trend_phase,
        method = list(post_minus_pre_slope = c(-1, 1)),
        by = "cue_type",
        adjust = "none"
      ),
      method = list(tone_minus_pseudo_slope = c(-1, 1)),
      by = NULL,
      adjust = "none"
    )
  )
  phase_response_did$outcome <- outcome_name
  phase_response_did$cue_type <- "tone_minus_pseudo"

  phase_response_trends <- bind_rows(
    phase_response_trends,
    phase_response_did
  )

  # --------------------------------------------------
  # Does post-pre response change across within-session time?
  # --------------------------------------------------

  trend_time <- emtrends(
    m,
    ~ window_position | cue_type,
    var = "session_time_10m_c",
    at = list(
      phase_session_c = 0
    ),
    lmer.df = "asymptotic"
  )

  session_time_response_trends <- as.data.frame(
    contrast(
      trend_time,
      method = list(post_minus_pre_slope = c(-1, 1)),
      by = "cue_type",
      adjust = "none"
    )
  )
  session_time_response_trends$outcome <- outcome_name

  # Difference in within-session-time response slope:
  # tone response slope - pseudo response slope
  session_time_response_did <- as.data.frame(
    contrast(
      contrast(
        trend_time,
        method = list(post_minus_pre_slope = c(-1, 1)),
        by = "cue_type",
        adjust = "none"
      ),
      method = list(tone_minus_pseudo_slope = c(-1, 1)),
      by = NULL,
      adjust = "none"
    )
  )
  session_time_response_did$outcome <- outcome_name
  session_time_response_did$cue_type <- "tone_minus_pseudo"

  session_time_response_trends <- bind_rows(
    session_time_response_trends,
    session_time_response_did
  )

  # --------------------------------------------------
  # R2
  # --------------------------------------------------

  r2_obj <- performance::r2_nakagawa(m)

  r2_df <- data.frame(
    outcome = outcome_name,
    R2_marginal = r2_obj$R2_marginal,
    R2_conditional = r2_obj$R2_conditional,
    stringsAsFactors = FALSE
  )

  return(
    list(
      model = m,
      model_info = model_info,
      fixed = fixed_df,
      prepost = prepost,
      did = did,
      cue_diffs = cue_diffs,
      phase_response_trends = phase_response_trends,
      session_time_response_trends = session_time_response_trends,
      r2 = r2_df
    )
  )
}

# --------------------------------------------------
# Run all outcomes
# --------------------------------------------------

cue_on_models_R <- list()
model_info_list <- list()
fixed_list <- list()
prepost_list <- list()
did_list <- list()
cue_diffs_list <- list()
phase_response_trends_list <- list()
session_time_response_trends_list <- list()
r2_list <- list()

for (outcome_name in cue_outcomes_R) {

  result <- fit_cue_on_outcome(outcome_name)

  cue_on_models_R[[outcome_name]] <- result$model
  model_info_list[[outcome_name]] <- result$model_info
  fixed_list[[outcome_name]] <- result$fixed
  prepost_list[[outcome_name]] <- result$prepost
  did_list[[outcome_name]] <- result$did
  cue_diffs_list[[outcome_name]] <- result$cue_diffs
  phase_response_trends_list[[outcome_name]] <- result$phase_response_trends
  session_time_response_trends_list[[outcome_name]] <- result$session_time_response_trends
  r2_list[[outcome_name]] <- result$r2
}

# --------------------------------------------------
# Combine tables
# --------------------------------------------------

cue_on_model_info_R <- bind_rows(model_info_list) %>% relocate(outcome)
cue_on_fixed_R <- bind_rows(fixed_list) %>% relocate(outcome)
cue_on_prepost_R <- bind_rows(prepost_list) %>% relocate(outcome)
cue_on_difference_of_differences_R <- bind_rows(did_list) %>% relocate(outcome)
cue_on_window_cue_diffs_R <- bind_rows(cue_diffs_list) %>% relocate(outcome)
cue_on_phase_session_response_trends_R <- bind_rows(phase_response_trends_list) %>% relocate(outcome)
cue_on_session_time_response_trends_R <- bind_rows(session_time_response_trends_list) %>% relocate(outcome)
cue_on_r2_R <- bind_rows(r2_list) %>% relocate(outcome)

# --------------------------------------------------
# Print key outputs
# --------------------------------------------------

cat("\n\n=== Model info ===\n")
print(cue_on_model_info_R)

cat("\n\n=== Pre/post response within pseudo-tone and real tone ===\n")
print(cue_on_prepost_R)

cat("\n\n=== Difference-of-differences: tone response minus pseudo-tone response ===\n")
print(cue_on_difference_of_differences_R)

cat("\n\n=== Tone vs pseudo at pre and post windows ===\n")
print(cue_on_window_cue_diffs_R)

cat("\n\n=== Phase-session modulation of post-pre response ===\n")
print(cue_on_phase_session_response_trends_R)

cat("\n\n=== Within-session-time modulation of post-pre response ===\n")
print(cue_on_session_time_response_trends_R)

cat("\n\n=== R2 ===\n")
print(cue_on_r2_R)

[1] "frac_moving"         "frac_forward"        "mean_speed_path_cms"
[4] "mean_speed_net_cms"  "distance_path_cm"    "distance_net_cm"


==============================
Fitting outcome: frac_moving
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: frac_forward
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: mean_speed_path_cms
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: mean_speed_net_cms
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: distance_path_cm
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: distance_net_cm
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

=== Model info ===
              outcome n_obs n_animals n_animal_day n_events       AIC       BIC
1         frac_moving 10594         5          127     5297  4617.945  4734.233
2        frac_forward 10594         5          127     5297  3433.768  3550.057
3 mean_speed_path_cms 10594         5          127     5297 38481.964 38598.252
4  mean_speed_net_cms 10594         5          127     5297 38975.321 39091.610
5    distance_path_cm 10594         5          127     5297 38499.889 38616.178
6     distance_net_cm 10594         5          127     5297 38999.196 39115.484
      logLik singular
1  -2292.972    FALSE
2  -1700.884    FALSE
3 -19224.982    FALSE
4 -19471.660    FALSE
5 -19233.945    FALSE
6 -19483.598    FALSE


=== Pre/post response within pseudo-tone and real tone ===
               outcome       contrast       cue_type    estimate          SE
1          frac_moving post_minus_pre pseudo_tone_on -0.01454643 0.004685846
2          frac_moving post_minus_pre        tone_on  0.15097073 0.006646448
3         frac_forward post_minus_pre pseudo_tone_on -0.01479422 0.004325650
4         frac_forward post_minus_pre        tone_on  0.11533475 0.006135542
5  mean_speed_path_cms post_minus_pre pseudo_tone_on -0.06178554 0.020736154
6  mean_speed_path_cms post_minus_pre        tone_on  0.23050283 0.029412353
7   mean_speed_net_cms post_minus_pre pseudo_tone_on -0.06460280 0.021569977
8   mean_speed_net_cms post_minus_pre        tone_on  0.15867628 0.030595055
9     distance_path_cm post_minus_pre pseudo_tone_on -0.06150698 0.020768391
10    distance_path_cm post_minus_pre        tone_on  0.23485408 0.029458079
11     distance_net_cm post_minus_pre pseudo_tone_on -0.06420696 0.021619468
12     distance_net_cm post_minus_pre        tone_on  0.15887785 0.030665254
    df   z.ratio       p.value
1  Inf -3.104333  1.907083e-03
2  Inf 22.714498 3.221238e-114
3  Inf -3.420114  6.259479e-04
4  Inf 18.797808  7.870268e-79
5  Inf -2.979605  2.886205e-03
6  Inf  7.836939  4.616610e-15
7  Inf -2.995033  2.744149e-03
8  Inf  5.186337  2.144700e-07
9  Inf -2.961567  3.060779e-03
10 Inf  7.972485  1.555155e-15
11 Inf -2.969868  2.979279e-03
12 Inf  5.181038  2.206545e-07


=== Difference-of-differences: tone response minus pseudo-tone response ===
              outcome          contrast  estimate          SE  df   z.ratio
1         frac_moving tone_minus_pseudo 0.1655172 0.008132185 Inf 20.353345
2        frac_forward tone_minus_pseudo 0.1301290 0.007507072 Inf 17.334184
3 mean_speed_path_cms tone_minus_pseudo 0.2922884 0.035987145 Inf  8.122022
4  mean_speed_net_cms tone_minus_pseudo 0.2232791 0.037434226 Inf  5.964570
5    distance_path_cm tone_minus_pseudo 0.2963611 0.036043092 Inf  8.222410
6     distance_net_cm tone_minus_pseudo 0.2230848 0.037520117 Inf  5.945739
       p.value
1 4.336498e-92
2 2.597283e-67
3 4.584815e-16
4 2.452784e-09
5 1.994548e-16
6 2.752130e-09


=== Tone vs pseudo at pre and post windows ===
               outcome          contrast window_position    estimate         SE
1          frac_moving tone_minus_pseudo             pre -0.13392564 0.02819106
2          frac_moving tone_minus_pseudo            post  0.03159153 0.02819106
3         frac_forward tone_minus_pseudo             pre -0.14389441 0.02812045
4         frac_forward tone_minus_pseudo            post -0.01376545 0.02812045
5  mean_speed_path_cms tone_minus_pseudo             pre -0.94621314 0.22571253
6  mean_speed_path_cms tone_minus_pseudo            post -0.65392478 0.22571253
7   mean_speed_net_cms tone_minus_pseudo             pre -0.99187351 0.22659619
8   mean_speed_net_cms tone_minus_pseudo            post -0.76859443 0.22659619
9     distance_path_cm tone_minus_pseudo             pre -0.94615010 0.22567656
10    distance_path_cm tone_minus_pseudo            post -0.64978903 0.22567656
11     distance_net_cm tone_minus_pseudo             pre -0.99157571 0.22656021
12     distance_net_cm tone_minus_pseudo            post -0.76849090 0.22656021
    df    z.ratio      p.value
1  Inf -4.7506416 2.027723e-06
2  Inf  1.1206220 2.624488e-01
3  Inf -5.1170739 3.103121e-07
4  Inf -0.4895174 6.244754e-01
5  Inf -4.1921161 2.763645e-05
6  Inf -2.8971576 3.765606e-03
7  Inf -4.3772736 1.201731e-05
8  Inf -3.3919125 6.940661e-04
9  Inf -4.1925049 2.758911e-05
10 Inf -2.8792934 3.985674e-03
11 Inf -4.3766542 1.205149e-05
12 Inf -3.3919941 6.938594e-04


=== Phase-session modulation of post-pre response ===
               outcome                contrast          cue_type      estimate
1          frac_moving    post_minus_pre_slope    pseudo_tone_on  0.0009106147
2          frac_moving    post_minus_pre_slope           tone_on -0.0007683616
3          frac_moving tone_minus_pseudo_slope tone_minus_pseudo -0.0016789764
4         frac_forward    post_minus_pre_slope    pseudo_tone_on  0.0009210688
5         frac_forward    post_minus_pre_slope           tone_on -0.0019908863
6         frac_forward tone_minus_pseudo_slope tone_minus_pseudo -0.0029119551
7  mean_speed_path_cms    post_minus_pre_slope    pseudo_tone_on  0.0073868464
8  mean_speed_path_cms    post_minus_pre_slope           tone_on -0.0029845643
9  mean_speed_path_cms tone_minus_pseudo_slope tone_minus_pseudo -0.0103714107
10  mean_speed_net_cms    post_minus_pre_slope    pseudo_tone_on  0.0075920062
11  mean_speed_net_cms    post_minus_pre_slope           tone_on -0.0050154679
12  mean_speed_net_cms tone_minus_pseudo_slope tone_minus_pseudo -0.0126074741
13    distance_path_cm    post_minus_pre_slope    pseudo_tone_on  0.0073353955
14    distance_path_cm    post_minus_pre_slope           tone_on -0.0029285497
15    distance_path_cm tone_minus_pseudo_slope tone_minus_pseudo -0.0102639452
16     distance_net_cm    post_minus_pre_slope    pseudo_tone_on  0.0075770623
17     distance_net_cm    post_minus_pre_slope           tone_on -0.0051082397
18     distance_net_cm tone_minus_pseudo_slope tone_minus_pseudo -0.0126853020
             SE  df    z.ratio    p.value
1  0.0009623099 Inf  0.9462801 0.34400572
2  0.0023261035 Inf -0.3303213 0.74115716
3  0.0025172997 Inf -0.6669752 0.50478799
4  0.0008883381 Inf  1.0368449 0.29980817
5  0.0021472983 Inf -0.9271587 0.35384414
6  0.0023237974 Inf -1.2531019 0.21016861
7  0.0042584848 Inf  1.7346185 0.08280840
8  0.0102936449 Inf -0.2899424 0.77186029
9  0.0111397405 Inf -0.9310280 0.35183906
10 0.0044297231 Inf  1.7138783 0.08655108
11 0.0107075634 Inf -0.4684042 0.63949555
12 0.0115876814 Inf -1.0880066 0.27659218
13 0.0042651053 Inf  1.7198627 0.08545740
14 0.0103096479 Inf -0.2840591 0.77636506
15 0.0111570589 Inf -0.9199508 0.35759847
16 0.0044398868 Inf  1.7065890 0.08789846
17 0.0107321314 Inf -0.4759763 0.63409130
18 0.0116142688 Inf -1.0922170 0.27473773


=== Within-session-time modulation of post-pre response ===
               outcome                contrast          cue_type      estimate
1          frac_moving    post_minus_pre_slope    pseudo_tone_on  0.0017604743
2          frac_moving    post_minus_pre_slope           tone_on  0.0174577069
3          frac_moving tone_minus_pseudo_slope tone_minus_pseudo  0.0156972326
4         frac_forward    post_minus_pre_slope    pseudo_tone_on -0.0024843111
5         frac_forward    post_minus_pre_slope           tone_on  0.0203279178
6         frac_forward tone_minus_pseudo_slope tone_minus_pseudo  0.0228122288
7  mean_speed_path_cms    post_minus_pre_slope    pseudo_tone_on -0.0001996012
8  mean_speed_path_cms    post_minus_pre_slope           tone_on  0.0471764069
9  mean_speed_path_cms tone_minus_pseudo_slope tone_minus_pseudo  0.0473760081
10  mean_speed_net_cms    post_minus_pre_slope    pseudo_tone_on -0.0117480746
11  mean_speed_net_cms    post_minus_pre_slope           tone_on  0.0663454418
12  mean_speed_net_cms tone_minus_pseudo_slope tone_minus_pseudo  0.0780935164
13    distance_path_cm    post_minus_pre_slope    pseudo_tone_on -0.0006010729
14    distance_path_cm    post_minus_pre_slope           tone_on  0.0483931149
15    distance_path_cm tone_minus_pseudo_slope tone_minus_pseudo  0.0489941879
16     distance_net_cm    post_minus_pre_slope    pseudo_tone_on -0.0120616642
17     distance_net_cm    post_minus_pre_slope           tone_on  0.0663039925
18     distance_net_cm tone_minus_pseudo_slope tone_minus_pseudo  0.0783656567
            SE  df      z.ratio    p.value
1  0.007614051 Inf  0.231213895 0.81714864
2  0.010918330 Inf  1.598935703 0.10983489
3  0.013311036 Inf  1.179264495 0.23829287
4  0.007028766 Inf -0.353449085 0.72375179
5  0.010079049 Inf  2.016848859 0.04371129
6  0.012287831 Inf  1.856489538 0.06338381
7  0.033694260 Inf -0.005923892 0.99527345
8  0.048316598 Inf  0.976401660 0.32886546
9  0.058904981 Inf  0.804278466 0.42123617
10 0.035049142 Inf -0.335188647 0.73748279
11 0.050259461 Inf  1.320058764 0.18681540
12 0.061273614 Inf  1.274504818 0.20248457
13 0.033746643 Inf -0.017811340 0.98578936
14 0.048391714 Inf  1.000028949 0.31729650
15 0.058996558 Inf  0.830458408 0.40627965
16 0.035129561 Inf -0.343347992 0.73133668
17 0.050374779 Inf  1.316214069 0.18810220
18 0.061414203 Inf  1.276018451 0.20194900


=== R2 ===
                            outcome R2_marginal R2_conditional
Marginal R2...1         frac_moving  0.04822123      0.7502374
Marginal R2...2        frac_forward  0.04843222      0.7715588
Marginal R2...3 mean_speed_path_cms  0.09492267      0.8622306
Marginal R2...4  mean_speed_net_cms  0.09525115      0.8530174
Marginal R2...5    distance_path_cm  0.09486091      0.8618565
Marginal R2...6     distance_net_cm  0.09520440      0.8523648

In [16]:
import numpy as np
import pandas as pd
from pathlib import Path

# --------------------------------------------------
# Identify anchor column
# --------------------------------------------------

anchor_col = "anchor_name" if "anchor_name" in encoder_epoch_df.columns else "epoch_name"
print("Using anchor column:", anchor_col)

print("\nPhases:")
print(encoder_epoch_df["phase"].value_counts())

print("\nAnchors by phase:")
display(
    encoder_epoch_df
    .groupby(["phase", anchor_col])
    .size()
    .reset_index(name="n")
    .sort_values(["phase", anchor_col])
)

# --------------------------------------------------
# Detect tone-air phase
# --------------------------------------------------

phases = encoder_epoch_df["phase"].dropna().astype(str).unique().tolist()

tone_air_phase_candidates = [
    p for p in phases
    if ("tone" in p.lower()) and ("air" in p.lower())
]

print("Tone-air phase candidates:", tone_air_phase_candidates)

tone_air_phase = tone_air_phase_candidates[0]
print("Using tone-air phase:", tone_air_phase)

# --------------------------------------------------
# Find tone_on anchor
# --------------------------------------------------

def find_anchor(df, phase, candidates, anchor_col):
    available = (
        df.loc[df["phase"] == phase, anchor_col]
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    for c in candidates:
        if c in available:
            return c

    raise ValueError(
        f"No anchor found for phase={phase}. "
        f"Tried {candidates}. Available anchors: {available}"
    )


tone_on_anchor = find_anchor(
    encoder_epoch_df,
    tone_air_phase,
    candidates=[
        "tone_on",
        "tone_onset",
        "tone_on_3s_before_air",
        "Tone_on",
        "Tone_ON",
    ],
    anchor_col=anchor_col,
)

print("tone_on anchor:", tone_on_anchor)

Using anchor column: anchor_name

Phases:
phase
air_training         42362
habituation          38237
tone_air_training    21262
Name: count, dtype: int64

Anchors by phase:

                phase      anchor_name     n
0        air_training          air_off  7060
1        air_training      air_off_mid  7033
2        air_training           air_on  7067
3        air_training       air_on_mid  7069
4        air_training  pseudo_tone_off  7070
5        air_training   pseudo_tone_on  7063
6         habituation          LED_off  6373
7         habituation      LED_off_mid  6327
8         habituation           LED_on  6390
9         habituation       LED_on_mid  6386
10        habituation  pseudo_tone_off  6381
11        habituation   pseudo_tone_on  6380
12  tone_air_training          air_off  3543
13  tone_air_training      air_off_mid  3520
14  tone_air_training           air_on  3550
15  tone_air_training       air_on_mid  3550
16  tone_air_training         tone_off  3549
17  tone_air_training          tone_on  3550

Tone-air phase candidates: ['tone_air_training']
Using tone-air phase: tone_air_training
tone_on anchor: tone_on

In [17]:
def prepare_tone_on_response_df(
    encoder_epoch_df,
    tone_air_phase,
    tone_on_anchor,
    anchor_col,
    require_good_session=True,
    require_valid_window=True,
    require_complete_prepost=True,
):
    """
    Builds tone-on-only dataframe from tone-air training.

    One row = one pre or post window around tone onset.
    """

    df = encoder_epoch_df.copy()

    tone_df = df[
        (df["phase"] == tone_air_phase) &
        (df[anchor_col].astype(str) == tone_on_anchor) &
        (df["window_position"].isin(["pre", "post"]))
    ].copy()

    # --------------------------------------------------
    # Optional filters
    # --------------------------------------------------

    if require_good_session and "good_session_basic" in tone_df.columns:
        tone_df = tone_df[tone_df["good_session_basic"] == True].copy()

    if require_valid_window and "valid_window" in tone_df.columns:
        tone_df = tone_df[tone_df["valid_window"] == True].copy()

    # --------------------------------------------------
    # Animal-day/session ID
    # --------------------------------------------------

    tone_df["animal_day"] = (
        tone_df["animal"].astype(str) + ":" +
        tone_df["date"].astype(str)
    )

    # --------------------------------------------------
    # Tone-event ID
    # --------------------------------------------------

    trial_col = "event_number"

    if trial_col not in tone_df.columns:
        raise ValueError("event_number column not found.")

    tone_df["tone_event_id"] = (
        tone_df["animal"].astype(str) + ":" +
        tone_df["date"].astype(str) + ":" +
        tone_df[trial_col].astype(str)
    )

    # --------------------------------------------------
    # Session time in minutes
    # --------------------------------------------------

    if "session_time_min" not in tone_df.columns:
        if "anchor_session_time_min" in tone_df.columns:
            tone_df["session_time_min"] = tone_df["anchor_session_time_min"]
        elif "anchor_time_s" in tone_df.columns:
            tone_df["session_time_min"] = tone_df["anchor_time_s"] / 60.0
        elif "session_time_s" in tone_df.columns:
            tone_df["session_time_min"] = tone_df["session_time_s"] / 60.0
        else:
            tone_df["session_time_min"] = np.nan

    # --------------------------------------------------
    # Tone-air session number
    # --------------------------------------------------

    if "phase_session_number" in tone_df.columns:
        tone_df["tone_air_session"] = tone_df["phase_session_number"]
    elif "phase_day_number_good" in tone_df.columns:
        tone_df["tone_air_session"] = tone_df["phase_day_number_good"]
    elif "phase_day" in tone_df.columns:
        tone_df["tone_air_session"] = tone_df["phase_day"]
    else:
        raise ValueError(
            "Could not find phase session/day column. "
            "Expected phase_session_number, phase_day_number_good, or phase_day."
        )

    # --------------------------------------------------
    # Center predictors
    # --------------------------------------------------

    tone_df["tone_air_session_c"] = (
        tone_df["tone_air_session"] -
        tone_df["tone_air_session"].mean()
    )

    tone_df["session_time_10m_c"] = (
        tone_df["session_time_min"] -
        tone_df["session_time_min"].mean()
    ) / 10.0

    # --------------------------------------------------
    # Ordered factor
    # --------------------------------------------------

    tone_df["window_position"] = pd.Categorical(
        tone_df["window_position"],
        categories=["pre", "post"],
        ordered=True,
    )

    # --------------------------------------------------
    # Keep only events with both pre and post windows
    # --------------------------------------------------

    if require_complete_prepost:
        counts = (
            tone_df
            .groupby("tone_event_id")["window_position"]
            .nunique()
        )

        complete_event_ids = counts[counts == 2].index

        tone_df = tone_df[
            tone_df["tone_event_id"].isin(complete_event_ids)
        ].copy()

    return tone_df.reset_index(drop=True)


tone_on_response_df = prepare_tone_on_response_df(
    encoder_epoch_df=encoder_epoch_df,
    tone_air_phase=tone_air_phase,
    tone_on_anchor=tone_on_anchor,
    anchor_col=anchor_col,
)

print("tone_on_response_df shape:", tone_on_response_df.shape)

display(
    tone_on_response_df
    .groupby(["window_position"])
    .size()
    .reset_index(name="n_windows")
)

display(
    tone_on_response_df
    .groupby(["animal"])["tone_event_id"]
    .nunique()
    .reset_index(name="n_tone_events")
)

display(
    tone_on_response_df[
        [
            "animal",
            "date",
            "phase",
            anchor_col,
            "event_number",
            "window_position",
            "tone_air_session",
            "tone_air_session_c",
            "session_time_min",
            "session_time_10m_c",
            "tone_event_id",
        ]
    ].head(20)
)

tone_on_response_df shape: (3532, 65)

  window_position  n_windows
0             pre       1766
1            post       1766

   animal  n_tone_events
0  NML_04            307
1  NML_05            180
2  NML_06            446
3  NML_07            355
4  NML_08            478

,animal,date,phase,anchor_name,event_number,window_position,tone_air_session,tone_air_session_c,session_time_min,session_time_10m_c,tone_event_id
0,NML_04,2026_01_28,tone_air_training,tone_on,0,post,1,-4.345413,0.666360,-0.882629,NML_04:2026_01_28:0
1,NML_04,2026_01_28,tone_air_training,tone_on,0,pre,1,-4.345413,0.666360,-0.882629,NML_04:2026_01_28:0
2,NML_04,2026_01_28,tone_air_training,tone_on,1,post,1,-4.345413,1.398697,-0.809395,NML_04:2026_01_28:1
3,NML_04,2026_01_28,tone_air_training,tone_on,1,pre,1,-4.345413,1.398697,-0.809395,NML_04:2026_01_28:1
4,NML_04,2026_01_28,tone_air_training,tone_on,2,post,1,-4.345413,1.929357,-0.756329,NML_04:2026_01_28:2
5,NML_04,2026_01_28,tone_air_training,tone_on,2,pre,1,-4.345413,1.929357,-0.756329,NML_04:2026_01_28:2
6,NML_04,2026_01_28,tone_air_training,tone_on,3,post,1,-4.345413,2.285977,-0.720667,NML_04:2026_01_28:3
7,NML_04,2026_01_28,tone_air_training,tone_on,3,pre,1,-4.345413,2.285977,-0.720667,NML_04:2026_01_28:3
8,NML_04,2026_01_28,tone_air_training,tone_on,4,post,1,-4.345413,2.649487,-0.684316,NML_04:2026_01_28:4
9,NML_04,2026_01_28,tone_air_training,tone_on,4,pre,1,-4.345413,2.649487,-0.684316,NML_04:2026_01_28:4
10,NML_04,2026_01_28,tone_air_training,tone_on,5,post,1,-4.345413,3.010777,-0.648187,NML_04:2026_01_28:5
11,NML_04,2026_01_28,tone_air_training,tone_on,5,pre,1,-4.345413,3.010777,-0.648187,NML_04:2026_01_28:5
12,NML_04,2026_01_28,tone_air_training,tone_on,6,post,1,-4.345413,3.388590,-0.610406,NML_04:2026_01_28:6
13,NML_04,2026_01_28,tone_air_training,tone_on,6,pre,1,-4.345413,3.388590,-0.610406,NML_04:2026_01_28:6
14,NML_04,2026_01_28,tone_air_training,tone_on,7,post,1,-4.345413,3.752150,-0.574050,NML_04:2026_01_28:7
15,NML_04,2026_01_28,tone_air_training,tone_on,7,pre,1,-4.345413,3.752150,-0.574050,NML_04:2026_01_28:7
16,NML_04,2026_01_28,tone_air_training,tone_on,8,post,1,-4.345413,4.160957,-0.533169,NML_04:2026_01_28:8
17,NML_04,2026_01_28,tone_air_training,tone_on,8,pre,1,-4.345413,4.160957,-0.533169,NML_04:2026_01_28:8
18,NML_04,2026_01_28,tone_air_training,tone_on,9,post,1,-4.345413,4.578973,-0.491367,NML_04:2026_01_28:9
19,NML_04,2026_01_28,tone_air_training,tone_on,9,pre,1,-4.345413,4.578973,-0.491367,NML_04:2026_01_28:9

In [18]:
%%R -i tone_on_response_df -o tone_on_model_info_R -o tone_on_prepost_R -o tone_on_session_response_trends_R -o tone_on_session_time_response_trends_R -o tone_on_response_grid_R -o tone_on_fixed_R -o tone_on_r2_R

library(lme4)
library(lmerTest)
library(emmeans)
library(broom.mixed)
library(dplyr)
library(performance)

emm_options(lmer.df = "asymptotic")

# --------------------------------------------------
# Prepare factors
# --------------------------------------------------

tone_on_response_df$animal <- factor(tone_on_response_df$animal)
tone_on_response_df$animal_day <- factor(tone_on_response_df$animal_day)
tone_on_response_df$tone_event_id <- factor(tone_on_response_df$tone_event_id)

tone_on_response_df$window_position <- factor(
  as.character(tone_on_response_df$window_position),
  levels = c("pre", "post")
)

# --------------------------------------------------
# Outcomes
# --------------------------------------------------

tone_outcomes_R <- c(
  "frac_moving",
  "frac_forward",
  "mean_speed_path_cms",
  "mean_speed_net_cms",
  "distance_path_cm",
  "distance_net_cm"
)

tone_outcomes_R <- tone_outcomes_R[tone_outcomes_R %in% names(tone_on_response_df)]

print(tone_outcomes_R)

# --------------------------------------------------
# Reference values for response grid
# --------------------------------------------------

session_sd <- sd(tone_on_response_df$tone_air_session_c, na.rm = TRUE)
time_sd <- sd(tone_on_response_df$session_time_10m_c, na.rm = TRUE)

session_grid <- c(-session_sd, 0, session_sd)
time_grid <- c(-time_sd, 0, time_sd)

session_grid_labels <- c("early_training", "mean_training", "late_training")
time_grid_labels <- c("early_session", "mean_session", "late_session")

# --------------------------------------------------
# Function to fit one outcome
# --------------------------------------------------

fit_tone_on_outcome <- function(outcome_name) {

  cat("\n\n==============================\n")
  cat("Fitting outcome:", outcome_name, "\n")
  cat("==============================\n")

  formula_text <- paste0(
    outcome_name,
    " ~ window_position * tone_air_session_c * session_time_10m_c + ",
    "(1 | animal) + (1 | animal_day) + (1 | tone_event_id)"
  )

  m <- lmer(
    as.formula(formula_text),
    data = tone_on_response_df,
    REML = FALSE,
    control = lmerControl(
      optimizer = "bobyqa",
      optCtrl = list(maxfun = 2e5)
    )
  )

  # --------------------------------------------------
  # Model info
  # --------------------------------------------------

  model_info <- data.frame(
    outcome = outcome_name,
    n_obs = nobs(m),
    n_animals = nlevels(tone_on_response_df$animal),
    n_animal_day = nlevels(tone_on_response_df$animal_day),
    n_events = nlevels(tone_on_response_df$tone_event_id),
    AIC = AIC(m),
    BIC = BIC(m),
    logLik = as.numeric(logLik(m)),
    singular = isSingular(m),
    stringsAsFactors = FALSE
  )

  # --------------------------------------------------
  # Fixed effects
  # --------------------------------------------------

  fixed_df <- broom.mixed::tidy(
    m,
    effects = "fixed",
    conf.int = TRUE
  )

  fixed_df$outcome <- outcome_name

  # --------------------------------------------------
  # Tone response at mean training session and mean session time
  # --------------------------------------------------

  emm_ref <- emmeans(
    m,
    ~ window_position,
    at = list(
      tone_air_session_c = 0,
      session_time_10m_c = 0
    ),
    lmer.df = "asymptotic"
  )

  prepost_ref <- as.data.frame(
    contrast(
      emm_ref,
      method = list(post_minus_pre = c(-1, 1)),
      adjust = "none"
    )
  )

  prepost_ref$outcome <- outcome_name

  # --------------------------------------------------
  # Does the tone response change across tone-air sessions?
  # This is the post-pre contrast of the session slope.
  # --------------------------------------------------

  session_trends <- emtrends(
    m,
    ~ window_position,
    var = "tone_air_session_c",
    at = list(
      session_time_10m_c = 0
    ),
    lmer.df = "asymptotic"
  )

  session_response_trend <- as.data.frame(
    contrast(
      session_trends,
      method = list(post_minus_pre_session_slope = c(-1, 1)),
      adjust = "none"
    )
  )

  session_response_trend$outcome <- outcome_name

  # --------------------------------------------------
  # Does the tone response change across within-session time?
  # This is the post-pre contrast of the within-session-time slope.
  # --------------------------------------------------

  session_time_trends <- emtrends(
    m,
    ~ window_position,
    var = "session_time_10m_c",
    at = list(
      tone_air_session_c = 0
    ),
    lmer.df = "asymptotic"
  )

  session_time_response_trend <- as.data.frame(
    contrast(
      session_time_trends,
      method = list(post_minus_pre_session_time_slope = c(-1, 1)),
      adjust = "none"
    )
  )

  session_time_response_trend$outcome <- outcome_name

  # --------------------------------------------------
  # Response grid:
  # estimated post-pre response at early/mean/late training
  # and early/mean/late within-session time.
  # --------------------------------------------------

  emm_grid <- emmeans(
    m,
    ~ window_position | tone_air_session_c * session_time_10m_c,
    at = list(
      tone_air_session_c = session_grid,
      session_time_10m_c = time_grid
    ),
    lmer.df = "asymptotic"
  )

  response_grid <- as.data.frame(
    contrast(
      emm_grid,
      method = list(post_minus_pre = c(-1, 1)),
      by = c("tone_air_session_c", "session_time_10m_c"),
      adjust = "none"
    )
  )

  response_grid$outcome <- outcome_name

  # Add readable labels
  response_grid$training_level <- session_grid_labels[
    match(response_grid$tone_air_session_c, session_grid)
  ]

  response_grid$session_time_level <- time_grid_labels[
    match(response_grid$session_time_10m_c, time_grid)
  ]

  # --------------------------------------------------
  # R2
  # --------------------------------------------------

  r2_obj <- performance::r2_nakagawa(m)

  r2_df <- data.frame(
    outcome = outcome_name,
    R2_marginal = r2_obj$R2_marginal,
    R2_conditional = r2_obj$R2_conditional,
    stringsAsFactors = FALSE
  )

  return(
    list(
      model = m,
      model_info = model_info,
      fixed = fixed_df,
      prepost = prepost_ref,
      session_response_trend = session_response_trend,
      session_time_response_trend = session_time_response_trend,
      response_grid = response_grid,
      r2 = r2_df
    )
  )
}

# --------------------------------------------------
# Run all outcomes
# --------------------------------------------------

tone_on_models_R <- list()
model_info_list <- list()
fixed_list <- list()
prepost_list <- list()
session_response_trend_list <- list()
session_time_response_trend_list <- list()
response_grid_list <- list()
r2_list <- list()

for (outcome_name in tone_outcomes_R) {

  result <- fit_tone_on_outcome(outcome_name)

  tone_on_models_R[[outcome_name]] <- result$model
  model_info_list[[outcome_name]] <- result$model_info
  fixed_list[[outcome_name]] <- result$fixed
  prepost_list[[outcome_name]] <- result$prepost
  session_response_trend_list[[outcome_name]] <- result$session_response_trend
  session_time_response_trend_list[[outcome_name]] <- result$session_time_response_trend
  response_grid_list[[outcome_name]] <- result$response_grid
  r2_list[[outcome_name]] <- result$r2
}

# --------------------------------------------------
# Combine output tables
# --------------------------------------------------

tone_on_model_info_R <- bind_rows(model_info_list) %>% relocate(outcome)
tone_on_fixed_R <- bind_rows(fixed_list) %>% relocate(outcome)
tone_on_prepost_R <- bind_rows(prepost_list) %>% relocate(outcome)
tone_on_session_response_trends_R <- bind_rows(session_response_trend_list) %>% relocate(outcome)
tone_on_session_time_response_trends_R <- bind_rows(session_time_response_trend_list) %>% relocate(outcome)
tone_on_response_grid_R <- bind_rows(response_grid_list) %>% relocate(outcome)
tone_on_r2_R <- bind_rows(r2_list) %>% relocate(outcome)

# --------------------------------------------------
# Print key outputs
# --------------------------------------------------

cat("\n\n=== Model info ===\n")
print(tone_on_model_info_R)

cat("\n\n=== Tone pre/post response at mean training and mean session time ===\n")
print(tone_on_prepost_R)

cat("\n\n=== Does tone response change across tone-air sessions? ===\n")
print(tone_on_session_response_trends_R)

cat("\n\n=== Does tone response change across within-session time? ===\n")
print(tone_on_session_time_response_trends_R)

cat("\n\n=== Tone response grid: early/mean/late training × early/mean/late session ===\n")
print(tone_on_response_grid_R)

cat("\n\n=== Fixed effects ===\n")
print(tone_on_fixed_R)

cat("\n\n=== R2 ===\n")
print(tone_on_r2_R)

[1] "frac_moving"         "frac_forward"        "mean_speed_path_cms"
[4] "mean_speed_net_cms"  "distance_path_cm"    "distance_net_cm"


==============================
Fitting outcome: frac_moving
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: frac_forward
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: mean_speed_path_cms
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: mean_speed_net_cms
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: distance_path_cm
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

==============================
Fitting outcome: distance_net_cm
==============================

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

=== Model info ===
              outcome n_obs n_animals n_animal_day n_events       AIC
1         frac_moving  3532         5           49     1766  1239.196
2        frac_forward  3532         5           49     1766   595.804
3 mean_speed_path_cms  3532         5           49     1766 10214.770
4  mean_speed_net_cms  3532         5           49     1766 10310.704
5    distance_path_cm  3532         5           49     1766 10228.594
6     distance_net_cm  3532         5           49     1766 10317.406
         BIC     logLik singular
1  1313.2317  -607.5981    FALSE
2   669.8395  -285.9020    FALSE
3 10288.8059 -5095.3852    FALSE
4 10384.7396 -5143.3521    FALSE
5 10302.6290 -5102.2968    FALSE
6 10391.4412 -5146.7029    FALSE


=== Tone pre/post response at mean training and mean session time ===
              outcome       contrast  estimate          SE  df   z.ratio
1         frac_moving post_minus_pre 0.1486416 0.007971113 Inf 18.647533
2        frac_forward post_minus_pre 0.1129795 0.007027406 Inf 16.076980
3 mean_speed_path_cms post_minus_pre 0.2255985 0.024377867 Inf  9.254235
4  mean_speed_net_cms post_minus_pre 0.1531571 0.024881965 Inf  6.155347
5    distance_path_cm post_minus_pre 0.2298923 0.024454361 Inf  9.400871
6     distance_net_cm post_minus_pre 0.1533896 0.024930103 Inf  6.152787
       p.value
1 1.322388e-77
2 3.699800e-58
3 2.157707e-20
4 7.491334e-10
5 5.411340e-21
6 7.613298e-10


=== Does tone response change across tone-air sessions? ===
              outcome                     contrast      estimate          SE
1         frac_moving post_minus_pre_session_slope -0.0009978894 0.002796594
2        frac_forward post_minus_pre_session_slope -0.0021982292 0.002465503
3 mean_speed_path_cms post_minus_pre_session_slope -0.0033714149 0.008552759
4  mean_speed_net_cms post_minus_pre_session_slope -0.0053280905 0.008729617
5    distance_path_cm post_minus_pre_session_slope -0.0033137869 0.008579596
6     distance_net_cm post_minus_pre_session_slope -0.0054160527 0.008746506
   df    z.ratio   p.value
1 Inf -0.3568231 0.7212243
2 Inf -0.8915946 0.3726103
3 Inf -0.3941903 0.6934405
4 Inf -0.6103464 0.5416324
5 Inf -0.3862404 0.6993186
6 Inf -0.6192247 0.5357683


=== Does tone response change across within-session time? ===
              outcome                          contrast   estimate         SE
1         frac_moving post_minus_pre_session_time_slope 0.01702765 0.01312133
2        frac_forward post_minus_pre_session_time_slope 0.01993943 0.01156788
3 mean_speed_path_cms post_minus_pre_session_time_slope 0.04645158 0.04012865
4  mean_speed_net_cms post_minus_pre_session_time_slope 0.06575969 0.04095845
5    distance_path_cm post_minus_pre_session_time_slope 0.04767131 0.04025457
6     distance_net_cm post_minus_pre_session_time_slope 0.06572726 0.04103769
   df  z.ratio    p.value
1 Inf 1.297708 0.19438775
2 Inf 1.723689 0.08476406
3 Inf 1.157566 0.24704099
4 Inf 1.605522 0.10837897
5 Inf 1.184246 0.23631569
6 Inf 1.601631 0.10923713


=== Tone response grid: early/mean/late training × early/mean/late session ===
               outcome       contrast tone_air_session_c session_time_10m_c
1          frac_moving post_minus_pre          -2.852088         -0.6076253
2          frac_moving post_minus_pre           0.000000         -0.6076253
3          frac_moving post_minus_pre           2.852088         -0.6076253
4          frac_moving post_minus_pre          -2.852088          0.0000000
5          frac_moving post_minus_pre           0.000000          0.0000000
6          frac_moving post_minus_pre           2.852088          0.0000000
7          frac_moving post_minus_pre          -2.852088          0.6076253
8          frac_moving post_minus_pre           0.000000          0.6076253
9          frac_moving post_minus_pre           2.852088          0.6076253
10        frac_forward post_minus_pre          -2.852088         -0.6076253
11        frac_forward post_minus_pre           0.000000         -0.6076253
12        frac_forward post_minus_pre           2.852088         -0.6076253
13        frac_forward post_minus_pre          -2.852088          0.0000000
14        frac_forward post_minus_pre           0.000000          0.0000000
15        frac_forward post_minus_pre           2.852088          0.0000000
16        frac_forward post_minus_pre          -2.852088          0.6076253
17        frac_forward post_minus_pre           0.000000          0.6076253
18        frac_forward post_minus_pre           2.852088          0.6076253
19 mean_speed_path_cms post_minus_pre          -2.852088         -0.6076253
20 mean_speed_path_cms post_minus_pre           0.000000         -0.6076253
21 mean_speed_path_cms post_minus_pre           2.852088         -0.6076253
22 mean_speed_path_cms post_minus_pre          -2.852088          0.0000000
23 mean_speed_path_cms post_minus_pre           0.000000          0.0000000
24 mean_speed_path_cms post_minus_pre           2.852088          0.0000000
25 mean_speed_path_cms post_minus_pre          -2.852088          0.6076253
26 mean_speed_path_cms post_minus_pre           0.000000          0.6076253
27 mean_speed_path_cms post_minus_pre           2.852088          0.6076253
28  mean_speed_net_cms post_minus_pre          -2.852088         -0.6076253
29  mean_speed_net_cms post_minus_pre           0.000000         -0.6076253
30  mean_speed_net_cms post_minus_pre           2.852088         -0.6076253
31  mean_speed_net_cms post_minus_pre          -2.852088          0.0000000
32  mean_speed_net_cms post_minus_pre           0.000000          0.0000000
33  mean_speed_net_cms post_minus_pre           2.852088          0.0000000
34  mean_speed_net_cms post_minus_pre          -2.852088          0.6076253
35  mean_speed_net_cms post_minus_pre           0.000000          0.6076253
36  mean_speed_net_cms post_minus_pre           2.852088          0.6076253
37    distance_path_cm post_minus_pre          -2.852088         -0.6076253
38    distance_path_cm post_minus_pre           0.000000         -0.6076253
39    distance_path_cm post_minus_pre           2.852088         -0.6076253
40    distance_path_cm post_minus_pre          -2.852088          0.0000000
41    distance_path_cm post_minus_pre           0.000000          0.0000000
42    distance_path_cm post_minus_pre           2.852088          0.0000000
43    distance_path_cm post_minus_pre          -2.852088          0.6076253
44    distance_path_cm post_minus_pre           0.000000          0.6076253
45    distance_path_cm post_minus_pre           2.852088          0.6076253
46     distance_net_cm post_minus_pre          -2.852088         -0.6076253
47     distance_net_cm post_minus_pre           0.000000         -0.6076253
48     distance_net_cm post_minus_pre           2.852088         -0.6076253
49     distance_net_cm post_minus_pre          -2.852088          0.0000000
50     distance_net_cm post_minus_pre           0.000000          0.0000000
51     distance_net_cm post_minus_pre           2.852088          0.0000000
52     distance_net_cm post_minus_pre          -2.852088          0.6076253
53     distance_net_cm post_minus_pre           0.000000          0.6076253
54     distance_net_cm post_minus_pre           2.852088          0.6076253
     estimate          SE  df   z.ratio      p.value training_level
1  0.12022195 0.016281418 Inf  7.383997 1.536064e-13 early_training
2  0.13829516 0.011269477 Inf 12.271657 1.285949e-34  mean_training
3  0.15636837 0.015344180 Inf 10.190728 2.181240e-24  late_training
4  0.15148766 0.011264865 Inf 13.447800 3.171685e-41 early_training
5  0.14864159 0.007971113 Inf 18.647533 1.322388e-77  mean_training
6  0.14579552 0.011287936 Inf 12.916047 3.654385e-38  late_training
7  0.18275336 0.015489235 Inf 11.798734 3.962279e-32 early_training
8  0.15898802 0.011278689 Inf 14.096321 4.000899e-45  mean_training
9  0.13522267 0.016641998 Inf  8.125387 4.459383e-16  late_training
10 0.08823596 0.014353847 Inf  6.147200 7.886284e-10 early_training
11 0.10086376 0.009935274 Inf 10.152086 3.243543e-24  mean_training
12 0.11349156 0.013527569 Inf  8.389649 4.875951e-17  late_training
13 0.11924900 0.009931208 Inf 12.007502 3.244983e-33 early_training
14 0.11297946 0.007027406 Inf 16.076980 3.699800e-58  mean_training
15 0.10670991 0.009951548 Inf 10.722947 7.943173e-27  late_training
16 0.15026204 0.013655451 Inf 11.003814 3.663036e-28 early_training
17 0.12509516 0.009943395 Inf 12.580729 2.695303e-36  mean_training
18 0.09992827 0.014671737 Inf  6.810937 9.696539e-12  late_training
19 0.17173116 0.049793080 Inf  3.448896 5.628835e-04 early_training
20 0.19737335 0.034465179 Inf  5.726747 1.023749e-08  mean_training
21 0.22301555 0.046926747 Inf  4.752419 2.009977e-06  late_training
22 0.23521408 0.034451074 Inf  6.827482 8.641820e-12 early_training
23 0.22559850 0.024377867 Inf  9.254235 2.157707e-20  mean_training
24 0.21598293 0.034521632 Inf  6.256452 3.938346e-10  late_training
25 0.29869700 0.047370366 Inf  6.305567 2.871415e-10 early_training
26 0.25382366 0.034493350 Inf  7.358626 1.858131e-13  mean_training
27 0.20895031 0.050895834 Inf  4.105450 4.035281e-05  late_training
28 0.09990347 0.050822726 Inf  1.965724 4.933045e-02 early_training
29 0.11319988 0.035177867 Inf  3.217929 1.291198e-03  mean_training
30 0.12649628 0.047897122 Inf  2.641000 8.266183e-03  late_training
31 0.16835331 0.035163471 Inf  4.787733 1.686758e-06 early_training
32 0.15315712 0.024881965 Inf  6.155347 7.491334e-10  mean_training
33 0.13796094 0.035235488 Inf  3.915397 9.025539e-05  late_training
34 0.23680315 0.048349914 Inf  4.897695 9.696724e-07 early_training
35 0.19311437 0.035206621 Inf  5.485172 4.130670e-08  mean_training
36 0.14942560 0.051948283 Inf  2.876430 4.022013e-03  late_training
37 0.17526649 0.049949324 Inf  3.508886 4.499875e-04 early_training
38 0.20092600 0.034573326 Inf  5.811590 6.188224e-09  mean_training
39 0.22658551 0.047073996 Inf  4.813390 1.483913e-06  late_training
40 0.23934350 0.034559177 Inf  6.925614 4.340900e-12 early_training
41 0.22989229 0.024454361 Inf  9.400871 5.411340e-21  mean_training
42 0.22044108 0.034629956 Inf  6.365618 1.945048e-10  late_training
43 0.30342052 0.047519007 Inf  6.385245 1.711230e-10 early_training
44 0.25885858 0.034601585 Inf  7.481119 7.369235e-14  mean_training
45 0.21429665 0.051055538 Inf  4.197324 2.700871e-05  late_training
46 0.10084490 0.050921050 Inf  1.980417 4.765673e-02 early_training
47 0.11345207 0.035245924 Inf  3.218871 1.286965e-03  mean_training
48 0.12605925 0.047989786 Inf  2.626793 8.619365e-03  late_training
49 0.16883668 0.035231500 Inf  4.792208 1.649557e-06 early_training
50 0.15338961 0.024930103 Inf  6.152787 7.613298e-10  mean_training
51 0.13794255 0.035303656 Inf  3.907316 9.332692e-05  late_training
52 0.23682845 0.048443454 Inf  4.888761 1.014728e-06 early_training
53 0.19332715 0.035274733 Inf  5.480613 4.238552e-08  mean_training
54 0.14982585 0.052048785 Inf  2.878566 3.994879e-03  late_training
   session_time_level
1       early_session
2       early_session
3       early_session
4        mean_session
5        mean_session
6        mean_session
7        late_session
8        late_session
9        late_session
10      early_session
11      early_session
12      early_session
13       mean_session
14       mean_session
15       mean_session
16       late_session
17       late_session
18       late_session
19      early_session
20      early_session
21      early_session
22       mean_session
23       mean_session
24       mean_session
25       late_session
26       late_session
27       late_session
28      early_session
29      early_session
30      early_session
31       mean_session
32       mean_session
33       mean_session
34       late_session
35       late_session
36       late_session
37      early_session
38      early_session
39      early_session
40       mean_session
41       mean_session
42       mean_session
43       late_session
44       late_session
45       late_session
46      early_session
47      early_session
48      early_session
49       mean_session
50       mean_session
51       mean_session
52       late_session
53       late_session
54       late_session


=== Fixed effects ===
# A tibble: 48 × 10
   outcome    effect term  estimate std.error statistic     df  p.value conf.low
   <chr>      <chr>  <chr>    <dbl>     <dbl>     <dbl>  <dbl>    <dbl>    <dbl>
 1 frac_movi… fixed  (Int…  2.04e-1   0.0568      3.59  5.02e0 1.55e- 2  0.0584
 2 frac_movi… fixed  wind…  1.49e-1   0.00797    18.6   1.77e3 5.53e-71  0.133
 3 frac_movi… fixed  tone… -2.17e-3   0.00489    -0.443 5.19e1 6.59e- 1 -0.0120
 4 frac_movi… fixed  sess…  5.93e-3   0.0116      0.511 3.08e3 6.09e- 1 -0.0168
 5 frac_movi… fixed  wind… -9.98e-4   0.00280    -0.357 1.77e3 7.21e- 1 -0.00648
 6 frac_movi… fixed  wind…  1.70e-2   0.0131      1.30  1.77e3 1.95e- 1 -0.00871
 7 frac_movi… fixed  tone…  5.17e-3   0.00408     1.27  3.08e3 2.05e- 1 -0.00283
 8 frac_movi… fixed  wind… -1.21e-2   0.00460    -2.62  1.77e3 8.80e- 3 -0.0211
 9 frac_forw… fixed  (Int…  1.72e-1   0.0546      3.16  5.00e0 2.51e- 2  0.0321
10 frac_forw… fixed  wind…  1.13e-1   0.00703    16.1   1.77e3 2.21e-54  0.0992
# ℹ 38 more rows
# ℹ 1 more variable: conf.high <dbl>
# ℹ Use `print(n = ...)` to see more rows


=== R2 ===
                            outcome R2_marginal R2_conditional
Marginal R2...1         frac_moving  0.05187208      0.5098034
Marginal R2...2        frac_forward  0.03953495      0.5540593
Marginal R2...3 mean_speed_path_cms  0.01084993      0.6627841
Marginal R2...4  mean_speed_net_cms  0.01008190      0.6565794
Marginal R2...5    distance_path_cm  0.01111289      0.6616252
Marginal R2...6     distance_net_cm  0.01010385      0.6554945

In [20]:
# Check available columns
print("tone_on_fixed_R columns:")
print(tone_on_fixed_R.columns.tolist())

print("\ntone_on_response_grid_R columns:")
print(tone_on_response_grid_R.columns.tolist())

tone_on_fixed_R columns:
['outcome', 'effect', 'term', 'estimate', 'std.error', 'statistic', 'df', 'p.value', 'conf.low', 'conf.high']

tone_on_response_grid_R columns:
['outcome', 'contrast', 'tone_air_session_c', 'session_time_10m_c', 'estimate', 'SE', 'df', 'z.ratio', 'p.value', 'training_level', 'session_time_level']

In [21]:
import pandas as pd
import numpy as np

# Make a clean copy
fixed = tone_on_fixed_R.copy()

# Show all terms containing both tone_air_session_c and session_time_10m_c
session_x_time_terms = fixed[
    fixed["term"].str.contains("tone_air_session_c", regex=False) &
    fixed["term"].str.contains("session_time_10m_c", regex=False)
].copy()

display(
    session_x_time_terms[
        ["outcome", "term", "estimate", "std.error", "statistic", "p.value"]
    ].sort_values(["outcome", "term"])
)

,outcome,term,estimate,std.error,statistic,p.value
47,distance_net_cm,tone_air_session_c:session_time_10m_c,0.007304,0.015851,0.460804,0.644978
48,distance_net_cm,window_positionpost:tone_air_session_c:session...,-0.016188,0.014395,-1.124538,0.260938
39,distance_path_cm,tone_air_session_c:session_time_10m_c,0.010480,0.015710,0.667107,0.504764
40,distance_path_cm,window_positionpost:tone_air_session_c:session...,-0.020260,0.014121,-1.434773,0.151529
15,frac_forward,tone_air_session_c:session_time_10m_c,0.003492,0.003775,0.925093,0.354993
16,frac_forward,window_positionpost:tone_air_session_c:session...,-0.010904,0.004058,-2.687234,0.007272
7,frac_moving,tone_air_session_c:session_time_10m_c,0.005166,0.004078,1.266803,0.205322
8,frac_moving,window_positionpost:tone_air_session_c:session...,-0.012071,0.004603,-2.622573,0.008802
31,mean_speed_net_cms,tone_air_session_c:session_time_10m_c,0.007456,0.015845,0.470573,0.637985
32,mean_speed_net_cms,window_positionpost:tone_air_session_c:session...,-0.016441,0.014368,-1.144319,0.252647
23,mean_speed_path_cms,tone_air_session_c:session_time_10m_c,0.010560,0.015690,0.673055,0.500973
24,mean_speed_path_cms,window_positionpost:tone_air_session_c:session...,-0.020345,0.014077,-1.445303,0.148550